#!/usr/bin/env python3
"""Generate `docs/findings/INDEX.md` from the write-ups beside it.

**Why this is generated rather than written.** The alternative to freezing
`docs/findings.md` is an index that every change appends to, and an index
nobody appends to by hand goes stale within a week. A generated one is a
function of the tree: two branches that both add a write-up and both regenerate
produce the same file, so the conflict is resolved once in the content and never
in the prose. That is the difference between a shared file that collides and a
shared file that is merely shared.

**What it reads.** The first `# ` heading of every `*.md` directly under
`docs/findings/`, minus this index and the census write-up that is a table of
the repository's own pins rather than a finding. Nothing else is read, so the
index cannot disagree with the tree except by being out of date, and `--check`
is what says so.

`--check` exits 1 when the committed index differs from what this run produces,
which is the form the gate wants; with no flag it prints the index.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir))
FINDINGS_DIR = os.path.join("docs", "findings")
INDEX = "INDEX.md"

# Not findings: the index itself, and the pin census, which is a table of the
# repository's citations rather than a conclusion about the machine. Both are
# reachable from `docs/findings.md` and neither belongs in a list of findings.
SKIP = {INDEX, "test-line-pin-census.md"}

HEADING = re.compile(r"^#\s+(.*\S)\s*$")


def entries(repo):
    """-> [(filename, title)] sorted by filename, for every write-up."""
    root = os.path.join(repo, FINDINGS_DIR)
    out = []
    for name in sorted(os.listdir(root)):
        if not name.endswith(".md") or name in SKIP:
            continue
        path = os.path.join(root, name)
        if not os.path.isfile(path):
            continue
        title = None
        with open(path, encoding="utf-8") as handle:
            for line in handle:
                if line.startswith("# "):
                    title = line[2:].strip()
                    break
                if line.strip():
                    # A file that opens with prose before its heading is still a
                    # write-up; keep looking rather than record no title.
                    continue
        out.append((name, title or name[:-3].replace("-", " ")))
    return out


def render(repo):
    found = entries(repo)
    lines = [
        "# Findings index",
        "",
        "**Generated by `ec/tools/gen_findings_index.py` — do not edit.** Every",
        "write-up under `docs/findings/`, by file name. `docs/findings.md` is",
        "frozen at §97 and is the record of what came before this directory was",
        "the place a finding went; `check_findings_frozen.py` holds that.",
        "",
        "%d write-ups." % len(found),
        "",
    ]
    for name, title in found:
        lines.append("- [`%s`](%s) — %s" % (name, name, title))
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--repo", default=REPO, help="repository root")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed index is out of date")
    args = parser.parse_args(argv)

    path = os.path.join(args.repo, FINDINGS_DIR, INDEX)
    want = render(args.repo)

    if not args.check:
        sys.stdout.write(want)
        return 0

    try:
        with open(path, encoding="utf-8") as handle:
            have = handle.read()
    except OSError:
        print("docs/findings/INDEX.md is missing; run gen_findings_index.py")
        return 1
    if have != want:
        print("docs/findings/INDEX.md is out of date: a write-up was added, "
              "removed or retitled. Regenerate with "
              "`python3 ec/tools/gen_findings_index.py > docs/findings/INDEX.md`.")
        return 1
    print("docs/findings/INDEX.md: %d write-up(s), current."
          % len(entries(args.repo)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
