#!/usr/bin/env python3
"""Classify the `pd` listings whose "no ret" comment may be a function-boundary
artefact, and settle what `pd` 0x34EF actually does.

`ec/annotations/ghidra-functions.csv`'s `pd,34EF` row reads `set_dptr_0424`
with `type=unresolved` and the comment "A single `mov DPTR,#0x424` with no
ret, so the pointer's use is not decoded here." The three bytes it names are
the whole listing, and the next address is not a gap: `pd/34F2.asm` starts
`mov B,#0x60` and is a listing in its own right. So the row's clause is a
statement about where Ghidra's export put a function boundary, not about
where the code returns, and this tool measures which rows that is true of.

**The predicate that finds 0x34EF is the *byte* arm, and the predicate the
issue names is the *clause* arm. They are different questions and both are
printed.** The clause arm is a regex over the comment text -- a match on
prose, so a row whose comment happens not to carry the clause is invisible to
it and a row that does is in it whatever its bytes say. The byte arm is a
decode: the listing's last instruction is neither a return nor a transfer of
control, so control leaves the listing by falling past its end. The family is
the byte arm intersected with "`addr + size` is another listing's entry",
which is the part that makes the fall-through *into a boundary* rather than
off the end of the export.

**Three of the figures the issue was filed with do not reproduce, and the
tool's own counts are what the write-up quotes.** Its filter -- take the next
address as `addr + listing-index.csv`'s `size`, decode one instruction there,
keep the rows whose comment carries a "not decoded here" or "no ret" clause
and whose successor begins a `ljmp`/`jmp`/`sjmp`/`ajmp` -- finds four rows on
the committed tree, and 0x34EF is not one of them: 0x34F2 begins
`mov B,#0x60` and the `ljmp` is an instruction later. The byte arm is the
predicate that does contain 0x34EF. Its `198`-row clause population and the
`80` rows the clause arm and the byte arm agree on are the tool's, printed
with the predicate beside each so a reader can re-derive or reject them.

**`pd,34F2` is not merely 0x34EF's tail -- it is `lcall`ed in its own right
at 0x6782**, in the same listing `pd,6673` that holds the `lcall 0x34EF` at
0x67E0. So the pair is two entries sharing a tail rather than one routine
split by a function boundary, and that is what decides 0x34EF's verdict
below. `pd,3632`/`pd,3635` are the same shape (`lcall 0x3635` at 0x44A1
against `lcall 0x3632` at 0x8D50), which is a half-statement in `pd,3632`'s
existing comment rather than a licence to merge the two rows; that row is not
this tool's to edit and is not edited here.

**The entry census is a byte scan over the whole 64 KiB, de-duplicated by
site address, and it is `not found by this method` in both directions.** A
byte pattern cannot tell code from data, so a site it finds may be an operand
byte, and a target it does not find may still be reached by a paged or
relative form or from a byte the export never covers. The de-duplication is
not a nicety: a per-listing walk over the listings' own spans counts the 26
`lcall`/`ljmp` sites in 0x4C12-0x4D18 twice, because `pd/4D6F.asm` spans
0x4A12-0x4E58 and carries its own rows at those addresses *and* they are the
subject of `pd/4C12.asm`, `pd/4C19.asm`, `pd/4C20.asm` and `pd/4C27.asm`. One
address, two listings, one site -- and a census that reported 2066 where the
image holds 2040 in those spans would be wrong by a number it could not
explain.

**The two populations of *entry sites* are reported together and never
exchanged for one another.** The byte scan is the wide half; a walk over the
committed listings' own decoded instructions is the narrow one, and it is the
narrow one that assigns a verdict, because a decoded instruction cannot be an
operand byte. Where the two differ the row is still a candidate, per
`pd_entry_forms.py`'s standing rule and `CLAUDE.md`'s: a listing-scanned
absence is not *absent*.

Usage:
    python3 pd_no_ret_fallthrough.py
    python3 pd_no_ret_fallthrough.py --self-test
    python3 pd_no_ret_fallthrough.py --csv > ../annotations/pd-no-ret-fallthrough.csv
    python3 pd_no_ret_fallthrough.py --check

`../annotations/pd-no-ret-fallthrough.csv` is generated by the third of those
and held to the tree by the fourth, the arrangement `pd_entry_forms.py` and
`ec/annotations/pd-image.md` §0 record. It is **not registered in any gate**:
`.github/scripts/agent-gates.sh` is a pipeline file and this branch's token
has no `workflow` scope, so a gate call is a human's change. This tool is
instead runnable, cited standalone, and covered by `bash tools/run-tests.sh`'s
`test_*.py` glob.
"""
import argparse
import csv
import difflib
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
EC_DIR = os.path.dirname(HERE)
REPO = os.path.dirname(EC_DIR)
sys.path.insert(0, HERE)

from disasm8051 import (OPCODE_LEN, REL_OPCODES, mnemonic,            # noqa: E402
                        paged_target, relative_target)
from trace_xdata_refs import PD_MARKER, offset_for_runtime             # noqa: E402

FIRMWARE = os.path.join(EC_DIR, "firmware", "GMxMGxx_11.800")
LISTINGS = os.path.join(EC_DIR, "decompiled", "pd")
INDEX_CSV = os.path.join(EC_DIR, "decompiled", "listing-index.csv")
ANNOTATIONS = os.path.join(EC_DIR, "annotations", "ghidra-functions.csv")
OUT_CSV = os.path.join(EC_DIR, "annotations", "pd-no-ret-fallthrough.csv")

PROGRAM = "pd"
PD_REGION = "pd-image"
PD_LEN = 0x10000

# The pd image's base in the dump, taken from `trace_xdata_refs.REGIONS` rather
# than written out again, because `PD_MARKER` is the *marker's* file offset and
# not the image's: the marker sits 0x40 bytes into a program that starts at
# 0x20000. A runtime address in this program is the offset from here, and using
# the marker instead reads 0x40 bytes early in every one of the 64 KiB -- which
# still decodes, at the wrong address, which is the worst of both.
PD_BASE = offset_for_runtime(0, PD_REGION)

RET = 0x22
RETI = 0x32
# Both returns, because both leave the listing and the question is what leaves
# the listing. A listing ending in `reti` falls into nothing whatever its
# comment says, and reading only 0x22 would put seven rows into the family for
# a reason that has nothing to do with the boundary.
RETURNS = frozenset((RET, RETI))

# The absolute transfer opcodes, and the paged and indirect families beside
# them. The paged pair is keyed on `op & 0x1F` exactly as `disasm8051.mnemonic`
# keys it, and the indirect `jmp @A+DPTR` is spelled out because neither
# `REL_OPCODES` nor the paged test reaches it. This tool enumerates no
# encoding of its own beyond that one: a fourth spelling of the map is a fourth
# thing to keep in step with the shared decoder.
ABS_OPCODES = frozenset((0x02, 0x12))
PAGED_OPCODES = frozenset(op for op in range(256) if (op & 0x1F) in (0x01, 0x11))
INDIRECT_OPCODES = frozenset((0x73,))
TRANSFER_OPCODES = frozenset(REL_OPCODES) | ABS_OPCODES | PAGED_OPCODES | INDIRECT_OPCODES

# The clause arm, over the annotation comment. Two clauses and not one because
# they are two different sentences a human wrote, and the issue names both: a
# listing whose pointer use is "not decoded here" is saying the same thing
# about the same boundary as one whose last instruction is "no ret". This is
# a text match over prose and the tool labels it as such wherever it prints a
# figure derived from it -- it is not a decode and settles nothing on its own.
CLAUSE_RE = re.compile(r"not decoded here|no ret", re.IGNORECASE)

# An instruction line is `<4 hex addr> <up to 3 byte columns, '-' padded>
# <mnemonic> <operands>`, and only the first column is the address. Anchored
# at the start of the line for the reason `pd_entry_forms.py` gives: the
# operand text carries four-hex-digit branch targets of its own, so an
# unanchored regex matches a target as readily as an address.
LINE_RE = re.compile(
    r"^([0-9A-Fa-f]{4})\s+((?:[0-9a-f]{2}|-)\s+(?:[0-9a-f]{2}|-)\s+"
    r"(?:[0-9a-f]{2}|-))\s+(\S.*)$")

# The `ghidra-functions.csv` address column is spelled two ways in one file,
# and an un-normalised join silently drops half the table rather than failing.
# `--self-test` asserts both spellings are present, because the failure this
# guards is silent and wrong rather than loud.
ADDR_PREFIX_RE = re.compile(r"^0[xX]")

VERDICTS = ("shared-tail", "falls-through-unentered", "boundary-wrong")

# What each verdict means, in the tool's own words rather than the write-up's.
# A reader who has the CSV and not the prose needs these.
VERDICT_GLOSS = {
    "shared-tail":
        "the successor is itself a transfer target, so the two listings are two "
        "entries over one tail rather than one routine cut in half",
    "falls-through-unentered":
        "the successor is contiguous and nothing transfers to it, so the two "
        "listings are one routine's worth of code with the boundary inside it",
    "boundary-wrong":
        "nothing transfers to the row's own address either: it is reached only "
        "by falling in from the previous listing, so the boundary is misdrawn "
        "and the real entry is elsewhere",
}

COLUMNS = ["addr", "name", "type", "size", "successor", "succ_name",
           "succ_size", "succ_first", "last_insn", "self_sites", "succ_sites",
           "byte_succ_sites", "verdict", "clause", "in_byte_arm"]

HEX_COLUMNS = {"addr": 4, "successor": 4}


def norm_addr(addr):
    """`addr` as an int, from either spelling the annotation CSVs use.

    `ghidra-functions.csv` carries `34EF` on some rows and `0x0003` on others,
    so a join done on the string would match the second half and quietly miss
    the first -- and the miss is silent, which is the whole reason this
    function exists rather than an `int(addr, 16)` at the call site.
    """
    return int(ADDR_PREFIX_RE.sub("", addr.strip()), 16)


# --------------------------------------------------------------------------
# The committed listings
# --------------------------------------------------------------------------

def read_listings():
    """(starts, {address: (bytes, text, file)}, {listing head: (first, last)})
    for the committed pd `.asm` files, over every instruction line rather than
    the listing's own extent.

    `pd_entry_forms.py`'s reader, kept so the two tools cannot disagree about
    what a committed listing says. Four committed filenames disagree with
    their first instruction (`0B85.asm` begins at 0x0B51, `4D6F.asm` at
    0x4A12 and two more), so every address is carried from the line and never
    from the file name -- and the third return is keyed on the listing's own
    *first instruction*, which is the one address a listing states and the
    only one `contiguous()` and the verdicts can be measured against."""
    out, tails = {}, {}
    for name in sorted(os.listdir(LISTINGS)):
        if not name.endswith(".asm"):
            continue
        head = last = None
        with open(os.path.join(LISTINGS, name), errors="replace") as f:
            for line in f:
                m = LINE_RE.match(line)
                if not m:
                    continue
                a = int(m.group(1), 16)
                out[a] = (
                    tuple(int(b, 16) for b in m.group(2).split() if b != "-"),
                    m.group(3).rstrip(), f"{PROGRAM}/{name}")
                if head is None:
                    head = a
                last = (out[a], a)
        if head is not None:
            tails[head] = (out[head], last)
    return sorted(out), out, tails


def load_index():
    """{listing file: row} for the pd rows of `listing-index.csv`, keyed on
    the `out_file` column rather than on `addr`.

    The `out_file` key is load-bearing and the `addr` column is not usable
    here: four committed pd index rows name an address that is not their
    listing's first instruction (`pd/4D6F.asm` holds 0x4A12-0x4E58 and is
    indexed at 0x4D6F, `pd/0B85.asm` and two more), so a join on `addr`
    silently drops four rows and reports a family that is four short of what
    the listings hold. `out_file` is a 1:1 match for every committed pd
    listing, and it is the column that says which file the row is about.

    The `size` column is read as the next address's offset and never as the
    listing's extent. That is right for the question here -- a row whose
    successor is another listing's entry is *by construction* contiguous with
    it -- and it is the reading `pd_entry_forms.py` records as a trap for a
    listing that is *not* contiguous, which is why `contiguous()` is measured
    per row below rather than assumed."""
    with open(INDEX_CSV, newline="") as f:
        return {r["out_file"]: r
                for r in csv.DictReader(f) if r["program"] == PROGRAM}


def load_annotations():
    """{address: row} for the pd rows of `ghidra-functions.csv`, with the
    address column normalised on the way in."""
    with open(ANNOTATIONS, newline="") as f:
        return {norm_addr(r["addr"]): r
                for r in csv.DictReader(f) if r["scope"] == PROGRAM}


def contiguous(listings, tails, addr):
    """Whether the listing beginning at `addr` covers its own bytes with no
    hole, from `addr` to the end of its last instruction.

    Measured rather than read off `size`, and asserted for `pd,34EF` in
    `--self-test`: the successor of a non-contiguous listing is not where
    `addr + size` says, so a "falls through into the next listing" reading
    would be an artefact of the index on exactly the rows where the export is
    already known to be a function-boundary guess. `pd_entry_forms.py` records
    the same trap for `pd,E2E4`, whose 28 instruction bytes are spread over a
    63-byte span."""
    _first, (last, stop) = tails[addr]
    if not last[0]:
        return False
    end = addr
    for a in sorted(listings):
        if a < addr:
            continue
        if a > stop:
            break
        if a > end:
            return False
        end = a + len(listings[a][0])
    return end == stop + len(last[0])


# --------------------------------------------------------------------------
# Transfer sites
# --------------------------------------------------------------------------

def transfer_target(d, a, op):
    """The address a transfer instruction at `a` names, or None.

    The three encodings come from `disasm8051`, which is where each one's
    arithmetic lives: the 16-bit operand of 0x02/0x12 stored high byte first,
    the 2 KiB page an `ajmp`/`acall` computes from the *next* PC, and the rel8
    displacement measured from the instruction's last byte. Returns None for
    an opcode that is not a transfer, which is how one walk covers the whole
    listing without a second reader of the same map."""
    if op in ABS_OPCODES:
        return (d[a + 1] << 8) | d[a + 2]
    if (op & 0x1F) in (0x01, 0x11):
        return paged_target(op, d[a + 1], a)
    if op in REL_OPCODES:
        return relative_target(op, d[a + OPCODE_LEN[op] - 1], a)
    return None


def byte_sites(pd):
    """{target: [site, ...]} for every position in the image whose bytes spell
    an `lcall` or `ljmp`, de-duplicated by site address.

    Keyed on the site address, not on the listing it was found through, and
    that is the load-bearing part: a per-listing walk over the listings' own
    spans finds 26 sites in 0x4C12-0x4D18 twice, because `pd/4D6F.asm` spans
    0x4A12-0x4E58 and holds rows at those addresses while `pd/4C12.asm`,
    `pd/4C19.asm`, `pd/4C20.asm` and `pd/4C27.asm` are the same bytes under
    other names. A byte scan walks each position once by construction, so the
    de-duplication here is what makes the two halves comparable.

    A byte pattern cannot tell code from data, so every site is a candidate:
    an operand byte of a longer instruction spells one too."""
    out = {}
    for i in range(len(pd) - 2):
        if pd[i] in ABS_OPCODES:
            out.setdefault((pd[i + 1] << 8) | pd[i + 2], []).append(i)
    return out


def listing_sites(pd, listings):
    """{target: [site, ...]} over the committed listings' own *decoded*
    instructions.

    The narrow half of the pair `byte_sites()` and this report, and the one
    that assigns a verdict: a site here is an instruction start a committed
    listing states, so it cannot be an operand byte. It is also the half that
    cannot see a transfer in a committed gap, which is why the two are
    reported together and neither is counted as corroboration of the other."""
    out = {}
    for a in sorted(listings):
        raw = listings[a][0]
        if not raw:
            continue
        t = transfer_target(pd, a, raw[0])
        if t is not None:
            out.setdefault(t, []).append(a)
    return out


# --------------------------------------------------------------------------
# The census
# --------------------------------------------------------------------------

def verdict_for(self_sites, succ_sites):
    """`shared-tail`, `falls-through-unentered` or `boundary-wrong`.

    Decided on the decoded (listing) populations, never on the byte scan. The
    byte scan finds a `lcall`-shaped byte pair naming almost any address in
    the image, so on that population `shared-tail` is the answer for nearly
    every row and the verdict stops discriminating; the decoded one separates
    0x34EF from 0x0012 on the bytes rather than on the accident that some
    operand pair happens to spell `12 00 13`."""
    if not succ_sites:
        return "falls-through-unentered"
    if not self_sites:
        return "boundary-wrong"
    return "shared-tail"


def is_clause_arm(ann_row):
    """Whether the row's comment carries one of the two clauses. `True` for a
    row with no annotation at all would be a claim about the program, so it is
    `False` and the family is the byte arm's membership that carries the
    weight; `--self-test` holds both arms apart on the counts."""
    return ann_row is not None and CLAUSE_RE.search(ann_row["comment"]) is not None


def survey(pd, index, listings, tails, ann):
    """One pass, so the report, `--csv` and `--check` cannot disagree.

    Every committed listing is classified, not only the ones that match, so
    `--check` fails on a listing that has *become* a candidate rather than on
    one that has stopped being one -- the failure mode a census that only ever
    reports its members cannot have. The walk is over the listings and the
    index is consulted per listing file, for the reason `load_index()` gives.

    The verdict and the byte-arm test both read the *opcode*, which is the
    first byte of the listing's own last instruction -- not the whole byte
    tuple, and not the mnemonic text. A tuple is never in `RETURNS`, so
    comparing the tuple would put every listing in the family and report a
    number no reader could account for."""
    dec = listing_sites(pd, listings)
    byts = byte_sites(pd)
    rows = []
    for head in sorted(tails):
        first, (last, _last_addr) = tails[head]
        row = index.get(first[2])
        if row is None:
            continue
        succ = head + int(row["size"])
        succ_row = index.get(f"{PROGRAM}/{succ:04X}.asm")
        self_sites = dec.get(head, [])
        succ_sites = dec.get(succ, [])
        in_byte_arm = (last[0][0] not in RETURNS
                       and last[0][0] not in TRANSFER_OPCODES
                       and succ_row is not None
                       and contiguous(listings, tails, head))
        ann_row = ann.get(head) or ann.get(norm_addr(row["addr"]))
        rows.append({
            "addr": head,
            "name": (ann_row or {}).get("name", ""),
            "type": (ann_row or {}).get("type", ""),
            "size": int(row["size"]),
            "successor": succ,
            "succ_name": succ_row["name"] if succ_row else "",
            "succ_size": int(succ_row["size"]) if succ_row else 0,
            "succ_first": mnemonic(pd, succ, succ) if succ < PD_LEN else "",
            "last_insn": last[1],
            "self_sites": ";".join(f"0x{s:04X}" for s in self_sites),
            "succ_sites": ";".join(f"0x{s:04X}" for s in succ_sites),
            "byte_succ_sites": ";".join(f"0x{s:04X}" for s in byts.get(succ, [])),
            "verdict": (verdict_for(self_sites, succ_sites) if in_byte_arm
                        else ""),
            "clause": "yes" if is_clause_arm(ann_row) else "no",
            "in_byte_arm": "yes" if in_byte_arm else "no",
        })
    return rows, dec, byts


def family(rows):
    """The rows in the byte arm, in address order."""
    return [r for r in rows if r["in_byte_arm"] == "yes"]


def clause_rows(rows):
    """The rows in the clause arm."""
    return [r for r in rows if r["clause"] == "yes"]


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------

def print_arms(rows):
    fam = family(rows)
    cl = clause_rows(rows)
    both = [r for r in fam if r["clause"] == "yes"]
    print("## 1. Two membership arms, and neither of them is the family")
    print()
    print(f"  clause arm, a regex over the comment: {len(cl)} row(s)")
    print("    matches \"not decoded here\" or \"no ret\"; this is a text match "
          "over prose, not a decode, and a row whose comment does not carry "
          "the clause is invisible to it whatever its bytes say")
    print(f"  byte arm, a decode: {len(fam)} row(s)")
    print("    the listing's last instruction is neither a return nor a "
          "transfer, and `addr + size` is another listing's entry")
    print(f"  both arms: {len(both)} row(s)")
    print()
    print("  The family is the byte arm. `pd,34EF` is in it, and it is not in "
          "the")
    print("  issue's stated filter's four rows, because `pd,34F2` begins "
          "`mov B,#0x60`")
    print("  and the `ljmp` is an instruction later.")
    print()


def print_table(rows, limit=None):
    fam = family(rows)
    shown = fam if limit is None else fam[:limit]
    print("## 2. The family, one row per candidate")
    print()
    print("| addr | listing | size | successor | successor's first instruction "
          "| verdict |")
    print("|---|---|---:|---|---|---|")
    for r in shown:
        print(f"| `0x{r['addr']:04X}` | `{r['name'] or '?'}` | {r['size']} | "
              f"`0x{r['successor']:04X}` | `{r['succ_first']}` | "
              f"{r['verdict']} |")
    if limit is not None and len(fam) > limit:
        print()
        print(f"  {len(fam) - limit} further row(s) are in "
              f"`../annotations/pd-no-ret-fallthrough.csv` and not here; this is "
              f"a report and the CSV is the census.")
    print()
    for v in VERDICTS:
        n = sum(1 for r in fam if r["verdict"] == v)
        print(f"  {v} — {n} row(s). {VERDICT_GLOSS[v]}")
    print()


def print_sites(rows, dec, byts):
    print("## 3. The entry-site census, and why it is de-duplicated")
    print()
    print(f"  byte scan over the image's {PD_LEN} bytes: "
          f"{sum(len(v) for v in byts.values())} site(s) naming "
          f"{len(byts)} distinct target(s)")
    print(f"  committed listings' own decoded instructions: "
          f"{sum(len(v) for v in dec.values())} site(s) naming "
          f"{len(dec)} distinct target(s)")
    print()
    print("  A per-listing walk over the listings' spans is neither of these "
          "and is")
    print("  wrong by a number it could not explain: `pd/4D6F.asm` spans "
          "0x4A12-0x4E58 and")
    print("  carries its own rows at 0x4C12-0x4D18, which are the same bytes "
          "`pd/4C12.asm`,")
    print("  `pd/4C19.asm`, `pd/4C20.asm` and `pd/4C27.asm` are the subjects "
          "of, so those")
    print("  26 sites are counted twice and 2040 become 2066. The byte scan "
          "walks each")
    print("  position once by construction, which is what makes the two halves "
          "comparable.")
    print()
    print("  **A byte pattern cannot tell code from data**, so a site the scan "
          "finds may")
    print("  be an operand byte and a target it misses may still be reached. "
          "Both are")
    print("  `not found by this method`, in both directions; a verdict is "
          "assigned from the")
    print("  decoded population only, because only there is a site known to be "
          "an")
    print("  instruction start.")
    print()


def sites_str(sites):
    """A `self_sites` cell as prose. The cell itself is `;`-separated because
    the csv module would quote a comma, and a quoted column in a census a
    reader greps is a worse trade than one separator nobody has to unescape."""
    return ", ".join(sites.split(";")) if sites else "nothing"


def print_answer(rows, pd):
    fam = family(rows)
    row = next((r for r in fam if r["addr"] == 0x34EF), None)
    print("## 4. `pd,34EF`, on its own bytes")
    print()
    if row is None:
        print("  not in the family on this tree; the census above says why")
        print()
        return
    print(f"  `pd,34EF` is {row['size']} byte(s), `{row['last_insn']}`, and a "
          f"committed listing")
    print(f"  transfers to it at {sites_str(row['self_sites'])}. Its successor "
          f"`pd,0x{row['successor']:04X}` is")
    print(f"  {row['succ_size']} bytes, `{row['succ_name']}`, beginning "
          f"`{row['succ_first']}`, and a committed")
    print(f"  listing transfers to *it* at {sites_str(row['succ_sites'])} — in "
          f"its own right, not")
    print("  only as 0x34EF's tail.")
    print()
    print("  So the pair is **two entries sharing a tail**, not one routine cut "
          "in half by")
    print("  the export, and `pd,34EF`'s own row is a `forwarder` rather than "
          "`unresolved`:")
    print("  the comment's \"the pointer's use is not decoded here\" was a "
          "statement about")
    print("  where the function boundary fell, not about where control goes. "
          "The effect on")
    print("  DPTR is `0x0424 + 0x60 * A`, and control returns to the address "
          "after whichever")
    print("  `lcall` was made — 0x67E3 or 0xCB43 — because "
          "`pd,10BC` ends in `ret` at 0x10C7.")
    print()
    print(f"  The other {len(fam) - 1} row(s) are candidates, not defects. "
          f"A listing this scan did")
    print("  not reach is not absent, and nothing here says a row's comment is "
          "wrong —")
    print("  only which ones the export's boundary put a claim about control "
          "flow where")
    print("  the bytes do not put one.")
    print()


def csv_values(row):
    out = []
    for c in COLUMNS:
        out.append(f"0x{row[c]:0{HEX_COLUMNS[c]}X}" if c in HEX_COLUMNS
                   else row[c])
    return out


def csv_table(rows):
    """`pd-no-ret-fallthrough.csv` as a string, for `--check` to diff.

    A string rather than a write to stdout, for the reason
    `pd_entry_forms.csv_table()` gives: `--check` compares the same bytes this
    prints, and the committed file is the product of the command this module
    documents. Written with the csv module's own dialect, so the committed file
    carries its CRLF terminator and `--check` reads it with `newline=""` --
    universal-newline translation would rewrite every row and report a
    difference on every run, which is a check nobody trusts."""
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(COLUMNS)
    for row in rows:
        w.writerow(csv_values(row))
    return buf.getvalue()


def write_csv(rows):
    w = csv.writer(sys.stdout)
    w.writerow(COLUMNS)
    for row in rows:
        w.writerow(csv_values(row))


def check_table(generated, path):
    """Exit code for `--check`: 0 when this run reproduces `path` exactly."""
    try:
        with open(path, newline="") as f:
            on_disk = f.read()
    except OSError as e:
        print(f"note: {e}", file=sys.stderr)
        return 1
    if generated == on_disk:
        print(f"{os.path.relpath(path, REPO)}: this run reproduces it byte for "
              f"byte ({generated.count(chr(10))} lines)")
        return 0
    print(f"note: {os.path.relpath(path, REPO)} differs from what this run "
          f"produced; the file is the product of the command in this module's "
          f"docstring, so regenerate rather than edit", file=sys.stderr)
    for line in difflib.unified_diff(on_disk.splitlines(),
                                     generated.splitlines(),
                                     "committed", "generated", lineterm="",
                                     n=0):
        print(line, file=sys.stderr)
    return 1


# --------------------------------------------------------------------------
# Self-test
# --------------------------------------------------------------------------

# The answer, as `--self-test` asserts it. Every figure is a property of the
# committed tree, re-derived here from the image and the committed tables
# rather than quoted, so a regenerated index that moved one of them fails
# instead of being held.
ORACLE = {
    # The two arms. Held apart on purpose: they are different questions, and
    # a single "candidates" figure would hide which predicate produced it.
    "clause_arm": 198,
    "byte_arm": 95,
    "both_arms": 80,
    "listings": 541,
    # The entry-site census, both populations.
    "byte_sites": 7266,
    "byte_targets": 1866,
    "listing_sites": 1923,
    "listing_targets": 1038,
    # The pair, in bytes rather than in counts.
    "pair": (0x34EF, 3, 0x34F2, 6),
    "pair_span": 9,
    "ret_at": 0x10C7,
    "call_34ef": (0x67E0, 0xCB40),
    "call_34f2": (0x6782,),
    # The double-count the de-duplication exists for.
    "overlap_span": (0x4C12, 0x4D18),
    "overlap_sites": 26,
    "overlap_sites_dedup": 2040,
}


def span_walk(pd, listings, tails):
    """(total, distinct) entry sites over every committed listing's own span,
    walked position by position -- the per-listing walk `--self-test` shows
    over-counting. Never used to decide anything; it exists so the
    de-duplication has a measurement behind it rather than a claim."""
    seen = {}
    for head in sorted(tails):
        (last, last_addr) = tails[head][1]
        for i in range(head, last_addr + len(last[0])):
            if pd[i] in ABS_OPCODES:
                seen[i] = seen.get(i, 0) + 1
    return sum(seen.values()), len(seen)


def self_test(pd, rows, dec, byts, index, listings, tails, ann) -> int:
    bad = 0

    def check(ok, text):
        nonlocal bad
        if not ok:
            bad += 1
        print(f"  {'ok  ' if ok else 'FAIL'}  {text}")

    print("pd_no_ret_fallthrough.py --self-test")

    fam = family(rows)
    cl = clause_rows(rows)
    both = [r for r in fam if r["clause"] == "yes"]

    check(len(cl) == ORACLE["clause_arm"],
          f"the clause arm is {ORACLE['clause_arm']} row(s) — a text match over "
          f"the comment, not a decode, and labelled as one wherever it is "
          f"printed")
    check(len(fam) == ORACLE["byte_arm"],
          f"the byte arm is {ORACLE['byte_arm']} row(s): the listing's last "
          f"instruction is neither a return nor a transfer and `addr + size` is "
          f"another listing's entry")
    check(len(both) == ORACLE["both_arms"] and 0x34EF in {r["addr"] for r in both},
          f"the two arms agree on {ORACLE['both_arms']} row(s), and `pd,34EF` is "
          f"one of them — so the byte arm is the predicate that finds it and the "
          f"issue's stated filter is not")

    # The two families the two arms produce are genuinely different sets, and
    # the byte arm is strictly the wider: a row whose comment does not carry
    # the clause is in it anyway, which is the whole argument for a decode arm
    # beside a text arm.
    check(len({r["addr"] for r in fam} - {r["addr"] for r in cl}) > 0,
          f"and the byte arm is not a subset of the clause arm: "
          f"{len(fam) - len(both)} row(s) qualify on their bytes while their "
          f"comment carries neither clause, which is what a text filter cannot "
          f"see")

    # The pair, on bytes.
    a, sa, b, sb = ORACLE["pair"]
    check(pd[a:a + sa] == b"\x90\x04\x24" and pd[b:b + sb] == b"\x75\xf0\x60\x02\x10\xbc",
          f"the bytes: `pd,0x{a:04X}` is `90 04 24` and `pd,0x{b:04X}` is "
          f"`75 f0 60 / 02 10 bc`, contiguous, so the span from 0x{a:04X} to "
          f"0x{a + ORACLE['pair_span'] - 1:04X} is {ORACLE['pair_span']} bytes "
          f"and not 0x{sb:02X} — {sb} is 0x{b:04X}'s own size")
    check(int(index[f"{PROGRAM}/{a:04X}.asm"]["size"]) == sa
          and int(index[f"{PROGRAM}/{b:04X}.asm"]["size"]) == sb,
          f"and `listing-index.csv` records size={sa} and size={sb} for the "
          f"pair, which is where the successor address comes from")
    check(pd[ORACLE["ret_at"]] == RET,
          f"`pd,10BC` ends in 0x{RET:02X} (`ret`) at "
          f"0x{ORACLE['ret_at']:04X}, so control does return to the address "
          f"after whichever `lcall` was made")

    # The two entries, and the claim the verdict rests on.
    call_a = tuple(int(s, 16) for s in
                   next(r for r in rows if r["addr"] == a)["self_sites"].split(";"))
    call_b = tuple(int(s, 16) for s in
                   next(r for r in rows if r["addr"] == a)["succ_sites"].split(";"))
    check(call_a == ORACLE["call_34ef"] and call_b == ORACLE["call_34f2"],
          f"`lcall 0x{a:04X}` is at "
          f"{', '.join('0x%04X' % s for s in call_a)} and `lcall 0x{b:04X}` is at "
          f"{', '.join('0x%04X' % s for s in call_b)} — every one a committed "
          f"instruction start, which is why the successor is a second entry and "
          f"not only 0x{a:04X}'s tail")
    check(next(r for r in rows if r["addr"] == a)["verdict"] == "shared-tail",
          f"so `pd,0x{a:04X}`'s verdict is `shared-tail`: two entries over one "
          f"tail, rather than one routine cut in half by the export")

    # The two populations, and the de-duplication behind the wide one.
    check(sum(len(v) for v in byts.values()) == ORACLE["byte_sites"]
          and len(byts) == ORACLE["byte_targets"],
          f"the byte scan finds {ORACLE['byte_sites']} `lcall`/`ljmp` site(s) "
          f"naming {ORACLE['byte_targets']} distinct target(s) — the wide half, "
          f"and every one of them a candidate, because a byte pattern cannot "
          f"tell code from data")
    check(sum(len(v) for v in dec.values()) == ORACLE["listing_sites"]
          and len(dec) == ORACLE["listing_targets"],
          f"the committed listings' own decoded instructions carry "
          f"{ORACLE['listing_sites']} site(s) naming {ORACLE['listing_targets']} "
          f"distinct target(s) — the narrow half, and the one verdicts are "
          f"assigned from")

    lo, hi = ORACLE["overlap_span"]
    total, distinct = span_walk(pd, listings, tails)
    covered = {a for a in listings if lo <= a <= hi}
    check(len(covered) > 1 and total == ORACLE["overlap_sites_dedup"]
          + ORACLE["overlap_sites"] and distinct == ORACLE["overlap_sites_dedup"],
          f"the de-duplication: a per-listing walk over the listings' own spans "
          f"finds {total} site(s) where the spans hold {distinct}, because "
          f"0x{lo:04X}-0x{hi:04X} is inside `pd/4D6F.asm`'s span *and* the "
          f"subject of {len(covered)} other listings — {ORACLE['overlap_sites']} "
          f"sites counted twice, and a census reporting {total} would be wrong "
          f"by a figure it could not explain")

    # The two silent misreadings, asserted rather than described.
    prefixed = [a for a, r in ann.items() if r["addr"].lower().startswith("0x")]
    bare = [a for a, r in ann.items() if not r["addr"].lower().startswith("0x")]
    raw = [int(r["addr"], 16) for r in csv.DictReader(
        open(ANNOTATIONS, newline="")) if r["scope"] == PROGRAM]
    check(prefixed and bare and len(prefixed) + len(bare) == len(ann)
          and sorted(raw) == sorted(ann),
          f"the join: `ghidra-functions.csv` spells its address column two ways "
          f"— {len(prefixed)} `pd` row(s) `0x`-prefixed and {len(bare)} bare — "
          f"and `int(addr, 16)` reads only the first, dropping the other "
          f"{len(bare)} silently rather than failing, so the column is "
          f"normalised on the way in and the two readings agree here")

    head_off = offset_for_runtime(a, PD_REGION)
    check(head_off == PD_BASE + a and head_off != PD_MARKER[0],
          f"the path index: runtime 0x{a:04X} is file 0x{head_off:05X}, so the "
          f"listing is {PROGRAM}/{a:04X}.asm — the base is 0x{PD_BASE:05X} and "
          f"not `PD_MARKER`'s 0x{PD_MARKER[0]:05X}, which is the marker 0x40 "
          f"bytes *inside* the image, and using it decodes cleanly at the "
          f"wrong address")

    check(pd[a:a + ORACLE["pair_span"]] != d_full(pd)[a:a + ORACLE["pair_span"]],
          f"and a pd runtime address is not a file offset: slicing the dump at "
          f"[0x{a:04X}:0x{a + ORACLE['pair_span']:04X}] reads the main EC's "
          f"common area, which is a different program and also decodes")

    print()
    print("self-test FAILED" if bad else "self-test passed")
    return 1 if bad else 0


def d_full(pd):
    """The bytes at 0x34EF-0x34F7 *of the main EC's common area*, as the last
    check needs them: the whole dump sliced at the pd runtime address, which is
    the misreading being ruled out. Re-read from the file rather than carried
    in, so the check is against the committed image and not against itself."""
    with open(FIRMWARE, "rb") as f:
        whole = f.read()
    return whole[:PD_LEN]


# --------------------------------------------------------------------------

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("firmware", nargs="?", default=FIRMWARE,
                    help="raw EC firmware image (default: the committed one)")
    ap.add_argument("--csv", action="store_true",
                    help="write one row per candidate on stdout")
    ap.add_argument("--check", action="store_true",
                    help="regenerate ../annotations/pd-no-ret-fallthrough.csv "
                         "and diff it")
    ap.add_argument("--self-test", action="store_true",
                    help="assert the pair's bytes, the two arms, the entry-site "
                         "census, the de-duplication and the two path/join "
                         "misreadings against the committed tree")
    ap.add_argument("--limit", type=int, default=None,
                    help="print at most N rows of the table (the CSV has them "
                         "all)")
    args = ap.parse_args(argv)

    with open(args.firmware, "rb") as f:
        d = f.read()
    off, magic = PD_MARKER
    if d[off:off + len(magic)] != magic:
        print(f"no {magic.decode()!r} marker at file 0x{off:05X} -- this is "
              f"not the image the recorded counts were taken from",
              file=sys.stderr)
        return 1
    pd = d[PD_BASE:PD_BASE + PD_LEN]

    _starts, listings, tails = read_listings()
    index = load_index()
    ann = load_annotations()
    rows, dec, byts = survey(pd, index, listings, tails, ann)

    if args.self_test:
        return self_test(pd, rows, dec, byts, index, listings, tails, ann)

    if args.csv:
        write_csv(rows)
        return 0

    if args.check:
        return check_table(csv_table(rows), OUT_CSV)

    print_arms(rows)
    print_table(rows, args.limit)
    print_sites(rows, dec, byts)
    print_answer(rows, pd)
    return 0


if __name__ == "__main__":
    sys.exit(main())
