#!/usr/bin/env python3
"""The `pd` code-table dispatch call sites, held to the framing their rows claim.

Seven committed `pd` listings reach one of the PD image's two code-table
dispatchers, and each has its table starting at the address the `lcall` returns
to: both dispatchers begin `pop dph ; pop dpl ; mov r0,a`, so DPTR already
points at the table before the first `movc`, and neither of them returns.
`docs/findings/pd-call-site-table-framing.md` is the reading; this file is what
it stands on.

**The sites are enumerated, never counted.** `SITES` below is a list, not a
figure taken from a census, because the property being held is about these seven
rows and a count of the tree moves every time a listing lands. Five of the seven
are the ones issue #643 corrected (`IN_SCOPE`); `0xA339` and `CB2A` were already
framed and are held only to the framing, which is what makes them the reference
the correction was checked against.

**Every address here is re-derived rather than transcribed.** The table start is
the `lcall`'s address plus three, from the framing; the `lcall` itself is read
out of the committed image and its target compared against the dispatcher the
site enumerates; the dispatcher prologue is read out of the image at both
dispatchers; and the first record's three bytes are read from the image and
compared against the bytes the comment quotes. A hand-typed table start that
disagreed with the image fails here rather than agreeing with the comment beside
it.

**Where each figure comes from, and why that matters.** The entry count, the
key range, the default and the table's last byte are read from
`../annotations/pd-index-table-spans.csv`, which `ec/tools/pd_index_tables.py`
generates. They are not re-derived here: five of the seven listings stop
mid-table, so the `.asm` bytes cannot close them, and reimplementing
`decode_index_table.py`'s layout is exactly the drift that importing it exists
to prevent. What this file adds is the direction that catches a regeneration
which *moves* a table -- a row whose comment keeps the old figures fails, and
the span CSV is regenerated by its own tool, not by this one.

**What the negative control is, and what was tried instead.** The property issue
#643 asks for is that no committed row describes the bytes after an `lcall` as
code, and the check that carries it is the positive one: a row that reads those
bytes as an instruction sequence has no reason to name where they begin or where
they stop, because under that reading they are neither a beginning nor an end.
`PRE_CHANGE` below holds the five texts this change replaced and requires each
one to fail that check, which is the negative control with teeth -- it is made
of the actual misframings rather than of a guess at their shape.

Two narrower rules were written and dropped, and the reasons are load-bearing
enough to record. A regex list of code-transfer verbs does not survive contact
with a correct row: `pd 0xA339` says "not a fall-through path" inside a denial,
so the list either reddens a right answer or is scoped until it catches
nothing. And a rule forbidding a comment to name *any* address inside its own
table span is wrong too, because naming an in-span address is what the corrected
rows do in order to show the misframing -- `pd 133F` names `0x1370` precisely to
say the listing's `inc R1` there is a record's key byte. What separates that
from the old reading is the positive check, not the shape of the sentence, and
a rule that looked like it was working while catching none of the real cases
would be worse than the scope note this is.

**It does not re-run `pd_index_tables.py`.** Asserting the generator against
itself would let a stale pair pass; the census's own `--self-test` is where that
argument lives, and this file reads its committed output as a peer.
"""
import csv
import re
import unittest
from pathlib import Path

HERE = Path(__file__).parent
DECOMPILED = HERE.parent / 'decompiled'
FIRMWARE = HERE.parent / 'firmware' / 'GMxMGxx_11.800'
ANNOTATIONS = HERE.parent / 'annotations'
FUNCTIONS_CSV = ANNOTATIONS / 'ghidra-functions.csv'
SPANS_CSV = ANNOTATIONS / 'pd-index-table-spans.csv'

# The PD image is a separate program at file offset 0x20000 with its own address
# space, so a runtime address is not a file offset. `PD_IMAGE_BASE` is the
# mapping and every byte read below goes through it -- a reader that indexed the
# dump by runtime address would read the wrong program's bytes throughout, and
# in the main EC's 0x0000-0x1FFFF common area it would read plausible ones.
PD_IMAGE_BASE = 0x20000

# The prologue both dispatchers open with: `pop dph ; pop dpl ; mov r0,a`. It is
# the whole of the framing claim in five bytes of assertion -- the two pops are
# what take the return address the `lcall` pushed, and the `mov r0,a` is the
# selector save. A dispatcher whose prologue differed would not put its table at
# the return address, and every table start below would move with it.
DISPATCHER_PROLOGUE = bytes.fromhex("d0 83 d0 82 f8")

# `lcall` is a three-byte instruction, so the return address -- and with it the
# table's first byte -- is three past the call site. Nothing derives this from
# the census; it is the framing, and `test_the_table_start_is_the_framing` is
# where it is checked rather than assumed.
LCALL_LEN = 3

# (the `addr` cell the annotation row carries, the call site, the dispatcher).
# The row's own `addr` spelling is used verbatim so a re-spelling shows up as a
# missing row rather than as a silently different one.
SITES = (
    ('133F', 0x136C, 0x119C),
    ('0x1EFE', 0x1F2D, 0x119C),
    ('0x4C27', 0x4C35, 0x119C),
    ('0xA339', 0xA34B, 0x119C),
    ('ADAB', 0xADE6, 0x119C),
    ('C873', 0xC879, 0x119C),
    ('CB2A', 0xCB4A, 0x11C2),
)

# The five issue #643 corrected. The other two already framed their table and
# are not rewritten here, so the census figures below are not asked of them --
# a row that says where its table begins without restating its entry count is
# not a row that has gone wrong. `pd 0xA339` names 0xA36D where the table's
# last byte is 0xA366; that residual is recorded in the write-up rather than
# fixed here, because the row does not claim the bytes are instructions.
IN_SCOPE = ('133F', '0x1EFE', '0x4C27', 'ADAB', 'C873')

# The five texts this change replaced, transcribed from the annotation rows as
# they stood before it. Each is held to fail the framing checks; the `pd ADAB`
# one is the issue's own worked example -- "tail-jumps to 0xA8AE" with no table
# named anywhere in the row.
PRE_CHANGE = {
    '133F': ("otherwise it reads XDATA 0x805, passes it to 0x119C, decrements R6, increments R1 "
             "and jumps into the 32-bit XDATA adder at 0x1013."),
    '0x1EFE': ("The fall-through at 0x1F29 is a third exit: it reads XDATA 0x0805, dispatches it "
               "through 0x119C (`dispatch_code_table`), decrements R7, ORs the result with R4 and "
               "transfers to 0x1820 with `ajmp` rather than returning."),
    '0x4C27': ("Prologue 0x4C27..0x4C37 immediately after RET at 0x4C26; its MOV A,R5 at 0x4C34 "
               "supplies the selector to LCALL 0x119C at 0x4C35. The framing is conditional on "
               "entry to 0x4C27: reset-to-0x4C27 reachability, all upstream callers, and occurrence "
               "of any selector are not established"),
    'ADAB': ("It then adds 2 to R1, reads XDATA 0x0805, calls 0x119C, loads R6 with 0x7A and "
             "tail-jumps to 0xA8AE. There is no ret; the .c renders that tail-jump as a call to a "
             "routine it names dispatch_code_table, whose body is not in this file pair."),
    'C873': ("Within 0xC873 it stores R7 at XDATA 0x0819, calls 0x119C with A = R5, and runs a "
             "carry/rotate sequence over R5, R0, @R1 and direct byte 0x77 ending in a compare of "
             "A against 0x55. On a match it stores 0x55 through @R1, calls 0x96FB, ORs 0x08 into "
             "XDATA 0x0819 and returns"),
}

# A hex literal the comment has to carry, matched so a longer number cannot
# satisfy it: `0x01` inside `0x0134` is a different address, and a key-range
# check that can be passed by an unrelated four-digit address is not a check.
HEX = r'0x%04X(?![0-9A-Fa-f])'
HEX8 = r'0x%02X(?![0-9A-Fa-f])'


def image():
    """The committed firmware, read once at import.

    One read rather than one per test, for the reason
    `test_bank1_e582_framing.py` gives its own `G.load_images()`: a 256 KiB
    image read per case is a cost worth not paying, and the assertions below
    compare what they read against committed tables and comments, so a wrong
    read fails rather than agreeing with itself.
    """
    return FIRMWARE.read_bytes()


IMAGE = image()


def pd_bytes(addr, length):
    """`length` bytes of the PD image at runtime `addr`."""
    start = PD_IMAGE_BASE + addr
    return IMAGE[start:start + length]


def listing_name(addr):
    """The `pd/<name>.asm` stem for a row's `addr` cell.

    The listing is named for the function's entry, which is the row's `addr`
    cell verbatim, so the two spellings of one address in this tree (`133F` and
    `0x1EFE` beside each other in the same column) both resolve rather than one
    of them needing a special case.
    """
    return '%04X' % int(addr, 16)


def listing_addresses(name):
    """Every address a committed `pd` listing shows an instruction at.

    Read here rather than through `merge_annotation_shards.parse_listing`,
    which leaves its file handle open and puts a ResourceWarning on every call
    under unittest; that is a shared tool's business and not this suite's, and a
    new suite that added to the noise would be a merge hazard on a file other
    agents are touching. Only the address column is wanted, and it is the
    first token of every line that is not a `;` comment, so nothing here can
    disagree with the mnemonic grammar about what a line means.
    """
    path = DECOMPILED / 'pd' / (name + '.asm')
    if not path.is_file():
        raise AssertionError('no listing at %s' % path)
    out = set()
    for line in path.read_text(errors='replace').splitlines():
        if not line.strip() or line.startswith(';'):
            continue
        head = line.split(None, 1)[0]
        out.add(int(head, 16))
    return out


def annotation_rows():
    """`{addr: row}` for the `pd` scope of the committed annotation CSV."""
    with open(FUNCTIONS_CSV, newline='', encoding='utf-8') as f:
        return {r['addr']: r for r in csv.DictReader(f) if r['scope'] == 'pd'}


def span_rows():
    """`{site_runtime: row}` of the committed census, keyed by the call site."""
    with open(SPANS_CSV, newline='', encoding='utf-8') as f:
        return {int(r['site_runtime'], 16): r for r in csv.DictReader(f)}


def facts(addr):
    """Everything one site is held to: its row, its census row, its framing.

    Raises rather than returning a half-filled dict, because a site with no
    annotation row or no census row is a different failure from a site whose
    comment has drifted, and a caller handed the first would report the second.
    An `assert` would be the wrong tool for that: it disappears under `-O`,
    and the caller would go on to read a `None` as an address.
    """
    row = annotation_rows().get(addr)
    if row is None:
        raise AssertionError('no pd annotation row at addr %r' % addr)
    site, dispatcher = next((s, d) for a, s, d in SITES if a == addr)
    span = span_rows().get(site)
    if span is None:
        raise AssertionError('pd-index-table-spans.csv has no row for site 0x%04X' % site)
    return {
        'addr': addr,
        'listing': listing_name(addr),
        'comment': row['comment'],
        'site': site,
        'dispatcher': dispatcher,
        'span': span,
        # Derived from the framing, never read out of the census: if the two
        # disagree the framing is what has to be defended, not the census.
        'table_start': site + LCALL_LEN,
        'last_byte': int(span['table_end'], 16) - 1 - PD_IMAGE_BASE,
        'entries': int(span['entries']),
        'first_key': int(span['first_key'], 16),
        'last_key': int(span['last_key'], 16),
        'default': int(span['default_runtime'], 16),
    }


def names_table_start(comment, f):
    """Whether the row says where its table begins. The check with the teeth.

    A row that reads the bytes after the `lcall` as an instruction sequence has
    no reason to name the address they start at -- there is nothing there for
    it. All five texts in `PRE_CHANGE` fail this, and that is what makes the
    suite a check rather than a description.
    """
    return bool(re.search(HEX % f['table_start'], comment))


def figures_missing(comment, f):
    """Which of the census row's figures the comment does not carry.

    The entry count, the first and last selector keys, the default and the
    table's last byte. Asking for the last byte rather than only the start is
    deliberate: a row that knows where its table begins and not where it stops
    has a framing with no end, and an instruction sequence that runs on from the
    start address is precisely what such a row goes on to claim.
    """
    missing = []
    if str(f['entries']) + '-entry' not in comment:
        missing.append('%d entries' % f['entries'])
    for label, key in (('first key', f['first_key']), ('last key', f['last_key'])):
        if not re.search(HEX8 % key, comment):
            missing.append('%s 0x%02X' % (label, key))
    if not re.search(HEX % f['default'], comment):
        missing.append('default 0x%04X' % f['default'])
    if not re.search(HEX % f['last_byte'], comment):
        missing.append('table end 0x%04X' % f['last_byte'])
    return missing


class FramingTests(unittest.TestCase):
    """The framing itself, read from the committed image rather than the census."""

    def test_both_dispatchers_open_by_popping_the_return_address(self):
        for dispatcher in (0x119C, 0x11C2):
            self.assertEqual(pd_bytes(dispatcher, len(DISPATCHER_PROLOGUE)),
                             DISPATCHER_PROLOGUE,
                             'pd 0x%04X does not open with pop dph ; pop dpl ; mov r0,a'
                             % dispatcher)

    def test_each_site_is_an_lcall_to_the_dispatcher_it_names(self):
        for addr, site, dispatcher in SITES:
            raw = pd_bytes(site, LCALL_LEN)
            self.assertEqual(raw[0], 0x12,
                             'pd %s: 0x%04X does not hold an lcall opcode' % (addr, site))
            self.assertEqual((raw[1] << 8) | raw[2], dispatcher,
                             'pd %s: the call at 0x%04X names another dispatcher'
                             % (addr, site))

    def test_the_table_start_is_the_framing_not_the_census_column(self):
        # The census carries its own `table_runtime`. It is checked against the
        # framing -- `site + 3`, from the pops above -- rather than taken on
        # trust, so a census row that drifted from the image cannot quietly
        # become the oracle the comments are held to.
        spans = span_rows()
        for addr, site, dispatcher in SITES:
            self.assertIn(site, spans,
                          'pd %s: pd-index-table-spans.csv has no row for 0x%04X'
                          % (addr, site))
            self.assertEqual(int(spans[site]['table_runtime'], 16), site + LCALL_LEN,
                             'pd %s: the census puts the table where the framing '
                             'does not' % addr)
            self.assertEqual(int(spans[site]['reader'], 16), dispatcher,
                             'pd %s: the census names another reader' % addr)

    def test_the_first_record_is_the_bytes_the_comment_quotes(self):
        # Each corrected row quotes its table's first record, so a reader can
        # see the misframing rather than take it on trust. The bytes are read
        # here, so a row quoting bytes the image does not hold fails.
        for addr in IN_SCOPE:
            f = facts(addr)
            quoted = '`%s`' % ' '.join('%02x' % b for b in pd_bytes(f['table_start'], 3))
            self.assertIn(quoted, f['comment'],
                          'pd %s: the comment does not quote its first record %s'
                          % (addr, quoted))

    def test_the_1efe_table_is_three_bytes_and_the_fourth_is_the_next_record(self):
        # The issue's body states this correctly and the row it described did
        # not: the table at 0x1F30 is `1f 4c 01`, and the fourth byte `20` is
        # record 2's high target byte. Held as bytes so the row cannot drift
        # back into reading all four as one instruction.
        f = facts('0x1EFE')
        record = pd_bytes(f['table_start'], 6)
        self.assertEqual(record.hex(' '), '1f 4c 01 20 7f 02')
        self.assertIn('`1f 4c 01`', f['comment'])


class RowTests(unittest.TestCase):
    """The seven committed rows, held to the framing they now carry."""

    def test_every_site_names_where_its_table_begins(self):
        for addr, _, _ in SITES:
            f = facts(addr)
            self.assertTrue(names_table_start(f['comment'], f),
                            'pd %s: the comment does not name 0x%04X, so it does not '
                            'say where its table begins'
                            % (addr, f['table_start']))

    def test_the_five_corrected_rows_carry_the_census_figures(self):
        for addr in IN_SCOPE:
            f = facts(addr)
            missing = figures_missing(f['comment'], f)
            self.assertEqual(missing, [], 'pd %s: missing %s' % (addr, ', '.join(missing)))

    def test_the_1efe_row_exists(self):
        # Issue #643's own body says `pd 0x1EFE` "has no row at all" and routes
        # it to #489. It has one, and it was one of the five corrected here.
        # This is the regression guard on that finding, so a later reader does
        # not re-route an existing row as a missing one.
        row = annotation_rows().get('0x1EFE')
        self.assertIsNotNone(row, 'pd 0x1EFE has no annotation row')
        self.assertEqual(row['name'], 'gate_0803_then_dispatch_through_code_table')
        self.assertTrue(row['evidence'].strip(),
                        'an annotation without an evidence citation is a claim, '
                        'not a finding')


class NegativeControlTests(unittest.TestCase):
    """The texts this change replaced, held to the checks that replaced them.

    A check that passes on the tree it was written to fix is not a check. Each
    case is one of those texts, run through the same predicates the live rows
    are held to, so the suite would have been red before this change and is
    green only because the rows now say what they say.
    """

    def test_every_pre_change_comment_fails_the_framing_checks(self):
        self.assertEqual(set(PRE_CHANGE), set(IN_SCOPE))
        for addr in IN_SCOPE:
            f = facts(addr)
            self.assertFalse(names_table_start(PRE_CHANGE[addr], f),
                             'pd %s: the text this change replaced already names its '
                             "table's start, so that check is not what fixed it" % addr)
            self.assertNotEqual(figures_missing(PRE_CHANGE[addr], f), [],
                                'pd %s: the text this change replaced already carries '
                                'the census figures' % addr)

    def test_a_row_that_names_the_start_but_not_the_end_is_refused(self):
        # The half-measure the figures check exists to catch, which is the
        # narrow form of issue #643's Done criterion: naming where the table
        # begins is not a framing until the table has an end.
        f = facts('ADAB')
        partial = ('Reads XDATA 0x0805 into A and calls 0x119C at 0xADE6. 0x119C pops the '
                   'return address into DPTR, so its table begins at 0x%04X.'
                   % f['table_start'])
        self.assertTrue(names_table_start(partial, f))
        self.assertIn('table end 0x%04X' % f['last_byte'], figures_missing(partial, f))


class ListingTests(unittest.TestCase):
    """Where the committed `.asm` listings reach, and where they stop.

    Five of the seven stop mid-table, which is why the entry count, the key
    range, the default and the last byte are cited from the census rather than
    re-derived from the listing. That is a property of the listings, so it is
    held here rather than asserted in prose: a listing that grew to carry its
    whole table would leave the suite checking less than its docstring says it
    checks, which is the failure mode this class exists to prevent.
    """

    def test_only_two_listings_reach_their_own_table_s_last_byte(self):
        complete, truncated = [], []
        for addr, _, _ in SITES:
            f = facts(addr)
            shown = listing_addresses(f['listing'])
            self.assertIn(f['table_start'], shown,
                          'pd %s: its listing does not reach its own table start'
                          % addr)
            (complete if f['last_byte'] in shown else truncated).append(addr)
        self.assertEqual(sorted(complete), ['0xA339', 'C873'],
                         'the set of listings that close their own table moved; the '
                         'census figures the write-up quotes assume only these two do')
        self.assertEqual(len(complete) + len(truncated), len(SITES))

    def test_the_4c27_listing_skips_the_middle_of_its_own_table(self):
        # Where the hand-walk cross-check in the write-up stops, said in a test
        # rather than in a sentence: `0x4C40` decodes as an `ljmp 0x4D15` and
        # the disassembler follows it, so the fourth record's key byte is not
        # in `4C27.asm` at all and only the image can finish that table.
        shown = listing_addresses('4C27')
        self.assertIn(0x4C38, shown)
        self.assertIn(0x4D15, shown)
        self.assertEqual([a for a in sorted(shown) if 0x4C43 <= a <= 0x4D14], [])


if __name__ == '__main__':
    unittest.main()