; DxeOverClock @ 000021B8   submit_oc_descriptor   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, DxeOverClock.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 000021B8.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

000021B8 40 55 - - - - - - - -         push     RBP
000021BA 53 - - - - - - - - -          push     RBX
000021BB 57 - - - - - - - - -          push     RDI
000021BC 48 8b ec - - - - - - -        mov      RBP, RSP
000021BF 48 83 ec 60 - - - - - -       sub      RSP, 0x60
000021C3 48 8b 02 - - - - - - -        mov      RAX, qword ptr [RDX]
000021C6 48 8b d9 - - - - - - -        mov      RBX, RCX
000021C9 48 8d 4d 28 - - - - - -       lea      RCX, [RBP + 0x28]
000021CD 48 8b fa - - - - - - -        mov      RDI, RDX
000021D0 ff 50 40 - - - - - - -        call     qword ptr [RAX + 0x40]
000021D3 48 85 c0 - - - - - - -        test     RAX, RAX
000021D6 0f 88 a2 00 00 00 - - - -     js       0x0000227e
000021DC 83 7d 28 00 - - - - - -       cmp      dword ptr [RBP + 0x28], 0x0
000021E0 0f 85 98 00 00 00 - - - -     jnz      0x0000227e
000021E6 48 8b 07 - - - - - - -        mov      RAX, qword ptr [RDI]
000021E9 48 8d 4d 30 - - - - - -       lea      RCX, [RBP + 0x30]
000021ED ff 50 38 - - - - - - -        call     qword ptr [RAX + 0x38]
000021F0 48 85 c0 - - - - - - -        test     RAX, RAX
000021F3 78 7d - - - - - - - -         js       0x00002272
000021F5 f6 45 30 0f - - - - - -       test     byte ptr [RBP + 0x30], 0xf
000021F9 75 77 - - - - - - - -         jnz      0x00002272
000021FB 48 8d 45 d0 - - - - - -       lea      RAX, [RBP + -0x30]
000021FF c7 45 38 30 00 00 00 - - -    mov      dword ptr [RBP + 0x38], 0x30
00002206 48 3b c3 - - - - - - -        cmp      RAX, RBX
00002209 74 12 - - - - - - - -         jz       0x0000221d
0000220B 41 b8 30 00 00 00 - - - -     mov      R8D, 0x30
00002211 48 8d 4d d0 - - - - - -       lea      RCX, [RBP + -0x30]
00002215 48 8b d3 - - - - - - -        mov      RDX, RBX
00002218 e8 a3 e0 ff ff - - - - -      call     0x000002c0
0000221D 48 8b 07 - - - - - - -        mov      RAX, qword ptr [RDI]
00002220 4c 8d 4d 38 - - - - - -       lea      R9, [RBP + 0x38]
00002224 83 65 d8 00 - - - - - -       and      dword ptr [RBP + -0x28], 0x0
00002228 48 8d 55 d0 - - - - - -       lea      RDX, [RBP + -0x30]
0000222C 83 65 e0 00 - - - - - -       and      dword ptr [RBP + -0x20], 0x0
00002230 41 b8 30 00 00 00 - - - -     mov      R8D, 0x30
00002236 c6 44 24 28 08 - - - - -      mov      byte ptr [RSP + 0x28], 0x8
0000223B 33 c9 - - - - - - - -         xor      ECX, ECX
0000223D c7 45 d0 00 00 05 00 - - -    mov      dword ptr [RBP + -0x30], 0x50000
00002244 c7 45 d4 1b 00 00 00 - - -    mov      dword ptr [RBP + -0x2c], 0x1b
0000224B c7 45 dc 1c 00 00 00 - - -    mov      dword ptr [RBP + -0x24], 0x1c
00002252 c6 44 24 20 00 - - - - -      mov      byte ptr [RSP + 0x20], 0x0
00002257 ff 10 - - - - - - - -         call     qword ptr [RAX]
00002259 48 85 c0 - - - - - - -        test     RAX, RAX
0000225C 78 2a - - - - - - - -         js       0x00002288
0000225E 83 7d d8 00 - - - - - -       cmp      dword ptr [RBP + -0x28], 0x0
00002262 48 b9 07 00 00 00 00 00 00 80 mov      RCX, -0x7ffffffffffffff9
0000226C 48 0f 45 c1 - - - - - -       cmovnz   RAX, RCX
00002270 eb 16 - - - - - - - -         jmp      0x00002288
00002272 48 b8 06 00 00 00 00 00 00 80 mov      RAX, -0x7ffffffffffffffa
0000227C eb 0a - - - - - - - -         jmp      0x00002288
0000227E 48 b8 03 00 00 00 00 00 00 80 mov      RAX, -0x7ffffffffffffffd
00002288 48 83 c4 60 - - - - - -       add      RSP, 0x60
0000228C 5f - - - - - - - - -          pop      RDI
0000228D 5b - - - - - - - - -          pop      RBX
0000228E 5d - - - - - - - - -          pop      RBP
0000228F c3 - - - - - - - - -          ret      
