; EcPs2Kbd @ 00000B60   memmove_bytes   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, EcPs2Kbd.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00000B60.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00000B60 57 - - - - - - - - -          push     RDI
00000B61 56 - - - - - - - - -          push     RSI
00000B62 53 - - - - - - - - -          push     RBX
00000B63 66 9c - - - - - - - -         pushf    
00000B65 51 - - - - - - - - -          push     RCX
00000B66 48 8b f2 - - - - - - -        mov      RSI, RDX
00000B69 48 8b f9 - - - - - - -        mov      RDI, RCX
00000B6C 49 8b c8 - - - - - - -        mov      RCX, R8
00000B6F b2 00 - - - - - - - -         mov      DL, 0x0
00000B71 48 8b c6 - - - - - - -        mov      RAX, RSI
00000B74 48 2b c7 - - - - - - -        sub      RAX, RDI
00000B77 73 16 - - - - - - - -         jnc      0x00000b8f
00000B79 48 8d 1c 31 - - - - - -       lea      RBX, [RCX + RSI*0x1]
00000B7D 48 f7 d8 - - - - - - -        neg      RAX
00000B80 48 3b df - - - - - - -        cmp      RBX, RDI
00000B83 72 0a - - - - - - - -         jc       0x00000b8f
00000B85 48 8b f3 - - - - - - -        mov      RSI, RBX
00000B88 48 8d 3c 39 - - - - - -       lea      RDI, [RCX + RDI*0x1]
00000B8C b2 01 - - - - - - - -         mov      DL, 0x1
00000B8E fd - - - - - - - - -          std      
00000B8F 48 83 f9 08 - - - - - -       cmp      RCX, 0x8
00000B93 72 68 - - - - - - - -         jc       0x00000bfd
00000B95 48 83 f8 08 - - - - - -       cmp      RAX, 0x8
00000B99 72 62 - - - - - - - -         jc       0x00000bfd
00000B9B 48 8b c6 - - - - - - -        mov      RAX, RSI
00000B9E 48 8b df - - - - - - -        mov      RBX, RDI
00000BA1 48 83 e0 07 - - - - - -       and      RAX, 0x7
00000BA5 48 83 e3 07 - - - - - -       and      RBX, 0x7
00000BA9 84 d2 - - - - - - - -         test     DL, DL
00000BAB 74 06 - - - - - - - -         jz       0x00000bb3
00000BAD 48 ff ce - - - - - - -        dec      RSI
00000BB0 48 ff cf - - - - - - -        dec      RDI
00000BB3 48 3b c3 - - - - - - -        cmp      RAX, RBX
00000BB6 75 1a - - - - - - - -         jnz      0x00000bd2
00000BB8 48 85 c0 - - - - - - -        test     RAX, RAX
00000BBB 74 15 - - - - - - - -         jz       0x00000bd2
00000BBD 84 d2 - - - - - - - -         test     DL, DL
00000BBF 75 07 - - - - - - - -         jnz      0x00000bc8
00000BC1 48 f7 d8 - - - - - - -        neg      RAX
00000BC4 48 83 c0 08 - - - - - -       add      RAX, 0x8
00000BC8 48 91 - - - - - - - -         xchg     RAX, RCX
00000BCA 48 2b c1 - - - - - - -        sub      RAX, RCX
00000BCD f3 a4 - - - - - - - -         movsb.rep RDI, RSI
00000BCF 48 8b c8 - - - - - - -        mov      RCX, RAX
00000BD2 84 d2 - - - - - - - -         test     DL, DL
00000BD4 74 08 - - - - - - - -         jz       0x00000bde
00000BD6 48 83 ee 07 - - - - - -       sub      RSI, 0x7
00000BDA 48 83 ef 07 - - - - - -       sub      RDI, 0x7
00000BDE 48 8b c1 - - - - - - -        mov      RAX, RCX
00000BE1 48 c1 e9 03 - - - - - -       shr      RCX, 0x3
00000BE5 f3 48 a5 - - - - - - -        movsq.rep RDI, RSI
00000BE8 48 83 e0 07 - - - - - -       and      RAX, 0x7
00000BEC 74 1b - - - - - - - -         jz       0x00000c09
00000BEE 84 d2 - - - - - - - -         test     DL, DL
00000BF0 74 08 - - - - - - - -         jz       0x00000bfa
00000BF2 48 83 c6 08 - - - - - -       add      RSI, 0x8
00000BF6 48 83 c7 08 - - - - - -       add      RDI, 0x8
00000BFA 48 8b c8 - - - - - - -        mov      RCX, RAX
00000BFD 84 d2 - - - - - - - -         test     DL, DL
00000BFF 74 06 - - - - - - - -         jz       0x00000c07
00000C01 48 ff ce - - - - - - -        dec      RSI
00000C04 48 ff cf - - - - - - -        dec      RDI
00000C07 f3 a4 - - - - - - - -         movsb.rep RDI, RSI
00000C09 58 - - - - - - - - -          pop      RAX
00000C0A 66 9d - - - - - - - -         popf     
00000C0C 5b - - - - - - - - -          pop      RBX
00000C0D 5e - - - - - - - - -          pop      RSI
00000C0E 5f - - - - - - - - -          pop      RDI
00000C0F c3 - - - - - - - - -          ret      
