; OemApControlDxe @ 00000BDC   FUN_00000bdc
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemApControlDxe.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00000BDC.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00000BDC 40 53      push     RBX
00000BDE 48 83 ec 20 sub      RSP, 0x20
00000BE2 48 69 d1 99 9e 36 00 imul     RDX, RCX, 0x369e99
00000BE9 48 8b d9   mov      RBX, RCX
00000BEC 48 b8 db 34 b6 d7 82 de 1b 43 mov      RAX, 0x431bde82d7b634db
00000BF6 48 f7 e2   mul      RDX
00000BF9 48 c1 ea 12 shr      RDX, 0x12
00000BFD 8b ca      mov      ECX, EDX
00000BFF e8 78 ff ff ff call     0x00000b7c
00000C04 48 8b c3   mov      RAX, RBX
00000C07 48 83 c4 20 add      RSP, 0x20
00000C0B 5b         pop      RBX
00000C0C c3         ret      
