; OemUniWillVariableDxe @ 000008E8   FUN_000008e8
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemUniWillVariableDxe.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 000008E8.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

000008E8 48 8b 0d 11 03 00 00 mov      RCX, qword ptr [0x00000c00]
000008EF 33 c0      xor      EAX, EAX
000008F1 48 85 c9   test     RCX, RCX
000008F4 75 57      jnz      0x0000094d
000008F6 48 8b 15 e3 02 00 00 mov      RDX, qword ptr [0x00000be0]
000008FD 8b c8      mov      ECX, EAX
000008FF 48 89 05 fa 02 00 00 mov      qword ptr [0x00000c00], RAX
00000906 4c 8b 42 68 mov      R8, qword ptr [RDX + 0x68]
0000090A 4d 85 c0   test     R8, R8
0000090D 74 3e      jz       0x0000094d
0000090F 4c 8b 4a 70 mov      R9, qword ptr [RDX + 0x70]
00000913 4c 8b 15 4e 02 00 00 mov      R10, qword ptr [0x00000b68]
0000091A 49 8b d1   mov      RDX, R9
0000091D 4c 8b 1d 3c 02 00 00 mov      R11, qword ptr [0x00000b60]
00000924 4c 3b 1a   cmp      R11, qword ptr [RDX]
00000927 75 06      jnz      0x0000092f
00000929 4c 3b 52 08 cmp      R10, qword ptr [RDX + 0x8]
0000092D 74 0e      jz       0x0000093d
0000092F 48 ff c0   inc      RAX
00000932 48 83 c2 18 add      RDX, 0x18
00000936 49 3b c0   cmp      RAX, R8
00000939 73 12      jnc      0x0000094d
0000093B eb e7      jmp      0x00000924
0000093D 48 8d 04 40 lea      RAX, [RAX + RAX*0x2]
00000941 49 8b 4c c1 10 mov      RCX, qword ptr [R9 + RAX*0x8 + 0x10]
00000946 48 89 0d b3 02 00 00 mov      qword ptr [0x00000c00], RCX
0000094D 48 8b c1   mov      RAX, RCX
00000950 c3         ret      
