; OemPowerModeDxe @ 00000670   write_port_byte_after_wait   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemPowerModeDxe.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00000670.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00000670 48 89 5c 24 08 - - - - -      mov      qword ptr [RSP + 0x8], RBX
00000675 48 89 74 24 10 - - - - -      mov      qword ptr [RSP + 0x10], RSI
0000067A 57 - - - - - - - - -          push     RDI
0000067B 48 83 ec 20 - - - - - -       sub      RSP, 0x20
0000067F 40 8a f2 - - - - - - -        mov      SIL, DL
00000682 33 db - - - - - - - -         xor      EBX, EBX
00000684 8d 53 66 - - - - - - -        lea      EDX, [RBX + 0x66]
00000687 80 f9 60 - - - - - - -        cmp      CL, 0x60
0000068A 8d 43 64 - - - - - - -        lea      EAX, [RBX + 0x64]
0000068D 0f 45 c2 - - - - - - -        cmovnz   EAX, EDX
00000690 0f b6 f8 - - - - - - -        movzx    EDI, AL
00000693 0f b7 d7 - - - - - - -        movzx    EDX, DI
00000696 ec - - - - - - - - -          in       AL, DX
00000697 a8 02 - - - - - - - -         test     AL, 0x2
00000699 74 33 - - - - - - - -         jz       0x000006ce
0000069B 48 81 fb 00 00 02 00 - - -    cmp      RBX, 0x20000
000006A2 73 1e - - - - - - - -         jnc      0x000006c2
000006A4 b9 0f 00 00 00 - - - - -      mov      ECX, 0xf
000006A9 e8 56 03 00 00 - - - - -      call     0x00000a04
000006AE 0f b7 d7 - - - - - - -        movzx    EDX, DI
000006B1 ec - - - - - - - - -          in       AL, DX
000006B2 48 ff c3 - - - - - - -        inc      RBX
000006B5 a8 02 - - - - - - - -         test     AL, 0x2
000006B7 75 e2 - - - - - - - -         jnz      0x0000069b
000006B9 48 81 fb 00 00 02 00 - - -    cmp      RBX, 0x20000
000006C0 72 0c - - - - - - - -         jc       0x000006ce
000006C2 48 b8 07 00 00 00 00 00 00 80 mov      RAX, -0x7ffffffffffffff9
000006CC eb 09 - - - - - - - -         jmp      0x000006d7
000006CE 0f b7 d7 - - - - - - -        movzx    EDX, DI
000006D1 40 8a c6 - - - - - - -        mov      AL, SIL
000006D4 ee - - - - - - - - -          out      DX, AL
000006D5 33 c0 - - - - - - - -         xor      EAX, EAX
000006D7 48 8b 5c 24 30 - - - - -      mov      RBX, qword ptr [RSP + 0x30]
000006DC 48 8b 74 24 38 - - - - -      mov      RSI, qword ptr [RSP + 0x38]
000006E1 48 83 c4 20 - - - - - -       add      RSP, 0x20
000006E5 5f - - - - - - - - -          pop      RDI
000006E6 c3 - - - - - - - - -          ret      
