; OemServiceSmm @ 000011C0   FUN_000011c0
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemServiceSmm.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 000011C0.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

000011C0 57         push     RDI
000011C1 51         push     RCX
000011C2 48 31 c0   xor      RAX, RAX
000011C5 48 89 cf   mov      RDI, RCX
000011C8 48 89 d1   mov      RCX, RDX
000011CB 48 c1 e9 03 shr      RCX, 0x3
000011CF 48 83 e2 07 and      RDX, 0x7
000011D3 f3 48 ab   stosq.rep RDI
000011D6 89 d1      mov      ECX, EDX
000011D8 f3 aa      stosb.rep RDI
000011DA 58         pop      RAX
000011DB 5f         pop      RDI
000011DC c3         ret      
