; OemServiceSmm @ 00003AD8   FUN_00003ad8
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemServiceSmm.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00003AD8.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00003AD8 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00003ADD 48 89 74 24 10 mov      qword ptr [RSP + 0x10], RSI
00003AE2 57         push     RDI
00003AE3 48 81 ec 30 01 00 00 sub      RSP, 0x130
00003AEA 48 8b d9   mov      RBX, RCX
00003AED e8 0a df ff ff call     0x000019fc
00003AF2 48 8d 15 8f 78 00 00 lea      RDX, [0xb388]
00003AF9 48 8b cb   mov      RCX, RBX
00003AFC e8 2f da ff ff call     0x00001530
00003B01 48 8d 15 b0 78 00 00 lea      RDX, [0xb3b8]
00003B08 48 8b cb   mov      RCX, RBX
00003B0B e8 20 da ff ff call     0x00001530
00003B10 48 8d 15 d1 78 00 00 lea      RDX, [0xb3e8]
00003B17 48 8b cb   mov      RCX, RBX
00003B1A e8 11 da ff ff call     0x00001530
00003B1F 48 8d 3d 82 5d 00 00 lea      RDI, [0x98a8]
00003B26 be 08 00 00 00 mov      ESI, 0x8
00003B2B 48 8b 47 f8 mov      RAX, qword ptr [RDI + -0x8]
00003B2F 4c 8d 05 aa 72 00 00 lea      R8, [0xade0]
00003B36 44 8b 0f   mov      R9D, dword ptr [RDI]
00003B39 48 8d 4c 24 30 lea      RCX, [RSP + 0x30]
00003B3E ba 00 01 00 00 mov      EDX, 0x100
00003B43 48 89 44 24 20 mov      qword ptr [RSP + 0x20], RAX
00003B48 e8 f3 4f 00 00 call     0x00008b40
00003B4D 48 8d 54 24 30 lea      RDX, [RSP + 0x30]
00003B52 48 8b cb   mov      RCX, RBX
00003B55 e8 d6 d9 ff ff call     0x00001530
00003B5A 48 8d 7f 0c lea      RDI, [RDI + 0xc]
00003B5E 48 83 ee 01 sub      RSI, 0x1
00003B62 75 c7      jnz      0x00003b2b
00003B64 4c 8d 9c 24 30 01 00 00 lea      R11, [RSP + 0x130]
00003B6C 49 8b 5b 10 mov      RBX, qword ptr [R11 + 0x10]
00003B70 49 8b 73 18 mov      RSI, qword ptr [R11 + 0x18]
00003B74 49 8b e3   mov      RSP, R11
00003B77 5f         pop      RDI
00003B78 c3         ret      
