; OemServiceSmm @ 00001270   FUN_00001270
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemServiceSmm.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00001270.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00001270 0f 31      rdtsc    
00001272 48 c1 e2 20 shl      RDX, 0x20
00001276 48 09 d0   or       RAX, RDX
00001279 c3         ret      
