; OemServiceSmm @ 000035D4   FUN_000035d4
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemServiceSmm.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 000035D4.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

000035D4 48 8b c4   mov      RAX, RSP
000035D7 48 89 58 08 mov      qword ptr [RAX + 0x8], RBX
000035DB 48 89 70 10 mov      qword ptr [RAX + 0x10], RSI
000035DF 48 89 78 18 mov      qword ptr [RAX + 0x18], RDI
000035E3 4c 89 60 20 mov      qword ptr [RAX + 0x20], R12
000035E7 55         push     RBP
000035E8 41 56      push     R14
000035EA 41 57      push     R15
000035EC 48 8d 68 a1 lea      RBP, [RAX + -0x5f]
000035F0 48 81 ec f0 00 00 00 sub      RSP, 0xf0
000035F7 48 a1 14 00 43 ff 00 00 00 00 mov      RAX, [0xff430014]
00003601 4c 8b f9   mov      R15, RCX
00003604 48 89 45 b7 mov      qword ptr [RBP + -0x49], RAX
00003608 48 8d 4d c7 lea      RCX, [RBP + -0x39]
0000360C 0f b6 55 be movzx    EDX, byte ptr [RBP + -0x42]
00003610 41 bc 80 00 00 00 mov      R12D, 0x80
00003616 44 0f b6 45 bd movzx    R8D, byte ptr [RBP + -0x43]
0000361B 44 0f b6 55 bc movzx    R10D, byte ptr [RBP + -0x44]
00003620 44 0f b6 5d bb movzx    R11D, byte ptr [RBP + -0x45]
00003625 0f b6 5d ba movzx    EBX, byte ptr [RBP + -0x46]
00003629 0f b6 7d b9 movzx    EDI, byte ptr [RBP + -0x47]
0000362D 0f b6 75 b8 movzx    ESI, byte ptr [RBP + -0x48]
00003631 89 54 24 50 mov      dword ptr [RSP + 0x50], EDX
00003635 41 8b d4   mov      EDX, R12D
00003638 44 89 44 24 48 mov      dword ptr [RSP + 0x48], R8D
0000363D 4c 8d 05 4c 7b 00 00 lea      R8, [0xb190]
00003644 44 89 54 24 40 mov      dword ptr [RSP + 0x40], R10D
00003649 44 89 5c 24 38 mov      dword ptr [RSP + 0x38], R11D
0000364E 89 5c 24 30 mov      dword ptr [RSP + 0x30], EBX
00003652 89 7c 24 28 mov      dword ptr [RSP + 0x28], EDI
00003656 44 0f b6 c8 movzx    R9D, AL
0000365A 89 74 24 20 mov      dword ptr [RSP + 0x20], ESI
0000365E e8 dd 54 00 00 call     0x00008b40
00003663 48 8d 55 c7 lea      RDX, [RBP + -0x39]
00003667 49 8b cf   mov      RCX, R15
0000366A e8 c1 de ff ff call     0x00001530
0000366F 48 a1 1c 00 43 ff 00 00 00 00 mov      RAX, [0xff43001c]
00003679 b9 2c 00 43 ff mov      ECX, 0xff43002c
0000367E 48 89 45 b7 mov      qword ptr [RBP + -0x49], RAX
00003682 0f b6 55 be movzx    EDX, byte ptr [RBP + -0x42]
00003686 44 0f b6 45 bd movzx    R8D, byte ptr [RBP + -0x43]
0000368B 0f b6 09   movzx    ECX, byte ptr [RCX]
0000368E 44 0f b6 55 bc movzx    R10D, byte ptr [RBP + -0x44]
00003693 44 0f b6 5d bb movzx    R11D, byte ptr [RBP + -0x45]
00003698 0f b6 5d ba movzx    EBX, byte ptr [RBP + -0x46]
0000369C 0f b6 7d b9 movzx    EDI, byte ptr [RBP + -0x47]
000036A0 0f b6 75 b8 movzx    ESI, byte ptr [RBP + -0x48]
000036A4 89 4c 24 58 mov      dword ptr [RSP + 0x58], ECX
000036A8 48 8d 4d c7 lea      RCX, [RBP + -0x39]
000036AC 89 54 24 50 mov      dword ptr [RSP + 0x50], EDX
000036B0 41 8b d4   mov      EDX, R12D
000036B3 44 89 44 24 48 mov      dword ptr [RSP + 0x48], R8D
000036B8 4c 8d 05 f9 7a 00 00 lea      R8, [0xb1b8]
000036BF 44 89 54 24 40 mov      dword ptr [RSP + 0x40], R10D
000036C4 44 89 5c 24 38 mov      dword ptr [RSP + 0x38], R11D
000036C9 89 5c 24 30 mov      dword ptr [RSP + 0x30], EBX
000036CD 89 7c 24 28 mov      dword ptr [RSP + 0x28], EDI
000036D1 44 0f b6 c8 movzx    R9D, AL
000036D5 89 74 24 20 mov      dword ptr [RSP + 0x20], ESI
000036D9 e8 62 54 00 00 call     0x00008b40
000036DE 48 8d 55 c7 lea      RDX, [RBP + -0x39]
000036E2 49 8b cf   mov      RCX, R15
000036E5 e8 46 de ff ff call     0x00001530
000036EA 48 a1 24 00 43 ff 00 00 00 00 mov      RAX, [0xff430024]
000036F4 4c 8d 05 95 7a 00 00 lea      R8, [0xb190]
000036FB 48 89 45 b7 mov      qword ptr [RBP + -0x49], RAX
000036FF 41 8b d4   mov      EDX, R12D
00003702 0f b6 4d be movzx    ECX, byte ptr [RBP + -0x42]
00003706 44 0f b6 55 bd movzx    R10D, byte ptr [RBP + -0x43]
0000370B 44 0f b6 5d bc movzx    R11D, byte ptr [RBP + -0x44]
00003710 0f b6 5d bb movzx    EBX, byte ptr [RBP + -0x45]
00003714 0f b6 7d ba movzx    EDI, byte ptr [RBP + -0x46]
00003718 0f b6 75 b9 movzx    ESI, byte ptr [RBP + -0x47]
0000371C 44 0f b6 75 b8 movzx    R14D, byte ptr [RBP + -0x48]
00003721 89 4c 24 50 mov      dword ptr [RSP + 0x50], ECX
00003725 48 8d 4d c7 lea      RCX, [RBP + -0x39]
00003729 44 89 54 24 48 mov      dword ptr [RSP + 0x48], R10D
0000372E 44 89 5c 24 40 mov      dword ptr [RSP + 0x40], R11D
00003733 89 5c 24 38 mov      dword ptr [RSP + 0x38], EBX
00003737 89 7c 24 30 mov      dword ptr [RSP + 0x30], EDI
0000373B 89 74 24 28 mov      dword ptr [RSP + 0x28], ESI
0000373F 44 0f b6 c8 movzx    R9D, AL
00003743 44 89 74 24 20 mov      dword ptr [RSP + 0x20], R14D
00003748 e8 f3 53 00 00 call     0x00008b40
0000374D 48 8d 55 c7 lea      RDX, [RBP + -0x39]
00003751 49 8b cf   mov      RCX, R15
00003754 e8 d7 dd ff ff call     0x00001530
00003759 4c 8d 9c 24 f0 00 00 00 lea      R11, [RSP + 0xf0]
00003761 49 8b 5b 20 mov      RBX, qword ptr [R11 + 0x20]
00003765 49 8b 73 28 mov      RSI, qword ptr [R11 + 0x28]
00003769 49 8b 7b 30 mov      RDI, qword ptr [R11 + 0x30]
0000376D 4d 8b 63 38 mov      R12, qword ptr [R11 + 0x38]
00003771 49 8b e3   mov      RSP, R11
00003774 41 5f      pop      R15
00003776 41 5e      pop      R14
00003778 5d         pop      RBP
00003779 c3         ret      
