; OemServiceSmm @ 00001530   append_text_record_to_output   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemServiceSmm.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00001530.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00001530 48 89 5c 24 08 - - - - - -       mov      qword ptr [RSP + 0x8], RBX
00001535 48 89 74 24 10 - - - - - -       mov      qword ptr [RSP + 0x10], RSI
0000153A 57 - - - - - - - - - -           push     RDI
0000153B 48 83 ec 20 - - - - - - -        sub      RSP, 0x20
0000153F 83 79 20 00 - - - - - - -        cmp      dword ptr [RCX + 0x20], 0x0
00001543 48 8b f2 - - - - - - - -         mov      RSI, RDX
00001546 48 8b f9 - - - - - - - -         mov      RDI, RCX
00001549 74 16 - - - - - - - - -          jz       0x00001561
0000154B f6 41 14 02 - - - - - - -        test     byte ptr [RCX + 0x14], 0x2
0000154F 74 10 - - - - - - - - -          jz       0x00001561
00001551 8b 59 20 - - - - - - - -         mov      EBX, dword ptr [RCX + 0x20]
00001554 48 03 d9 - - - - - - - -         add      RBX, RCX
00001557 c6 43 24 0a - - - - - - -        mov      byte ptr [RBX + 0x24], 0xa
0000155B 48 83 c3 25 - - - - - - -        add      RBX, 0x25
0000155F eb 04 - - - - - - - - -          jmp      0x00001565
00001561 48 8d 59 24 - - - - - - -        lea      RBX, [RCX + 0x24]
00001565 c6 03 02 - - - - - - - -         mov      byte ptr [RBX], 0x2
00001568 45 33 c0 - - - - - - - -         xor      R8D, R8D
0000156B 48 ff c3 - - - - - - - -         inc      RBX
0000156E 44 38 02 - - - - - - - -         cmp      byte ptr [RDX], R8B
00001571 74 1c - - - - - - - - -          jz       0x0000158f
00001573 49 ff c0 - - - - - - - -         inc      R8
00001576 41 80 3c 10 00 - - - - - -       cmp      byte ptr [R8 + RDX*0x1], 0x0
0000157B 75 f6 - - - - - - - - -          jnz      0x00001573
0000157D 4d 85 c0 - - - - - - - -         test     R8, R8
00001580 74 0d - - - - - - - - -          jz       0x0000158f
00001582 48 3b de - - - - - - - -         cmp      RBX, RSI
00001585 74 08 - - - - - - - - -          jz       0x0000158f
00001587 48 8b cb - - - - - - - -         mov      RCX, RBX
0000158A e8 f1 fb ff ff - - - - - -       call     0x00001180
0000158F 33 c0 - - - - - - - - -          xor      EAX, EAX
00001591 38 06 - - - - - - - - -          cmp      byte ptr [RSI], AL
00001593 74 09 - - - - - - - - -          jz       0x0000159e
00001595 48 ff c0 - - - - - - - -         inc      RAX
00001598 80 3c 30 00 - - - - - - -        cmp      byte ptr [RAX + RSI*0x1], 0x0
0000159C 75 f7 - - - - - - - - -          jnz      0x00001595
0000159E 48 8b 74 24 38 - - - - - -       mov      RSI, qword ptr [RSP + 0x38]
000015A3 48 03 d8 - - - - - - - -         add      RBX, RAX
000015A6 c6 03 03 - - - - - - - -         mov      byte ptr [RBX], 0x3
000015A9 2b df - - - - - - - - -          sub      EBX, EDI
000015AB 83 4f 14 02 - - - - - - -        or       dword ptr [RDI + 0x14], 0x2
000015AF 83 eb 23 - - - - - - - -         sub      EBX, 0x23
000015B2 89 5f 20 - - - - - - - -         mov      dword ptr [RDI + 0x20], EBX
000015B5 33 c0 - - - - - - - - -          xor      EAX, EAX
000015B7 48 8b 5c 24 30 - - - - - -       mov      RBX, qword ptr [RSP + 0x30]
000015BC 48 83 c4 20 - - - - - - -        add      RSP, 0x20
000015C0 5f - - - - - - - - - -           pop      RDI
000015C1 c3 - - - - - - - - - -           ret      
