; OemOcPei @ FFF82874   FUN_fff82874
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemOcPei.efi (TE body, execute-in-place 0xFFF8223C), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is FFF82874.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

FFF82874 53         push     EBX
FFF82875 55         push     EBP
FFF82876 56         push     ESI
FFF82877 57         push     EDI
FFF82878 8b f9      mov      EDI, ECX
FFF8287A bd 08 18 00 00 mov      EBP, 0x1808
FFF8287F 8b f7      mov      ESI, EDI
FFF82881 c1 ee 16   shr      ESI, 0x16
FFF82884 81 e7 ff ff 3f 00 and      EDI, 0x3fffff
FFF8288A 66 8b d5   mov      DX, BP
FFF8288D ed         in       EAX, DX
FFF8288E 8b d8      mov      EBX, EAX
FFF82890 81 e3 ff ff ff 00 and      EBX, 0xffffff
FFF82896 03 df      add      EBX, EDI
FFF82898 bf 00 00 40 00 mov      EDI, 0x400000
FFF8289D eb 05      jmp      0xfff828a4
FFF8289F f3 90      pause    
FFF828A1 66 8b d5   mov      DX, BP
FFF828A4 ed         in       EAX, DX
FFF828A5 8b cb      mov      ECX, EBX
FFF828A7 2b c8      sub      ECX, EAX
FFF828A9 f7 c1 00 00 80 00 test     ECX, 0x800000
FFF828AF 74 ee      jz       0xfff8289f
FFF828B1 8b c6      mov      EAX, ESI
FFF828B3 4e         dec      ESI
FFF828B4 85 c0      test     EAX, EAX
FFF828B6 75 d2      jnz      0xfff8288a
FFF828B8 5f         pop      EDI
FFF828B9 5e         pop      ESI
FFF828BA 5d         pop      EBP
FFF828BB 5b         pop      EBX
FFF828BC c3         ret      
