; OemHooks @ 00000A00   ec_read_reg_byte   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemHooks.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00000A00.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00000A00 48 89 5c 24 08 - - - - - -       mov      qword ptr [RSP + 0x8], RBX
00000A05 48 89 74 24 10 - - - - - -       mov      qword ptr [RSP + 0x10], RSI
00000A0A 57 - - - - - - - - - -           push     RDI
00000A0B 48 83 ec 20 - - - - - - -        sub      RSP, 0x20
00000A0F 49 8b f0 - - - - - - - -         mov      RSI, R8
00000A12 40 8a fa - - - - - - - -         mov      DIL, DL
00000A15 41 b0 04 - - - - - - - -         mov      R8B, 0x4
00000A18 b2 a3 - - - - - - - - -          mov      DL, 0xa3
00000A1A b1 62 - - - - - - - - -          mov      CL, 0x62
00000A1C 33 db - - - - - - - - -          xor      EBX, EBX
00000A1E e8 cd fe ff ff - - - - - -       call     0x000008f0
00000A23 48 85 c0 - - - - - - - -         test     RAX, RAX
00000A26 78 63 - - - - - - - - -          js       0x00000a8b
00000A28 44 8a c7 - - - - - - - -         mov      R8B, DIL
00000A2B b2 a2 - - - - - - - - -          mov      DL, 0xa2
00000A2D b1 62 - - - - - - - - -          mov      CL, 0x62
00000A2F e8 bc fe ff ff - - - - - -       call     0x000008f0
00000A34 48 85 c0 - - - - - - - -         test     RAX, RAX
00000A37 78 52 - - - - - - - - -          js       0x00000a8b
00000A39 b2 a4 - - - - - - - - -          mov      DL, 0xa4
00000A3B b1 62 - - - - - - - - -          mov      CL, 0x62
00000A3D e8 4a fd ff ff - - - - - -       call     0x0000078c
00000A42 48 85 c0 - - - - - - - -         test     RAX, RAX
00000A45 78 44 - - - - - - - - -          js       0x00000a8b
00000A47 8d 53 66 - - - - - - - -         lea      EDX, [RBX + 0x66]
00000A4A ec - - - - - - - - - -           in       AL, DX
00000A4B a8 01 - - - - - - - - -          test     AL, 0x1
00000A4D 75 32 - - - - - - - - -          jnz      0x00000a81
00000A4F bf 00 00 02 00 - - - - - -       mov      EDI, 0x20000
00000A54 48 3b df - - - - - - - -         cmp      RBX, RDI
00000A57 73 1c - - - - - - - - -          jnc      0x00000a75
00000A59 b9 0f 00 00 00 - - - - - -       mov      ECX, 0xf
00000A5E e8 05 01 00 00 - - - - - -       call     0x00000b68
00000A63 ba 66 00 00 00 - - - - - -       mov      EDX, 0x66
00000A68 ec - - - - - - - - - -           in       AL, DX
00000A69 48 ff c3 - - - - - - - -         inc      RBX
00000A6C a8 01 - - - - - - - - -          test     AL, 0x1
00000A6E 74 e4 - - - - - - - - -          jz       0x00000a54
00000A70 48 3b df - - - - - - - -         cmp      RBX, RDI
00000A73 72 0c - - - - - - - - -          jc       0x00000a81
00000A75 48 b8 07 00 00 00 00 00 00 80 -  mov      RAX, -0x7ffffffffffffff9
00000A7F eb 0a - - - - - - - - -          jmp      0x00000a8b
00000A81 ba 62 00 00 00 - - - - - -       mov      EDX, 0x62
00000A86 ec - - - - - - - - - -           in       AL, DX
00000A87 88 06 - - - - - - - - -          mov      byte ptr [RSI], AL
00000A89 33 c0 - - - - - - - - -          xor      EAX, EAX
00000A8B 48 8b 5c 24 30 - - - - - -       mov      RBX, qword ptr [RSP + 0x30]
00000A90 48 8b 74 24 38 - - - - - -       mov      RSI, qword ptr [RSP + 0x38]
00000A95 48 83 c4 20 - - - - - - -        add      RSP, 0x20
00000A99 5f - - - - - - - - - -           pop      RDI
00000A9A c3 - - - - - - - - - -           ret      
