; OemACPIDriverSmm @ 00001684   FUN_00001684
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemACPIDriverSmm.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00001684.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00001684 48 8b 0d 5d 0a 00 00 mov      RCX, qword ptr [0x000020e8]
0000168B 33 c0      xor      EAX, EAX
0000168D 48 85 c9   test     RCX, RCX
00001690 75 57      jnz      0x000016e9
00001692 48 8b 15 27 0a 00 00 mov      RDX, qword ptr [0x000020c0]
00001699 8b c8      mov      ECX, EAX
0000169B 48 89 05 46 0a 00 00 mov      qword ptr [0x000020e8], RAX
000016A2 4c 8b 42 68 mov      R8, qword ptr [RDX + 0x68]
000016A6 4d 85 c0   test     R8, R8
000016A9 74 3e      jz       0x000016e9
000016AB 4c 8b 4a 70 mov      R9, qword ptr [RDX + 0x70]
000016AF 4c 8b 15 82 09 00 00 mov      R10, qword ptr [0x00002038]
000016B6 49 8b d1   mov      RDX, R9
000016B9 4c 8b 1d 70 09 00 00 mov      R11, qword ptr [0x00002030]
000016C0 4c 3b 1a   cmp      R11, qword ptr [RDX]
000016C3 75 06      jnz      0x000016cb
000016C5 4c 3b 52 08 cmp      R10, qword ptr [RDX + 0x8]
000016C9 74 0e      jz       0x000016d9
000016CB 48 ff c0   inc      RAX
000016CE 48 83 c2 18 add      RDX, 0x18
000016D2 49 3b c0   cmp      RAX, R8
000016D5 73 12      jnc      0x000016e9
000016D7 eb e7      jmp      0x000016c0
000016D9 48 8d 04 40 lea      RAX, [RAX + RAX*0x2]
000016DD 49 8b 4c c1 10 mov      RCX, qword ptr [R9 + RAX*0x8 + 0x10]
000016E2 48 89 0d ff 09 00 00 mov      qword ptr [0x000020e8], RCX
000016E9 48 8b c1   mov      RAX, RCX
000016EC c3         ret      
