// bank0 @ 4777   stage_0a54_0a55_then_dispatch   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Writes R5 to XDATA 0x0A54 and R3 to 0x0A55, then exchanges R1 through the accumulator twice so R1
   ends up holding the caller's R7 while R3 is cleared. If that value is 0xFF it sets R7 to 0 and
   returns; otherwise it calls 0x4A76 and then 0x4A4D, which the decompiled C marks as not
   returning. The C reads the 0xFF test as a separate third parameter compared against the entry
   value, which the instruction sequence does not support.
   type: state
   evidence: ec/decompiled/bank0/4777.asm; ec/decompiled/bank0/4777.c
   basis: hand-decoded
   name_basis: code-shape */

void stage_0a54_0a55_then_dispatch(undefined1 param_1,undefined1 param_2,char param_3)

{
  DAT_EXTMEM_0a54 = param_2;
  DAT_EXTMEM_0a55 = param_1;
  if (param_3 == -1) {
    return;
  }
  mov_a_from_r1_4a76(0);
                    /* WARNING: Subroutine does not return */
  code_word_to_dptr_4a4d();
}


