; bank0 @ 9049   FUN_CODE_9049
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 9049.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

9049     90 04 90   mov      DPTR, #0x490
904C     e0         movx     A, @DPTR
904D     30 e2 08   jnb      0xe2, 0x9058
9050     90 03 98   mov      DPTR, #0x398
9053     e0         movx     A, @DPTR
9054     64 a5      xrl      A, #0xa5
9056     60 07      jz       0x905f
9058     90 06 e6   mov      DPTR, #0x6e6
905B     e0         movx     A, @DPTR
905C     b4 05 08   cjne     A, #0x5, 0x9067
905F     12 c3 63   lcall    0xc363
9062     12 c3 71   lcall    0xc371
9065     80 0a      sjmp     0x9071
9067     90 04 90   mov      DPTR, #0x490
906A     e0         movx     A, @DPTR
906B     30 e0 09   jnb      0xe0, 0x9077
906E     12 c3 6a   lcall    0xc36a
9071     e4         clr      A
9072     90 08 06   mov      DPTR, #0x806
9075     f0         movx     @DPTR, A
9076     22         ret      
9077     90 06 e6   mov      DPTR, #0x6e6
907A     e0         movx     A, @DPTR
907B     b4 03 09   cjne     A, #0x3, 0x9087
907E     12 c3 6a   lcall    0xc36a
9081     90 08 06   mov      DPTR, #0x806
9084     74 64      mov      A, #0x64
9086     f0         movx     @DPTR, A
9087     90 08 06   mov      DPTR, #0x806
908A     e0         movx     A, @DPTR
908B     60 0d      jz       0x909a
908D     e0         movx     A, @DPTR
908E     14         dec      A
908F     f0         movx     @DPTR, A
9090     e0         movx     A, @DPTR
9091     b4 0a 06   cjne     A, #0xa, 0x909a
9094     12 c3 63   lcall    0xc363
9097     12 c3 71   lcall    0xc371
909A     22         ret      
