// bank0 @ 9A0E   FUN_CODE_9a0e
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


char FUN_CODE_9a0e(void)

{
  undefined1 uVar1;
  char cVar2;
  char in_PSW;
  char *pcVar3;
  undefined1 *puVar4;
  
  uVar1 = 0;
  cVar2 = DAT_EXTMEM_08ea;
  mul16(0,0x13);
  FUN_CODE_708f(10);
  DAT_EXTMEM_0a49 = uVar1;
  DAT_EXTMEM_0a4a = cVar2;
  FUN_CODE_bb31(0x8ca);
  if (((-1 < in_PSW) && (FUN_CODE_bb31(0x8cb), -1 < in_PSW)) && (FUN_CODE_bb31(0x8c2), -1 < in_PSW))
  {
    if (DAT_EXTMEM_044b == '\x04') {
      pcVar3 = &DAT_EXTMEM_08cb;
    }
    else if (DAT_EXTMEM_044b == '\x02') {
      pcVar3 = &DAT_EXTMEM_08c2;
    }
    else {
      pcVar3 = &DAT_EXTMEM_08ca;
    }
    puVar4 = &DAT_EXTMEM_0a4a;
    DAT_EXTMEM_0a4a = DAT_EXTMEM_0a4a - *pcVar3;
    uVar1 = FUN_CODE_bb39();
    *puVar4 = uVar1;
    return DAT_EXTMEM_0a4a;
  }
  DAT_EXTMEM_0a4a = 1;
  DAT_EXTMEM_0a49 = 0;
  return '\x01';
}


