// bank0 @ A169   clear_0983_bit1_then_0xa1c8   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Four instructions: reads XDATA 0x0983, clears bit 1, writes it back, and jumps to 0xA1C8. 0x0983
   has no entry in ec/annotations/registers.yaml, so the meaning of that bit is not determined here.
   This address is a jump target from 0xA00E at 0xA0F3 rather than a called routine.
   type: writer
   evidence: ec/decompiled/bank0/A169.asm; ec/decompiled/bank0/A169.c
   basis: hand-decoded */

void clear_0983_bit1_then_0xa1c8(void)

{
  DAT_EXTMEM_0983 = DAT_EXTMEM_0983 & 0xfd;
  select_code_table_entry_and_store_0872_087a_088a();
  return;
}


