// bank0 @ A72A   gate_a747_on_06c2_0766   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads XDATA 0x6C2 and returns immediately if it is zero. Otherwise it reads XDATA 0x766
   (SUPPORT_2) and calls 0xA747 if bit 4 is set; if bit 4 is clear it re-reads 0x766 and calls
   0xA747 only when bit 5 is set, otherwise falling through to the shared ret at 0xA73E.
   type: gate
   evidence: ec/decompiled/bank0/A72A.asm; ec/decompiled/bank0/A72A.c; ec/annotations/registers.yaml
   basis: hand-decoded
   name_basis: ec-register */

void gate_a747_on_06c2_0766(void)

{
  if ((XDATA_06C2 != '\0') && (((SUPPORT_2 >> 4 & 1) == 1 || ((SUPPORT_2 >> 5 & 1) != 0)))) {
    stage_0769_076e_convert_to_1803();
  }
  return;
}


