// bank0 @ A96B   clear_073f_and_0899   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Calls 0xC15C, writes zero to XDATA 0x73F and XDATA 0x899, then calls 0xBEF7 and returns. The
   effects of the two called routines are not shown in this listing.
   type: writer
   evidence: ec/decompiled/bank0/A96B.asm; ec/decompiled/bank0/A96B.c
   basis: hand-decoded
   name_basis: code-shape */

void clear_073f_and_0899(void)

{
  clear_1602_bit7();
  DAT_EXTMEM_073f = 0;
  DAT_EXTMEM_0899 = 0;
  set_089a_to_3c();
  return;
}


