// bank0 @ ACB4   FUN_CODE_acb4
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_acb4(void)

{
  char cVar1;
  undefined2 *puVar2;
  
  cVar1 = '\0';
  do {
    puVar2 = (undefined2 *)
             CONCAT11('d' - (((0xd1U < (byte)(cVar1 * '\x03')) << 7) >> 7),cVar1 * '\x03' + 0x2e);
    DAT_INTMEM_b7 = *(undefined1 *)puVar2;
    DAT_INTMEM_b8 = *(undefined1 *)((short)puVar2 + 1);
    *(undefined1 *)*puVar2 =
         *(undefined1 *)
          CONCAT11('d' - (((0xcfU < (byte)(cVar1 * '\x03')) << 7) >> 7),cVar1 * '\x03' + 0x30);
    cVar1 = cVar1 + '\x01';
  } while (cVar1 != '!');
  DAT_EXTMEM_0988 = 1;
  DAT_EXTMEM_075e = DAT_EXTMEM_075e | 0x10;
  route_074c_nibble_to_160a_and_1608();
  clear_0741_bit0_and_08e2_bit4();
  DAT_EXTMEM_07c5 = DAT_EXTMEM_07c5 & 0x7f;
  AP_OEM_6 = AP_OEM_6 & 0xfb;
  OEM_4_CHARGING_PROFILE = OEM_4_CHARGING_PROFILE & 0xbf;
  clear_08a5_and_08a6();
  AP_OEM = AP_OEM & 0xfb;
  DAT_EXTMEM_073c = DAT_EXTMEM_073c & 0xf9;
  DAT_EXTMEM_045a = DAT_EXTMEM_045a & 0x10;
  set_1606_bit2();
  set_1605_bit6();
  DAT_EXTMEM_072d = DAT_EXTMEM_072d | 1;
  DAT_EXTMEM_097a = 0xf2;
  DAT_EXTMEM_0720 = 0xf2;
  load_dptr_8955_tail_jump_1114();
  AP_OEM = AP_OEM & 0x7f;
  store_a_then_clear_0824_bit7_and_0768_bit2(0,0x816);
  mask_0476_with_1f();
  DAT_EXTMEM_0471 = DAT_EXTMEM_0471 & 0x7f;
  DAT_EXTMEM_0442 = DAT_EXTMEM_0442 & 0xe7;
  DAT_EXTMEM_0456 = DAT_EXTMEM_0456 & 0xcf;
  DAT_EXTMEM_074c = DAT_EXTMEM_074c & 0xcf;
  FUN_CODE_2896();
  clear_08a5_and_08a6();
  zero_96_bytes_at_0f00();
  DAT_EXTMEM_0787 = 0;
  CPU_TCC_OFFSET = 0;
  CTGP_DB_CTRL = CTGP_DB_CTRL & 0xfa;
  DAT_EXTMEM_07c5 = DAT_EXTMEM_07c5 & 0xdf;
  DAT_EXTMEM_0788 = 0xff;
  DAT_EXTMEM_07d5 = 0xff;
  ring_push_0990(0xe1);
  return;
}


