// bank0 @ AE87   FUN_CODE_ae87
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_ae87(void)

{
  FUN_CODE_af8a();
  FUN_CODE_b012();
  FUN_CODE_b947(0x790);
  DAT_EXTMEM_0791 = FUN_CODE_b01c();
  FUN_CODE_b990(0xa4c);
  FUN_CODE_b958(0x47);
  DAT_EXTMEM_0793 = FUN_CODE_b01c();
  DAT_EXTMEM_0794 = DAT_EXTMEM_0a4c;
  if (DAT_EXTMEM_0790 != '\0') {
    FUN_CODE_af66();
    return;
  }
  FUN_CODE_af72();
  return;
}


