// bank0 @ B40C   zero_xdata_block_ptr_r6r7_count_r4r5   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Takes a 16-bit XDATA destination pointer in R6:R7 and a 16-bit count in R4:R5, staging them at
   XDATA 0x0A56/0x0A57 and 0x0A58/0x0A59 and copying the pointer into the direct-byte pair
   0xB7/0xB8. It clears a 16-bit index at XDATA 0x0A5A/0x0A5B and loops while that index is below
   the count, writing 0 through the pointer, advancing the pointer, and lcalling 0xBADE after each
   byte. The RET at 0xB460 leaves A holding the borrow-adjusted low byte of the last
   index-minus-count subtraction, which the caller does not use. The .c reads the direct pair
   0xB7/0xB8 as the arguments and 0x0A5A as the argument to 0xBADE; the .asm has the roles the other
   way round.
   type: writer
   evidence: ec/decompiled/bank0/B40C.asm; ec/decompiled/bank0/B40C.c
   basis: hand-decoded */

char zero_xdata_block_ptr_r6r7_count_r4r5(char param_1,byte param_2,char param_3,char param_4)

{
  byte bVar1;
  
  DAT_EXTMEM_0a5a = 0;
  DAT_EXTMEM_0a5b = 0;
  DAT_INTMEM_b7 = param_3;
  DAT_INTMEM_b8 = param_4;
  DAT_EXTMEM_0a56 = param_3;
  DAT_EXTMEM_0a57 = param_4;
  DAT_EXTMEM_0a58 = param_1;
  DAT_EXTMEM_0a59 = param_2;
  while (bVar1 = DAT_EXTMEM_0a58 - (((DAT_EXTMEM_0a5b < DAT_EXTMEM_0a59) << 7) >> 7),
        DAT_EXTMEM_0a5a < bVar1) {
    *(undefined1 *)CONCAT11(DAT_INTMEM_b7,DAT_INTMEM_b8) = 0;
    DAT_INTMEM_b8 = DAT_INTMEM_b8 + '\x01';
    if (DAT_INTMEM_b8 == '\0') {
      DAT_INTMEM_b7 = DAT_INTMEM_b7 + '\x01';
    }
    tailcall_70e4_add_0100_at_dptr(FUN_CODE_0a5a);
  }
  return DAT_EXTMEM_0a5a - bVar1;
}


