// bank0 @ B737   FUN_CODE_b737
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


byte FUN_CODE_b737(undefined1 param_1,byte param_2)

{
  char cVar1;
  byte bVar2;
  char cVar3;
  byte bVar4;
  byte *pbVar5;
  short sVar6;
  
  cVar1 = FUN_CODE_b9d8();
  if ((((cVar1 != '\0') || (-1 < MANUAL_FAN_CTRL)) || ((DAT_EXTMEM_0490 & 1) == 0)) ||
     ((cVar1 = (DAT_EXTMEM_04ab < 100) << 7, DAT_EXTMEM_04ab != 100 ||
      (pbVar5 = &DAT_EXTMEM_07c5, (DAT_EXTMEM_07c5 >> 4 & 1) != 0)))) {
    bVar2 = FUN_CODE_b82e();
    return bVar2;
  }
  cVar3 = FUN_CODE_ba36();
  if (cVar3 != '\0') {
    param_2 = *pbVar5 & 0xf;
    cVar1 = (param_2 < 5) << 7;
    if (param_2 != 5) {
      cVar3 = FUN_CODE_ba36();
      if (cVar3 != '\b') {
        param_2 = *pbVar5 & 0xf;
        cVar1 = (param_2 < 9) << 7;
        if (param_2 != 9) {
          cVar3 = FUN_CODE_ba36();
          if (cVar3 != '\x03') {
            param_2 = *pbVar5 & 0xf;
            cVar1 = (param_2 < 7) << 7;
            if (param_2 != 7) {
              FUN_CODE_b8c0();
              if (param_2 == 0) {
                FUN_CODE_be4a(0xa47);
              }
              else {
                FUN_CODE_be42();
              }
              goto LAB_CODE_b7bb;
            }
          }
          FUN_CODE_b8c0();
          if (param_2 == 0) {
            FUN_CODE_be3a();
          }
          else {
            DAT_EXTMEM_0a47 = 100;
            DAT_EXTMEM_0a48 = 0xeb;
          }
          goto LAB_CODE_b7bb;
        }
      }
      FUN_CODE_be32(0xa47);
      goto LAB_CODE_b7bb;
    }
  }
  FUN_CODE_be2a(0xa47);
LAB_CODE_b7bb:
  if ((DAT_EXTMEM_08eb >> 6 & 1) == 1) {
    sVar6 = 0xa47;
    FUN_CODE_b93d();
    if (*(byte *)(sVar6 + 0xf) <= CPU_TEMP) {
      return CPU_TEMP - *(byte *)(sVar6 + 0xf);
    }
    bVar2 = *(byte *)(CONCAT11(param_1,param_2) + 0x10);
    bVar4 = GPU_TEMP - bVar2;
    if (bVar2 <= GPU_TEMP) {
      return bVar4;
    }
    FUN_CODE_b989(bVar4,0xa47);
    cVar1 = '\0';
    bVar2 = FUN_CODE_bc37(0x11);
    if (-1 < cVar1) {
      return bVar2;
    }
    DAT_EXTMEM_08eb = DAT_EXTMEM_08eb & 0xbf;
  }
  else {
    FUN_CODE_b93d(0xa47);
    FUN_CODE_bb55(0xc);
    if ((-1 < cVar1) && (FUN_CODE_bbdd(0xd,CONCAT11(param_1,param_2)), -1 < cVar1)) {
      FUN_CODE_b989(0xa47);
      cVar3 = -0x80;
      FUN_CODE_bc37(0xe);
      cVar1 = DAT_EXTMEM_08a0;
      if (-1 < cVar3) {
        DAT_EXTMEM_08a0 = DAT_EXTMEM_08a0 + 1;
        if (DAT_EXTMEM_08a0 < 0xb) {
          return cVar1 - 10;
        }
        DAT_EXTMEM_08eb = DAT_EXTMEM_08eb | 0x40;
        return DAT_EXTMEM_08eb;
      }
    }
  }
  DAT_EXTMEM_08a0 = 0;
  return 0;
}


