// bank0 @ B737   FUN_CODE_b737
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


byte FUN_CODE_b737(undefined1 param_1,byte param_2)

{
  char cVar1;
  byte bVar2;
  char cVar3;
  byte *pbVar4;
  short sVar5;
  
  cVar1 = read_06e6_xor_01();
  if ((((cVar1 != '\0') || (-1 < MANUAL_FAN_CTRL)) || ((DAT_EXTMEM_0490 & 1) == 0)) ||
     ((cVar1 = (DAT_EXTMEM_04ab < 100) << 7, DAT_EXTMEM_04ab != 100 ||
      (pbVar4 = &DAT_EXTMEM_07c5, (DAT_EXTMEM_07c5 >> 4 & 1) != 0)))) {
    bVar2 = clear_08eb_bit6_and_zero_08a0();
    return bVar2;
  }
  cVar3 = read_low_nibble_074c();
  if (cVar3 != '\0') {
    param_2 = *pbVar4 & 0xf;
    cVar1 = (param_2 < 5) << 7;
    if (param_2 != 5) {
      cVar3 = read_low_nibble_074c();
      if (cVar3 != '\b') {
        param_2 = *pbVar4 & 0xf;
        cVar1 = (param_2 < 9) << 7;
        if (param_2 != 9) {
          cVar3 = read_low_nibble_074c();
          if (cVar3 != '\x03') {
            param_2 = *pbVar4 & 0xf;
            cVar1 = (param_2 < 7) << 7;
            if (param_2 != 7) {
              test_0770_equals_04();
              if (param_2 == 0) {
                write_64_a3_pair(0xa47);
              }
              else {
                write_64_b5_pair();
              }
              goto LAB_CODE_b7bb;
            }
          }
          test_0770_equals_04();
          if (param_2 == 0) {
            write_64_d9_pair();
          }
          else {
            DAT_EXTMEM_0a47 = 100;
            DAT_EXTMEM_0a48 = 0xeb;
          }
          goto LAB_CODE_b7bb;
        }
      }
      write_64_c7_pair(0xa47);
      goto LAB_CODE_b7bb;
    }
  }
  write_64_91_pair(0xa47);
LAB_CODE_b7bb:
  if ((XDATA_08EB >> 6 & 1) == 1) {
    sVar5 = 0xa47;
    load_dptr_be16_from_xdata(0xa47);
    if (*(byte *)(sVar5 + 0xf) <= CPU_TEMP) {
      return CPU_TEMP - *(byte *)(sVar5 + 0xf);
    }
    bVar2 = *(byte *)(CONCAT11(param_1,param_2) + 0x10);
    if (bVar2 <= GPU_TEMP) {
      return GPU_TEMP - bVar2;
    }
    finish_dptr_be16_load(0xa47);
    cVar1 = '\0';
    bVar2 = code_byte_sub_from_044c(0x11);
    if (-1 < cVar1) {
      return bVar2;
    }
    XDATA_08EB = XDATA_08EB & 0xbf;
  }
  else {
    load_dptr_be16_from_xdata(0xa47);
    set_cy_before_043e_sub(0xc);
    if ((-1 < cVar1) && (set_cy_before_044f_sub(0xd,CONCAT11(param_1,param_2)), -1 < cVar1)) {
      finish_dptr_be16_load(0xa47);
      cVar3 = -0x80;
      code_byte_sub_from_044c(0xe);
      cVar1 = XDATA_08A0;
      if (-1 < cVar3) {
        XDATA_08A0 = XDATA_08A0 + 1;
        if (XDATA_08A0 < 0xb) {
          return cVar1 - 10;
        }
        XDATA_08EB = XDATA_08EB | 0x40;
        return XDATA_08EB;
      }
    }
  }
  XDATA_08A0 = 0;
  return 0;
}


