// bank0 @ B8CD   test_0770_equals_08   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Same 13-byte shape as 0xB8C0: reads XDATA 0x0770 and returns 1 in R7 if it equals 0x08, 0
   otherwise. It is one of nine adjacent routines at 0xB8C0-0xB928 that each compare the same byte
   against a different constant; 0x0770 has no entry in ec/annotations/registers.yaml.
   type: reader
   evidence: ec/decompiled/bank0/B8CD.asm; ec/decompiled/bank0/B8CD.c
   basis: hand-decoded
   name_basis: code-shape */

void test_0770_equals_08(void)

{
  if (DAT_EXTMEM_0770 == '\b') {
    return;
  }
  return;
}


