// bank0 @ B965   FUN_CODE_b965
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


byte FUN_CODE_b965(char *param_1,char param_2,byte param_3)

{
  byte bVar1;
  
  bVar1 = *param_1 + (param_2 - ((CARRY1(DAT_EXTMEM_0a59,param_3) << 7) >> 7));
  DAT_EXTMEM_0a58 = bVar1 >> 1;
  DAT_EXTMEM_0a59 = DAT_EXTMEM_0a59 + param_3 >> 1 | bVar1 * -0x80;
  return DAT_EXTMEM_0a58;
}


