// bank0 @ BA81   FUN_CODE_ba81
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


char FUN_CODE_ba81(char param_1)

{
  undefined1 uVar1;
  undefined1 uVar2;
  undefined1 *puVar3;
  
  puVar3 = (undefined1 *)
           CONCAT11('c' - (((0xfU < (byte)(param_1 * '\x02')) << 7) >> 7),param_1 * '\x02' - 0x10);
  uVar1 = *puVar3;
  uVar2 = puVar3[1];
  puVar3 = (undefined1 *)CONCAT11(DAT_EXTMEM_0a56,DAT_EXTMEM_0a57);
  FUN_CODE_7110(param_1,2);
  *puVar3 = uVar1;
  puVar3[1] = uVar2;
  return param_1 + '\x01';
}


