; bank0 @ BB40   fan_mode_get   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is BB40.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

BB40     90 07 51   mov      DPTR, #0x751
BB43     e0         movx     A, @DPTR
BB44     54 90      anl      A, #0x90
BB46     22         ret      
