// bank0 @ BB5E   FUN_CODE_bb5e
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


undefined1 FUN_CODE_bb5e(byte param_1,undefined2 param_2)

{
  return *(undefined1 *)
          CONCAT11((char)((ushort)param_2 >> 8) - ((CARRY1(param_1,(byte)param_2) << 7) >> 7),
                   param_1 + (byte)param_2);
}


