; bank0 @ BB6A   fill_0852_0854_with_ff   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is BB6A.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

BB6A     90 08 52 mov      DPTR, #0x852
BB6D     74 ff -  mov      A, #0xff
BB6F     f0 - -   movx     @DPTR, A
BB70     90 08 53 mov      DPTR, #0x853
BB73     f0 - -   movx     @DPTR, A
BB74     90 08 54 mov      DPTR, #0x854
BB77     f0 - -   movx     @DPTR, A
