// bank0 @ BB88   sub_19_from_0857   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Loads DPTR with XDATA 0x0857, reads the byte, clears the carry and subtracts the constant 0x19
   (25) from it, returning the difference in A. No borrow is subtracted further. 0x0857 has no entry
   in ec/annotations/registers.yaml, so the constant is not attached to any documented quantity
   here.
   type: math
   evidence: ec/decompiled/bank0/BB88.asm; ec/decompiled/bank0/BB88.c
   basis: hand-decoded */

char sub_19_from_0857(void)

{
  return DAT_EXTMEM_0857 + -0x19;
}


