// bank0 @ BBDE   gpu_temp_minus_code_table_byte   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads the CODE byte at DPTR+A into R7, reads GPU_TEMP at XDATA 0x044F, and returns it minus that
   CODE byte minus the incoming carry. The carry is the one 0xBBDD sets, which is why the decompiled
   C shows the -1 form. The index A and the table base DPTR are whatever the caller left; the table
   itself is not decoded here.
   type: math
   evidence: ec/decompiled/bank0/BBDE.asm; ec/decompiled/bank0/BBDE.c; ec/annotations/registers.yaml
   basis: hand-decoded
   name_basis: code-shape */

char gpu_temp_minus_code_table_byte(byte param_1,short param_2)

{
  char in_PSW;
  
  return GPU_TEMP - (*(char *)(param_2 + (ushort)param_1) - (in_PSW >> 7));
}


