// bank0 @ BC5F   inc_09e4_and_return_new   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Increments the byte at XDATA 0x09E4, writes it straight back and returns the new value in A. The
   INC sets no carry, so 0xFF wraps to 0x00; 0x09E4 has no entry in ec/annotations/registers.yaml.
   type: math
   evidence: ec/decompiled/bank0/BC5F.asm; ec/decompiled/bank0/BC5F.c
   basis: hand-decoded */

char inc_09e4_and_return_new(void)

{
  DAT_EXTMEM_09e4 = DAT_EXTMEM_09e4 + '\x01';
  return DAT_EXTMEM_09e4;
}


