; bank0 @ BD54   store_be16_b   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is BD54.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

BD54     ff - -   mov      R7, A
BD55     ec - -   mov      A, R4
BD56     fe - -   mov      R6, A
BD57     ee - -   mov      A, R6
BD58     f0 - -   movx     @DPTR, A
BD59     a3 - -   inc      DPTR
BD5A     ef - -   mov      A, R7
BD5B     f0 - -   movx     @DPTR, A
BD5C     22 - -   ret      
