// bank0 @ BD5D   be16_0464_0465_minus_100   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Clears the carry, subtracts 0x64 (100) from XDATA 0x0465, then subtracts 0x00 from XDATA 0x0464
   through the borrow chain. The net effect is the big-endian 16-bit pair {0x0465,0x0464} minus 100,
   low byte in A and borrow in CY. Both addresses now carry an entry in
   ec/annotations/registers.yaml (MAIN_FAN_RPM, 0x0464/0x0465) as of issue #29; this comment said
   otherwise until then.
   type: math
   evidence: ec/decompiled/bank0/BD5D.asm; ec/decompiled/bank0/BD5D.c
   basis: hand-decoded
   name_basis: ec-register */

char be16_0464_0465_minus_100(void)

{
  return MAIN_FAN_RPM_0 + (((MAIN_FAN_RPM_1 < 100) << 7) >> 7);
}


