// bank0 @ BD6B   be16_046c_046d_minus_100   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Same shape as the routine at 0xBD5D but over XDATA 0x046D/0x046C: clears the carry, subtracts
   0x64 from 0x046D, then subtracts 0x00 from 0x046C through the borrow. Returns the low byte of
   {0x046D,0x046C} minus 100 in A with the borrow in CY; neither address has an entry in
   ec/annotations/registers.yaml.
   type: math
   evidence: ec/decompiled/bank0/BD6B.asm; ec/decompiled/bank0/BD6B.c
   basis: hand-decoded
   name_basis: code-shape */

char be16_046c_046d_minus_100(void)

{
  return DAT_EXTMEM_046c + (((DAT_EXTMEM_046d < 100) << 7) >> 7);
}


