// bank0 @ BE21   write_a_to_x1805_and_x1808   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Writes the incoming A to XDATA 0x1805 and then to XDATA 0x1808. Two separate single-byte stores
   three bytes apart; the listing does not present them as one register.
   type: writer
   evidence: ec/decompiled/bank0/BE21.asm; ec/decompiled/bank0/BE21.c
   basis: hand-decoded
   name_basis: code-shape */

void write_a_to_x1805_and_x1808(undefined1 value_a)

{
  DAT_EXTMEM_1805 = value_a;
  DAT_EXTMEM_1808 = value_a;
  return;
}


