; bank0 @ BEAA   FUN_CODE_beaa
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is BEAA.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

BEAA     90 09 e4   mov      DPTR, #0x9e4
BEAD     e0         movx     A, @DPTR
BEAE     54 7f      anl      A, #0x7f
BEB0     d3         setb     CY
BEB1     94 32      subb     A, #0x32
BEB3     22         ret      
