; bank0 @ BF08   sub_0a4e_against_4d_with_borrow   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is BF08.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

BF08     e0 - -   movx     A, @DPTR
BF09     94 61 -  subb     A, #0x61
BF0B     90 0a 4e mov      DPTR, #0xa4e
BF0E     e0 - -   movx     A, @DPTR
BF0F     94 4d -  subb     A, #0x4d
BF11     22 - -   ret      
