// bank0 @ C1CB   test_1603_bit5   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads the byte at XDATA 0x1603 and returns 1 in R7 if bit 5 is set, 0 if it is clear. No other
   XDATA access and no call. The decompiled C drops the R7 return.
   type: reader
   evidence: ec/decompiled/bank0/C1CB.asm; ec/decompiled/bank0/C1CB.c
   basis: hand-decoded
   name_basis: code-shape */

void test_1603_bit5(void)

{
  if ((DAT_EXTMEM_1603 >> 5 & 1) != 0) {
    return;
  }
  return;
}


