; bank0 @ C26E   FUN_CODE_c26e
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is C26E.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

C26E     90 04 56   mov      DPTR, #0x456
C271     e0         movx     A, @DPTR
C272     20 e7 03   jb       0xe7, 0xc278
C275     7f 01      mov      R7, #0x1
C277     22         ret      
C278     90 16 65   mov      DPTR, #0x1665
C27B     e0         movx     A, @DPTR
C27C     30 e2 03   jnb      0xe2, 0xc282
C27F     7f 01      mov      R7, #0x1
C281     22         ret      
C282     7f 00      mov      R7, #0x0
C284     22         ret      
