; bank0 @ C295   test_1665_bit4_inverted   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is C295.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

C295     90 16 65 mov      DPTR, #0x1665
C298     e0 - -   movx     A, @DPTR
C299     30 e4 03 jnb      0xe4, 0xc29f
C29C     7f 00 -  mov      R7, #0x0
C29E     22 - -   ret      
C29F     7f 01 -  mov      R7, #0x1
C2A1     22 - -   ret      
