; bank0 @ C371   clear_1607_bit1   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is C371.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

C371     90 16 07 mov      DPTR, #0x1607
C374     e0 - -   movx     A, @DPTR
C375     54 fd -  anl      A, #0xfd
C377     f0 - -   movx     @DPTR, A
C378     22 - -   ret      
