// bank0 @ C412   test_1668_bit4   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Loads A from XDATA 0x1668 and leaves 1 in R7 when bit 4 is set, 0 when it is clear: JNB on bit 4
   jumps to the R7=0 return. This is the only site the image holds for the byte, so unlike 0x1663
   and 0x1667 there is no mirror accessor to pair it with and no second polarity to compare against.
   The byte's row is XDATA_1668.
   type: logic
   evidence: ec/decompiled/bank0/C412.asm; ec/decompiled/bank0/C412.c
   basis: hand-decoded
   name_basis: ec-register */

void test_1668_bit4(void)

{
  if ((XDATA_1668 >> 4 & 1) != 0) {
    return;
  }
  return;
}


