// bank0 @ C8C5   FUN_CODE_c8c5
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_c8c5(char param_1)

{
  FUN_CODE_b8cd();
  if (param_1 != '\0') {
    DAT_EXTMEM_0027 = 0x66;
    DAT_EXTMEM_0028 = 0x8b;
    return;
  }
  FUN_CODE_b8da();
  if (param_1 != '\0') {
    DAT_EXTMEM_0027 = 0x67;
    DAT_EXTMEM_0028 = 0x8b;
    return;
  }
  FUN_CODE_b8c0();
  if (param_1 != '\0') {
    DAT_EXTMEM_0027 = 0x67;
    DAT_EXTMEM_0028 = 0xb;
    return;
  }
  FUN_CODE_b8e7();
  if (param_1 != '\0') {
    DAT_EXTMEM_0027 = 0x68;
    DAT_EXTMEM_0028 = 0xb;
    return;
  }
  FUN_CODE_b8f4();
  if (param_1 != '\0') {
    DAT_EXTMEM_0027 = 0x68;
    DAT_EXTMEM_0028 = 0x8b;
    return;
  }
  DAT_EXTMEM_0027 = 0x66;
  DAT_EXTMEM_0028 = 0xb;
  return;
}


