; bank0 @ CCCF   init_06e6_1_ccf   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is CCCF.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

CCCF     12 28 96 lcall    0x2896
CCD2     90 06 e6 mov      DPTR, #0x6e6
CCD5     74 01 -  mov      A, #0x1
CCD7     f0 - -   movx     @DPTR, A
CCD8     12 cc 51 lcall    0xcc51
CCDB     12 18 a0 lcall    0x18a0
CCDE     12 c4 c9 lcall    0xc4c9
CCE1     12 d0 84 lcall    0xd084
CCE4     22 - -   ret      
