; bank0 @ D389   FUN_CODE_d389
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is D389.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

D389     90 00 df   mov      DPTR, #0xdf
D38C     e0         movx     A, @DPTR
D38D     04         inc      A
D38E     f0         movx     @DPTR, A
D38F     90 00 d8   mov      DPTR, #0xd8
D392     12 d6 df   lcall    0xd6df
D395     ef         mov      A, R7
D396     f0         movx     @DPTR, A
D397     90 00 d8   mov      DPTR, #0xd8
D39A     e0         movx     A, @DPTR
D39B     04         inc      A
D39C     f0         movx     @DPTR, A
D39D     e0         movx     A, @DPTR
D39E     d3         setb     CY
D39F     94 07      subb     A, #0x7
D3A1     40 02      jc       0xd3a5
D3A3     e4         clr      A
D3A4     f0         movx     @DPTR, A
D3A5     90 00 d9   mov      DPTR, #0xd9
D3A8     e0         movx     A, @DPTR
D3A9     ff         mov      R7, A
D3AA     90 00 d8   mov      DPTR, #0xd8
D3AD     e0         movx     A, @DPTR
D3AE     6f         xrl      A, R7
D3AF     70 16      jnz      0xd3c7
D3B1     90 00 db   mov      DPTR, #0xdb
D3B4     e0         movx     A, @DPTR
D3B5     04         inc      A
D3B6     f0         movx     @DPTR, A
D3B7     90 00 d8   mov      DPTR, #0xd8
D3BA     e0         movx     A, @DPTR
D3BB     70 04      jnz      0xd3c1
D3BD     74 07      mov      A, #0x7
D3BF     f0         movx     @DPTR, A
D3C0     22         ret      
D3C1     90 00 d8   mov      DPTR, #0xd8
D3C4     e0         movx     A, @DPTR
D3C5     14         dec      A
D3C6     f0         movx     @DPTR, A
D3C7     22         ret      
