// bank0 @ D73D   gather_0200_from_table_6d74   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Loops 14 times with R7 running from 0 to 13, and is the mirror image of 0xD72B: each pass calls
   0xD872 to set DPTR to a 16-bit address read big-endian from the CODE table at 0x6D74+2*R7, saves
   the byte read there in R6, calls 0xD894 to set DPTR to XDATA 0x0200+R7, and writes the saved byte
   to it, so it gathers 14 bytes from the table's addresses into XDATA 0x0200-0x020D. Which
   addresses those are is not decoded here.
   type: copy
   evidence: ec/decompiled/bank0/D73D.asm; ec/decompiled/bank0/D73D.c
   basis: hand-decoded
   name_basis: code-shape */

void gather_0200_from_table_6d74(undefined1 *param_1)

{
  undefined1 uVar1;
  char cVar2;
  
  cVar2 = '\0';
  do {
    load_code_ptr_from_table_6d74();
    uVar1 = *param_1;
    set_dptr_0200_plus_r7();
    *param_1 = uVar1;
    cVar2 = cVar2 + '\x01';
  } while (cVar2 != '\x0e');
  return;
}


