// bank0 @ DB3E   rec_ptr_from_index_6e65   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Treats R3 as a 6-byte-stride table index: DPL = 0x65 + R3*6 (MUL AB by 6, then ADD #0x65) and DPH
   = 0x6E plus the carry of that low-byte add, the high byte of the product being dropped. It then
   reads the two CODE bytes at that address with MOVC and loads them into DPTR, first table byte as
   DPH and second as DPL. The .c collapses the DPTR into a one-byte return with an 'n'-based
   expression, which the .asm does not support; what the pointer is used for is not in this body.
   type: reader
   evidence: ec/decompiled/bank0/DB3E.asm; ec/decompiled/bank0/DB3E.c
   basis: hand-decoded
   name_basis: code-shape */

undefined1 rec_ptr_from_index_6e65(char param_1)

{
  return *(undefined1 *)
          (CONCAT11('n' - (((0x9aU < (byte)(param_1 * '\x06')) << 7) >> 7),param_1 * '\x06' + 0x65)
          + 1);
}


