; bank0 @ E161   read_code_pair_at_dptr_into_r2_r1   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is E161.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

E161     f5 83 -  mov      DPH, A
E163     e4 - -   clr      A
E164     93 - -   movc     A, @A+DPTR
E165     fe - -   mov      R6, A
E166     74 01 -  mov      A, #0x1
E168     93 - -   movc     A, @A+DPTR
E169     ca - -   xch      A, R2
E16A     ee - -   mov      A, R6
E16B     ca - -   xch      A, R2
E16C     f9 - -   mov      R1, A
E16D     22 - -   ret      
