// bank0 @ E256   dispatch_on_0046_copy_status_to_0083   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Clears XDATA 0x0083, then, if XDATA 0x0046 is 0x64, 0x66 or 0x6C, writes 0xFA to XDATA 0x1306,
   0x1501 or 0x1511 respectively. It then loops on XDATA 0x0046: for 0x64 it reads XDATA 0x1304 and
   requires bit 1 (JNB bit address 0xE1) and bit 3 (JB bit address 0xE3) before copying XDATA 0x130A
   into XDATA 0x0083; 0x66 does the same with XDATA 0x1500 and 0x1504, and 0x6C with XDATA 0x1510
   and 0x1514. A clear bit 1 spins back to the loop head, bit 3 clear stores the second byte and
   loops back, and bit 3 set stores it and falls through to the 0x0083 tests, which are also
   reachable directly when 0x0046 is none of the three codes. Finally, if XDATA 0x0083 reads 0x95
   the routine writes 0x33 to XDATA 0x0045, calls 0x1978 and jumps to 0x0200; if it reads 0xAF it
   writes 0xAF to XDATA 0x1036, clears bit 3 of XDATA 0x1121, writes 0x08 to 0x1120, sets bit 0 of
   XDATA 0x2011, sets bit 0 of the direct bytes 0xD8 and 0xD9, and then spins forever on the SJMP to
   itself at 0xE31A. What the selector codes 0x64/0x66/0x6C and the result codes 0x95/0xAF denote is
   not established by the listing.
   type: dispatch
   evidence: ec/decompiled/bank0/E256.asm; ec/decompiled/bank0/E256.c
   basis: hand-decoded */

void dispatch_on_0046_copy_status_to_0083(void)

{
  undefined1 *puVar1;
  char *pcVar2;
  
  DAT_EXTMEM_0083 = '\0';
  if (DAT_EXTMEM_0046 == 'd') {
    puVar1 = &DAT_EXTMEM_1306;
  }
  else if (DAT_EXTMEM_0046 == 'f') {
    puVar1 = &DAT_EXTMEM_1501;
  }
  else {
    if (DAT_EXTMEM_0046 != 'l') goto LAB_CODE_e280;
    puVar1 = &DAT_EXTMEM_1511;
  }
  *puVar1 = 0xfa;
LAB_CODE_e280:
  while (DAT_EXTMEM_0046 == 'd') {
    if ((DAT_EXTMEM_1304 >> 1 & 1) != 0) {
      if ((DAT_EXTMEM_1304 >> 3 & 1) != 1) {
        pcVar2 = &DAT_EXTMEM_130a;
        goto LAB_CODE_e2d8;
      }
      pcVar2 = &DAT_EXTMEM_130a;
LAB_CODE_e2e2:
      DAT_EXTMEM_0083 = *pcVar2;
LAB_CODE_e2e7:
      if (DAT_EXTMEM_0083 == -0x6b) {
        DAT_EXTMEM_0045 = 0x33;
        trampoline_bank1_a710();
        nop();
        FUN_CODE_0200();
        return;
      }
      if (DAT_EXTMEM_0083 == -0x51) {
        CCF_0 = 1;
        CCF_1 = 1;
        do {
                    /* WARNING: Do nothing block with infinite loop */
        } while( true );
      }
    }
  }
  if (DAT_EXTMEM_0046 == 'f') {
    if ((DAT_EXTMEM_1500 >> 1 & 1) == 0) goto LAB_CODE_e280;
    if ((DAT_EXTMEM_1500 >> 3 & 1) == 1) {
      pcVar2 = &DAT_EXTMEM_1504;
      goto LAB_CODE_e2e2;
    }
    pcVar2 = &DAT_EXTMEM_1504;
  }
  else {
    if (DAT_EXTMEM_0046 != 'l') goto LAB_CODE_e2e7;
    if ((DAT_EXTMEM_1510 >> 1 & 1) == 0) goto LAB_CODE_e280;
    if ((DAT_EXTMEM_1510 >> 3 & 1) == 1) {
      pcVar2 = &DAT_EXTMEM_1514;
      goto LAB_CODE_e2e2;
    }
    pcVar2 = &DAT_EXTMEM_1514;
  }
LAB_CODE_e2d8:
  DAT_EXTMEM_0083 = *pcVar2;
  goto LAB_CODE_e280;
}


