// bank0 @ E37B   store_a_to_dptr_then_164c_164e   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Writes A to the XDATA byte at the caller's DPTR, then writes the same A to XDATA 0x164C, 0x164D
   and 0x164E and returns. Entered from 0xE376 with DPTR = 0x164B and A = 0x80, the whole run fills
   XDATA 0x164B through 0x164E with 0x80.
   type: writer
   evidence: ec/decompiled/bank0/E37B.asm; ec/decompiled/bank0/E37B.c
   basis: hand-decoded
   name_basis: code-shape */

void store_a_to_dptr_then_164c_164e(undefined1 a80_from_e379,undefined1 *param_2)

{
  *param_2 = a80_from_e379;
  DAT_EXTMEM_164c = a80_from_e379;
  DAT_EXTMEM_164d = a80_from_e379;
  DAT_EXTMEM_164e = a80_from_e379;
  return;
}


