// bank0 @ EBD5   dispatch_on_0a4b_via_7151   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Fall-through continuation of 0xEADA: calls 0x1510; loads DPTR=0x0A4B; reads that byte and calls
   0x7151 with it in A. Whatever 0x7151 returns in R3/R4 is then adjusted (R3 is decremented) and
   control jumps to 0xE8EC with A holding R4. The table 0x7151 indexes and the targets at 0xE8EC are
   not decoded in this listing.
   type: dispatch
   evidence: ec/decompiled/bank0/EBD5.asm; ec/decompiled/bank0/EBD5.c
   basis: hand-decoded */

void dispatch_on_0a4b_via_7151(char param_1,undefined1 param_2)

{
  FUN_CODE_1510();
  switch_case_dispatch(DAT_EXTMEM_0a4b);
  nop();
  mask_1603_and_wait_tf1(param_2,param_1 + -1);
  return;
}


