; bank0 @ ED52   FUN_CODE_ed52
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is ED52.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

ED52     90 1c 41   mov      DPTR, #0x1c41
ED55     74 12      mov      A, #0x12
ED57     f0         movx     @DPTR, A
ED58     90 0a 49   mov      DPTR, #0xa49
ED5B     e0         movx     A, @DPTR
ED5C     ff         mov      R7, A
ED5D     a3         inc      DPTR
ED5E     e0         movx     A, @DPTR
ED5F     90 08 fe   mov      DPTR, #0x8fe
ED62     cf         xch      A, R7
ED63     f0         movx     @DPTR, A
ED64     a3         inc      DPTR
ED65     ef         mov      A, R7
ED66     f0         movx     @DPTR, A
ED67     90 16 01   mov      DPTR, #0x1601
ED6A     e0         movx     A, @DPTR
ED6B     54 ef      anl      A, #0xef
ED6D     f0         movx     @DPTR, A
