// bank0 @ ED74   FUN_CODE_ed74
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


undefined1 FUN_CODE_ed74(void)

{
  undefined1 uVar1;
  
  FUN_CODE_0ea2(0x14);
  DAT_EXTMEM_0a59 = 0xb6;
  DAT_EXTMEM_0a5a = 0;
  DAT_EXTMEM_0a5b = 0xc0;
  DAT_EXTMEM_0a5c = 0;
  uVar1 = 1;
  FUN_CODE_445e(DAT_EXTMEM_0a48,0xc,0,1);
  return uVar1;
}


