// bank0 @ EED6   send_0x10_via_f079_then_chain   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Same shape as 0xEE0F but loads A=0x10 and calls 0xF079 instead of 0xF078; the rest of the chain
   is identical. The listing ends on the jz after the 0xEDBC call so the success path's return value
   is not shown - unlike 0xEE0F the mov R7 1 bytes are missing from it.
   type: logic
   evidence: ec/decompiled/bank0/EED6.asm; ec/decompiled/bank0/EED6.c
   basis: hand-decoded
   name_basis: code-shape */

void send_0x10_via_f079_then_chain(short param_1,char param_2)

{
  char cVar1;
  
  write_98_to_0f60();
  store_a_0_1_zeros_at_dptr(0x10,param_1 + 1);
  set_r3_09_r5_80_r7_01();
  stage_0a54_0a55_then_dispatch();
  if (param_2 != '\0') {
    cVar1 = '\x14';
    timer1_counted_delay_using_0a56('\x14');
    set_0f60_84_and_0a56_block();
    stage_0a54_0a55_then_dispatch();
    if ((cVar1 != '\0') && (DAT_EXTMEM_0f81 != '\0')) {
      set_0f60_88_and_0a56_0f_60();
      copy_0f81_to_0a58();
      store_0f_80_and_setup_regs();
      stage_0a54_0a55_then_dispatch();
      if (cVar1 != '\0') {
        four_calls_then_4777_flag();
        if (cVar1 != '\0') {
          return;
        }
      }
    }
  }
  return;
}


