// bank0 @ EFDC   call_ef17_then_copy_0f80_to_0fb1   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Calls 0xEF17 and jumps to 0xF06B if it returns zero. On success it copies XDATA 0x0F80 to 0x0FB1
   and then sets DPTR to 0x0F81; the listing stops there so the copies of 0x0F81-0x0F83 that the
   decompiled C shows are not in it.
   type: copy
   evidence: ec/decompiled/bank0/EFDC.asm; ec/decompiled/bank0/EFDC.c
   basis: hand-decoded
   name_basis: code-shape */

void call_ef17_then_copy_0f80_to_0fb1(char param_1)

{
  char cVar1;
  byte bVar2;
  
  call_f0a1_with_d6_then_4777_flag();
  if (param_1 == '\0') {
    clear_0fc3_bit0_and_zero_0fc0();
    return;
  }
  DAT_EXTMEM_0fb1 = DAT_EXTMEM_0f80;
  DAT_EXTMEM_0fb2 = DAT_EXTMEM_0f81;
  DAT_EXTMEM_0fb3 = DAT_EXTMEM_0f82;
  DAT_EXTMEM_0fb4 = DAT_EXTMEM_0f83;
  DAT_EXTMEM_0a43 = DAT_EXTMEM_0f82 & 3;
  DAT_EXTMEM_0a44 = DAT_EXTMEM_0f83;
  DAT_EXTMEM_0a46 = DAT_EXTMEM_0f82 & 0xfc;
  cVar1 = '\x02';
  bVar2 = DAT_EXTMEM_0f81 & 0xf;
  do {
    DAT_EXTMEM_0a45 = bVar2 >> 1;
    DAT_EXTMEM_0a46 = DAT_EXTMEM_0a46 >> 1 | bVar2 << 7;
    cVar1 = cVar1 + -1;
    bVar2 = DAT_EXTMEM_0a45;
  } while (cVar1 != '\0');
  cVar1 = (DAT_EXTMEM_0a45 < 1U - (((DAT_EXTMEM_0a46 < 0x90) << 7) >> 7)) << 7;
  if ((cVar1 < '\0') ||
     (((DAT_EXTMEM_0f82 & 3) < 1U - (((DAT_EXTMEM_0f83 < 0x45U - (cVar1 >> 7)) << 7) >> 7)) << 7 <
      '\0')) {
    DAT_EXTMEM_0fc3 = DAT_EXTMEM_0fc3 & 0xfe;
  }
  else {
    DAT_EXTMEM_0fc3 = DAT_EXTMEM_0fc3 | 1;
  }
  DAT_EXTMEM_0fc0 = 0;
  return;
}


