// bank0 @ F0F3   set_0a56_to_0f_60   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Sets DPTR to 0x0A56, writes 0x0F there and 0x60 at XDATA 0x0A57, then returns. It touches only
   the first two bytes of the 0x0A56-0x0A5A block and neither reads nor writes the caller's DPTR.
   The .asm covers the whole sequence including the `ret`. Neither address has an entry in
   ec/annotations/registers.yaml.
   type: writer
   evidence: ec/decompiled/bank0/F0F3.asm; ec/decompiled/bank0/F0F3.c
   basis: hand-decoded */

void set_0a56_to_0f_60(void)

{
  DAT_EXTMEM_0a56 = 0xf;
  DAT_EXTMEM_0a57 = 0x60;
  return;
}


