// bank0 @ F116   store_40_to_1621_1622   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* The listing here is a single instruction, mov A,#0x40; the bytes that follow at 0xF118 store that
   A to XDATA 0x1621 and XDATA 0x1622 and return, so this entry is one fragment of a 7-byte routine
   rather than a function of its own. No other address is touched by either half.
   type: writer
   evidence: ec/decompiled/bank0/F116.asm; ec/decompiled/bank0/F116.c
   basis: hand-decoded */

void store_40_to_1621_1622(void)

{
  DAT_EXTMEM_1621 = 0x40;
  DAT_EXTMEM_1622 = 0x40;
  return;
}


