// bank0 @ F159   inc_dptr_byte_sub3   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Increments the byte at the address already in the caller's DPTR and writes it back, reloads it,
   clears the carry and subtracts 0x03. It returns with A holding the new value minus 3 modulo 256
   and the carry set when the new value is below 3; DPTR is never reloaded here, so the byte touched
   is whatever the caller left in DPTR.
   type: math
   evidence: ec/decompiled/bank0/F159.asm; ec/decompiled/bank0/F159.c
   basis: hand-decoded */

char inc_dptr_byte_sub3(char *param_1)

{
  *param_1 = *param_1 + '\x01';
  return *param_1 + -3;
}


