; bank0 @ F17E   read_0a51_with_r7_from_0a4e   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is F17E.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

F17E     90 0a 4d mov      DPTR, #0xa4d
F181     a3 - -   inc      DPTR
F182     e0 - -   movx     A, @DPTR
F183     ff - -   mov      R7, A
F184     90 0a 51 mov      DPTR, #0xa51
F187     e0 - -   movx     A, @DPTR
F188     22 - -   ret      
