// bank0 @ F495   set_dptr_0f60_then_store_a   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* The listing is a single mov DPTR,#0x0F60, the middle of the routine that starts at 0xF493. Taken
   as an entry point in its own right it only loads DPTR and then falls into the store at 0xF498,
   the 0x0A56/0x0A57 writes at 0xF499 and the return; the call from 0xF1E9 passes 0x80 in A.
   type: writer
   evidence: ec/decompiled/bank0/F495.asm; ec/decompiled/bank0/F495.c
   basis: hand-decoded */

void set_dptr_0f60_then_store_a(undefined1 param_1)

{
  DAT_EXTMEM_0f60 = param_1;
  DAT_EXTMEM_0a56 = 0xf;
  DAT_EXTMEM_0a57 = 0x60;
  return;
}


