; OverClockSmiHandler @ 000058E4   FUN_000058e4
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OverClockSmiHandler.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 000058E4.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

000058E4 48 8b 0d 35 08 00 00 mov      RCX, qword ptr [0x00006120]
000058EB 33 c0      xor      EAX, EAX
000058ED 48 85 c9   test     RCX, RCX
000058F0 75 57      jnz      0x00005949
000058F2 48 8b 15 07 08 00 00 mov      RDX, qword ptr [0x00006100]
000058F9 8b c8      mov      ECX, EAX
000058FB 48 89 05 1e 08 00 00 mov      qword ptr [0x00006120], RAX
00005902 4c 8b 42 68 mov      R8, qword ptr [RDX + 0x68]
00005906 4d 85 c0   test     R8, R8
00005909 74 3e      jz       0x00005949
0000590B 4c 8b 4a 70 mov      R9, qword ptr [RDX + 0x70]
0000590F 4c 8b 15 42 07 00 00 mov      R10, qword ptr [0x00006058]
00005916 49 8b d1   mov      RDX, R9
00005919 4c 8b 1d 30 07 00 00 mov      R11, qword ptr [0x00006050]
00005920 4c 3b 1a   cmp      R11, qword ptr [RDX]
00005923 75 06      jnz      0x0000592b
00005925 4c 3b 52 08 cmp      R10, qword ptr [RDX + 0x8]
00005929 74 0e      jz       0x00005939
0000592B 48 ff c0   inc      RAX
0000592E 48 83 c2 18 add      RDX, 0x18
00005932 49 3b c0   cmp      RAX, R8
00005935 73 12      jnc      0x00005949
00005937 eb e7      jmp      0x00005920
00005939 48 8d 04 40 lea      RAX, [RAX + RAX*0x2]
0000593D 49 8b 4c c1 10 mov      RCX, qword ptr [R9 + RAX*0x8 + 0x10]
00005942 48 89 0d d7 07 00 00 mov      qword ptr [0x00006120], RCX
00005949 48 8b c1   mov      RAX, RCX
0000594C c3         ret      
