; OverClockSmiHandler @ 00005530   call_protocol_table_three_times   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OverClockSmiHandler.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00005530.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00005530 48 89 54 24 10 - - - - -      mov      qword ptr [RSP + 0x10], RDX
00005535 48 89 4c 24 08 - - - - -      mov      qword ptr [RSP + 0x8], RCX
0000553A 48 83 ec 48 - - - - - -       sub      RSP, 0x48
0000553E 4c 8d 44 24 28 - - - - -      lea      R8, [RSP + 0x28]
00005543 33 d2 - - - - - - - -         xor      EDX, EDX
00005545 48 8d 0d 34 0b 00 00 - - -    lea      RCX, [0x6080]
0000554C 48 8b 05 c5 0b 00 00 - - -    mov      RAX, qword ptr [0x00006118]
00005553 ff 90 d0 00 00 00 - - - -     call     qword ptr [RAX + 0xd0]
00005559 48 89 44 24 20 - - - - -      mov      qword ptr [RSP + 0x20], RAX
0000555E 0f b6 05 3b 0b 00 00 - - -    movzx    EAX, byte ptr [0x000060a0]
00005565 48 89 44 24 30 - - - - -      mov      qword ptr [RSP + 0x30], RAX
0000556A 4c 8d 4c 24 38 - - - - -      lea      R9, [RSP + 0x38]
0000556F 4c 8d 44 24 30 - - - - -      lea      R8, [RSP + 0x30]
00005574 48 8d 15 05 c6 ff ff - - -    lea      RDX, [0x1b80]
0000557B 48 8b 4c 24 28 - - - - -      mov      RCX, qword ptr [RSP + 0x28]
00005580 48 8b 44 24 28 - - - - -      mov      RAX, qword ptr [RSP + 0x28]
00005585 ff 10 - - - - - - - -         call     qword ptr [RAX]
00005587 48 89 44 24 20 - - - - -      mov      qword ptr [RSP + 0x20], RAX
0000558C 4c 8d 05 c5 0c 00 00 - - -    lea      R8, [0x6258]
00005593 33 d2 - - - - - - - -         xor      EDX, EDX
00005595 48 8d 0d 84 0a 00 00 - - -    lea      RCX, [0x6020]
0000559C 48 8b 05 75 0b 00 00 - - -    mov      RAX, qword ptr [0x00006118]
000055A3 ff 90 d0 00 00 00 - - - -     call     qword ptr [RAX + 0xd0]
000055A9 48 89 44 24 20 - - - - -      mov      qword ptr [RSP + 0x20], RAX
000055AE 4c 8d 05 ab 0c 00 00 - - -    lea      R8, [0x6260]
000055B5 33 d2 - - - - - - - -         xor      EDX, EDX
000055B7 48 8d 0d 52 0a 00 00 - - -    lea      RCX, [0x6010]
000055BE 48 8b 05 53 0b 00 00 - - -    mov      RAX, qword ptr [0x00006118]
000055C5 ff 90 d0 00 00 00 - - - -     call     qword ptr [RAX + 0xd0]
000055CB 48 89 44 24 20 - - - - -      mov      qword ptr [RSP + 0x20], RAX
000055D0 48 8b 44 24 20 - - - - -      mov      RAX, qword ptr [RSP + 0x20]
000055D5 48 83 c4 48 - - - - - -       add      RSP, 0x48
000055D9 c3 - - - - - - - - -          ret      
