// bank0 @ 0003   int0_vector_forwarder_to_052f   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Single ljmp to 0x052F. 0x0003 is the external interrupt 0 vector slot in the 8051 vector table,
   whose entries are 8 bytes apart -- 0x0000, 0x0003, 0x000B, 0x0013, 0x001B and 0x0023 all hold a
   bare ljmp here. The .c body for this address is empty, so nothing about the handler at 0x052F is
   available from this file pair.
   type: forwarder
   evidence: ec/decompiled/bank0/0003.asm; ec/decompiled/bank0/0003.c
   basis: hand-decoded */

void int0_vector_forwarder_to_052f(void)

{
  return;
}


