// bank0 @ 029B   FUN_CODE_029b
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_029b(void)

{
  char cVar1;
  
  if ((DAT_EXTMEM_1708 >> 3 & 1) == 0) {
    FUN_CODE_07d0(0x1701);
    DAT_INTMEM_aa = 0;
    DAT_EXTMEM_1106 = DAT_EXTMEM_1106 | 0x10;
  }
  else {
    DAT_EXTMEM_1106 = DAT_EXTMEM_1106 & 0xef;
    DAT_EXTMEM_1102 = 0x10;
    if (_c_0 == '\0') {
      DAT_EXTMEM_200b = 0;
    }
    else {
      DAT_EXTMEM_0043 = 0;
      do {
        if ((DAT_EXTMEM_1708 & 1) == 1) break;
        DAT_EXTMEM_200b = 0;
        cVar1 = FUN_CODE_07f0();
      } while (cVar1 != '\x05');
    }
    FUN_CODE_07c1();
    DAT_INTMEM_84 = 0;
    FUN_CODE_07e7();
    DAT_INTMEM_97 = DAT_EXTMEM_170c;
  }
  load_dptr_bf57_tail_jump_1100();
  return;
}


