// bank0 @ 0556   int1_target_six_calls_14c8_012f_018c_029b_7110_7177   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* The external interrupt 1 handler, 96 bytes, with the same full save and restore of A, B, DPH, DPL
   and PSW as its neighbours. Between them it calls six routines -- 0x14C8, 0x012F, 0x018C, 0x029B,
   0x7110 and 0x7177 -- and the body of the frame between 0x012F and 0x029B tests a byte and
   branches on it, which is what makes this a dispatch rather than a straight-line sequence. It
   restores the saved registers and returns with `reti` at 0x05B5. None of the six callees is
   decoded here, so what this handler decides is not established.
   type: dispatch
   evidence: ec/decompiled/common/0556.asm; ec/decompiled/common/0556.c
   basis: hand-decoded */

undefined1 int1_target_six_calls_14c8_012f_018c_029b_7110_7177(undefined1 param_1)

{
  undefined1 *puVar1;
  
  if (_d_6 == '\0') {
    if (DAT_EXTMEM_1110 == '\"') {
      FUN_CODE_012f();
    }
    else if (DAT_EXTMEM_1110 == '#') {
      FUN_CODE_018c();
    }
    else if (DAT_EXTMEM_1110 == '$') {
      FUN_CODE_029b();
    }
    else {
      puVar1 = (undefined1 *)0x636;
      FUN_CODE_7110(DAT_EXTMEM_1110,2);
      FUN_CODE_7177(puVar1[1],*puVar1);
    }
  }
  else {
    FUN_CODE_14c8();
  }
  _d_4 = 1;
  return param_1;
}


