// bank0 @ 05E8   critical_section_enter_05e8   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Clears EA, the direct bit 0xAF, and executes four NOPs before returning. EA is IE.7, the global
   interrupt enable, so this is the enter half of a matched critical section: interrupts off, a
   four-NOP delay whose purpose is not decoded here, and back to the caller. The matching exit is
   0x05EF (critical_section_exit_05ef). The address suffix is in the name because several
   one-instruction routines in the common area are genuinely the same code and the name has to
   identify this one.
   type: gate
   evidence: ec/decompiled/common/05E8.asm; ec/decompiled/common/05E8.c
   basis: hand-decoded
   name_basis: code-shape */

void critical_section_enter_05e8(void)

{
  EA = 0;
  nop();
  nop();
  nop();
  nop();
  return;
}


