; bank0 @ 08D0   FUN_CODE_08d0
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 08D0.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

08D0     e5 36      mov      A, 0x36
08D2     14         dec      A
08D3     60 07      jz       0x08dc
08D5     14         dec      A
08D6     70 07      jnz      0x08df
08D8     85 37 38   mov      0x38, 0x37
08DB     22         ret      
08DC     12 08 e0   lcall    0x08e0
08DF     22         ret      
