; bank0 @ 0A74   rearm_timer1_then_set_bit_4_of_internal_41   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 0A74.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

0A74     12 0e 72 lcall    0x0e72
0A77     af 41 -  mov      R7, 0x41
0A79     ef - -   mov      A, R7
0A7A     44 10 -  orl      A, #0x10
0A7C     f5 41 -  mov      0x41, A
0A7E     22 - -   ret      
