// bank0 @ 1114   bl51_bank_select_1   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Keil BL51 cross-bank switch stub that selects bank 1 in the common area: 53 of the 403
   trampolines in 0x1150-0x1ABC route through it. The audit counts bank0 calling 61 bank-1
   trampolines and bank1 calling 229 bank-0 ones but does not say how these 53 split between those
   callers so no caller is attributed to this stub
   type: gate
   evidence: ec/annotations/bank-call-audit.md
   basis: hand-decoded
   name_basis: abi-symbol */

void bl51_bank_select_1(void)

{
  BANK1_R0 = 0x1e;
  P1_0 = 1;
  P1_1 = 0;
  P1_2 = 0;
  return;
}


