; bank0 @ 113C   bl51_bank_select_3   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 113C.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

113C     c0 08 -  push     0x08
113E     74 11 -  mov      A, #0x11
1140     c0 e0 -  push     A
1142     c0 82 -  push     DPL
1144     c0 83 -  push     DPH
1146     75 08 46 mov      0x08, #0x46
1149     d2 90 -  setb     0x90
114B     d2 91 -  setb     0x91
114D     c2 92 -  clr      0x92
114F     22 - -   ret      
