// bank0 @ 2632   FUN_CODE_2632
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_2632(void)

{
  byte bVar1;
  char cVar2;
  byte bVar3;
  
  bVar1 = DAT_INTMEM_4d >> 4;
  DAT_INTMEM_4c = DAT_INTMEM_4c & 0xf0 | bVar1;
  DAT_INTMEM_65 = *(byte *)CONCAT11('\r' - (((0x8f < bVar1) << 7) >> 7),bVar1 + 0x70);
  bVar3 = 1;
  cVar2 = (DAT_INTMEM_4d & 7) + 1;
  while (cVar2 = cVar2 + -1, cVar2 != '\0') {
    bVar3 = bVar3 << 1;
  }
  DAT_INTMEM_66 = bVar3 & DAT_INTMEM_65;
  FUN_CODE_23f4(bVar1);
  zero_xdata_200b();
  if (_3_7 == '\0') {
    DAT_INTMEM_65 = DAT_EXTMEM_1d04 ^ 0xff;
  }
  else {
    DAT_INTMEM_65 = DAT_EXTMEM_1d04;
  }
  bVar3 = FUN_CODE_2a35();
  while (cVar2 = cVar2 + -1, cVar2 != '\0') {
    bVar3 = bVar3 << 1;
  }
  DAT_INTMEM_66 = bVar3 & DAT_INTMEM_65;
  if (DAT_INTMEM_66 == 0) {
    if ((DAT_INTMEM_49 >> 1 & 1) != 1) goto LAB_CODE_26ac;
  }
  else if ((DAT_INTMEM_49 >> 1 & 1) == 1) {
LAB_CODE_26ac:
    DAT_INTMEM_49 = DAT_INTMEM_49 & 0xef;
    goto LAB_CODE_26b8;
  }
  DAT_INTMEM_49 = DAT_INTMEM_49 | 0x10;
LAB_CODE_26b8:
  if ((DAT_INTMEM_49 >> 4 & 1) == 1) {
    FUN_CODE_26cb();
    return;
  }
  DAT_INTMEM_4d = 0;
  DAT_INTMEM_49 = 0;
  return;
}


