// bank0 @ 271A   FUN_CODE_271a
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_271a(byte *param_1)

{
  byte bVar1;
  
  DAT_INTMEM_66 = '\0';
  DAT_INTMEM_65 = FUN_CODE_2a38(DAT_EXTMEM_0a48);
  while (param_1 = param_1 + -1, param_1 != (byte *)0x0) {
    DAT_INTMEM_65 = DAT_INTMEM_65 << 1;
  }
  FUN_CODE_2aa5(DAT_EXTMEM_0a48);
  DAT_INTMEM_65 = DAT_INTMEM_65 & *param_1;
  if (DAT_INTMEM_65 == 0) {
    DAT_INTMEM_66 = '\x01';
    DAT_INTMEM_4e = 0;
  }
  if ((DAT_INTMEM_66 == '\0') &&
     (bVar1 = (DAT_INTMEM_4b >> 4) - 1, DAT_INTMEM_4b = bVar1 * '\x10' | DAT_INTMEM_4b & 0xf,
     (bVar1 & 0xf) != 0)) {
    DAT_INTMEM_66 = '\x01';
  }
  if (DAT_INTMEM_66 == '\0') {
    DAT_INTMEM_4b = DAT_INTMEM_4b & 0xf | 0x20;
    DAT_EXTMEM_0025 = DAT_EXTMEM_0025 + -1;
    if (DAT_EXTMEM_0025 != '\0') {
      DAT_INTMEM_66 = '\x01';
    }
  }
  if (DAT_INTMEM_66 == '\0') {
    DAT_EXTMEM_0025 = DAT_EXTMEM_0023;
    FUN_CODE_2a42(0x48,10,1);
    DAT_EXTMEM_0a4a = 2;
    FUN_CODE_1059();
  }
  return;
}


