// bank0 @ 2990   advance_bfe_counter_publish_at_bfd   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Sets XDATA 0x0A59 to 1, then advances the byte at 0x0BFE: it calls 0x2A84, stores the result in
   R7's place at 0x0BFE, increments 0x0BFE, and clamps it back to 0 when it has reached 0xFD. If the
   new value equals the byte at 0x0BFD it copies 0x0BFE to 0x0BFF, calls 0x2A84, zeroes 0x0BFE and
   zeroes 0x0A59. It returns 0x0A59 in R7. It carries 34 transfer sites from five distinct callers,
   the largest of them contributing 20 and 0xAA90 contributing 8, so the count is a hot loop rather
   than 34 independent uses.
   type: state
   evidence: ec/decompiled/common/2990.asm; ec/decompiled/common/2990.c
   basis: hand-decoded
   name_basis: code-shape */

undefined1 advance_bfe_counter_publish_at_bfd(undefined1 param_1)

{
  undefined1 *puVar1;
  
  DAT_EXTMEM_0a59 = 1;
  puVar1 = &DAT_EXTMEM_0bfe;
  FUN_CODE_2a84();
  *puVar1 = param_1;
  DAT_EXTMEM_0bfe = DAT_EXTMEM_0bfe + 1;
  if (0xfc < DAT_EXTMEM_0bfe) {
    DAT_EXTMEM_0bfe = 0;
  }
  if (DAT_EXTMEM_0bfe == DAT_EXTMEM_0bfd) {
    puVar1 = &DAT_EXTMEM_0bfe;
    DAT_EXTMEM_0bfe = DAT_EXTMEM_0bff;
    FUN_CODE_2a84();
    *puVar1 = 0;
    DAT_EXTMEM_0a59 = 0;
  }
  return DAT_EXTMEM_0a59;
}


