; bank0 @ 2ACD   FUN_CODE_2acd
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 2ACD.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

2ACD     90 13 04 mov      DPTR, #0x1304
2AD0     e0 - -   movx     A, @DPTR
2AD1     20 e0 11 jb       0xe0, 0x2ae5
2AD4     e0 - -   movx     A, @DPTR
2AD5     30 e1 02 jnb      0xe1, 0x2ada
2AD8     80 0b -  sjmp     0x2ae5
2ADA     78 85 -  mov      R0, #0x85
2ADC     e6 - -   mov      A, @R0
2ADD     60 03 -  jz       0x2ae2
2ADF     16 - -   dec      @R0
2AE0     80 08 -  sjmp     0x2aea
2AE2     30 05 05 jnb      0x05, 0x2aea
2AE5     7f 06 -  mov      R7, #0x6
2AE7     02 2b c1 ljmp     0x2bc1
2AEA     78 8b -  mov      R0, #0x8b
2AEC     e6 - -   mov      A, @R0
2AED     ff - -   mov      R7, A
2AEE     12 2b 6c lcall    0x2b6c
2AF1     30 13 0b jnb      0x13, 0x2aff
2AF4     12 30 b5 lcall    0x30b5
2AF7     7f 06 -  mov      R7, #0x6
2AF9     12 2b cb lcall    0x2bcb
2AFC     02 2b 68 ljmp     0x2b68
2AFF     e4 - -   clr      A
2B00     ff - -   mov      R7, A
2B01     74 88 -  mov      A, #0x88
2B03     2f - -   add      A, R7
2B04     f8 - -   mov      R0, A
2B05     e6 - -   mov      A, @R0
2B06     30 e6 1a jnb      0xe6, 0x2b23
2B09     ef - -   mov      A, R7
2B0A     12 3b 22 lcall    0x3b22
2B0D     12 3b 32 lcall    0x3b32
2B10     12 3b 70 lcall    0x3b70
2B13     c0 83 -  push     DPH
2B15     c0 82 -  push     DPL
2B17     12 3b 4e lcall    0x3b4e
2B1A     93 - -   movc     A, @A+DPTR
2B1B     fd - -   mov      R5, A
2B1C     ee - -   mov      A, R6
2B1D     4d - -   orl      A, R5
2B1E     d0 82 -  pop      DPL
2B20     d0 83 -  pop      DPH
2B22     f0 - -   movx     @DPTR, A
2B23     0f - -   inc      R7
2B24     ef - -   mov      A, R7
2B25     b4 03 d9 cjne     A, #0x3, 0x2b01
2B28     e4 - -   clr      A
2B29     ff - -   mov      R7, A
2B2A     78 87 -  mov      R0, #0x87
2B2C     e6 - -   mov      A, @R0
2B2D     6f - -   xrl      A, R7
2B2E     70 2e -  jnz      0x2b5e
2B30     e6 - -   mov      A, @R0
2B31     12 3b 22 lcall    0x3b22
2B34     fc - -   mov      R4, A
2B35     74 01 -  mov      A, #0x1
2B37     93 - -   movc     A, @A+DPTR
2B38     f5 82 -  mov      DPL, A
2B3A     8c 83 -  mov      DPH, R4
2B3C     74 17 -  mov      A, #0x17
2B3E     f0 - -   movx     @DPTR, A
2B3F     e6 - -   mov      A, @R0
2B40     12 3b 3e lcall    0x3b3e
2B43     fc - -   mov      R4, A
2B44     74 01 -  mov      A, #0x1
2B46     93 - -   movc     A, @A+DPTR
2B47     f5 82 -  mov      DPL, A
2B49     8c 83 -  mov      DPH, R4
2B4B     c0 83 -  push     DPH
2B4D     c0 82 -  push     DPL
2B4F     e0 - -   movx     A, @DPTR
2B50     fe - -   mov      R6, A
2B51     e6 - -   mov      A, @R0
2B52     12 3b 51 lcall    0x3b51
2B55     93 - -   movc     A, @A+DPTR
2B56     fd - -   mov      R5, A
2B57     ee - -   mov      A, R6
2B58     4d - -   orl      A, R5
2B59     d0 82 -  pop      DPL
2B5B     d0 83 -  pop      DPH
2B5D     f0 - -   movx     @DPTR, A
2B5E     0f - -   inc      R7
2B5F     ef - -   mov      A, R7
2B60     b4 03 c7 cjne     A, #0x3, 0x2b2a
2B63     7f 06 -  mov      R7, #0x6
2B65     12 2b c1 lcall    0x2bc1
