// bank0 @ 2E9C   store_0a4c_triplet_then_countdown_and_dispatch   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* 129 bytes, the second-largest row in the tranche, ending in a tail jump to 0x3A0D, so its frame
   is the head of a longer sequence. It stores R7, R5 and R3 into XDATA 0x0A4C-0x0A4E, calls 0x2DE3,
   and if 0x0A4D holds 0xFF sets R7 to 0x78; otherwise it takes upper internal RAM 0x85, or 0x9D
   when 0x85 is zero, multiplies it by six into 0x0A4F, with 6 as the fallback. It then calls
   0x2BC1, clears R7, calls 0x3ACC -- the setter that zeroes internal 0x9F from its R7 argument --
   clears direct bit 0x61 and sets direct bit 0x60, and then runs the five-item helper sequence from
   0x2EE9 -- `0x3BD0`, `0x3B8A`, `0x3B20`, `0x3B70`, `A=0x1E` -- which 0x2F1D runs at 0x2F33 as six
   items, `0x3B1D` leading and standing where `0x3B20` is here, so the two share a template rather
   than an identical sequence. It diverges after `A=0x1E`: this one calls 0x3B3C and 0x3BAE, pushes
   DPH and DPL, reads a code-table byte with `movc`, ORs it into a saved-and-restored DPTR and
   writes it back, then tail-jumps to 0x3A0D at 0x2F1A. The multiply by six of a small internal
   counter is the one arithmetic the bytes state outright; 0x0A4D holding 0xFF reads as a not-set
   sentinel because it takes a wholly different path. What the countdown counts is not established.
   None of 0x0A4C, 0x0A4D, 0x0A4F, nor internal 0x85, 0x9D, 0x60, 0x61 has a row in
   ec/annotations/registers.yaml.
   type: state
   evidence: ec/decompiled/common/2E9C.asm; ec/decompiled/common/2E9C.c
   basis: hand-decoded
   name_basis: code-shape */

void store_0a4c_triplet_then_countdown_and_dispatch
               (undefined1 param_1,char param_2,undefined1 param_3)

{
  char *pcVar1;
  byte bVar2;
  char cVar3;
  byte bVar4;
  byte *pbVar5;
  short sVar6;
  
  DAT_EXTMEM_0a4c = param_3;
  DAT_EXTMEM_0a4d = param_2;
  DAT_EXTMEM_0a4e = param_1;
  mask_1106_then_clear_18_34();
  if (DAT_EXTMEM_0a4d == -1) {
    cVar3 = 'x';
  }
  else {
    pcVar1 = &DAT_INTMEM_85;
    if ((DAT_INTMEM_85 == '\0') && (pcVar1 = &DAT_INTMEM_9d, DAT_INTMEM_9d == '\0')) {
      DAT_EXTMEM_0a4f = '\x06';
      cVar3 = DAT_EXTMEM_0a4f;
    }
    else {
      DAT_EXTMEM_0a4f = *pcVar1 * '\x06';
      cVar3 = DAT_EXTMEM_0a4f;
    }
  }
  clamp_iram_80_up_to_r7(cVar3);
  store_r7_to_upper_internal_ram_byte_3acc(0);
  _c_1 = 0;
  _c_0 = 1;
  read_xdata_at_dptr_into_r7(0xa4c);
  FUN_CODE_3bd0();
  FUN_CODE_3b8a(0xa4d);
  pbVar5 = (byte *)0xa4c;
  read_xdata_at_dptr_into_r7();
  dph_from_a_dpl_from_code_3b70();
  FUN_CODE_3b3c(0x1e);
  load_dptr_high_from_a_low_from_code_table();
  bVar2 = *pbVar5;
  sVar6 = 0xa4c;
  bVar4 = dptr_3a00_plus_13x_3b51(DAT_EXTMEM_0a4c);
  *pbVar5 = bVar2 | *(byte *)(sVar6 + (ushort)bVar4);
  FUN_CODE_3a0d();
  return;
}


