// bank0 @ 2F1D   store_0a4f_triplet_then_retry_loop   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* 104 bytes, the third-largest row, and it opens the way 0x2E9C does: it writes R7, R5 and R3 into
   XDATA 0x0A4F-0x0A51, clears internal byte 0x95, calls 0x2DE3, clears direct bits 0x61 and 0x60,
   and then runs a six-item helper sequence at 0x2F33 -- `0x3B1D`, `0x3BD0`, `0x3B8A`, `0x3B1D`,
   `0x3B70`, `A=0x1E` -- against the five 0x2E9C runs at 0x2EE9, `0x3BD0`, `0x3B8A`, `0x3B20`,
   `0x3B70`, `A=0x1E`: `0x3B1D` leads here and stands where `0x3B20` is there, so the two share a
   template and differ in the leading item and in the fourth -- before entering a retry loop at
   0x2F4B. It diverges where 0x2E9C diverges: this one *writes* the 0x1E through DPTR and calls
   0x3609, where 0x2E9C calls 0x3B3C and 0x3BAE and ORs in a code-table byte. When a call to 0x3609
   leaves R7 zero it stores that zero to 0x0A52, and the loop at 0x2F52 then loads 0x0A51 into R6,
   increments DPTR to 0x0A52, reads that byte back, clears carry and does `subb A, R6` -- a compare
   of 0x0A52 against 0x0A51. On a borrow it arms a second countdown to 0x17 and tries again,
   incrementing 0x0A52 on each pass, so that byte counts retries. It finishes with four more calls
   and returns at 0x2F84. The two large rows are therefore one template written twice, differing in
   the leading helper call, in `0x3B20` against `0x3B1D` in the fourth, and in everything after
   `A=0x1E` -- and *not* one routine seen twice, which is what the 45 bytes at 0x2EED-0x2F19 and at
   0x2F33 settling: they are not byte-identical. None of 0x0A4F, 0x0A50, 0x0A51, 0x0A52, nor
   internal 0x95, 0x60, 0x61 has a row in ec/annotations/registers.yaml.
   type: state
   evidence: ec/decompiled/common/2F1D.asm; ec/decompiled/common/2F1D.c
   basis: hand-decoded
   name_basis: code-shape */

void store_0a4f_triplet_then_retry_loop(byte param_1,undefined1 param_2,char param_3)

{
  char cVar1;
  undefined1 *puVar2;
  
  DAT_INTMEM_95 = 0;
  DAT_EXTMEM_0a4f = param_3;
  DAT_EXTMEM_0a50 = param_2;
  DAT_EXTMEM_0a51 = param_1;
  mask_1106_then_clear_18_34();
  _c_1 = 0;
  _c_0 = 0;
  FUN_CODE_3b1d();
  FUN_CODE_3bd0();
  puVar2 = (undefined1 *)0xa50;
  FUN_CODE_3b8a();
  FUN_CODE_3b1d();
  dph_from_a_dpl_from_code_3b70();
  *puVar2 = 0x1e;
  FUN_CODE_3609();
  if (param_3 == '\0') {
    DAT_EXTMEM_0a52 = 0;
    while( true ) {
      cVar1 = '\0';
      puVar2 = &DAT_EXTMEM_0a52;
      if (DAT_EXTMEM_0a51 <= DAT_EXTMEM_0a52) break;
      FUN_CODE_3b1d(DAT_EXTMEM_0a52 - DAT_EXTMEM_0a51);
      dph_from_a_dpl_from_code_3b70();
      *puVar2 = 0x17;
      FUN_CODE_3609();
      if (cVar1 != '\0') break;
      DAT_EXTMEM_0a52 = DAT_EXTMEM_0a52 + 1;
    }
  }
  mul13_table_lookup_3b22(DAT_EXTMEM_0a4f);
  dph_from_a_dpl_from_code_3b70();
  FUN_CODE_3bbf();
  FUN_CODE_2ac1();
  return;
}


