; bank0 @ 36E5   FUN_CODE_36e5
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 36E5.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

36E5     90 0a 0d   mov      DPTR, #0xa0d
36E8     ed         mov      A, R5
36E9     f0         movx     @DPTR, A
36EA     90 0a 0c   mov      DPTR, #0xa0c
36ED     ef         mov      A, R7
36EE     f0         movx     @DPTR, A
36EF     90 0a 0f   mov      DPTR, #0xa0f
36F2     74 01      mov      A, #0x1
36F4     f0         movx     @DPTR, A
36F5     ef         mov      A, R7
36F6     64 03      xrl      A, #0x3
36F8     70 29      jnz      0x3723
36FA     90 0a 0e   mov      DPTR, #0xa0e
36FD     f0         movx     @DPTR, A
36FE     90 0a 0e   mov      DPTR, #0xa0e
3701     e0         movx     A, @DPTR
3702     fe         mov      R6, A
3703     c3         clr      CY
3704     94 03      subb     A, #0x3
3706     50 50      jnc      0x3758
3708     90 0a 0d   mov      DPTR, #0xa0d
370B     e0         movx     A, @DPTR
370C     ff         mov      R7, A
370D     ee         mov      A, R6
370E     90 3b 1a   mov      DPTR, #0x3b1a
3711     93         movc     A, @A+DPTR
3712     fd         mov      R5, A
3713     12 36 af   lcall    0x36af
3716     ef         mov      A, R7
3717     70 02      jnz      0x371b
3719     80 2f      sjmp     0x374a
371B     90 0a 0e   mov      DPTR, #0xa0e
371E     e0         movx     A, @DPTR
371F     04         inc      A
3720     f0         movx     @DPTR, A
3721     80 db      sjmp     0x36fe
3723     90 0a 0c   mov      DPTR, #0xa0c
3726     e0         movx     A, @DPTR
3727     64 04      xrl      A, #0x4
3729     70 2d      jnz      0x3758
372B     90 0a 0e   mov      DPTR, #0xa0e
372E     f0         movx     @DPTR, A
372F     90 0a 0e   mov      DPTR, #0xa0e
3732     e0         movx     A, @DPTR
3733     fe         mov      R6, A
3734     c3         clr      CY
3735     94 03      subb     A, #0x3
3737     50 1f      jnc      0x3758
3739     90 0a 0d   mov      DPTR, #0xa0d
373C     e0         movx     A, @DPTR
373D     ff         mov      R7, A
373E     ee         mov      A, R6
373F     90 3b 17   mov      DPTR, #0x3b17
3742     93         movc     A, @A+DPTR
3743     fd         mov      R5, A
3744     12 36 af   lcall    0x36af
3747     ef         mov      A, R7
3748     70 06      jnz      0x3750
374A     90 0a 0f   mov      DPTR, #0xa0f
374D     f0         movx     @DPTR, A
374E     80 08      sjmp     0x3758
3750     90 0a 0e   mov      DPTR, #0xa0e
3753     e0         movx     A, @DPTR
3754     04         inc      A
3755     f0         movx     @DPTR, A
3756     80 d7      sjmp     0x372f
3758     90 0a 0f   mov      DPTR, #0xa0f
375B     e0         movx     A, @DPTR
375C     ff         mov      R7, A
375D     22         ret      
