; bank0 @ 3835   store_r7_to_upper_internal_ram_byte_3835   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 3835.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

3835     78 9d -  mov      R0, #0x9d
3837     ef - -   mov      A, R7
3838     f6 - -   mov      @R0, A
3839     22 - -   ret      
