// bank0 @ 3B32   load_dptr_high_from_a_low_from_code_table_3b32   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Ten bytes, and the frame stops mid-routine: copies A into R4, loads A with 1, reads one code byte
   through `movc A,@A+DPTR` into DPL, puts R4 into DPH, and then loads A with 0x17 and stops. The
   first four instructions therefore build DPTR as (A_in << 8) | code[DPTR_in + 1] -- high byte from
   the argument, low byte from a table one entry in -- and the 0x17 is the start of whatever the
   routine does with that address. 0x3BAE is the same four instructions in R6 and ends at the `ret`,
   so the pair reads as the two-byte-constant-to-DPTR idiom and its longer variant. The table's
   address is the caller's DPTR, not a constant here, and what follows 0x3B3A is not in this
   listing.
   type: math
   evidence: ec/decompiled/common/3B32.asm; ec/decompiled/common/3B32.c
   basis: hand-decoded
   name_basis: code-shape */

undefined1
load_dptr_high_from_a_low_from_code_table_3b32(undefined1 param_1,short param_2,char param_3)

{
  *(undefined1 *)CONCAT11(param_1,*(undefined1 *)(param_2 + 1)) = 0x17;
  return *(undefined1 *)
          CONCAT11(':' - (((7U < (byte)(param_3 * '\r')) << 7) >> 7),param_3 * '\r' - 8);
}


