; bank0 @ 3BD0   FUN_CODE_3bd0
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 3BD0.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

3BD0     fc - -   mov      R4, A
3BD1     74 01 -  mov      A, #0x1
3BD3     93 - -   movc     A, @A+DPTR
3BD4     fd - -   mov      R5, A
3BD5     f5 82 -  mov      DPL, A
3BD7     8c 83 -  mov      DPH, R4
3BD9     74 1d -  mov      A, #0x1d
3BDB     f0 - -   movx     @DPTR, A
3BDC     22 - -   ret      
