// bank0 @ 3F9D   store_r7_to_iram_bb_then_set_68_0   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Points R0 at the direct internal byte 0xBB, writes R7 there, sets the direct bit 0x68 and
   returns. So the value arrives in R7 and the call also raises a flag bit. It has 16 callers, one
   per call site, of which 4 are named. Most of them hand it a byte read from XDATA into R7, but not
   all: 0x3CD9 loads the constant 0x20 and tail-jumps here, so the argument is not always an XDATA
   byte.
   type: writer
   evidence: ec/decompiled/common/3F9D.asm; ec/decompiled/common/3F9D.c
   basis: hand-decoded
   name_basis: register-map */

void store_r7_to_iram_bb_then_set_68_0(undefined1 param_1)

{
  DAT_INTMEM_bb = param_1;
  _d_0 = 1;
  return;
}


