; bank0 @ 412E   FUN_CODE_412e
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 412E.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

412E     78 9c -  mov      R0, #0x9c
4130     e6 - -   mov      A, @R0
4131     70 24 -  jnz      0x4157
4133     ff - -   mov      R7, A
4134     12 38 35 lcall    0x3835
4137     90 0a 48 mov      DPTR, #0xa48
413A     e0 - -   movx     A, @DPTR
413B     ff - -   mov      R7, A
413C     60 51 -  jz       0x418f
413E     12 0a 39 lcall    0x0a39
4141     90 0a 49 mov      DPTR, #0xa49
4144     e0 - -   movx     A, @DPTR
4145     ff - -   mov      R7, A
4146     60 47 -  jz       0x418f
4148     12 09 e9 lcall    0x09e9
414B     90 0a 4a mov      DPTR, #0xa4a
414E     e0 - -   movx     A, @DPTR
414F     ff - -   mov      R7, A
4150     60 3d -  jz       0x418f
4152     12 09 e9 lcall    0x09e9
4155     80 38 -  sjmp     0x418f
4157     12 43 4c lcall    0x434c
415A     90 0a 47 mov      DPTR, #0xa47
415D     e0 - -   movx     A, @DPTR
415E     b4 ff 02 cjne     A, #0xff, 0x4163
4161     80 18 -  sjmp     0x417b
4163     90 0a 47 mov      DPTR, #0xa47
4166     e0 - -   movx     A, @DPTR
4167     b4 f2 04 cjne     A, #0xf2, 0x416e
416A     7f 03 -  mov      R7, #0x3
416C     80 13 -  sjmp     0x4181
416E     90 0a 47 mov      DPTR, #0xa47
4171     e0 - -   movx     A, @DPTR
4172     ff - -   mov      R7, A
4173     64 f3 -  xrl      A, #0xf3
4175     60 04 -  jz       0x417b
4177     ef - -   mov      A, R7
4178     b4 ed 04 cjne     A, #0xed, 0x417f
417B     7f 02 -  mov      R7, #0x2
417D     80 02 -  sjmp     0x4181
417F     7f 01 -  mov      R7, #0x1
4181     12 38 35 lcall    0x3835
4184     78 9c -  mov      R0, #0x9c
4186     12 43 76 lcall    0x4376
4189     fd - -   mov      R5, A
418A     7b 01 -  mov      R3, #0x1
418C     12 2e 9c lcall    0x2e9c
418F     90 0a 47 mov      DPTR, #0xa47
4192     e0 - -   movx     A, @DPTR
4193     ff - -   mov      R7, A
4194     12 16 24 lcall    0x1624
4197     22 - -   ret      
