; bank0 @ 57C2   FUN_CODE_57c2
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 57C2.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

57C2     35 36      addc     A, 0x36
57C4     3a         addc     A, R2
57C5     3d         addc     A, R5
57C6     40 43      jc       0x580b
57C8     44 45      orl      A, #0x45
57CA     ff         mov      R7, A
57CB     ff         mov      R7, A
57CC     ff         mov      R7, A
57CD     ff         mov      R7, A
57CE     ff         mov      R7, A
57CF     ff         mov      R7, A
57D0     ff         mov      R7, A
57D1     ff         mov      R7, A
57D2     00         nop      
57D3     30 37 3b   jnb      0x37, 0x5811
57D6     3e         addc     A, R6
57D7     41 44      ajmp     0x5244
