// bank0 @ 5802   FUN_CODE_5802
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


byte * FUN_CODE_5802(byte param_1,byte *param_2,byte param_3,char param_4,char param_5,char param_6,
                    byte param_7,byte param_8)

{
  undefined1 uVar1;
  byte bVar2;
  byte bVar3;
  byte bVar4;
  byte *pbVar5;
  byte bVar6;
  char in_PSW;
  char cVar7;
  
  nop();
  if (_6_2 == '\0') {
    nop();
    bVar2 = param_5 - (in_PSW >> 7);
    bVar6 = param_1 + bVar2;
    bVar2 = param_5 - ((CARRY1(param_1,bVar2) << 7) >> 7);
    cVar7 = CARRY1(bVar6,bVar2) << 7;
    param_3 = (bVar6 + bVar2 | *param_2) & param_3;
    bVar2 = 0;
    if (param_3 == 0) goto LAB_CODE_58ad;
    bVar2 = param_3 ^ param_7;
    DAT_SFR_aa = param_5;
LAB_CODE_584c:
    uVar1 = DAT_SFR_aa;
    uVar1 = DAT_SFR_aa;
    param_3 = DAT_SFR_aa;
    bVar6 = DAT_INTMEM_39 - (cVar7 >> 7);
    bVar3 = bVar2 + bVar6;
    bVar2 = param_4 - ((CARRY1(bVar2,bVar6) << 7) >> 7);
    bVar6 = bVar3 + bVar2;
    bVar2 = param_6 - ((CARRY1(bVar3,bVar2) << 7) >> 7);
    bVar3 = bVar6 + bVar2;
    param_1 = param_1 - ((CARRY1(bVar6,bVar2) << 7) >> 7);
    cVar7 = CARRY1(bVar3,param_1) << 7;
    bVar3 = bVar3 + param_1;
    DAT_INTMEM_45 = DAT_INTMEM_45 | 0x47;
    nop();
    if (_6_2 != '\0') {
      bVar2 = param_7 - (cVar7 >> 7);
      cVar7 = CARRY1(bVar3,bVar2) << 7;
      bVar2 = bVar3 + bVar2;
      if (cVar7 < '\0') goto LAB_CODE_58ad;
      bVar2 = bVar2 | *param_2 | (byte)param_2;
      nop();
      bVar6 = param_5 - (cVar7 >> 7);
      bVar3 = bVar2 + bVar6;
      bVar6 = param_5 - ((CARRY1(bVar2,bVar6) << 7) >> 7);
      cVar7 = CARRY1(bVar3,bVar6) << 7;
      bVar6 = (bVar3 + bVar6 | *param_2) & param_3;
      if (bVar6 == 0) {
        return param_2;
      }
      goto LAB_CODE_587d;
    }
  }
  else {
    bVar6 = param_5 - (in_PSW >> 7);
    bVar2 = param_1 + bVar6;
    bVar6 = param_7 - ((CARRY1(param_1,bVar6) << 7) >> 7);
    cVar7 = CARRY1(bVar2,bVar6) << 7;
    bVar2 = bVar2 + bVar6;
    param_1 = param_8;
    if (cVar7 < '\0') goto LAB_CODE_584c;
    bVar2 = bVar2 | DAT_INTMEM_4f;
    bVar6 = DAT_SFR_ff;
    DAT_SFR_ff = bVar6 & bVar2;
    nop();
    bVar6 = param_5 - (cVar7 >> 7);
    bVar3 = bVar2 + bVar6;
    bVar6 = param_5 - ((CARRY1(bVar2,bVar6) << 7) >> 7);
    cVar7 = CARRY1(bVar3,bVar6) << 7;
    bVar3 = (bVar3 + bVar6 | *param_2) & param_3;
    bVar6 = 0;
    if (bVar3 != 0) {
      bVar3 = bVar3 ^ param_7;
      DAT_SFR_aa = param_5;
      bVar6 = DAT_INTMEM_39 - (cVar7 >> 7);
      bVar4 = bVar3 + bVar6;
      bVar6 = param_4 - ((CARRY1(bVar3,bVar6) << 7) >> 7);
      bVar3 = bVar4 + bVar6;
      bVar6 = param_6 - ((CARRY1(bVar4,bVar6) << 7) >> 7);
      pbVar5 = (byte *)FUN_CODE_5a43(bVar3 + bVar6 + (bVar2 - ((CARRY1(bVar3,bVar6) << 7) >> 7)),
                                     param_2);
      return pbVar5;
    }
LAB_CODE_587d:
    bVar3 = DAT_INTMEM_39 - (cVar7 >> 7);
    bVar4 = (bVar6 ^ param_7) + bVar3;
    bVar6 = param_4 - ((CARRY1(bVar6 ^ param_7,bVar3) << 7) >> 7);
    bVar3 = bVar4 + bVar6;
    bVar6 = param_6 - ((CARRY1(bVar4,bVar6) << 7) >> 7);
    bVar4 = bVar3 + bVar6;
    bVar2 = bVar2 - ((CARRY1(bVar3,bVar6) << 7) >> 7);
    bVar6 = bVar4 + bVar2;
    DAT_INTMEM_45 = DAT_INTMEM_45 | 0x47;
    nop();
    cVar7 = (CARRY1(bVar4,bVar2) << 7) >> 7;
    if (_6_2 == '\0') {
      nop();
      bVar2 = param_5 - cVar7;
      bVar3 = bVar6 + bVar2;
      bVar2 = param_5 - ((CARRY1(bVar6,bVar2) << 7) >> 7);
      bVar4 = (bVar3 + bVar2 | *param_2) & param_3;
      if (bVar4 != 0) {
        DAT_SFR_aa = param_5;
        return (byte *)(bVar4 ^ param_7);
      }
      bVar2 = 0x35 - ((CARRY1(bVar3,bVar2) << 7) >> 7);
      bVar3 = param_7 + bVar2;
      bVar2 = (char)param_2 - ((CARRY1(param_7,bVar2) << 7) >> 7);
      bVar4 = bVar3 + bVar2;
      param_3 = param_3 - ((CARRY1(bVar3,bVar2) << 7) >> 7);
      bVar3 = bVar4 + param_3;
      bVar2 = param_5 - ((CARRY1(bVar4,param_3) << 7) >> 7);
      pbVar5 = (byte *)FUN_CODE_5a43(bVar3 + bVar2 + (bVar6 - ((CARRY1(bVar3,bVar2) << 7) >> 7)));
      return pbVar5;
    }
    bVar2 = param_7 - cVar7;
    cVar7 = CARRY1(bVar6,bVar2) << 7;
    if (cVar7 < '\0') {
      return param_2;
    }
    bVar3 = bVar6 + bVar2 | *param_2 | (byte)param_2;
  }
  nop();
  bVar2 = param_5 - (cVar7 >> 7);
  bVar4 = bVar3 + bVar2;
  bVar6 = param_5 - ((CARRY1(bVar3,bVar2) << 7) >> 7);
  bVar2 = (bVar4 + bVar6 | *param_2) & param_3;
  if (bVar2 == 0) {
    uVar1 = DAT_SFR_aa;
    uVar1 = DAT_SFR_aa;
    bVar2 = DAT_INTMEM_38 - ((CARRY1(bVar4,bVar6) << 7) >> 7);
    bVar6 = bVar2 + DAT_INTMEM_34;
    bVar2 = param_5 - ((CARRY1(bVar2,DAT_INTMEM_34) << 7) >> 7);
    pbVar5 = (byte *)FUN_CODE_5a43(bVar6 + bVar2 + (bVar3 - ((CARRY1(bVar6,bVar2) << 7) >> 7)));
    return pbVar5;
  }
LAB_CODE_58ad:
  return (byte *)(bVar2 ^ param_7);
}


