// bank0 @ 6402   FUN_CODE_6402
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


/* WARNING: Instruction at (CODE,0x608f) overlaps instruction at (CODE,0x608d)
    */
/* WARNING: Removing unreachable block (CODE,0x6090) */

byte FUN_CODE_6402(byte param_1,byte *param_2,char *param_3,byte param_4,char param_5,char param_6,
                  char param_7,byte param_8)

{
  bool bVar1;
  byte bVar2;
  byte bVar3;
  byte bVar4;
  byte bVar5;
  byte bVar6;
  byte *pbVar7;
  byte *pbVar8;
  char cVar9;
  char in_PSW;
  
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  nop();
  bVar4 = DAT_INTMEM_39 - (in_PSW >> 7);
  bVar2 = param_1 + bVar4;
  bVar4 = param_5 - ((CARRY1(param_1,bVar4) << 7) >> 7);
  bVar3 = bVar2 + bVar4;
  bVar4 = param_7 - ((CARRY1(bVar2,bVar4) << 7) >> 7);
  bVar2 = bVar3 + bVar4;
  param_1 = param_1 - ((CARRY1(bVar3,bVar4) << 7) >> 7);
  bVar1 = CARRY1(bVar2,param_1);
  bVar2 = bVar2 + param_1;
  DAT_INTMEM_45 = DAT_INTMEM_45 | 0x47;
  nop();
  while( true ) {
    cVar9 = bVar1 << 7;
    if (_6_2 != '\0') {
      bVar4 = param_6 - (cVar9 >> 7);
      bVar3 = bVar2 + bVar4;
      bVar4 = param_8 - ((CARRY1(bVar2,bVar4) << 7) >> 7);
      bVar2 = bVar3 + bVar4;
      DAT_INTMEM_44 = DAT_INTMEM_44 | bVar2;
      bVar2 = bVar2 | *param_2;
      nop();
      bVar4 = param_6 - ((CARRY1(bVar3,bVar4) << 7) >> 7);
      bVar4 = (bVar2 + bVar4 + (param_6 - ((CARRY1(bVar2,bVar4) << 7) >> 7)) | *param_2) & param_4;
      if (bVar4 != 0) {
        return bVar4 ^ param_8;
      }
      cVar9 = -0x80;
      bVar4 = 0;
      bVar3 = 0;
      if (_6_3 == '\0') goto LAB_CODE_607e;
      while( true ) {
        bVar3 = (char)param_2 - (cVar9 >> 7);
        bVar5 = bVar4 + bVar3;
        bVar4 = param_5 - ((CARRY1(bVar4,bVar3) << 7) >> 7);
        bVar6 = bVar5 + bVar4;
        bVar3 = param_7 - ((CARRY1(bVar5,bVar4) << 7) >> 7);
        cVar9 = CARRY1(bVar6,bVar3) << 7;
        bVar4 = bVar6 + bVar3;
        if (!CARRY1(bVar6,bVar3)) break;
LAB_CODE_608d_2:
        cVar9 = (bVar4 < 0xb4) << 7;
        if (bVar4 == 0xb4) {
          pbVar8 = param_2 + -0x17;
          bVar4 = DAT_INTMEM_38 - (((&BANK2_R6 < param_2) << 7) >> 7);
          pbVar7 = pbVar8 + bVar4;
          param_4 = param_4 - ((CARRY1((byte)pbVar8,bVar4) << 7) >> 7);
          bVar4 = param_6 - ((CARRY1((byte)pbVar7,param_4) << 7) >> 7);
          bVar4 = FUN_CODE_6243(pbVar7 + param_4 +
                                (bVar2 - ((CARRY1((byte)(pbVar7 + param_4),bVar4) << 7) >> 7)) +
                                bVar4);
          return bVar4;
        }
code_c0x6046:
        bVar3 = *param_3 - (cVar9 >> 7);
        cVar9 = CARRY1(bVar4,bVar3) << 7;
        bVar4 = bVar4 + bVar3;
      }
      bVar2 = bVar4 | (byte)param_2;
    }
    nop();
    bVar4 = param_6 - (cVar9 >> 7);
    bVar3 = bVar2 + bVar4;
    bVar4 = param_6 - ((CARRY1(bVar2,bVar4) << 7) >> 7);
    cVar9 = CARRY1(bVar3,bVar4) << 7;
    bVar4 = (bVar3 + bVar4 | *param_2) & param_4;
    if (bVar4 == 0) break;
    bVar2 = bVar4 ^ param_8;
    P2 = param_6;
    bVar1 = bVar2 < 0xb4;
    if (bVar2 == 0xb4) {
      return 0xb4;
    }
  }
  bVar4 = 0;
code_c0x60bf:
  bVar3 = 0x35 - (cVar9 >> 7);
  bVar5 = (bVar4 ^ param_8) + bVar3;
  bVar4 = (char)param_2 - ((CARRY1(bVar4 ^ param_8,bVar3) << 7) >> 7);
  bVar3 = bVar5 + bVar4;
  param_4 = param_4 - ((CARRY1(bVar5,bVar4) << 7) >> 7);
  bVar5 = bVar3 + param_4;
  bVar4 = param_6 - ((CARRY1(bVar3,param_4) << 7) >> 7);
  bVar4 = FUN_CODE_6243(bVar5 + bVar4 + (bVar2 - ((CARRY1(bVar5,bVar4) << 7) >> 7)));
  return bVar4;
LAB_CODE_607e:
  while( true ) {
    bVar2 = bVar3;
    nop();
    bVar4 = param_6 - (cVar9 >> 7);
    bVar4 = (bVar2 + bVar4 + (param_6 - ((CARRY1(bVar2,bVar4) << 7) >> 7)) | *param_2) & param_4;
    if (bVar4 == 0) {
      DAT_INTMEM_56 = DAT_INTMEM_56 ^ param_8 & *param_2;
      _a_7 = _a_7 & 1;
      bVar4 = FUN_CODE_57c2();
      return bVar4;
    }
    bVar4 = bVar4 ^ param_8;
    P2 = param_6;
    cVar9 = (bVar4 < 0xb4) << 7;
    if (bVar4 == 0xb4) goto LAB_CODE_608d_2;
    if (_6_0 != '\0') goto code_c0x6046;
    bVar3 = param_7 - (cVar9 >> 7);
    cVar9 = CARRY1(bVar4,bVar3) << 7;
    bVar4 = bVar4 + bVar3;
    if (cVar9 < '\0') break;
    bVar3 = bVar4 | (byte)param_2;
  }
  goto code_c0x60bf;
}


