; bank0 @ 741C   FUN_CODE_741c
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 741C.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

741C     ff - -   mov      R7, A
741D     ff - -   mov      R7, A
741E     ff - -   mov      R7, A
741F     ff - -   mov      R7, A
7420     ff - -   mov      R7, A
7421     ff - -   mov      R7, A
7422     ff - -   mov      R7, A
7423     ff - -   mov      R7, A
7424     ff - -   mov      R7, A
7425     ff - -   mov      R7, A
7426     ff - -   mov      R7, A
7427     ff - -   mov      R7, A
7428     ff - -   mov      R7, A
7429     ff - -   mov      R7, A
742A     ff - -   mov      R7, A
742B     ff - -   mov      R7, A
742C     ff - -   mov      R7, A
