; bank0 @ 7F02   FUN_CODE_7f02
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 0 at file 0x08000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 7F02.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

7F02     ff - -   mov      R7, A
7F03     ff - -   mov      R7, A
7F04     ff - -   mov      R7, A
7F05     ff - -   mov      R7, A
7F06     ff - -   mov      R7, A
7F07     ff - -   mov      R7, A
7F08     ff - -   mov      R7, A
7F09     ff - -   mov      R7, A
7F0A     ff - -   mov      R7, A
7F0B     ff - -   mov      R7, A
7F0C     ff - -   mov      R7, A
7F0D     ff - -   mov      R7, A
7F0E     ff - -   mov      R7, A
7F0F     ff - -   mov      R7, A
7F10     ff - -   mov      R7, A
7F11     ff - -   mov      R7, A
