; OemQkeyDxe @ 00000A28   scale_argument_to_ticks_and_wait   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemQkeyDxe.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00000A28.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00000A28 40 53 - - - - - - - -         push     RBX
00000A2A 48 83 ec 20 - - - - - -       sub      RSP, 0x20
00000A2E 48 69 d1 99 9e 36 00 - - -    imul     RDX, RCX, 0x369e99
00000A35 48 8b d9 - - - - - - -        mov      RBX, RCX
00000A38 48 b8 db 34 b6 d7 82 de 1b 43 mov      RAX, 0x431bde82d7b634db
00000A42 48 f7 e2 - - - - - - -        mul      RDX
00000A45 48 c1 ea 12 - - - - - -       shr      RDX, 0x12
00000A49 8b ca - - - - - - - -         mov      ECX, EDX
00000A4B e8 78 ff ff ff - - - - -      call     0x000009c8
00000A50 48 8b c3 - - - - - - -        mov      RAX, RBX
00000A53 48 83 c4 20 - - - - - -       add      RSP, 0x20
00000A57 5b - - - - - - - - -          pop      RBX
00000A58 c3 - - - - - - - - -          ret      
