// bank1 @ 8048   store_acc_and_read_0639   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Three instructions: write the accumulator back to the XDATA byte DPTR points at, then load DPTR
   with 0x0639 and read that byte into the accumulator. Inside the body running 0x8018 to the `ret`
   at 0x8189, so this boundary is the call-target byte scan's hypothesis and the function-level role
   here is not determined.
   type: writer
   evidence: ec/decompiled/bank1/8048.asm; ec/decompiled/bank1/8048.c
   basis: hand-decoded
   name_basis: ec-register */

void store_acc_and_read_0639(undefined1 a_from_8047,undefined1 *param_2,char param_3)

{
  *param_2 = a_from_8047;
  if (XDATA_0639 != '\0') {
    XDATA_0639 = XDATA_0639 + -1;
  }
  if ((-1 < XDATA_063A) && (XDATA_063A != '\0')) {
    XDATA_063A = XDATA_063A + -1;
  }
  if (XDATA_0890 != '\0') {
    XDATA_0890 = XDATA_0890 + -1;
  }
  if (XDATA_07F6 != '\0') {
    XDATA_07F6 = XDATA_07F6 + -1;
  }
  if (XDATA_06D6 != '\0') {
    XDATA_06D6 = XDATA_06D6 + -1;
    return;
  }
  XDATA_06D6 = 9;
  if (XDATA_06C2 != '\0') {
    XDATA_06C2 = XDATA_06C2 + -1;
  }
  if (XDATA_06C3 != '\0') {
    XDATA_06C3 = XDATA_06C3 + -1;
  }
  if ((XDATA_0440 != '\0') && (XDATA_06D8 != '\0')) {
    XDATA_06D8 = XDATA_06D8 + -1;
  }
  trampoline_to_c10c();
  if (param_3 == '\0') {
    trampoline_to_c1e7();
    if ((param_3 == '\0') && (XDATA_06D9 != '\0')) {
      XDATA_06D9 = XDATA_06D9 + -1;
    }
  }
  if (XDATA_06DA != '\0') {
    XDATA_06DA = XDATA_06DA + -1;
  }
  if (XDATA_08E4 != '\0') {
    XDATA_08E4 = XDATA_08E4 + -1;
  }
  if (XDATA_055F != '\0') {
    XDATA_055F = XDATA_055F + -1;
  }
  if (XDATA_09CE != '\0') {
    XDATA_09CE = XDATA_09CE + -1;
  }
  if (XDATA_070B != '\0') {
    XDATA_070B = XDATA_070B + -1;
  }
  if (XDATA_0706 != '\0') {
    XDATA_0706 = XDATA_0706 + -1;
    if (XDATA_0706 == '\0') {
      XDATA_0460 = 0;
      XDATA_0468 = 0;
    }
  }
  if (XDATA_06C5 != '\0') {
    XDATA_06C5 = XDATA_06C5 + -1;
  }
  if ((XDATA_0440 != '\0') && (XDATA_085B != '\0')) {
    XDATA_085B = XDATA_085B + -1;
  }
  if (XDATA_0986 != '\0') {
    XDATA_0986 = XDATA_0986 + -1;
  }
  if (XDATA_070D != '\0') {
    XDATA_070D = XDATA_070D + -1;
  }
  if (XDATA_07F3 != '\0') {
    XDATA_07F3 = XDATA_07F3 + -1;
  }
  if (XDATA_0981 != '\0') {
    XDATA_0981 = XDATA_0981 + -1;
  }
  if (XDATA_0982 != '\0') {
    XDATA_0982 = XDATA_0982 + -1;
  }
  if (XDATA_0811 != '\0') {
    XDATA_0811 = XDATA_0811 + -1;
  }
  if (XDATA_0809 != '\0') {
    XDATA_0809 = XDATA_0809 + -1;
  }
  if ((XDATA_0843 != '\0') && (XDATA_0843 = XDATA_0843 + -1, XDATA_0843 == '\0')) {
    XDATA_080C = 1;
  }
  if ((XDATA_0844 != '\0') && (XDATA_0844 = XDATA_0844 + -1, XDATA_0844 == '\0')) {
    XDATA_0621 = 0;
  }
  if ((XDATA_0440 != '\0') && (XDATA_06DB != '\0')) {
    XDATA_06DB = XDATA_06DB + -1;
  }
  if (XDATA_080D != '\0') {
    XDATA_080D = XDATA_080D + -1;
  }
  if (XDATA_08A7 != '\0') {
    XDATA_08A7 = XDATA_08A7 + -1;
  }
  if ((XDATA_08A8 != '\0') && (XDATA_08A8 = XDATA_08A8 + -1, XDATA_08A8 == '\0')) {
    XDATA_0985 = XDATA_0985 & 0xfb;
    XDATA_0723 = XDATA_0723 & 0xef;
  }
  return;
}


