// bank1 @ 8886   read_xdata_pair_to_r1r2   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads two consecutive XDATA bytes at DPTR into R1 for the first and R2 for the second, leaving
   DPTR one past the second byte, and returns the second byte in A. No other address is touched.
   type: reader
   evidence: ec/decompiled/bank1/8886.asm; ec/decompiled/bank1/8886.c
   basis: hand-decoded
   name_basis: code-shape */

undefined1 read_xdata_pair_to_r1r2(short param_1)

{
  return *(undefined1 *)(param_1 + 1);
}


