// bank1 @ 8A6C   clear_06f8_bit3_then_call_abce   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads XDATA 0x06F8, XORs it with 0x08, masks it with 0xF8 and writes it back, which clears bit 3
   of that byte and leaves the other seven bits as they were. The `JB 0xE3` at 0x8A75 then tests
   accumulator bit 3, which the preceding `ANL A,#0xF8` has just cleared, so the branch is never
   taken: 0xABCE is called unconditionally and the `LCALL 0xABD8` at 0x8A7C is unreachable as the
   bytes stand. The decompile tests the pre-mask value in `(bVar1 >> 3 & 1) != 1`, which is why it
   shows both calls.
   type: writer
   evidence: ec/decompiled/bank1/8A6C.asm; ec/decompiled/bank1/8A6C.c
   basis: hand-decoded
   name_basis: code-shape */

void clear_06f8_bit3_then_call_abce(void)

{
  byte bVar1;
  
  bVar1 = DAT_EXTMEM_06f8 ^ 8;
  DAT_EXTMEM_06f8 = bVar1 & 0xf8;
  if ((bVar1 >> 3 & 1) != 1) {
    call_b728_c614_8915();
    return;
  }
  call_95e5_a054_a389();
  return;
}


