; bank1 @ 8AE5   probe_159a_19f0_0983_then_dispatch   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 8AE5.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

8AE5     12 15 9a lcall    0x159a
8AE8     ef - -   mov      A, R7
8AE9     70 46 -  jnz      0x8b31
8AEB     12 19 f0 lcall    0x19f0
8AEE     40 45 -  jc       0x8b35
8AF0     90 09 83 mov      DPTR, #0x983
8AF3     e0 - -   movx     A, @DPTR
8AF4     54 01 -  anl      A, #0x1
8AF6     60 03 -  jz       0x8afb
8AF8     02 8b 8f ljmp     0x8b8f
8AFB     12 19 90 lcall    0x1990
8AFE     ef - -   mov      A, R7
8AFF     70 0b -  jnz      0x8b0c
