; bank1 @ 8F54   write_047f_and_arm_06d2_fa   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 8F54.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

8F54     90 06 d2 mov      DPTR, #0x6d2
8F57     e0 - -   movx     A, @DPTR
8F58     70 10 -  jnz      0x8f6a
8F5A     ec - -   mov      A, R4
8F5B     90 04 7f mov      DPTR, #0x47f
8F5E     f0 - -   movx     @DPTR, A
8F5F     7d 0a -  mov      R5, #0xa
8F61     12 88 f0 lcall    0x88f0
8F64     74 fa -  mov      A, #0xfa
8F66     90 06 d2 mov      DPTR, #0x6d2
8F69     f0 - -   movx     @DPTR, A
8F6A     22 - -   ret      
