// bank1 @ 9182   add_two_xdata_bytes_to_r1r2_and_halve   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads two consecutive XDATA bytes at DPTR and DPTR+1 into R3 and R4, adds them to the 16-bit
   value held in R1 (low) and R2 (high) with carry, then shifts that sum right by one bit through
   the carry and leaves the result in R1:R2. DPTR is left pointing one byte past the second byte
   read.
   type: math
   evidence: ec/decompiled/bank1/9182.asm; ec/decompiled/bank1/9182.c
   basis: hand-decoded */

byte add_two_xdata_bytes_to_r1r2_and_halve(byte *param_1,byte param_2,char param_3)

{
  return param_2 + *param_1 >> 1 |
         (param_3 + (param_1[1] - ((CARRY1(param_2,*param_1) << 7) >> 7))) * -0x80;
}


