// bank1 @ 966C   step_06fd_06fe_06ff_counters_via_1a32   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Calls 0x9733, then unless XDATA 0x06C2 is zero and 0x0440 is nonzero it clears 0x06FD, 0x06FE and
   0x06FF and returns. Otherwise it looks at whichever of those three bytes is nonzero, tests its
   bits in turn to pick a constant (bits 0/4/5/6/7 for 0x06FD, all eight for 0x06FE and for 0x06FF),
   writes that byte back unchanged, and calls 0x1A32 twice with R3 = 0 then R3 = 2 and R1 holding
   the constant. No bit-clearing instruction appears anywhere in the listing, although the
   decompiler's C renders the three writes that way.
   type: state
   evidence: ec/decompiled/bank1/966C.asm; ec/decompiled/bank1/966C.c
   basis: hand-decoded */

void step_06fd_06fe_06ff_counters_via_1a32(void)

{
  undefined1 uVar1;
  
  sync_085a_from_iram28_and_call_896a();
  if ((DAT_EXTMEM_06c2 == '\0') && (XDATA_0440 != '\0')) {
    if (DAT_EXTMEM_06fd == 0) {
      if (DAT_EXTMEM_06fe == 0) {
        if (DAT_EXTMEM_06ff == 0) {
          return;
        }
        uVar1 = 0xd0;
        if ((DAT_EXTMEM_06ff & 1) == 0) {
          uVar1 = 0xcd;
          if ((DAT_EXTMEM_06ff & 2) == 0) {
            uVar1 = 0x95;
            if ((DAT_EXTMEM_06ff & 4) == 0) {
              uVar1 = 0xbb;
              if ((DAT_EXTMEM_06ff & 8) == 0) {
                uVar1 = 0xb4;
                if ((DAT_EXTMEM_06ff & 0x10) == 0) {
                  uVar1 = 0xa1;
                  if ((DAT_EXTMEM_06ff & 0x20) == 0) {
                    uVar1 = 0xb2;
                    if ((DAT_EXTMEM_06ff & 0x40) == 0) {
                      uVar1 = 0xa3;
                      if ((DAT_EXTMEM_06ff & 0x80) == 0) {
                        return;
                      }
                      DAT_EXTMEM_06ff = DAT_EXTMEM_06ff & 0x7f;
                    }
                    else {
                      DAT_EXTMEM_06ff = DAT_EXTMEM_06ff & 0xbf;
                    }
                  }
                  else {
                    DAT_EXTMEM_06ff = DAT_EXTMEM_06ff & 0xdf;
                  }
                }
                else {
                  DAT_EXTMEM_06ff = DAT_EXTMEM_06ff & 0xef;
                }
              }
              else {
                DAT_EXTMEM_06ff = DAT_EXTMEM_06ff & 0xf7;
              }
            }
            else {
              DAT_EXTMEM_06ff = DAT_EXTMEM_06ff & 0xfb;
            }
          }
          else {
            DAT_EXTMEM_06ff = DAT_EXTMEM_06ff & 0xfd;
          }
        }
        else {
          DAT_EXTMEM_06ff = DAT_EXTMEM_06ff & 0xfe;
        }
      }
      else {
        uVar1 = 200;
        if ((DAT_EXTMEM_06fe & 1) == 0) {
          uVar1 = 0xba;
          if ((DAT_EXTMEM_06fe & 2) == 0) {
            uVar1 = 0x98;
            if ((DAT_EXTMEM_06fe & 4) == 0) {
              uVar1 = 0x90;
              if ((DAT_EXTMEM_06fe & 8) == 0) {
                uVar1 = 0xa0;
                if ((DAT_EXTMEM_06fe & 0x10) == 0) {
                  uVar1 = 0xa8;
                  if ((DAT_EXTMEM_06fe & 0x20) == 0) {
                    uVar1 = 0xfa;
                    if ((DAT_EXTMEM_06fe & 0x40) == 0) {
                      uVar1 = 0xfd;
                      if ((DAT_EXTMEM_06fe & 0x80) == 0) {
                        return;
                      }
                      DAT_EXTMEM_06fe = DAT_EXTMEM_06fe & 0x7f;
                    }
                    else {
                      DAT_EXTMEM_06fe = DAT_EXTMEM_06fe & 0xbf;
                    }
                  }
                  else {
                    DAT_EXTMEM_06fe = DAT_EXTMEM_06fe & 0xdf;
                  }
                }
                else {
                  DAT_EXTMEM_06fe = DAT_EXTMEM_06fe & 0xef;
                }
              }
              else {
                DAT_EXTMEM_06fe = DAT_EXTMEM_06fe & 0xf7;
              }
            }
            else {
              DAT_EXTMEM_06fe = DAT_EXTMEM_06fe & 0xfb;
            }
          }
          else {
            DAT_EXTMEM_06fe = DAT_EXTMEM_06fe & 0xfd;
          }
        }
        else {
          DAT_EXTMEM_06fe = DAT_EXTMEM_06fe & 0xfe;
        }
      }
    }
    else {
      uVar1 = 0x5a;
      if ((DAT_EXTMEM_06fd & 1) == 0) {
        uVar1 = 0xb7;
        if ((DAT_EXTMEM_06fd & 0x10) == 0) {
          uVar1 = 0xbf;
          if ((DAT_EXTMEM_06fd & 0x20) == 0) {
            uVar1 = 0xab;
            if ((DAT_EXTMEM_06fd & 0x40) == 0) {
              uVar1 = 0xc0;
              if ((DAT_EXTMEM_06fd & 0x80) == 0) {
                return;
              }
              DAT_EXTMEM_06fd = DAT_EXTMEM_06fd & 0x7f;
            }
            else {
              DAT_EXTMEM_06fd = DAT_EXTMEM_06fd & 0xbf;
            }
          }
          else {
            DAT_EXTMEM_06fd = DAT_EXTMEM_06fd & 0xdf;
          }
        }
        else {
          DAT_EXTMEM_06fd = DAT_EXTMEM_06fd & 0xef;
        }
      }
      else {
        DAT_EXTMEM_06fd = DAT_EXTMEM_06fd & 0xfe;
      }
    }
    load_dptr_8567_tail_jump_1100(0,uVar1);
    load_dptr_8567_tail_jump_1100(uVar1,2);
    return;
  }
  DAT_EXTMEM_06fd = 0;
  DAT_EXTMEM_06fe = 0;
  DAT_EXTMEM_06ff = 0;
  return;
}


