; bank1 @ 98FE   set_0680_to_2   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 98FE.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

98FE     90 06 80 mov      DPTR, #0x680
9901     74 02 -  mov      A, #0x2
9903     f0 - -   movx     @DPTR, A
9904     22 - -   ret      
