// bank1 @ 9A0E   set_161c_80_and_0681_85   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Writes 0x80 to XDATA 0x161C and 0x85 to XDATA 0x0681, then returns.
   type: writer
   evidence: ec/decompiled/bank1/9A0E.asm; ec/decompiled/bank1/9A0E.c
   basis: hand-decoded */

void set_161c_80_and_0681_85(void)

{
  DAT_EXTMEM_161c = 0x80;
  DAT_EXTMEM_0681 = 0x85;
  return;
}


