// bank1 @ 9A2E   set_1c10_1_and_0681_87   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Writes 1 to XDATA 0x1C10 and 0x87 to XDATA 0x0681, then returns.
   type: writer
   evidence: ec/decompiled/bank1/9A2E.asm; ec/decompiled/bank1/9A2E.c
   basis: hand-decoded */

void set_1c10_1_and_0681_87(void)

{
  DAT_EXTMEM_1c10 = 1;
  DAT_EXTMEM_0681 = 0x87;
  return;
}


