; bank1 @ 9BF8   FUN_CODE_9bf8
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 9BF8.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

9BF8     74 ff      mov      A, #0xff
9BFA     90 1c 11   mov      DPTR, #0x1c11
9BFD     f0         movx     @DPTR, A
9BFE     e4         clr      A
9BFF     90 1c 15   mov      DPTR, #0x1c15
9C02     f0         movx     @DPTR, A
9C03     90 1c 16   mov      DPTR, #0x1c16
9C06     f0         movx     @DPTR, A
9C07     90 06 8b   mov      DPTR, #0x68b
9C0A     74 04      mov      A, #0x4
9C0C     f0         movx     @DPTR, A
9C0D     22         ret      
