// bank1 @ 9CD8   halve_be16_after_add_r1   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Entry point with no prologue: DPTR and R1 both arrive from the caller. It adds R1 to the low byte
   of the big-endian 16-bit XDATA value at DPTR, divides that byte by two (rrc with carry clear, so
   the low bit is lost), adds the halved byte to the high byte at DPTR+1 and halves that too,
   writing both bytes back. It returns carry set, having written nothing, if either byte addition
   overflowed; on success it clears carry. The caller at 0x9CE8 sets DPTR to 0x0615 and R1 from
   XDATA 0x1C15.
   type: math
   evidence: ec/decompiled/bank1/9CD8.asm; ec/decompiled/bank1/9CD8.c
   basis: hand-decoded
   name_basis: code-shape */

void halve_be16_after_add_r1(byte *param_1,byte param_2)

{
  byte bVar1;
  byte bVar2;
  
  bVar1 = *param_1;
  if (!CARRY1(bVar1,param_2)) {
    bVar2 = bVar1 + param_2 >> 1 | CARRY1(bVar1,param_2) << 7;
    *param_1 = bVar2;
    bVar1 = param_1[1];
    if (!CARRY1(bVar1,bVar2)) {
      param_1[1] = bVar1 + bVar2 >> 1 | CARRY1(bVar1,bVar2) << 7;
    }
  }
  return;
}


