// bank1 @ 9D4C   write_0_to_068b   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Writes the constant 0x00 to XDATA 0x068B and returns. No value is read and no other byte is
   touched.
   type: writer
   evidence: ec/decompiled/bank1/9D4C.asm; ec/decompiled/bank1/9D4C.c
   basis: hand-decoded */

void write_0_to_068b(void)

{
  DAT_EXTMEM_068b = 0;
  return;
}


