// bank1 @ 9FF0   FUN_CODE_9ff0
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_9ff0(void)

{
  byte bVar1;
  char in_PSW;
  
  if (-1 < (char)DAT_EXTMEM_0724) {
    exit_ret();
    return;
  }
  DAT_EXTMEM_067d = DAT_EXTMEM_067d + -1;
  if (DAT_EXTMEM_067d == '\0') {
    bVar1 = 8 - (in_PSW >> 7);
    if (bVar1 <= XDATA_06C5) {
      exit_ret(XDATA_06C5 - bVar1);
      return;
    }
    if (XDATA_06C2 == '\0') {
      DAT_EXTMEM_0724 = DAT_EXTMEM_0724 & 0x7f;
      if (DAT_EXTMEM_047b < '\0') {
        load_dptr_c2ba_tail_jump_1100();
        return;
      }
      load_dptr_c2b2_tail_jump_1100();
      return;
    }
  }
  return;
}


