; bank1 @ A12D   FUN_CODE_a12d
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is A12D.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

A12D     90 04 40   mov      DPTR, #0x440
A130     e0         movx     A, @DPTR
A131     b4 08 03   cjne     A, #0x8, 0xa137
A134     02 a1 be   ljmp     0xa1be
A137     90 04 5a   mov      DPTR, #0x45a
A13A     e0         movx     A, @DPTR
A13B     54 01      anl      A, #0x1
A13D     60 7f      jz       0xa1be
A13F     12 19 a8   lcall    0x19a8
A142     ef         mov      A, R7
A143     70 05      jnz      0xa14a
A145     12 1a 50   lcall    0x1a50
A148     80 44      sjmp     0xa18e
A14A     90 07 f6   mov      DPTR, #0x7f6
A14D     e0         movx     A, @DPTR
A14E     60 03      jz       0xa153
A150     02 a1 be   ljmp     0xa1be
A153     90 06 c2   mov      DPTR, #0x6c2
A156     e0         movx     A, @DPTR
A157     60 03      jz       0xa15c
A159     02 a1 be   ljmp     0xa1be
A15C     90 06 c5   mov      DPTR, #0x6c5
A15F     e0         movx     A, @DPTR
A160     94 08      subb     A, #0x8
A162     40 03      jc       0xa167
A164     02 a1 be   ljmp     0xa1be
A167     90 09 7a   mov      DPTR, #0x97a
A16A     e0         movx     A, @DPTR
A16B     30 e7 50   jnb      0xe7, 0xa1be
A16E     90 04 5a   mov      DPTR, #0x45a
A171     e0         movx     A, @DPTR
A172     30 e7 49   jnb      0xe7, 0xa1be
A175     90 04 7b   mov      DPTR, #0x47b
A178     e0         movx     A, @DPTR
A179     30 e7 0a   jnb      0xe7, 0xa186
A17C     90 07 20   mov      DPTR, #0x720
A17F     e0         movx     A, @DPTR
A180     54 80      anl      A, #0x80
A182     70 0a      jnz      0xa18e
A184     80 08      sjmp     0xa18e
A186     90 07 20   mov      DPTR, #0x720
A189     e0         movx     A, @DPTR
A18A     54 80      anl      A, #0x80
A18C     70 00      jnz      0xa18e
A18E     90 06 7d   mov      DPTR, #0x67d
A191     74 06      mov      A, #0x6
A193     f0         movx     @DPTR, A
A194     90 07 24   mov      DPTR, #0x724
A197     e0         movx     A, @DPTR
A198     44 80      orl      A, #0x80
A19A     f0         movx     @DPTR, A
A19B     90 09 7a   mov      DPTR, #0x97a
A19E     e0         movx     A, @DPTR
A19F     54 7f      anl      A, #0x7f
A1A1     f0         movx     @DPTR, A
A1A2     90 07 20   mov      DPTR, #0x720
A1A5     e0         movx     A, @DPTR
A1A6     54 7f      anl      A, #0x7f
A1A8     f0         movx     @DPTR, A
A1A9     90 07 41   mov      DPTR, #0x741
A1AC     e0         movx     A, @DPTR
A1AD     54 01      anl      A, #0x1
A1AF     60 07      jz       0xa1b8
A1B1     90 07 f6   mov      DPTR, #0x7f6
A1B4     74 05      mov      A, #0x5
A1B6     f0         movx     @DPTR, A
A1B7     22         ret      
A1B8     90 07 f6   mov      DPTR, #0x7f6
A1BB     74 32      mov      A, #0x32
A1BD     f0         movx     @DPTR, A
