; bank1 @ A567   FUN_CODE_a567
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is A567.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

A567     c0 e0      push     A
A569     c0 06      push     0x06
A56B     ae 05      mov      R6, 0x05
A56D     7d 43      mov      R5, #0x43
A56F     74 00      mov      A, #0x0
A571     90 20 0b   mov      DPTR, #0x200b
A574     f0         movx     @DPTR, A
A575     dd f8      djnz     R5, 0xa56f
A577     de f4      djnz     R6, 0xa56d
A579     d0 06      pop      0x06
A57B     d0 e0      pop      A
A57D     22         ret      
