// bank1 @ AD80   forwarder_to_ad8b   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Two bytes: sjmp 0xAD8B, with nothing executed here. AD80.c is the decompiler following that jump,
   so the tests of XDATA 0x0490, 0x0492, 0x04A0, 0x0524, 0x0494, 0x0518, 0x0546 and 0x0497 that it
   shows belong to 0xAD8B and are reported from the .c, not decoded from these bytes.
   type: forwarder
   evidence: ec/decompiled/bank1/AD80.asm; ec/decompiled/bank1/AD80.c
   basis: hand-decoded
   name_basis: code-shape */

void forwarder_to_ad8b(void)

{
  char cVar1;
  
  cVar1 = ((DAT_EXTMEM_0490 & 7) < 7) << 7;
  if ((DAT_EXTMEM_0490 & 7) != 7) {
    DAT_EXTMEM_0492 = 0;
    return;
  }
  if (DAT_EXTMEM_0492 == 0) {
    if (DAT_EXTMEM_0524 == BANK0_R1) {
      DAT_EXTMEM_0492 = DAT_EXTMEM_0524 & 0x20;
    }
    return;
  }
  if (((DAT_EXTMEM_04a0 >> 5 & 1) != 1) && (DAT_EXTMEM_0494 == '\0')) {
    read_xdata_pair_to_r3r4(0x518);
    read_xdata_pair_to_r1r2(0x546);
    cmp_r3r4_against_r1r2_16bit();
    if (cVar1 < '\0') {
      DAT_EXTMEM_0497 = DAT_EXTMEM_0497 & 0x7f;
      clear_0492_0496_0577_0578_0542();
      return;
    }
  }
  return;
}


