; bank1 @ BDEF   FUN_CODE_bdef
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is BDEF.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

BDEF     90 04 99   mov      DPTR, #0x499
BDF2     e0         movx     A, @DPTR
BDF3     54 c0      anl      A, #0xc0
BDF5     44 21      orl      A, #0x21
BDF7     f0         movx     @DPTR, A
BDF8     90 01 80   mov      DPTR, #0x180
BDFB     ad 82      mov      R5, DPL
BDFD     ae 83      mov      R6, DPH
BDFF     90 05 b9   mov      DPTR, #0x5b9
