; bank1 @ BF3A   guard_then_store_pair_0834   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is BF3A.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

BF3A     90 08 e2 mov      DPTR, #0x8e2
BF3D     e0 - -   movx     A, @DPTR
BF3E     54 80 -  anl      A, #0x80
BF40     60 17 -  jz       0xbf59
BF42     90 04 00 mov      DPTR, #0x400
BF45     ab 82 -  mov      R3, DPL
BF47     ac 83 -  mov      R4, DPH
BF49     ee - -   mov      A, R6
BF4A     fa - -   mov      R2, A
BF4B     ed - -   mov      A, R5
BF4C     f9 - -   mov      R1, A
BF4D     12 88 63 lcall    0x8863
BF50     50 07 -  jnc      0xbf59
BF52     90 04 00 mov      DPTR, #0x400
BF55     ad 82 -  mov      R5, DPL
BF57     ae 83 -  mov      R6, DPH
BF59     90 08 34 mov      DPTR, #0x834
BF5C     12 88 98 lcall    0x8898
BF5F     45 f0 -  orl      A, B
BF61     60 33 -  jz       0xbf96
BF63     ee - -   mov      A, R6
BF64     fa - -   mov      R2, A
BF65     ed - -   mov      A, R5
BF66     f9 - -   mov      R1, A
BF67     90 08 34 mov      DPTR, #0x834
BF6A     12 88 92 lcall    0x8892
BF6D     12 88 63 lcall    0x8863
BF70     20 e0 20 jb       0xe0, 0xbf93
BF73     90 08 36 mov      DPTR, #0x836
BF76     12 88 92 lcall    0x8892
BF79     90 05 22 mov      DPTR, #0x522
BF7C     12 88 86 lcall    0x8886
BF7F     90 04 97 mov      DPTR, #0x497
BF82     e0 - -   movx     A, @DPTR
BF83     30 e0 06 jnb      0xe0, 0xbf8c
BF86     90 05 22 mov      DPTR, #0x522
BF89     12 88 86 lcall    0x8886
BF8C     12 88 63 lcall    0x8863
BF8F     20 e0 01 jb       0xe0, 0xbf93
BF92     22 - -   ret      
BF96     90 05 22 mov      DPTR, #0x522
BF99     12 88 92 lcall    0x8892
BF9C     90 08 36 mov      DPTR, #0x836
BF9F     12 88 9e lcall    0x889e
BFA2     90 08 32 mov      DPTR, #0x832
BFA5     e0 - -   movx     A, @DPTR
BFA6     44 02 -  orl      A, #0x2
BFA8     f0 - -   movx     @DPTR, A
BFA9     ee - -   mov      A, R6
BFAA     fc - -   mov      R4, A
BFAB     ed - -   mov      A, R5
BFAC     fb - -   mov      R3, A
BFAD     90 08 34 mov      DPTR, #0x834
BFB0     12 88 9e lcall    0x889e
BFB3     90 08 32 mov      DPTR, #0x832
BFB6     e0 - -   movx     A, @DPTR
BFB7     44 01 -  orl      A, #0x1
BFB9     f0 - -   movx     @DPTR, A
BFBA     22 - -   ret      
