// bank1 @ C2B0   clear_04f2_04f4_04f8_set_04f6_ffff   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Calls 0xB1B3 and 0xC613, copies bit 0 of XDATA 0x043C into XDATA 0x04FC, then uses the 16-bit
   store at 0x888C to write 0x0000 to 0x04F2/0x04F3, 0x04F4/0x04F5 and 0x04F8/0x04F9, and 0xFFFF to
   0x04F6/0x04F7. R1:R2 holds 0x0000 for the first three stores and 0xFFFF for the last. None of
   these addresses is documented in ec/annotations/registers.yaml.
   type: writer
   evidence: ec/decompiled/bank1/C2B0.asm; ec/decompiled/bank1/C2B0.c
   basis: hand-decoded */

void clear_04f2_04f4_04f8_set_04f6_ffff(void)

{
  dispatch_0490_low3();
  return_immediately();
  DAT_EXTMEM_04fc = DAT_EXTMEM_043c & 1;
  write_r1r2_to_xdata_pair(0x4f2,0,0);
  write_r1r2_to_xdata_pair(0x4f4);
  write_r1r2_to_xdata_pair(0x4f8);
  write_r1r2_to_xdata_pair(0x4f6,0xff,0xff);
  return;
}


