// bank1 @ C2B0   FUN_CODE_c2b0
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


void FUN_CODE_c2b0(void)

{
  FUN_CODE_b1b3();
  FUN_CODE_c613();
  DAT_EXTMEM_04fc = DAT_EXTMEM_043c & 1;
  FUN_CODE_888c(0x4f2,0,0);
  FUN_CODE_888c(0x4f4);
  FUN_CODE_888c(0x4f8);
  FUN_CODE_888c(0x4f6,0xff,0xff);
  return;
}


