; bank1 @ C614   FUN_CODE_c614
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is C614.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

C614     12 19 a8   lcall    0x19a8
C617     ef         mov      A, R7
C618     60 2c      jz       0xc646
C61A     12 19 84   lcall    0x1984
C61D     ef         mov      A, R7
C61E     60 26      jz       0xc646
C620     90 07 55   mov      DPTR, #0x755
C623     e0         movx     A, @DPTR
C624     54 01      anl      A, #0x1
C626     60 02      jz       0xc62a
C628     80 2f      sjmp     0xc659
C62A     90 04 40   mov      DPTR, #0x440
C62D     e0         movx     A, @DPTR
C62E     60 16      jz       0xc646
C630     90 07 0d   mov      DPTR, #0x70d
C633     e0         movx     A, @DPTR
C634     70 10      jnz      0xc646
C636     80 0f      sjmp     0xc647
