// bank1 @ C700   setup_state_and_copy_30_byte_table   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Saves XDATA 0x036D into R4, XDATA 0x03FB into R5 and the value of bit 2 of XDATA 0x03A1 into R6,
   zeroes XDATA 0x082F and, if that bit was set, copies XDATA 0x0399 into 0x082F. It calls 0xC747,
   writes R4, R5 and R6 back to XDATA 0x036D, 0x03FB and 0x03A1 (only bit 2 survives in the last),
   calls 0xD8F9, writes 0x81 to XDATA 0x0497, calls 0xA530 with DPTR=0xC6E2 and R2=0x0A, and
   finishes by calling the far-call stub 0x19DE. What 0xA530 does with those two arguments is not
   decoded in this listing.
   type: init
   evidence: ec/decompiled/bank1/C700.asm; ec/decompiled/bank1/C700.c
   basis: hand-decoded
   name_basis: code-shape */

void setup_state_and_copy_30_byte_table(void)

{
  byte bVar1;
  
  DAT_EXTMEM_082f = 0;
  bVar1 = DAT_EXTMEM_03a1 & 4;
  if (bVar1 != 0) {
    DAT_EXTMEM_082f = DAT_EXTMEM_0399;
  }
  tail_call_89f4_with_r1_0_r2_3_r3_ff();
  DAT_EXTMEM_03a1 = bVar1;
  FUN_CODE_d8f9();
  DAT_EXTMEM_0497 = 0x81;
  code_table_scatter_to_xdata(0xc6e2,10);
  trampoline_to_c174();
  return;
}


