; bank1 @ C80E   dispatch_0394_low3_through_ljmp_table   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is C80E.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

C7F6     02 c8 30 ljmp     0xc830
C7F9     02 c8 61 ljmp     0xc861
C7FC     02 c8 84 ljmp     0xc884
C7FF     02 c8 c7 ljmp     0xc8c7
C802     02 d1 e7 ljmp     0xd1e7
C805     02 d2 19 ljmp     0xd219
C808     02 c8 30 ljmp     0xc830
C80B     02 c8 30 ljmp     0xc830
C80E     90 04 97 mov      DPTR, #0x497
C811     e0 - -   movx     A, @DPTR
C812     30 e0 4b jnb      0xe0, 0xc860
C815     90 04 5f mov      DPTR, #0x45f
C818     e0 - -   movx     A, @DPTR
C819     b4 db 02 cjne     A, #0xdb, 0xc81e
C81C     80 05 -  sjmp     0xc823
C81E     e4 - -   clr      A
C81F     90 03 ff mov      DPTR, #0x3ff
C822     f0 - -   movx     @DPTR, A
C823     90 03 94 mov      DPTR, #0x394
C826     e0 - -   movx     A, @DPTR
C827     54 07 -  anl      A, #0x7
C829     90 c7 f6 mov      DPTR, #0xc7f6
C82C     f8 - -   mov      R0, A
C82D     28 - -   add      A, R0
C82E     28 - -   add      A, R0
C82F     73 - -   jmp      @A+DPTR
