// bank1 @ C8EA   call_d5b4_then_d32c_and_d34b   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* The whole body is a call to 0xD5B4 followed by calls to 0xD32C and 0xD34B, with no XDATA access
   and no branch of its own. None of the three callees is decoded in this listing, so the routine's
   role is not determinable from its own instructions.
   type: unresolved
   evidence: ec/decompiled/bank1/C8EA.asm; ec/decompiled/bank1/C8EA.c
   basis: hand-decoded */

void call_d5b4_then_d32c_and_d34b(void)

{
  FUN_CODE_d5b4();
  copy_0514_to_03c1_and_set_03a1_bit0();
  bump_counter_mirror_to_04a6_04a7();
  return;
}


