// bank1 @ CB80   FUN_CODE_cb80
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_cb80(byte param_1,char param_2)

{
  byte bVar1;
  
  bVar1 = DAT_EXTMEM_031e;
  FUN_CODE_8886(0x343);
  if ((param_2 == '\0') && (((param_1 & 0xe0) == 0 || ((bVar1 & 0xe0) == 0)))) {
    DAT_EXTMEM_03a9 = 0;
    return;
  }
  FUN_CODE_a5e6(0);
  DAT_EXTMEM_03a9 = param_1;
  return;
}


