// bank1 @ D018   dispatch_on_03c3_low3   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads XDATA 0x0514 into R5 and 0x0342 into B, then reads XDATA 0x03C3 and keeps only its low
   three bits in R0. When that field is 3 or more it computes A = 3*field and jumps to 0xD000 + A,
   i.e. into a table with a 3-byte stride starting at 0xD000 (the five reachable addresses are
   0xD009, 0xD00C, 0xD00F, 0xD012 and 0xD015). When the field is 0 to 2 it falls through to code
   past 0xD036 that is not part of this listing, so that path is not decoded here.
   type: dispatch
   evidence: ec/decompiled/bank1/D018.asm; ec/decompiled/bank1/D018.c
   basis: hand-decoded */

void dispatch_on_03c3_low3(void)

{
                    /* WARNING: Could not find normalized switch variable to match jumptable */
  switch(DAT_EXTMEM_03c3 & 7) {
  case 0:
                    /* WARNING: This code block may not be properly labeled as switch case */
    switchD_CODE:d036::default();
    return;
  case 1:
    scale_store_to_0397(0xe);
    return;
  case 2:
                    /* WARNING: This code block may not be properly labeled as switch case */
    set_r1_0c_jump_d068();
    return;
  case 3:
    set_r1_08_jump_d068();
    return;
  case 4:
    set_r1_06_jump_d068();
    return;
  case 5:
    set_r1_04_jump_d068();
    return;
  case 6:
    set_r1_02_jump_d068();
    return;
  case 7:
    set_r1_00_jump_d068();
    return;
  }
  if (DAT_EXTMEM_0514 < 9) {
    store_ff_to_0397(DAT_EXTMEM_0514 - 9,DAT_EXTMEM_0342);
    return;
  }
  DAT_EXTMEM_0397 = DAT_EXTMEM_0342;
  return;
}


