// bank1 @ D0C4   update_0524_0526_4a0_and_0497_flags   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Copies XDATA 0x0524 into 0x0526 and 0x04A0 and clears 0x0525, 0x0527 and 0x04A1, then calls
   0x198A; a zero result in R7 tail-calls 0xD1B8. The remaining path runs a chain of guards (0x8898
   on 0x0834, 0xD1BC, bit 2 of 0x0367, 0x8886 on 0x0382 followed by 0x885B, and a second 0x885B on
   0x0190 reached only when bit 0 of 0x0497 is set with 0x0539 == 1, or bit 0 clear with 0x0403
   below 0x14), and every failure branch reaches 0xD16F, which writes 0x0A to 0x0648. On success it
   returns without writing if 0x0648 is already nonzero, otherwise it sets bit 5 of 0x0497; if
   0x0514 then equals 0x64 it calls 0xCBF3 and, unless bit 5 of 0x0524 is set, writes 0x63 to 0x03C1
   and 0x20 to 0x0524, 0x0526, 0x04A0 and 0x0492. When 0x0514 is not 0x64 it only sets bit 7 of
   0x0497.
   type: state
   evidence: ec/decompiled/bank1/D0C4.asm; ec/decompiled/bank1/D0C4.c
   basis: hand-decoded */

void update_0524_0526_4a0_and_0497_flags(char param_1,char param_2)

{
  bool bVar1;
  char cVar2;
  char in_PSW;
  char cVar3;
  
  DAT_EXTMEM_0526 = DAT_EXTMEM_0524;
  DAT_EXTMEM_04a0 = DAT_EXTMEM_0524;
  DAT_EXTMEM_0525 = 0;
  DAT_EXTMEM_0527 = 0;
  DAT_EXTMEM_04a1 = 0;
  trampoline_to_c1e7();
  if (param_2 == '\0') {
    trampoline_to_d16f();
    return;
  }
  cVar2 = read_xdata_pair_to_b_and_a(0x834);
  if (cVar2 == '\0' && param_1 == '\0') {
    increment_0514_toward_0x64();
    return;
  }
  select_ptr_0491_c080_then_0506();
  if (in_PSW < '\0') {
    DAT_EXTMEM_0648 = 10;
    return;
  }
  if ((DAT_EXTMEM_0367 >> 2 & 1) == 1) {
    DAT_EXTMEM_0648 = 10;
    return;
  }
  read_xdata_pair_to_r1r2(0x382);
  sub_r1r2_from_r3r4(0x90,1);
  if (in_PSW < '\0') {
    DAT_EXTMEM_0648 = 10;
    return;
  }
  if ((DAT_EXTMEM_0497 & 1) == 1) {
    bVar1 = DAT_EXTMEM_0539 == '\0';
    cVar2 = '\x01';
    if (DAT_EXTMEM_0539 != '\x01') goto LAB_CODE_d136;
  }
  else {
    cVar2 = DAT_EXTMEM_0403 - 0x14;
    if (0x13 < DAT_EXTMEM_0403) goto LAB_CODE_d136;
    bVar1 = true;
  }
  cVar3 = bVar1 << 7;
  sub_r1r2_from_r3r4(cVar2,0x90,1);
  if (cVar3 < '\0') {
    DAT_EXTMEM_0648 = 10;
    return;
  }
LAB_CODE_d136:
  if (DAT_EXTMEM_0648 == '\0') {
    if (DAT_EXTMEM_0514 != 'd') {
      DAT_EXTMEM_0497 = DAT_EXTMEM_0497 | 0xa0;
      return;
    }
    DAT_EXTMEM_0497 = DAT_EXTMEM_0497 | 0x20;
    publish_0514_and_0342_product();
    if ((DAT_EXTMEM_0524 >> 5 & 1) == 1) {
      DAT_EXTMEM_0648 = 10;
      return;
    }
    DAT_EXTMEM_03c1 = 99;
    DAT_EXTMEM_0524 = 0x20;
    DAT_EXTMEM_0526 = 0x20;
    DAT_EXTMEM_04a0 = 0x20;
    DAT_EXTMEM_0492 = 0x20;
  }
  return;
}


