// bank1 @ D472   FUN_CODE_d472
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


/* WARNING: Removing unreachable block (CODE,0xd48b) */
/* WARNING: Removing unreachable block (CODE,0xd494) */
/* WARNING: Removing unreachable block (CODE,0xd496) */
/* WARNING: Removing unreachable block (CODE,0xd49a) */

byte FUN_CODE_d472(void)

{
  byte bVar1;
  
  bVar1 = DAT_EXTMEM_0514;
  if ((0x1d < DAT_EXTMEM_0514) &&
     ((DAT_EXTMEM_0308 != DAT_EXTMEM_036d || (bVar1 = DAT_EXTMEM_03fb, DAT_EXTMEM_03fb == 0)))) {
    DAT_EXTMEM_03ab = 0;
    DAT_EXTMEM_0514 = 0;
    FUN_CODE_cbf3();
    bVar1 = DAT_EXTMEM_03a1 | 1;
    DAT_EXTMEM_03a1 = bVar1;
  }
  return bVar1;
}


