// bank1 @ D946   FUN_CODE_d946
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_d946(byte param_1,char param_2,char param_3)

{
  bool bVar1;
  byte bVar2;
  undefined1 uVar3;
  char cVar4;
  byte bVar5;
  undefined2 uStack_1;
  
  trampoline_to_c174();
  decrement_0365_and_0368_if_nonzero();
  countdown_03a8_gated_by_0490_bit1();
  if ((DAT_EXTMEM_0367 & 2) != 0) {
    compute_097e_times_10_write_0386_0387();
  }
  if ((((DAT_EXTMEM_03ff & 1) == 1) || ((DAT_EXTMEM_04fe >> 4 & 1) != 0)) ||
     ((DAT_EXTMEM_0497 & 1) == 0)) {
    return;
  }
  trampoline_bank0_c184();
  if (param_3 != '\0') {
    FUN_CODE_d8f9();
    return;
  }
  FUN_CODE_dacc();
  read_xdata_pair_to_r1r2(0x60e);
  BANK0_R2 = BANK0_R2 & 3;
  uVar3 = 3;
  if (0x87 < (DAT_EXTMEM_03bd & 6)) {
    uVar3 = 4;
  }
  uStack_1 = CONCAT11(BANK0_R4,(DAT_EXTMEM_03bd & 6) + 0x78);
  add_two_xdata_bytes_to_r1r2_and_halve(uVar3);
  store_r1_r2_to_xdata_at_dptr(uStack_1);
  DAT_EXTMEM_03bd = DAT_EXTMEM_03bd + 2 & 0xcf;
  FUN_CODE_d8bc(0x378);
  bVar1 = CARRY1(DAT_EXTMEM_0392,param_1);
  DAT_EXTMEM_0392 = DAT_EXTMEM_0392 + param_1;
  DAT_EXTMEM_0393 = DAT_EXTMEM_0393 + (param_2 - ((bVar1 << 7) >> 7));
  if ((DAT_EXTMEM_0490 & 1) == 1) {
    cVar4 = '\0';
  }
  else if ((DAT_EXTMEM_0491 & 0xc0) == 0xc0) {
    cVar4 = '\x01';
  }
  else if ((DAT_EXTMEM_0491 & 0xc0) == 0x80) {
    cVar4 = '\x01';
  }
  else {
    cVar4 = '\x01';
  }
  uVar3 = 0x17;
  bVar2 = (DAT_EXTMEM_0383 << 2 | (DAT_EXTMEM_0382 >> 7) << 1 | (DAT_EXTMEM_0382 & 0x7f) >> 6) *
          cVar4;
  bVar5 = bVar2 + 0x75;
  if (0x8a < bVar2) {
    uVar3 = 0x18;
  }
  BANK0_R7 = BANK0_R3;
  BANK0_R6 = BANK0_R2;
  BANK0_R0 = param_1;
  BANK0_R1 = param_2;
  mul_partial_products_r0_r1_r2_r3(bVar5,uVar3);
  write_r1r2_to_xdata_pair(0x380);
  DAT_EXTMEM_03be = DAT_EXTMEM_03be + 1;
  if ((DAT_EXTMEM_03be >> 6 & 1) == 1) {
    DAT_EXTMEM_03be = 0;
    read_xdata_pair_to_r1r2(0x392);
    DAT_EXTMEM_0392 = 0;
    DAT_EXTMEM_0393 = 0;
    BANK0_R3 = BANK0_R7;
    BANK0_R2 = BANK0_R6;
    mul_partial_products_r0_r1_r2_r3
              ((param_1 >> 7) << 1 | (param_1 & 0x7f) >> 6 | bVar5 << 2,
               (bVar5 >> 7) << 1 | (bVar5 & 0x7f) >> 6);
    write_r1r2_to_xdata_pair(900);
    if ((DAT_EXTMEM_03a2 & 1) == 0) {
      DAT_EXTMEM_03a2 = DAT_EXTMEM_03a2 | 1;
      write_r1r2_to_xdata_pair(0x3f2);
    }
    else if ((DAT_EXTMEM_03a2 >> 1 & 1) == 0) {
      DAT_EXTMEM_03a2 = DAT_EXTMEM_03a2 | 2;
      write_r1r2_to_xdata_pair(0x3f4);
    }
    if ((DAT_EXTMEM_0497 & 1) == 1) {
      write_r1r2_to_xdata_pair(0x506);
      write_r1r2_to_xdata_pair(0x508);
      DAT_EXTMEM_0848 = DAT_EXTMEM_0848 | 1;
      return;
    }
    return;
  }
  if ((DAT_EXTMEM_03be >> 3 & 1) != 0) {
    DAT_EXTMEM_03a2 = DAT_EXTMEM_03a2 | 0x80;
  }
  return;
}


