// bank1 @ DB0B   FUN_CODE_db0b
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_db0b(byte param_1,undefined1 param_2)

{
  undefined1 uVar1;
  byte bVar2;
  byte bVar3;
  char in_PSW;
  char cVar4;
  
  DAT_EXTMEM_0975 = 0xa1;
  UD = 0;
  DAT_EXTMEM_0976 = 0xc;
  FUN_CODE_c4d2();
  if (in_PSW < '\0') {
    return;
  }
  DAT_EXTMEM_0976 = 10;
  DAT_EXTMEM_030c = param_1;
  DAT_EXTMEM_030d = param_2;
  FUN_CODE_c4d2();
  if (-1 < in_PSW) {
    bVar2 = param_1 & 7;
    if (bVar2 == 4) {
      DAT_EXTMEM_0491 = DAT_EXTMEM_0491 | 0xc0;
      cVar4 = '\0';
    }
    else {
      cVar4 = (bVar2 < 3) << 7;
      if (bVar2 == 3) {
        DAT_EXTMEM_0491 = DAT_EXTMEM_0491 | 0x80;
      }
      else {
        DAT_EXTMEM_0491 = DAT_EXTMEM_0491 | 0x40;
      }
    }
    DAT_EXTMEM_0976 = 0x42;
    DAT_EXTMEM_030a = param_1;
    DAT_EXTMEM_030b = param_2;
    DAT_EXTMEM_0539 = param_2;
    FUN_CODE_c4d2();
    if (-1 < cVar4) {
      DAT_EXTMEM_0976 = 0x47;
      DAT_EXTMEM_0342 = param_1;
      FUN_CODE_c4d2();
      if (cVar4 < '\0') {
        return;
      }
      DAT_EXTMEM_055f = 0x14;
      DAT_EXTMEM_0399 = param_2;
      DAT_EXTMEM_04ab = param_1;
      DAT_EXTMEM_04ac = param_1;
      DAT_EXTMEM_0514 = param_1;
      DAT_EXTMEM_0516 = param_1;
      FUN_CODE_d6c6();
      FUN_CODE_cbf3();
      FUN_CODE_888c(0x436);
      DAT_EXTMEM_0975 = 0x9b;
      DAT_EXTMEM_0976 = 0;
      FUN_CODE_c4f0();
      uVar1 = BANK0_R5;
      if (cVar4 < '\0') {
        FUN_CODE_e8a4();
      }
      else {
        DAT_EXTMEM_0391 = param_1;
        FUN_CODE_a567(100);
        DAT_EXTMEM_0975 = 0x9b;
        DAT_EXTMEM_0976 = 1;
        BANK0_R5 = uVar1;
        FUN_CODE_c4f0();
        if (cVar4 < '\0') {
          return;
        }
        bVar3 = (byte)((ushort)param_1 * 10);
        bVar2 = (char)((ushort)param_1 * 10 >> 8) - (((0x55 < bVar3) << 7) >> 7);
        cVar4 = (0xf5 < bVar2) << 7;
        FUN_CODE_889e(0x502,bVar3 + 0xaa,bVar2 + 10);
      }
      DAT_EXTMEM_0975 = 0xa1;
      DAT_EXTMEM_0976 = 0x12;
      FUN_CODE_c4d2();
      if (-1 < cVar4) {
        FUN_CODE_889e(0x52a);
        FUN_CODE_889e(FUN_CODE_0402);
        FUN_CODE_889e(0x404);
        DAT_EXTMEM_0976 = 0xe;
        FUN_CODE_c4d2();
        if (-1 < cVar4) {
          FUN_CODE_889e(FUN_CODE_0408);
          FUN_CODE_889e(0x438);
          FUN_CODE_889e(0x506);
          FUN_CODE_889e(0x508);
          FUN_CODE_19e4(7);
          FUN_CODE_daad();
          FUN_CODE_dc52();
          return;
        }
      }
      return;
    }
    return;
  }
  return;
}


