// bank1 @ E0CE   FUN_CODE_e0ce
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_e0ce(undefined1 param_1)

{
  FUN_CODE_8886(0x340);
  FUN_CODE_a5e6(100,0);
  if (DAT_EXTMEM_0342 == BANK0_R1) {
    return;
  }
  FUN_CODE_8886(0x312);
  FUN_CODE_888c(0x340);
  FUN_CODE_a5e6(100,0);
  DAT_EXTMEM_0342 = param_1;
  DAT_EXTMEM_03c0 = param_1;
  return;
}


