// bank1 @ E1D7   counter_tick_03ae_0560   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Increments XDATA 0x03AE and, unless that wraps from 0xFF, stores it back, setting bit 0x02 of
   0x0367 when bit address 0xE2 is set and bit 0x10 of 0x0494 when bit address 0xE4 is set. It then
   adds 2 to 0x0560: without a carry it calls 0xE2C3 and tail-jumps to 0xE27D, and with a carry it
   goes to 0xE1FB where 0x0367 is tested against 0x30 - when those two bits are not both set it adds
   0x10 to 0x0367, calls 0x1ABC, and clears 0x0560, 0x03AE and bit 0x10 of 0x0494 before calling
   0xE2C3 anyway. None of 0x03AE, 0x0367, 0x0494 or 0x0560 has an entry in
   ec/annotations/registers.yaml, so the two counters and two flag bytes are named here only by
   address.
   type: logic
   evidence: ec/decompiled/bank1/E1D7.asm; ec/decompiled/bank1/E1D7.c
   basis: hand-decoded
   name_basis: code-shape */

void counter_tick_03ae_0560(void)

{
  byte bVar1;
  
  bVar1 = DAT_EXTMEM_03ae + 1;
  if (DAT_EXTMEM_03ae != 0xff) {
    if ((bVar1 >> 2 & 1) != 0) {
      DAT_EXTMEM_0367 = DAT_EXTMEM_0367 | 2;
    }
    DAT_EXTMEM_03ae = bVar1;
    if ((bVar1 >> 4 & 1) != 0) {
      DAT_EXTMEM_0494 = DAT_EXTMEM_0494 | 0x10;
    }
  }
  bVar1 = DAT_EXTMEM_0560 + 2;
  if (((0xfd < DAT_EXTMEM_0560) << 7 < '\0') &&
     (bVar1 = DAT_EXTMEM_0560, (DAT_EXTMEM_0367 & 0x30) != 0x30)) {
    DAT_EXTMEM_0367 = DAT_EXTMEM_0367 + 0x10;
    trampoline_bank0_c17c();
    DAT_EXTMEM_0560 = 0;
    DAT_EXTMEM_03ae = 0;
    DAT_EXTMEM_0494 = DAT_EXTMEM_0494 & 0xef;
    bVar1 = DAT_EXTMEM_0560;
  }
  DAT_EXTMEM_0560 = bVar1;
  set_1c00_ff_clear_1c04_1c05();
  reset_1c00_group_and_toggle_03a0();
  return;
}


