// bank1 @ E3B5   FUN_CODE_e3b5
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_e3b5(void)

{
  if ((DAT_EXTMEM_045f == -0x25) && (DAT_EXTMEM_1c00 == 0)) {
    DAT_EXTMEM_1c02 = DAT_EXTMEM_03cd;
    DAT_EXTMEM_03cd = 0;
    if (-1 < DAT_EXTMEM_03a1) {
      DAT_EXTMEM_1c04 = 0;
      DAT_EXTMEM_1c05 = 0;
      DAT_EXTMEM_1c03 = 0xa1;
      DAT_EXTMEM_1c01 = 0x48;
      return;
    }
    DAT_EXTMEM_1c04 = DAT_EXTMEM_03ce;
    DAT_EXTMEM_1c05 = DAT_EXTMEM_03cf;
    DAT_EXTMEM_1c03 = 0xa0;
    DAT_EXTMEM_1c01 = 0x48;
    return;
  }
  if (((DAT_EXTMEM_1c00 >> 1 & 1) != 0) && ((DAT_EXTMEM_1c00 & 0x7c) == 0)) {
    DAT_EXTMEM_03ce = DAT_EXTMEM_1c04;
    DAT_EXTMEM_03cf = DAT_EXTMEM_1c05;
    FUN_CODE_e501();
    return;
  }
  FUN_CODE_e4e9();
  FUN_CODE_e501();
  return;
}


