; bank1 @ E6DC   read_0404_0405_into_r1r2_then_mul_and_clamp   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is E6DC.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

E6DC     12 19 8a lcall    0x198a
E6DF     ef - -   mov      A, R7
E6E0     70 0e -  jnz      0xe6f0
E6E2     90 03 69 mov      DPTR, #0x369
E6E5     e0 - -   movx     A, @DPTR
E6E6     04 - -   inc      A
E6E7     90 03 69 mov      DPTR, #0x369
E6EA     f0 - -   movx     @DPTR, A
E6EB     c3 - -   clr      CY
E6EC     94 3c -  subb     A, #0x3c
E6EE     50 03 -  jnc      0xe6f3
E6F0     02 e7 68 ljmp     0xe768
E6F3     e4 - -   clr      A
E6F4     90 03 69 mov      DPTR, #0x369
E6F7     f0 - -   movx     @DPTR, A
E6F8     90 03 6a mov      DPTR, #0x36a
E6FB     12 88 92 lcall    0x8892
E6FE     79 01 -  mov      R1, #0x1
E700     7a 00 -  mov      R2, #0x0
E702     12 88 54 lcall    0x8854
E705     90 03 6a mov      DPTR, #0x36a
E708     12 88 9e lcall    0x889e
E70B     90 04 04 mov      DPTR, #0x404
E70E     12 88 86 lcall    0x8886
E711     7c 00 -  mov      R4, #0x0
E713     7b 19 -  mov      R3, #0x19
E715     12 a5 e6 lcall    0xa5e6
E718     89 00 -  mov      0x00, R1
E71A     8a 01 -  mov      0x01, R2
E71C     7b 00 -  mov      R3, #0x0
E71E     7a 06 -  mov      R2, #0x6
