; bank1 @ E781   FUN_CODE_e781
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is E781.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

E781     90 03 a8   mov      DPTR, #0x3a8
E784     e0         movx     A, @DPTR
E785     60 29      jz       0xe7b0
E787     90 04 90   mov      DPTR, #0x490
E78A     e0         movx     A, @DPTR
E78B     30 e1 07   jnb      0xe1, 0xe795
E78E     e4         clr      A
E78F     90 03 a8   mov      DPTR, #0x3a8
E792     f0         movx     @DPTR, A
E793     80 1b      sjmp     0xe7b0
E795     90 03 a8   mov      DPTR, #0x3a8
E798     e0         movx     A, @DPTR
E799     c3         clr      CY
E79A     94 01      subb     A, #0x1
E79C     70 0e      jnz      0xe7ac
E79E     90 03 a8   mov      DPTR, #0x3a8
E7A1     f0         movx     @DPTR, A
E7A2     90 03 fe   mov      DPTR, #0x3fe
E7A5     e0         movx     A, @DPTR
E7A6     90 03 6d   mov      DPTR, #0x36d
E7A9     f0         movx     @DPTR, A
E7AA     80 04      sjmp     0xe7b0
E7AC     90 03 a8   mov      DPTR, #0x3a8
E7AF     f0         movx     @DPTR, A
E7B0     22         ret      
