// bank1 @ E954   unresolved_byte_stream_e954   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* The bytes decode to a register-only arithmetic stream - interleaved DEC R1/R2/R3, ADD, XRL and
   SUBB against the same few registers, writes to direct addresses 0x19 and 0x1A, and a final AJMP
   0xEA19 that lands inside the 0xE9CE listing - with no branch target resolving back into this
   range and no coherent entry sequence at 0xE954. 0xE954 is a call target in
   ec/annotations/bank-call-targets.csv, so something reaches it, but these bytes do not decode as a
   routine that could be entered there. The decompiled C's pointer arithmetic over BANK3 registers
   is a reading of this stream, not behaviour the instructions support. Not decoded further.
   type: unresolved
   evidence: ec/decompiled/bank1/E954.asm; ec/decompiled/bank1/E954.c
   basis: hand-decoded */

byte unresolved_byte_stream_e954(byte *param_1,byte *param_2,char param_3,char param_4)

{
  bool bVar1;
  byte bVar2;
  
  *param_2 = *param_2 & 0xf0 |
             (BANK3_R2 * '\x02' ^ BANK3_R2) - ('\x19' - ((CARRY1(BANK3_R2,BANK3_R2) << 7) >> 7)) &
             0xf;
  bVar1 = CARRY1(*(byte *)ZEXT12(param_2),BANK3_R3);
  bVar2 = *(byte *)ZEXT12(param_2) + BANK3_R3 ^ *(byte *)(BANK3_R1 + -1) ^ param_4 - 4U;
  *param_1 = bVar2;
  BANK3_R2 = 0xb8;
  BANK3_R1 = BANK3_R1 + -7;
  *(char *)BANK3_R1 = BANK3_R1;
  param_2[-1] = (bVar2 << 1 | bVar1) - 2 ^ param_3 - 10U;
  return BANK3_R2 >> 1 | BANK3_R2 << 7;
}


