// bank1 @ EF32   xdata_request_dispatch_048c   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads the request byte at XDATA 0x048C and branches on three of its bits. Bit 0 copies two bytes
   out of the address formed by XDATA 0x048B:0x048A into XDATA 0x048D/0x048E (the first byte to
   0x048D); bit 1 writes the single byte 0x048D back to that address; bit 3 stores the high nibble
   of XDATA 0x048D into direct byte 0x00 and dispatches through the three-byte ljmp table at 0xEFE8.
   When 0x048B is 0x30 the two byte accesses use mov A,@R1 / mov @R0,A, which touch internal RAM,
   not the XDATA the .c assumes. With all three bits clear the function jumps to the RET at 0xEFBC;
   otherwise it clears bits 0, 1 and 3 of 0x048C and sets bit 7.
   type: dispatch
   evidence: ec/decompiled/bank1/EF32.asm; ec/decompiled/bank1/EF32.c
   basis: hand-decoded */

void xdata_request_dispatch_048c(void)

{
  if ((DAT_EXTMEM_048c & 1) == 1) {
    if (DAT_EXTMEM_048b == '0') {
      DAT_EXTMEM_048d = *DAT_EXTMEM_048a;
      DAT_EXTMEM_048e = DAT_EXTMEM_048a['\x01'];
    }
    else {
      DAT_EXTMEM_048d = *(byte *)CONCAT11(DAT_EXTMEM_048b,DAT_EXTMEM_048a);
      DAT_EXTMEM_048e = ((byte *)CONCAT11(DAT_EXTMEM_048b,DAT_EXTMEM_048a))[1];
    }
  }
  else if ((DAT_EXTMEM_048c >> 1 & 1) == 1) {
    if (DAT_EXTMEM_048b == '0') {
      *DAT_EXTMEM_048a = DAT_EXTMEM_048d;
    }
    else {
      *(byte *)CONCAT11(DAT_EXTMEM_048b,DAT_EXTMEM_048a) = DAT_EXTMEM_048d;
    }
  }
  else {
    if ((DAT_EXTMEM_048c >> 3 & 1) != 1) {
      ret_stub_no_request_bit();
      return;
    }
    BANK0_R0 = DAT_EXTMEM_048d >> 4;
    dispatch_index_3x_from_byte_00(0xefe8,DAT_EXTMEM_048d);
  }
  DAT_EXTMEM_048c = DAT_EXTMEM_048c & 0xf4 | 0x80;
  return;
}


