// bank1 @ F275   set_06ff_80_else_toggle_0471_80   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads the byte at XDATA 0x0440. If it is non-zero the routine sets bit 7 of XDATA 0x06FF, calls
   0x896A with R7 = 0x35 and returns; if it is zero it instead XORs 0x80 into XDATA 0x0471 and
   returns. Nothing beyond those two stores and the one call is decoded here.
   type: writer
   evidence: ec/decompiled/bank1/F275.asm; ec/decompiled/bank1/F275.c
   basis: hand-decoded */

void set_06ff_80_else_toggle_0471_80(void)

{
  if (DAT_EXTMEM_0440 != '\0') {
    DAT_EXTMEM_06ff = DAT_EXTMEM_06ff | 0x80;
    gate_06e6_0440_then_call_89b5(0x35);
    return;
  }
  DAT_EXTMEM_0471 = DAT_EXTMEM_0471 ^ 0x80;
  return;
}


