; bank1 @ F290   FUN_CODE_f290
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is F290.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

F290     90 06 cd   mov      DPTR, #0x6cd
F293     e0         movx     A, @DPTR
F294     70 16      jnz      0xf2ac
F296     74 02      mov      A, #0x2
F298     f0         movx     @DPTR, A
F299     90 06 ff   mov      DPTR, #0x6ff
F29C     e0         movx     A, @DPTR
F29D     44 20      orl      A, #0x20
F29F     f0         movx     @DPTR, A
F2A0     7f 36      mov      R7, #0x36
F2A2     12 89 6a   lcall    0x896a
F2A5     90 04 71   mov      DPTR, #0x471
F2A8     e0         movx     A, @DPTR
F2A9     54 7f      anl      A, #0x7f
F2AB     f0         movx     @DPTR, A
F2AC     22         ret      
