; bank1 @ F2AD   FUN_CODE_f2ad
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, CODE bank 1 at file 0x10000 + the 0x0000-0x7FFF common area, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is F2AD.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.
; function boundary from a call-target byte scan; that census is an upper bound (ec/annotations/bank-call-audit.md §1),
; so this boundary is a hypothesis and the instructions below may not be the whole function.

F2AD     90 06 cd   mov      DPTR, #0x6cd
F2B0     e0         movx     A, @DPTR
F2B1     70 16      jnz      0xf2c9
F2B3     74 02      mov      A, #0x2
F2B5     f0         movx     @DPTR, A
F2B6     90 06 ff   mov      DPTR, #0x6ff
F2B9     e0         movx     A, @DPTR
F2BA     44 40      orl      A, #0x40
F2BC     f0         movx     @DPTR, A
F2BD     7f 37      mov      R7, #0x37
F2BF     12 89 6a   lcall    0x896a
F2C2     90 04 71   mov      DPTR, #0x471
F2C5     e0         movx     A, @DPTR
F2C6     54 7f      anl      A, #0x7f
F2C8     f0         movx     @DPTR, A
F2C9     22         ret      
