; pd @ 3689   read_0a8b_then_tail_10bc   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 3689.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

3689     90 0a 8b mov      DPTR, #0xa8b
368C     e0 - -   movx     A, @DPTR
368D     90 04 99 mov      DPTR, #0x499
3690     ff - -   mov      R7, A
3691     75 f0 60 mov      B, #0x60
3694     02 10 bc ljmp     0x10bc
