// pd @ 38D3   read_be16_from_dptr   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads two consecutive XDATA bytes: the byte at the incoming DPTR into R4, then after inc DPTR the
   next byte into A, and finally moves R4 into B. Returns the pair in A:B, so the byte at DPTR+1 is
   the high byte. The C returns a single byte and drops the B load.
   type: reader
   evidence: ec/decompiled/pd/38D3.asm; ec/decompiled/pd/38D3.c
   basis: hand-decoded
   name_basis: code-shape */

undefined1 read_be16_from_dptr(short param_1)

{
  return *(undefined1 *)(param_1 + 1);
}


