; pd @ 4BA5   call_f739_set_dptr_07d0_04ba5   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 4BA5.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

4BA5     12 f7 39 lcall    0xf739
4BA8     90 07 d0 mov      DPTR, #0x7d0
4BAB     12 34 7b lcall    0x347b
4BAE     12 10 4d lcall    0x104d
4BB1     00 - -   nop      
4BB2     00 - -   nop      
4BB3     00 - -   nop      
4BB4     18 - -   dec      R0
4BB5     af 03 -  mov      R7, 0x03
4BB7     12 f7 5c lcall    0xf75c
4BBA     bf 01 09 cjne     R7, #0x1, 0x4bc6
4BBD     e4 - -   clr      A
4BBE     7f ff -  mov      R7, #0xff
4BC0     7e 01 -  mov      R6, #0x1
4BC2     fd - -   mov      R5, A
4BC3     fc - -   mov      R4, A
4BC4     80 07 -  sjmp     0x4bcd
4BC6     e4 - -   clr      A
4BC7     7f ff -  mov      R7, #0xff
4BC9     7e 02 -  mov      R6, #0x2
4BCB     fd - -   mov      R5, A
4BCC     fc - -   mov      R4, A
4BCD     90 07 d0 mov      DPTR, #0x7d0
4BD0     e0 - -   movx     A, @DPTR
4BD1     fb - -   mov      R3, A
4BD2     12 35 1a lcall    0x351a
4BD5     12 34 97 lcall    0x3497
