// pd @ 5950   index_stride_77_r7   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Stride 0x77 helper reached from site 0xDA9B via 0xDAA3: it gives 0x0870 + low8(R7 * 0x77) so the
   high byte of the product is dropped while the low base addition still carries into the high byte
   type: math
   evidence: ec/annotations/ec-0x07d0-sites.md
   basis: hand-decoded */

char index_stride_77_r7(byte param_1)

{
  return '\b' - (((0x8f < param_1) << 7) >> 7);
}


