; pd @ 5CCA   call_f739_set_dptr_085e_05cca   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 5CCA.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

5CCA     12 f7 39 lcall    0xf739
5CCD     90 08 5e mov      DPTR, #0x85e
5CD0     e0 - -   movx     A, @DPTR
5CD1     75 f0 17 mov      B, #0x17
5CD4     a4 - -   mul      AB
5CD5     24 1f -  add      A, #0x1f
5CD7     f5 82 -  mov      DPL, A
5CD9     e4 - -   clr      A
5CDA     34 0a -  addc     A, #0xa
5CDC     f5 83 -  mov      DPH, A
5CDE     12 10 41 lcall    0x1041
5CE1     7f 00 -  mov      R7, #0x0
5CE3     22 - -   ret      
