// pd @ 6673   FUN_CODE_6673
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


void FUN_CODE_6673(char param_1)

{
  byte bVar1;
  byte bVar2;
  byte bVar3;
  undefined1 uVar4;
  byte bVar5;
  undefined1 uVar6;
  char cVar7;
  byte bVar8;
  undefined1 *puVar9;
  byte *pbVar10;
  char *pcVar11;
  
  puVar9 = &DAT_EXTMEM_07f3;
  DAT_EXTMEM_07d2 = param_1;
  zero_5_xdata_bytes();
  uVar6 = store_a_to_5_xdata_bytes();
  *puVar9 = uVar6;
  uVar4 = 0x20;
  FUN_CODE_39e6(uVar6,0x20);
  fill_bytes_by_ptr_kind();
  setup_3byte_store_r3r2r1_at_0807();
  write_r7_and_r3r2r1_to_0803(0xfb,7);
  cVar7 = store_a_and_copy_07f4_masked_to_07f5(uVar4,0x7fa);
  if (cVar7 != '\0') goto LAB_CODE_66a0;
  do {
    store_3byte_r3r2r1_at_0803(0,8,1,DAT_EXTMEM_07d2);
    DAT_EXTMEM_0802 = DAT_EXTMEM_0801 & 0x1f;
LAB_CODE_66a0:
    cVar7 = DAT_EXTMEM_07d2;
    read_04a3_then_call_9a90();
    if (((cVar7 != '\0') || (DAT_EXTMEM_07f5 != '\x0f')) || (DAT_EXTMEM_0802 != 0xf)) break;
    setup_3byte_store_r3r2r1_at_0807(DAT_EXTMEM_07fa);
    write_r7_and_r3r2r1_to_0803(0xfb,7);
    cVar7 = store_a_and_copy_07f4_masked_to_07f5(0x7fa);
  } while (cVar7 == '\0');
  if (DAT_EXTMEM_07fa == '\0') {
    return;
  }
  DAT_EXTMEM_07f6 = DAT_EXTMEM_07f3 >> 1 & 7;
  DAT_EXTMEM_07f7 = DAT_EXTMEM_07f3 >> 4 & 7;
  bVar5 = -((char)DAT_EXTMEM_07f3 >> 7);
  cVar7 = '\x06';
  bVar2 = BANK0_R4;
  bVar8 = DAT_EXTMEM_07f4;
  do {
    bVar3 = bVar2 >> 1;
    bVar1 = bVar8 >> 1;
    bVar8 = bVar1 | bVar2 << 7;
    cVar7 = cVar7 + -1;
    bVar2 = bVar3;
  } while (cVar7 != '\0');
  DAT_EXTMEM_07f9 = bVar1 & 3;
  DAT_EXTMEM_07f8 = bVar5;
  if (bVar5 == 1) {
    read4xdata_to_r4_r7(0x7d3);
    DAT_EXTMEM_07fe = bVar3 & 1;
    DAT_EXTMEM_07fc = bVar3;
    DAT_EXTMEM_07fd = bVar5;
    DAT_EXTMEM_07ff = bVar5;
  }
  if (DAT_EXTMEM_07fb != '\0') {
    puVar9 = (undefined1 *)0x7d2;
    if (DAT_EXTMEM_07f9 == 2) {
      scale_dptr_from_dptr_byte_5e_f5();
      *puVar9 = 2;
    }
    else {
      scale_dptr_from_dptr_byte_5e_f5();
      *puVar9 = 1;
    }
  }
  if ((DAT_EXTMEM_07f5 == '\r') && (DAT_EXTMEM_07f7 == 0)) {
    uVar4 = read_dptr_byte_then_07d2(0x7f6);
    pbVar10 = (byte *)0x42c;
    add_60a_to_dptr_34f2(uVar4);
    dph_plus_double_a_349b(uVar4);
    add_carry_into_dph();
    *pbVar10 = bVar3;
  }
  else {
    uVar4 = set_dptr_07fb_then_fall_through();
    pcVar11 = (char *)0x42c;
    add_60a_to_dptr_3500(uVar4);
    dph_plus_double_a_349b(uVar4);
    add_r6_to_dpl();
    if (*pcVar11 == BANK0_R5) {
      write_3bytes_to_0a86(0x99,0xa7,0xff);
      write_xdata_then_set_r5_2(0x11);
      store_4bytes_to_0a82();
      return;
    }
    bVar5 = DAT_EXTMEM_07f6;
    uVar4 = set_dptr_07fb_then_fall_through(DAT_EXTMEM_07f6);
    pbVar10 = (byte *)0x42c;
    add_60a_to_dptr_353e(uVar4);
    dph_plus_double_a_349b(uVar4);
    add_r6_to_dpl();
    *pbVar10 = bVar5;
  }
  pcVar11 = &DAT_EXTMEM_07d2;
  cVar7 = DAT_EXTMEM_07d2;
  set_dptr_0424(DAT_EXTMEM_07d2);
  dph_plus_double_a_349b(cVar7);
  if (pcVar11[1] != '\x01' || *pcVar11 != '\0') {
    cVar7 = BANK0_R6;
    store_0803_0805_then_jump_c808(DAT_EXTMEM_07f5,DAT_EXTMEM_07fb);
    if (cVar7 == '\x01') {
      return;
    }
    cVar7 = ((DAT_EXTMEM_07ff < 0x1b) << 7) >> 7;
    if (DAT_EXTMEM_07fe < (byte)-cVar7) {
      pbVar10 = &DAT_EXTMEM_07d2;
      read_xdata_at_dptr_to_r7_3509(DAT_EXTMEM_07fe + cVar7);
      if ((1 < *pbVar10) && (DAT_EXTMEM_07f8 == 1)) {
        set_r2_07_r1_d3_tail_10e8(0x806,1);
        DAT_EXTMEM_0809 = DAT_EXTMEM_07ff;
        copy_0809_to_080a_then_dispatch_0805(DAT_EXTMEM_07f5,0);
        return;
      }
    }
    pbVar10 = &DAT_EXTMEM_07d2;
    index_5e_f4(DAT_EXTMEM_07d2);
    if (((*pbVar10 < 2) << 7 < '\0') || (DAT_EXTMEM_07f8 != 1)) {
      if (DAT_EXTMEM_07f7 != 0) {
        set_args_r1_d3_r2_07_r3_01();
                    /* WARNING: Subroutine does not return */
        store_3byte_r3r2r1(0x806);
      }
      DAT_EXTMEM_0806 = DAT_EXTMEM_07f6;
      clear_0807_0808_dispatch_0805(DAT_EXTMEM_07f5,DAT_EXTMEM_07fb,0,DAT_EXTMEM_07d2);
    }
    else {
      load_b_60(0x400,DAT_EXTMEM_07d2);
      DAT_EXTMEM_080a = write4_inline_args();
      nop();
      nop();
      nop();
      FUN_CODE_1efe(DAT_EXTMEM_07f5);
    }
    return;
  }
  return;
}


