// pd @ 6FD4   set_r5_then_fall_through   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* One instruction: R5 = A. There is no ret, and the next entry 0x6FD5 loads B and DPTR before
   calling 0x10BC, so whether this is a real routine or a fragment the exporter split off is not
   determined here. The C claims a call to add_full_product_to_dptr at 0x0433, which is in the
   0x6FD5 listing and not in these bytes.
   type: unresolved
   evidence: ec/decompiled/pd/6FD4.asm; ec/decompiled/pd/6FD4.c
   basis: hand-decoded */

void set_r5_then_fall_through(undefined1 param_1)

{
                    /* WARNING: Subroutine does not return */
  add_full_product_to_dptr(0x433,0x60,param_1);
}


