; pd @ 7095   dptr_08ea_plus_5e_times_a   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 7095.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

7095     75 f0 5e mov      B, #0x5e
7098     a4 - -   mul      AB
7099     24 ea -  add      A, #0xea
709B     f5 82 -  mov      DPL, A
709D     e4 - -   clr      A
709E     34 08 -  addc     A, #0x8
70A0     f5 83 -  mov      DPH, A
70A2     22 - -   ret      
