; pd @ 718D   FUN_CODE_718d
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 718D.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

718D     f0         movx     @DPTR, A
718E     e4         clr      A
718F     fb         mov      R3, A
7190     fa         mov      R2, A
7191     7d 02      mov      R5, #0x2
7193     22         ret      
