// pd @ 8814   store_3bytes_at_dptr_plus_1   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Increments DPTR and calls 0x10E8 (store_3byte_r3r2r1), which writes R3, R2 and R1 at DPTR and the
   two bytes after it. No address is loaded here, so the store lands wherever the caller left DPTR.
   The listing stops after the call with no ret, and the .c renders it as a non-returning
   store_3byte_r3r2r1(param_1+1) with a pointer argument this listing does not set up.
   type: writer
   evidence: ec/decompiled/pd/8814.asm; ec/decompiled/pd/8814.c
   basis: hand-decoded
   name_basis: code-shape */

void store_3bytes_at_dptr_plus_1(short entry_dptr)

{
                    /* WARNING: Subroutine does not return */
  store_3byte_r3r2r1(entry_dptr + 1);
}


