; pd @ 8EA6   call_7ce0_with_r5_0b   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 8EA6.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

8EA6     7d 0b -  mov      R5, #0xb
8EA8     12 7c e0 lcall    0x7ce0
8EAB     90 07 d2 mov      DPTR, #0x7d2
8EAE     e0 - -   movx     A, @DPTR
8EAF     ff - -   mov      R7, A
8EB0     7b ff -  mov      R3, #0xff
8EB2     22 - -   ret      
