// pd @ 909A   read_bit0_of_08fc_row   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Computes DPTR = 0x08FC + A*0x5E by multiplying A by 0x5E in B:A and adding 0x08FC with carry,
   calls 0x0FAF to read the four bytes there into R4-R7, then masks bit 0 of R7 and clears R6 before
   the ret at 0x90B0. The observable result is R6:R7 holding the low bit of the byte at 0x08FF +
   A*0x5E, with R4 and R5 left holding the two bytes below it. The .c returns a constant 0 and loses
   both the masking and the 0x08FC base.
   type: reader
   evidence: ec/decompiled/pd/909A.asm; ec/decompiled/pd/909A.c
   basis: hand-decoded
   name_basis: code-shape */

undefined1 read_bit0_of_08fc_row(char param_1)

{
  read4xdata_to_r4_r7('\b' - (((3U < (byte)(param_1 * '^')) << 7) >> 7),param_1 * '^' - 4);
  return 0;
}


