; pd @ 9166   FUN_CODE_9166
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 9166.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

9166     90 07 c9   mov      DPTR, #0x7c9
9169     e0         movx     A, @DPTR
916A     fe         mov      R6, A
916B     e4         clr      A
916C     22         ret      
