; pd @ 97B9   read_xdata_byte_at_r4_minus_3_page_01   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 97B9.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

97B9     fc - -   mov      R4, A
97BA     e4 - -   clr      A
97BB     24 01 -  add      A, #0x1
97BD     fd - -   mov      R5, A
97BE     ec - -   mov      A, R4
97BF     34 fd -  addc     A, #0xfd
97C1     8d 82 -  mov      DPL, R5
97C3     f5 83 -  mov      DPH, A
97C5     e0 - -   movx     A, @DPTR
97C6     22 - -   ret      
