// pd @ 98A1   load_dptr_07d0   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* One instruction: DPTR = 0x07D0, the address the read in the next entry (0x98A4) is made from.
   That 0x07D0 is the ITE8850-PD image's own XDATA, not the EC's: ec/annotations/registers.yaml
   records all 254 of its sites for that address in the PD image and none in the EC firmware, so
   this listing is not evidence about the EC byte of the same address.
   type: reader
   evidence: ec/decompiled/pd/98A1.asm; ec/decompiled/pd/98A1.c; ec/annotations/registers.yaml
   basis: hand-decoded */

char load_dptr_07d0(void)

{
  return DAT_EXTMEM_07d0 * '\f';
}


