// pd @ 9936   add_r6r7_to_r1r2_tail_0c58   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Adds the 16-bit pair R6:R7 into R1:R2 -- R1 += R7, then R2 += R6 with the carry -- copies R5 into
   the accumulator and tail-jumps to 0x0C58, which is not decoded in this file pair. Same 16-bit add
   as the entry at 0x98C1 with a different tail target; the C's four arguments and carry-shift
   expression are not in the listing.
   type: math
   evidence: ec/decompiled/pd/9936.asm; ec/decompiled/pd/9936.c
   basis: hand-decoded */

void add_r6r7_to_r1r2_tail_0c58
               (byte param_1,char param_2,undefined1 param_3,char param_4,byte param_5)

{
  write_byte_at_dptr_plus_r1r2_by_tag
            (param_3,param_1 + param_5,param_2 + (param_4 - ((CARRY1(param_1,param_5) << 7) >> 7)));
  return;
}


