; pd @ 9A91   FUN_CODE_9a91
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is 9A91.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

9A91     75 f0 60   mov      B, #0x60
9A94     90 04 a4   mov      DPTR, #0x4a4
9A97     22         ret      
