// pd @ A571   dispatch_on_state_07d0   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Reads XDATA 0x07D0: if the byte is zero it calls 0x98A5, 0x9850 and 0x98C1 and stores 0x98C1's
   return value in XDATA 0x07D1, and if that byte then compares equal to the value 0x98BE returns it
   tail-jumps to 0xA678, which increments 0x07D0 and re-enters this address. If the byte is non-zero
   it tail-jumps to 0xA681 instead, which clears R7 and returns. Otherwise it calls 0x98E0, 0x9885
   and 0x0D38 and tests the A|B result of that 16-bit read. The listing stops at 0xA5B0 mid-sequence
   (0xA5B1..0xA5B2 are not shown), and the longer body the decompiled C renders starts at 0xA5B4,
   which is listed under 0xA5B3. registers.yaml's 0x07D0 row names it from the EC side and records
   that all of its references in this PD image belong to a different program's XDATA, so no EC
   meaning is carried over.
   type: dispatch
   evidence: ec/decompiled/pd/A571.asm; ec/decompiled/pd/A571.c; ec/annotations/registers.yaml
   basis: hand-decoded */

void dispatch_on_state_07d0(byte param_1,byte param_2,char param_3,byte param_4,byte param_5)

{
  bool bVar1;
  byte bVar2;
  char cVar3;
  byte bVar4;
  undefined1 *puVar5;
  short sVar6;
  byte *pbVar7;
  
  if (DAT_EXTMEM_07d0 != '\0') {
    zero_r7_return(DAT_EXTMEM_07d0 + -1);
    return;
  }
  mul_by_0c_return_r6r7(0);
  load_dptr_d9ef_tail_jump_10f1();
  DAT_EXTMEM_07d1 = add_r6r7_to_r1r2_tail_0bc4(3);
  do {
    load_dptr_07d0();
    load_dptr_d9ef_tail_jump_10f1();
    bVar2 = load_dptr_0004();
    puVar5 = &DAT_EXTMEM_07d1;
    if (DAT_EXTMEM_07d1 == bVar2) {
      inc_07d0_reenter_a571();
      return;
    }
    add_5_to_r2r1();
    set_multiplier_2(*puVar5);
    cVar3 = read_two_bytes_at_offset_by_ptr_kind();
    if (cVar3 != '\0' || param_1 != 0) {
      load_dptr_07d0();
      load_dptr_d9ef_tail_jump_10f1();
      bVar1 = CARRY1(param_2,bVar2);
      param_2 = param_2 + bVar2;
      store_a_to_r2(param_3 + (param_5 - ((bVar1 << 7) >> 7)),param_2);
      set_multiplier_2(DAT_EXTMEM_07d1);
      bVar2 = read_two_bytes_at_offset_by_ptr_kind();
      param_5 = param_1;
      load_dptr_d9ef_tail_jump_10f1();
      param_4 = dptr_001d_tail_0d38();
      param_5 = param_1 & param_5;
      DAT_EXTMEM_07d3 = bVar2 & param_4;
      sVar6 = 2000;
      DAT_EXTMEM_07d2 = param_5;
      FUN_CODE_9965(DAT_EXTMEM_07d0);
      store_a_to_r2();
      read_xdata_byte_to_r7(sVar6 + 1);
      param_1 = 0;
      call_0d8f_then_take_r7();
      load_dptr_07d0();
      load_dptr_d9ef_tail_jump_10f1();
      add_r6r7_to_r1r2_tail_0c58(3);
      bVar2 = DAT_EXTMEM_07d2;
      if (DAT_EXTMEM_07d2 == 0) {
        bVar2 = DAT_EXTMEM_07d3;
      }
      if (bVar2 != 0) {
        bVar2 = DAT_EXTMEM_07d0 + 1;
        load_dptr_d9ef_tail_jump_10f1(bVar2);
        dptr_0010_tail_0c58(bVar2);
        dptr_0011_tail_0d8f(DAT_EXTMEM_07d2,DAT_EXTMEM_07d3);
        bVar4 = call_10fd_dptr_0004_tail_0bc4();
        write_byte_at_dptr_plus_r1r2_by_tag(bVar2 * '\x02' | bVar4 & 1,4,bVar2 & 0x7f);
        set_00bd_bit1_clear_ff42_bit7();
        load_dptr_d9ef_tail_jump_10f1();
        write_byte_at_dptr_plus_r1r2_by_tag(5,0x21);
        call_0eeae(0xa2);
        bVar2 = call_10fd_dptr_0004_tail_0bc4();
        write_r7_at_0x0260_plus_0bab_result(bVar2 >> 1);
        write_r7_at_0x0260_plus_0bab_result(DAT_EXTMEM_07d2);
        write_r7_at_0x0260_plus_0bab_result(DAT_EXTMEM_07d3);
        return;
      }
    }
    pbVar7 = &DAT_EXTMEM_07d1;
    inc_r7_carry_to_r6_setup_0005(DAT_EXTMEM_07d1);
    *pbVar7 = param_4;
  } while( true );
}


