; pd @ A571   FUN_CODE_a571
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is A571.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

A571     90 07 d0   mov      DPTR, #0x7d0
A574     e0         movx     A, @DPTR
A575     ff         mov      R7, A
A576     c3         clr      CY
A577     94 01      subb     A, #0x1
A579     40 03      jc       0xa57e
A57B     02 a6 81   ljmp     0xa681
A57E     ef         mov      A, R7
A57F     12 98 a5   lcall    0x98a5
A582     12 98 50   lcall    0x9850
A585     90 00 03   mov      DPTR, #0x3
A588     12 98 c1   lcall    0x98c1
A58B     90 07 d1   mov      DPTR, #0x7d1
A58E     f0         movx     @DPTR, A
A58F     12 98 a1   lcall    0x98a1
A592     12 98 50   lcall    0x9850
A595     12 98 be   lcall    0x98be
A598     ff         mov      R7, A
A599     90 07 d1   mov      DPTR, #0x7d1
A59C     e0         movx     A, @DPTR
A59D     6f         xrl      A, R7
A59E     70 03      jnz      0xa5a3
A5A0     02 a6 78   ljmp     0xa678
A5A3     12 98 e0   lcall    0x98e0
A5A6     e0         movx     A, @DPTR
A5A7     12 98 85   lcall    0x9885
A5AA     12 0d 38   lcall    0x0d38
A5AD     45 f0      orl      A, B
A5AF     70 03      jnz      0xa5b4
