// pd @ AD24   copy_a_to_r0_r1_tail_jump_0f0e   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Copies A into R1 and R0 in turn, clears the carry, and tail-jumps to 0x0F0E rather than
   returning, so 0x0F0E's return is this entry's return. R2 was loaded from A by the single
   instruction listed separately at 0xAD23. 0x0F0E is not decoded here; the .c reports the two moves
   and drops the tail-jump.
   type: forwarder
   evidence: ec/decompiled/pd/AD24.asm; ec/decompiled/pd/AD24.c
   basis: hand-decoded
   name_basis: code-shape */

void copy_a_to_r0_r1_tail_jump_0f0e(undefined1 param_1)

{
  sub_or_cmp_r0_r7(param_1,param_1);
  return;
}


