// pd @ AD8C   read_07d2_into_r7_r5_zero   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Loads DPTR with XDATA 0x07D2, reads that byte into A and R7, then clears A and R5, so R5 is left
   0 whatever the byte held, and returns with A = 0. It is the single-byte form of the two-byte read
   at 0xAD83. The .c drops the read entirely and returns 0.
   type: reader
   evidence: ec/decompiled/pd/AD8C.asm; ec/decompiled/pd/AD8C.c
   basis: hand-decoded
   name_basis: code-shape */

undefined1 read_07d2_into_r7_r5_zero(void)

{
  return 0;
}


