// pd @ B1F2   unresolved_0xB1F2   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* The handed DPTR is now resolved one level further than it was: lcalls the 3-byte loader 0x10C8
   with it, so the access is a read, which register_ref_table.py --callee-depth 2 reaches with the
   chain 0xB1F2 -> 0x10C8 on its row. The name stays unresolved_* because the tool settled the
   pointer, not this routine: walk() stops at the first control-flow instruction, so the mov a,#0x01
   and the ljmp 0x0C46 after the call are in no window at any depth, and the decompile below shows
   that tail calling write_byte_by_tag_r3(1,...). What remains unresolved is what this routine does
   after the load, not what the load did
   type: forwarder
   evidence: ec/annotations/lightbar-bat-flow.md
   basis: hand-decoded
   name_basis: code-shape */

void unresolved_0xB1F2(undefined1 *param_1,undefined1 param_2,char param_3)

{
  read3_xdata_to_r3r1_10c8();
  write_byte_by_tag_r3(1,param_1,param_2,param_3);
  return;
}


