// pd @ B311   FUN_CODE_b311
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


void FUN_CODE_b311(char param_1)

{
  byte bVar1;
  undefined1 uVar2;
  char cVar3;
  char in_PSW;
  byte *pbVar4;
  
  DAT_EXTMEM_07d2 = param_1;
  cVar3 = FUN_CODE_acf4(0x7d1);
  if (cVar3 != '\0') {
    cVar3 = DAT_EXTMEM_07d1;
    FUN_CODE_e4d0(0x11,0x94,param_1 + '\x01');
    if (cVar3 != '\0') {
      return;
    }
    return;
  }
  if (DAT_EXTMEM_07d2 == '\0') {
    cVar3 = FUN_CODE_ad10(0x7d1);
    if (cVar3 == '\0') {
      return;
    }
    if ((*(byte *)(CONCAT11('\b' - (((9U < (byte)(DAT_EXTMEM_07d1 * '^')) << 7) >> 7),
                            DAT_EXTMEM_07d1 * '^' - 10) + 1) >> 1 & 1) == 0) {
      bVar1 = *(byte *)CONCAT11('\b' - (((0x17U < (byte)(DAT_EXTMEM_07d1 * '^')) << 7) >> 7),
                                DAT_EXTMEM_07d1 * '^' - 0x18);
      if ((bVar1 >> 3 & 1) == 0) {
        return;
      }
      if ((bVar1 >> 2 & 1) != 0) {
        return;
      }
    }
    else {
      pbVar4 = (byte *)CONCAT11('\b' - (((8U < (byte)(DAT_EXTMEM_07d1 * '^')) << 7) >> 7),
                                DAT_EXTMEM_07d1 * '^' - 9);
      *pbVar4 = *pbVar4 & 0xfd;
    }
  }
  else {
    uVar2 = 0;
    cVar3 = DAT_EXTMEM_07d1;
    FUN_CODE_becb(0,DAT_EXTMEM_07d2);
    if (cVar3 == '\0') {
      FUN_CODE_acbf(0x7d1);
      write4_inline_args();
      nop();
      nop();
      nop();
      nop();
      return;
    }
    FUN_CODE_ace4(0x7d1);
    FUN_CODE_ada4();
    cVar3 = FUN_CODE_ad09();
    if (cVar3 != '\0') {
      FUN_CODE_acc0(uVar2);
      cVar3 = FUN_CODE_ad1e();
      if (cVar3 == '\0') {
        call_returns_with_dptr_loaded();
        FUN_CODE_acbf(0x7d1);
        write4xdata_from_r4_r7();
        return;
      }
      call_returns_with_dptr_loaded();
      FUN_CODE_acb7(0x7d1);
      FUN_CODE_ad4d();
      FUN_CODE_ad23(100);
      if (in_PSW < '\0') {
        return;
      }
    }
  }
  return;
}


