; pd @ BECB   write_07d6_07d7_07d8_07d9_then_store_07df   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is BECB.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

BECB     90 07 d6 mov      DPTR, #0x7d6
BECE     ed - -   mov      A, R5
BECF     f0 - -   movx     @DPTR, A
BED0     a3 - -   inc      DPTR
BED1     eb - -   mov      A, R3
BED2     f0 - -   movx     @DPTR, A
BED3     e4 - -   clr      A
BED4     a3 - -   inc      DPTR
BED5     f0 - -   movx     @DPTR, A
BED6     a3 - -   inc      DPTR
BED7     f0 - -   movx     @DPTR, A
BED8     ef - -   mov      A, R7
BED9     12 ac d3 lcall    0xacd3
BEDC     e0 - -   movx     A, @DPTR
BEDD     90 07 da mov      DPTR, #0x7da
BEE0     f0 - -   movx     @DPTR, A
BEE1     7b 01 -  mov      R3, #0x1
BEE3     7a 07 -  mov      R2, #0x7
BEE5     79 d9 -  mov      R1, #0xd9
BEE7     90 07 df mov      DPTR, #0x7df
BEEA     12 10 e8 lcall    0x10e8
