// pd @ C1EF   FUN_CODE_c1ef
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


void FUN_CODE_c1ef(undefined1 param_1,undefined1 *param_2)

{
  *param_2 = param_1;
                    /* WARNING: Subroutine does not return */
  FUN_CODE_122f(0xffff);
}


