// pd @ C2FA   write_07d0_then_run_indexed_state_chain   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Stores R7 in XDATA 0x07D0 and immediately uses that byte as an index: DPTR is built as 0x08F8 +
   low8(XDATA[0x07D0] x 0x5E), and when the byte there is zero 0x8A4A is called with R7 holding that
   value. It then calls 0xEE8B on 0x07D0, calls 0xB3ED when the result is 1, and after 0xF739,
   0xAD75, 0xAD4D and 0xAD24 with R2 = 3 and R3 = 0xE8 either writes four bytes at 0x07D0 through
   0x1041 or falls through to a second chain that calls 0xAD3C, 0x0FAF and 0xAD09 and, when bit 1 of
   the fourth byte read is set, calls 0xC398 and then 0xB311 and 0xD72E if 0xB311 returns 1. The
   routine has several exits and no single return value. ec/annotations/registers.yaml records the
   PD image's 0x07D0 as an index or state variable and says it establishes nothing about the EC's
   own 0x07D0.
   type: state
   evidence: ec/decompiled/pd/C2FA.asm; ec/decompiled/pd/C2FA.c; ec/annotations/registers.yaml
   basis: hand-decoded
   name_basis: code-shape */

void write_07d0_then_run_indexed_state_chain(char param_1,byte param_2)

{
  byte bVar1;
  char cVar2;
  
  DAT_EXTMEM_07d0 = param_2;
  if (*(char *)CONCAT11('\b' - (((7 < param_2 * '^') << 7) >> 7),param_2 * '^' - 8) == '\0') {
    FUN_CODE_8a4a(param_2);
  }
  bVar1 = DAT_EXTMEM_07d0;
  FUN_CODE_ee8b();
  cVar2 = (bVar1 == 0) << 7;
  if (bVar1 == 1) {
    bVar1 = DAT_EXTMEM_07d0;
    write_r7_at_0d0d_then_load_0d0b();
  }
  call_returns_with_dptr_loaded();
  dptr_0a3d_plus_17_times_a(DAT_EXTMEM_07d0,BANK0_R4,BANK0_R5,BANK0_R6,BANK0_R7);
  call_0faf_0f00_0dbc_return_0();
  copy_a_to_r0_r1_tail_jump_0f0e(3,0xe8);
  if (cVar2 < '\0') {
    call_returns_with_dptr_loaded();
    dptr_0a3d_plus_17_times_a(DAT_EXTMEM_07d0);
    write4xdata_from_r4_r7();
    bVar1 = BANK0_R3;
    stage_07d6_chain_tail_f351();
  }
  set_dptr_07d0();
  cVar2 = read4xdata_bit0_to_a();
  if (cVar2 == '\0') {
    set_dptr_07d0();
    read4xdata_to_r4_r7();
    cVar2 = zero_extend_a_into_r4_r7(bVar1 & 2);
    if (cVar2 != '\0') {
      set_r7_r5_from_iram_then_read_07d0();
      write_07d2_then_dispatch_on_07d1(param_1);
      if (bVar1 == 1) {
        FUN_CODE_d72e(DAT_EXTMEM_07d0);
      }
    }
  }
  else {
    set_r7_r5_from_iram_then_read_07d0();
    set_07d2_and_return_r7_zero_or_one();
    if (bVar1 == 1) {
      write_07d1_then_call_chain(DAT_EXTMEM_07d0);
      return;
    }
  }
  return;
}


