// pd @ C348   call_f739_set_dptr_07d0_0c348   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Seven-byte unit: calls 0xF739 and loads DPTR with 0x07D0, then falls through to the next
   instruction at 0x0C34F. This is a fragment of a larger routine, with no return instruction of its
   own.
   type: fragment
   evidence: ec/decompiled/pd/C348.asm; ec/decompiled/pd/C348.c
   basis: hand-decoded
   name_basis: code-shape */

void call_f739_set_dptr_07d0_0c348(char param_1)

{
  byte bVar1;
  char cVar2;
  
  call_returns_with_dptr_loaded();
  dptr_0a3d_plus_17_times_a(DAT_EXTMEM_07d0);
  write4xdata_from_r4_r7();
  bVar1 = BANK0_R3;
  stage_07d6_chain_tail_f351();
  set_dptr_07d0();
  cVar2 = read4xdata_bit0_to_a();
  if (cVar2 == '\0') {
    set_dptr_07d0();
    read4xdata_to_r4_r7();
    cVar2 = zero_extend_a_into_r4_r7(bVar1 & 2);
    if (cVar2 != '\0') {
      set_r7_r5_from_iram_then_read_07d0();
      write_07d2_then_dispatch_on_07d1(param_1);
      if (bVar1 == 1) {
        stage_07d1_set_0ffd4_bit5_then_tail_c755(DAT_EXTMEM_07d0);
      }
    }
  }
  else {
    set_r7_r5_from_iram_then_read_07d0();
    set_07d2_and_return_r7_zero_or_one();
    if (bVar1 == 1) {
      write_07d1_then_call_chain(DAT_EXTMEM_07d0);
      return;
    }
  }
  return;
}


