// pd @ C398   set_r7_r5_from_iram_then_read_07d0   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Copies the internal-RAM byte at fixed address 0x03 into R7 (opcode 0xAF, mov R7,direct, which the
   Ghidra listing prints as mov R7,0x03), calls 0xF75C, then copies the internal-RAM byte at fixed
   address 0x07 into R5 (opcode 0xAD). It finishes by reading XDATA 0x07D0 and returning that byte
   in R7, with DPTR left at 0x07D0. The direct addresses are fixed, not indirect through R3, so the
   decompiled C's reading of the first assignment as the constant 3 is a coincidence of the same
   number appearing in the opcode's operand byte.
   type: copy
   evidence: ec/decompiled/pd/C398.asm; ec/decompiled/pd/C398.c
   basis: hand-decoded */

undefined1 set_r7_r5_from_iram_then_read_07d0(void)

{
  read_dptr_byte_via_716c(BANK0_R3);
  return DAT_EXTMEM_07d0;
}


