// pd @ CCB7   store_0a94_0a97_then_add_0a94_times_60   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Stores R5, R2, R3 and R7 into XDATA 0x0A95, 0x0A96, 0x0A97 and 0x0A94, reads four bytes from
   XDATA 0x0A98 into R4:R7 with 0x0FAF, and calls 0x3883, which sets B = 0x60 and DPTR = 0x0400,
   then 0x10BC, which adds A * B to DPTR with A = the byte stored at 0x0A94. The listing ends on
   that call with no ret of its own, so the address left in DPTR is the only result these bytes
   show.
   type: math
   evidence: ec/decompiled/pd/CCB7.asm; ec/decompiled/pd/CCB7.c
   basis: hand-decoded */

void store_0a94_0a97_then_add_0a94_times_60
               (undefined1 param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4)

{
  DAT_EXTMEM_0a94 = param_4;
  DAT_EXTMEM_0a95 = param_3;
  DAT_EXTMEM_0a96 = param_1;
  DAT_EXTMEM_0a97 = param_2;
  read4xdata_to_r4_r7(0xa98,param_4);
  FUN_CODE_3883(param_4);
                    /* WARNING: Subroutine does not return */
  add_full_product_to_dptr();
}


