// pd @ D013   latch_07d4_07d5_and_call_7014_with_63_or_6c   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Latches R7 and R5 into XDATA 0x07D4 and XDATA 0x07D5; on R5 == 1 it calls 0x714F, reads four
   bytes at the saved DPTR into R4:R7, sets bit 1 of the R7 byte, calls 0x7063 with A = R4 and that
   byte, then sets bit 0 of the byte at DPTR and calls 0x7014 with R1 = 0x63, R2 = 0xD6 and R3 =
   0xFF. The other path clears those same two bits and calls 0x7014 with R1 = 0x6C instead, and
   passes A = 9 rather than 8 to 0x718D. Both paths then call 0xF4AB, read XDATA 0x07D4 through
   0x6FAD, and only if that comes back zero read XDATA 0x07D5 into R5 and call 0xBBE7.
   type: writer
   evidence: ec/decompiled/pd/D013.asm; ec/decompiled/pd/D013.c
   basis: hand-decoded
   name_basis: code-shape */

void latch_07d4_07d5_and_call_7014_with_63_or_6c(undefined1 param_1,char param_2,byte param_3)

{
  undefined1 uVar1;
  char cVar2;
  byte *pbVar3;
  
  pbVar3 = (byte *)0x7d4;
  DAT_EXTMEM_07d4 = param_3;
  DAT_EXTMEM_07d5 = param_2;
  if (param_2 == '\x01') {
    dptr_0a2d_plus_17_times_a();
    read4xdata_to_r4_r7();
    call_1041_then_point_dptr_07d4(param_1,param_3 | 2);
    *pbVar3 = *pbVar3 | 1;
    set_dptr_0a86_and_call_10e8(99,0xd6,0xff);
    uVar1 = 8;
  }
  else {
    dptr_0a2d_plus_17_times_a();
    read4xdata_to_r4_r7();
    call_1041_then_point_dptr_07d4(param_1,param_3 & 0xfd);
    *pbVar3 = *pbVar3 & 0xfe;
    set_dptr_0a86_and_call_10e8(0x6c,0xd6,0xff);
    uVar1 = 9;
  }
  store_a_to_dptr_and_zero_r2_r3(uVar1);
  store_4bytes_to_0a82();
  cVar2 = read_dptr_byte_into_r7(0x7d4);
  if (cVar2 == '\0') {
    branch_on_ram_r5_then_set_indirect_bits(DAT_EXTMEM_07d5);
  }
  return;
}


