// pd @ D72E   stage_07d1_set_0ffd4_bit5_then_tail_c755   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* WARNING: Instruction at (CODE,0xd775) overlaps instruction at (CODE,0xd773)
    */
/* Writes R7 to XDATA 0x07D1, then stages a three-byte value through 0xAD58
   (`set_r3_ff_dptr_0a86_call_10e8`) with R2:R1 = 0xF4:0x35, writes 0x0A to the address it leaves,
   and calls 0xF4AB (`store_4bytes_to_0a82`) with R5 = 2. It reads 0x07D1 back through 0xACD1,
   writes four bytes to 0x0A6D with 0x104D, dispatches through 0xA339, and writes four more to
   0x080F. It then sets bit 5 of XDATA 0xFFD4, calls 0xAD67 (`dptr_08fb_plus_5e_times_a`), takes the
   byte at the DPTR that leaves into R5, and tail-jumps to 0xC755
   (`latch_07d2_07d3_then_zero_23_bytes`) with no ret of its own. The five `nop` bytes at 0xD757 and
   0xD768 are padding between the calls, and the `rr A` / `jb` / `acall` run at 0xD76A is the
   export's decode of those bytes rather than a separate entry. **What the record being staged is
   for is not decoded here.**
   type: unresolved
   evidence: ec/decompiled/pd/D72E.asm; ec/decompiled/pd/D72E.c
   basis: hand-decoded
   name_basis: code-shape */

void stage_07d1_set_0ffd4_bit5_then_tail_c755(char param_1,byte param_2,undefined1 param_3)

{
  undefined1 uVar1;
  byte bVar2;
  char cVar3;
  undefined1 *puVar4;
  
  puVar4 = &DAT_EXTMEM_07d1;
  DAT_EXTMEM_07d1 = param_3;
  set_r3_ff_dptr_0a86_call_10e8(0x35,0xf4);
  *puVar4 = 10;
  store_4bytes_to_0a82(0,0,2);
  puVar4 = &DAT_EXTMEM_07d1;
  read_xdata_to_a_r7();
  uVar1 = BANK0_R7;
  write4_inline_args(0xa6d,0,*puVar4);
  nop();
  nop();
  nop();
  nop();
  BANK0_R7 = uVar1;
  stash_args_dispatch_code_table(1);
  bVar2 = write4_inline_args(0x80f);
  nop();
  nop();
  bVar2 = bVar2 >> 1 | bVar2 << 7;
  cVar3 = P1_0;
  if (cVar3 == '\x01') {
    bVar2 = bVar2 | param_2;
  }
  cVar3 = inc_r0_then_reti(bVar2);
  write_080d_then_branch_on_70e7(param_1,'\x01',cVar3);
  DAT_EXTMEM_ffd4 = DAT_EXTMEM_ffd4 | 0x20;
  puVar4 = &DAT_EXTMEM_07d1;
  dptr_08fb_plus_5e_times_a(DAT_EXTMEM_07d1);
  latch_07d2_07d3_then_zero_23_bytes(*puVar4);
  return;
}


