// pd @ D8EE   FUN_CODE_d8ee
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


void FUN_CODE_d8ee(char param_1,char param_2)

{
  char cVar1;
  char cVar2;
  char cVar3;
  
  DAT_EXTMEM_083c = param_2;
  read4xdata_to_r4_r7(0x83d);
  cVar2 = '\0';
  cVar1 = '\0';
  if (param_1 != '\0' || param_2 != '\0') {
    read4xdata_to_r4_r7(0x83d);
    cVar1 = BANK0_R6;
    cVar2 = BANK0_R7;
    FUN_CODE_c0ef(DAT_EXTMEM_083c);
  }
  if (DAT_EXTMEM_083c == BANK0_R7) {
    cVar3 = DAT_EXTMEM_097f;
    read4xdata_to_r4_r7(0x980);
    load_xdata_to_r0_r1_r2_or_r3(0x83d);
    FUN_CODE_0ee6();
    if (((cVar1 != '\0' || cVar2 != '\0') || param_1 != '\0') || cVar3 != '\0') {
      DAT_EXTMEM_097e = 1;
      read4xdata_to_r4_r7(0x841);
      write4xdata_from_r4_r7(0x984);
    }
  }
  return;
}


