// pd @ DF6A   FUN_CODE_df6a
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


void FUN_CODE_df6a(void)

{
  undefined1 uVar1;
  char cVar2;
  undefined1 *puVar3;
  
  DAT_EXTMEM_07cf = 0;
  uVar1 = 1;
  FUN_CODE_128d(0xe3,8,1,0,0,0x5e);
  cVar2 = '\0';
  DAT_EXTMEM_08f8 = 0;
  DAT_EXTMEM_07cf = '\0';
  do {
    puVar3 = &DAT_EXTMEM_07cf;
    FUN_CODE_70f8(cVar2);
    *puVar3 = 2;
    FUN_CODE_f28d();
    FUN_CODE_70d7(1999);
    write4xdata_from_r4_r7();
    cVar2 = FUN_CODE_6faf(uVar1);
    if (cVar2 == '\0') {
      FUN_CODE_e8d4(BANK0_R3);
    }
    cVar2 = DAT_EXTMEM_07cf;
    DAT_EXTMEM_07cf = DAT_EXTMEM_07cf + '\x01';
  } while ((DAT_EXTMEM_07cf == '\0') << 7 < '\0');
  return;
}


