// pd @ E902   FUN_CODE_e902
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


char FUN_CODE_e902(void)

{
  byte bVar1;
  char cVar2;
  
  FUN_CODE_9850();
  FUN_CODE_0c13(1,0x24);
  bVar1 = FUN_CODE_0bc4(0x21);
  if (bVar1 < 6) {
    FUN_CODE_10f1(CONCAT11(-0x26 - (((0xcd < bVar1 * '\x03') << 7) >> 7),bVar1 * '\x03' + 0x32));
    cVar2 = FUN_CODE_1229();
    return cVar2;
  }
  return bVar1 - 6;
}


