// pd @ EC36   set_or_clear_bits_0_5_via_9028   [named]
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.


/* Sets R4=0x07 and branches on R5 being exactly 1. Both arms load R6 with 0x07 and call 0x9028 with
   A=0x1E, then modify the byte at the DPTR that call leaves: the R5==1 arm ORs in bit 0 and then
   bit 5, and every other R5 value ANDs out bit 0 and then bit 5. Each arm returns immediately after
   its two read-modify-writes, with no common tail, and the address behind 0x9028 is not shown in
   this listing. The .c writes through a parameter pointer, which the .asm does not have.
   type: logic
   evidence: ec/decompiled/pd/EC36.asm; ec/decompiled/pd/EC36.c
   basis: hand-decoded */

void set_or_clear_bits_0_5_via_9028(byte *param_1,char param_2)

{
  if (param_2 == '\x01') {
    make_dptr_r6_minus_3_9028(0x1e,BANK0_R7);
    *param_1 = *param_1 | 1;
    *param_1 = *param_1 | 0x20;
    return;
  }
  make_dptr_r6_minus_3_9028(0x1e,BANK0_R7);
  *param_1 = *param_1 & 0xfe;
  *param_1 = *param_1 & 0xdf;
  return;
}


