// pd @ F126   FUN_CODE_f126
// Ghidra 12.1.3 decompile, generated by ec/tools/build_ec_decompile.py -- do not edit.
// Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
// Machine output carrying this repository's symbols. Not the vendor's source.
// function boundary from a call-target byte scan; that census is an upper bound
// (ec/annotations/bank-call-audit.md §1), so this boundary is a hypothesis.


void FUN_CODE_f126(void)

{
  char cVar1;
  
  cVar1 = FUN_CODE_6f96();
  if (cVar1 == '\0') {
    FUN_CODE_7108();
    FUN_CODE_7045();
    FUN_CODE_7108();
    FUN_CODE_7045();
    FUN_CODE_7108();
    FUN_CODE_cc36();
  }
                    /* WARNING: Subroutine does not return */
  FUN_CODE_122f(10);
}


