; pd @ F3E2   dptr_high_r6_low_a   [named]
; Ghidra 12.1.3 disassembly, generated by ec/tools/build_ec_decompile.py -- do not edit.
; Source: ec/firmware/GMxMGxx_11.800, the ITE8850-PD image at file 0x20000 -- a separate program with its own address space, not a third bank, SHA-256 158d1c6416426939a814146b766a44e2ff0e9286b0abd237e70e51a0c03399c4
; This is the machine code. The decompiled C for this address is F3E2.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

F3E2     ff - -   mov      R7, A
F3E3     ee - -   mov      A, R6
F3E4     34 fd -  addc     A, #0xfd
F3E6     8f 82 -  mov      DPL, R7
F3E8     f5 83 -  mov      DPH, A
F3EA     22 - -   ret      
