; OemTurboModeDxe @ 0000090C   scale_units_to_port_ticks   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemTurboModeDxe.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 0000090C.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

0000090C 40 53 - - - - - - - - - -           push     RBX
0000090E 48 83 ec 20 - - - - - - - -         sub      RSP, 0x20
00000912 48 69 d1 99 9e 36 00 - - - - -      imul     RDX, RCX, 0x369e99
00000919 48 8b d9 - - - - - - - - -          mov      RBX, RCX
0000091C 48 b8 db 34 b6 d7 82 de 1b 43 - -   mov      RAX, 0x431bde82d7b634db
00000926 48 f7 e2 - - - - - - - - -          mul      RDX
00000929 48 c1 ea 12 - - - - - - - -         shr      RDX, 0x12
0000092D 8b ca - - - - - - - - - -           mov      ECX, EDX
0000092F e8 78 ff ff ff - - - - - - -        call     0x000008ac
00000934 48 8b c3 - - - - - - - - -          mov      RAX, RBX
00000937 48 83 c4 20 - - - - - - - -         add      RSP, 0x20
0000093B 5b - - - - - - - - - - -            pop      RBX
0000093C c3 - - - - - - - - - - -            ret      
