; OemServiceDxe @ 00001054   find_record_by_id   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemServiceDxe.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00001054.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00001054 48 8b 0d 7d 03 00 00 - - -    mov      RCX, qword ptr [0x000013d8]
0000105B 33 c0 - - - - - - - -         xor      EAX, EAX
0000105D 48 85 c9 - - - - - - -        test     RCX, RCX
00001060 75 57 - - - - - - - -         jnz      0x000010b9
00001062 48 8b 15 47 03 00 00 - - -    mov      RDX, qword ptr [0x000013b0]
00001069 8b c8 - - - - - - - -         mov      ECX, EAX
0000106B 48 89 05 66 03 00 00 - - -    mov      qword ptr [0x000013d8], RAX
00001072 4c 8b 42 68 - - - - - -       mov      R8, qword ptr [RDX + 0x68]
00001076 4d 85 c0 - - - - - - -        test     R8, R8
00001079 74 3e - - - - - - - -         jz       0x000010b9
0000107B 4c 8b 4a 70 - - - - - -       mov      R9, qword ptr [RDX + 0x70]
0000107F 4c 8b 15 62 02 00 00 - - -    mov      R10, qword ptr [0x000012e8]
00001086 49 8b d1 - - - - - - -        mov      RDX, R9
00001089 4c 8b 1d 50 02 00 00 - - -    mov      R11, qword ptr [0x000012e0]
00001090 4c 3b 1a - - - - - - -        cmp      R11, qword ptr [RDX]
00001093 75 06 - - - - - - - -         jnz      0x0000109b
00001095 4c 3b 52 08 - - - - - -       cmp      R10, qword ptr [RDX + 0x8]
00001099 74 0e - - - - - - - -         jz       0x000010a9
0000109B 48 ff c0 - - - - - - -        inc      RAX
0000109E 48 83 c2 18 - - - - - -       add      RDX, 0x18
000010A2 49 3b c0 - - - - - - -        cmp      RAX, R8
000010A5 73 12 - - - - - - - -         jnc      0x000010b9
000010A7 eb e7 - - - - - - - -         jmp      0x00001090
000010A9 48 8d 04 40 - - - - - -       lea      RAX, [RAX + RAX*0x2]
000010AD 49 8b 4c c1 10 - - - - -      mov      RCX, qword ptr [R9 + RAX*0x8 + 0x10]
000010B2 48 89 0d 1f 03 00 00 - - -    mov      qword ptr [0x000013d8], RCX
000010B9 48 8b c1 - - - - - - -        mov      RAX, RCX
000010BC c3 - - - - - - - - -          ret      
