; Setup @ 0000D400   FUN_0000d400
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 0000D400.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

0000D400 48 89 4c 24 08 mov      qword ptr [RSP + 0x8], RCX
0000D405 55         push     RBP
0000D406 53         push     RBX
0000D407 56         push     RSI
0000D408 57         push     RDI
0000D409 41 54      push     R12
0000D40B 41 55      push     R13
0000D40D 41 56      push     R14
0000D40F 41 57      push     R15
0000D411 48 8d 6c 24 e1 lea      RBP, [RSP + -0x1f]
0000D416 48 81 ec b8 00 00 00 sub      RSP, 0xb8
0000D41D 45 33 e4   xor      R12D, R12D
0000D420 48 8d 45 9f lea      RAX, [RBP + -0x61]
0000D424 48 89 44 24 20 mov      qword ptr [RSP + 0x20], RAX
0000D429 4c 8d 4d 97 lea      R9, [RBP + -0x69]
0000D42D 48 8b 05 44 c0 01 00 mov      RAX, qword ptr [0x00029478]
0000D434 48 8d 15 65 62 01 00 lea      RDX, [0x236a0]
0000D43B 45 33 c0   xor      R8D, R8D
0000D43E 44 89 65 6f mov      dword ptr [RBP + 0x6f], R12D
0000D442 41 8d 5c 24 02 lea      EBX, [R12 + 0x2]
0000D447 8b cb      mov      ECX, EBX
0000D449 ff 90 38 01 00 00 call     qword ptr [RAX + 0x138]
0000D44F 48 8b 4d 97 mov      RCX, qword ptr [RBP + -0x69]
0000D453 41 8a fc   mov      DIL, R12B
0000D456 48 85 c0   test     RAX, RAX
0000D459 49 0f 48 cc cmovs    RCX, R12
0000D45D 48 89 4d 97 mov      qword ptr [RBP + -0x69], RCX
0000D461 48 85 c9   test     RCX, RCX
0000D464 0f 84 84 00 00 00 jz       0x0000d4ee
0000D46A 41 8b dc   mov      EBX, R12D
0000D46D 48 8b 4d 9f mov      RCX, qword ptr [RBP + -0x61]
0000D471 4c 8d 45 af lea      R8, [RBP + -0x51]
0000D475 48 8b 05 fc bf 01 00 mov      RAX, qword ptr [0x00029478]
0000D47C 48 8d 15 1d 62 01 00 lea      RDX, [0x236a0]
0000D483 48 8b 0c d9 mov      RCX, qword ptr [RCX + RBX*0x8]
0000D487 ff 90 98 00 00 00 call     qword ptr [RAX + 0x98]
0000D48D 48 8d 45 c7 lea      RAX, [RBP + -0x39]
0000D491 48 89 44 24 20 mov      qword ptr [RSP + 0x20], RAX
0000D496 4c 8d 4d bf lea      R9, [RBP + -0x41]
0000D49A 48 8b 45 af mov      RAX, qword ptr [RBP + -0x51]
0000D49E 4c 8d 45 b7 lea      R8, [RBP + -0x49]
0000D4A2 48 8d 55 0f lea      RDX, [RBP + 0xf]
0000D4A6 48 8b c8   mov      RCX, RAX
0000D4A9 ff 50 70   call     qword ptr [RAX + 0x70]
0000D4AC 4c 39 65 b7 cmp      qword ptr [RBP + -0x49], R12
0000D4B0 75 2a      jnz      0x0000d4dc
0000D4B2 48 83 7d bf 17 cmp      qword ptr [RBP + -0x41], 0x17
0000D4B7 75 23      jnz      0x0000d4dc
0000D4B9 4c 39 65 c7 cmp      qword ptr [RBP + -0x39], R12
0000D4BD 75 1d      jnz      0x0000d4dc
0000D4BF 48 8b 4d 9f mov      RCX, qword ptr [RBP + -0x61]
0000D4C3 41 b1 01   mov      R9B, 0x1
0000D4C6 48 8b 05 ab bf 01 00 mov      RAX, qword ptr [0x00029478]
0000D4CD 45 33 c0   xor      R8D, R8D
0000D4D0 33 d2      xor      EDX, EDX
0000D4D2 48 8b 0c d9 mov      RCX, qword ptr [RCX + RBX*0x8]
0000D4D6 ff 90 08 01 00 00 call     qword ptr [RAX + 0x108]
0000D4DC 40 fe c7   inc      DIL
0000D4DF 40 0f b6 df movzx    EBX, DIL
0000D4E3 48 3b 5d 97 cmp      RBX, qword ptr [RBP + -0x69]
0000D4E7 72 84      jc       0x0000d46d
0000D4E9 bb 02 00 00 00 mov      EBX, 0x2
0000D4EE 48 8b 4d 9f mov      RCX, qword ptr [RBP + -0x61]
0000D4F2 48 85 c9   test     RCX, RCX
0000D4F5 74 0a      jz       0x0000d501
0000D4F7 48 8b 05 7a bf 01 00 mov      RAX, qword ptr [0x00029478]
0000D4FE ff 50 48   call     qword ptr [RAX + 0x48]
0000D501 ba 00 01 00 00 mov      EDX, 0x100
0000D506 c6 05 93 be 01 00 01 mov      byte ptr [0x000293a0], 0x1
0000D50D e8 02 e0 00 00 call     0x0001b514
0000D512 48 8b f8   mov      RDI, RAX
0000D515 48 85 c0   test     RAX, RAX
0000D518 0f 84 3b 03 00 00 jz       0x0000d859
0000D51E ba 40 00 00 00 mov      EDX, 0x40
0000D523 e8 ec df 00 00 call     0x0001b514
0000D528 48 89 45 d7 mov      qword ptr [RBP + -0x29], RAX
0000D52C 48 8b f0   mov      RSI, RAX
0000D52F 48 85 c0   test     RAX, RAX
0000D532 75 08      jnz      0x0000d53c
0000D534 48 8b cf   mov      RCX, RDI
0000D537 e9 13 03 00 00 jmp      0x0000d84f
0000D53C 48 8d 45 9f lea      RAX, [RBP + -0x61]
0000D540 45 33 c0   xor      R8D, R8D
0000D543 48 89 44 24 20 mov      qword ptr [RSP + 0x20], RAX
0000D548 4c 8d 4d 97 lea      R9, [RBP + -0x69]
0000D54C 48 8b 05 25 bf 01 00 mov      RAX, qword ptr [0x00029478]
0000D553 48 8d 15 66 5f 01 00 lea      RDX, [0x234c0]
0000D55A 8b cb      mov      ECX, EBX
0000D55C 4d 8b f4   mov      R14, R12
0000D55F ff 90 38 01 00 00 call     qword ptr [RAX + 0x138]
0000D565 48 8b 4d 97 mov      RCX, qword ptr [RBP + -0x69]
0000D569 45 8a fc   mov      R15B, R12B
0000D56C 48 85 c0   test     RAX, RAX
0000D56F 49 0f 48 cc cmovs    RCX, R12
0000D573 48 89 4d 97 mov      qword ptr [RBP + -0x69], RCX
0000D577 48 85 c9   test     RCX, RCX
0000D57A 0f 84 ac 02 00 00 jz       0x0000d82c
0000D580 49 8b dc   mov      RBX, R12
0000D583 4c 8d 2d 76 2a ff ff lea      R13, [0x0]
0000D58A 48 8b 4d 9f mov      RCX, qword ptr [RBP + -0x61]
0000D58E 4c 8d 45 cf lea      R8, [RBP + -0x31]
0000D592 48 8b 05 df be 01 00 mov      RAX, qword ptr [0x00029478]
0000D599 48 8d 15 f0 60 01 00 lea      RDX, [0x23690]
0000D5A0 48 8b 0c d9 mov      RCX, qword ptr [RCX + RBX*0x8]
0000D5A4 ff 90 98 00 00 00 call     qword ptr [RAX + 0x98]
0000D5AA 48 8b 4d cf mov      RCX, qword ptr [RBP + -0x31]
0000D5AE 8a 01      mov      AL, byte ptr [RCX]
0000D5B0 3c 7f      cmp      AL, 0x7f
0000D5B2 74 15      jz       0x0000d5c9
0000D5B4 3c 01      cmp      AL, 0x1
0000D5B6 75 05      jnz      0x0000d5bd
0000D5B8 38 41 01   cmp      byte ptr [RCX + 0x1], AL
0000D5BB 74 09      jz       0x0000d5c6
0000D5BD 0f b7 41 02 movzx    EAX, word ptr [RCX + 0x2]
0000D5C1 48 03 c8   add      RCX, RAX
0000D5C4 eb e8      jmp      0x0000d5ae
0000D5C6 4c 8b f1   mov      R14, RCX
0000D5C9 4d 85 f6   test     R14, R14
0000D5CC 0f 84 49 02 00 00 jz       0x0000d81b
0000D5D2 41 80 7e 05 17 cmp      byte ptr [R14 + 0x5], 0x17
0000D5D7 0f 85 3e 02 00 00 jnz      0x0000d81b
0000D5DD 45 38 66 04 cmp      byte ptr [R14 + 0x4], R12B
0000D5E1 0f 85 34 02 00 00 jnz      0x0000d81b
0000D5E7 48 8b 4d 9f mov      RCX, qword ptr [RBP + -0x61]
0000D5EB 4c 8d 45 a7 lea      R8, [RBP + -0x59]
0000D5EF 48 8b 05 82 be 01 00 mov      RAX, qword ptr [0x00029478]
0000D5F6 48 8d 15 c3 5e 01 00 lea      RDX, [0x234c0]
0000D5FD 48 8b 0c d9 mov      RCX, qword ptr [RCX + RBX*0x8]
0000D601 ff 90 98 00 00 00 call     qword ptr [RAX + 0x98]
0000D607 48 8b 45 a7 mov      RAX, qword ptr [RBP + -0x59]
0000D60B 4c 8d 45 7f lea      R8, [RBP + 0x7f]
0000D60F 48 8d 55 77 lea      RDX, [RBP + 0x77]
0000D613 48 8b c8   mov      RCX, RAX
0000D616 ff 50 28   call     qword ptr [RAX + 0x28]
0000D619 8b 45 77   mov      EAX, dword ptr [RBP + 0x77]
0000D61C ba 00 02 00 00 mov      EDX, 0x200
0000D621 45 0f b7 a4 45 c0 6a 02 00 movzx    R12D, word ptr [R13 + RAX*0x2 + 0x26ac0]
0000D62A 45 0f b7 ac 45 d0 6a 02 00 movzx    R13D, word ptr [R13 + RAX*0x2 + 0x26ad0]
0000D633 e8 dc de 00 00 call     0x0001b514
0000D638 48 8b d8   mov      RBX, RAX
0000D63B 48 85 c0   test     RAX, RAX
0000D63E 0f 84 15 02 00 00 jz       0x0000d859
0000D644 ba 00 02 00 00 mov      EDX, 0x200
0000D649 48 8b c8   mov      RCX, RAX
0000D64C e8 ef 2c ff ff call     0x00000340
0000D651 4c 8b 4d a7 mov      R9, qword ptr [RBP + -0x59]
0000D655 4c 8d 45 6f lea      R8, [RBP + 0x6f]
0000D659 48 8b d3   mov      RDX, RBX
0000D65C c7 45 6f 00 02 00 00 mov      dword ptr [RBP + 0x6f], 0x200
0000D663 49 8b c9   mov      RCX, R9
0000D666 41 ff 51 18 call     qword ptr [R9 + 0x18]
0000D66A ba 2a 00 00 00 mov      EDX, 0x2a
0000D66F 48 8d 4d df lea      RCX, [RBP + -0x21]
0000D673 e8 c8 2c ff ff call     0x00000340
0000D678 48 8d 53 36 lea      RDX, [RBX + 0x36]
0000D67C 48 8d 45 df lea      RAX, [RBP + -0x21]
0000D680 48 3b c2   cmp      RAX, RDX
0000D683 74 0f      jz       0x0000d694
0000D685 41 b8 28 00 00 00 mov      R8D, 0x28
0000D68B 48 8d 4d df lea      RCX, [RBP + -0x21]
0000D68F e8 4c 2c ff ff call     0x000002e0
0000D694 45 33 d2   xor      R10D, R10D
0000D697 45 0f b7 ca movzx    R9D, R10W
0000D69B 41 8d 42 01 lea      EAX, [R10 + 0x1]
0000D69F 8d 70 01   lea      ESI, [RAX + 0x1]
0000D6A2 8b c8      mov      ECX, EAX
0000D6A4 45 0f b7 c1 movzx    R8D, R9W
0000D6A8 66 44 03 ce add      R9W, SI
0000D6AC 8a 44 0d df mov      AL, byte ptr [RBP + RCX*0x1 + -0x21]
0000D6B0 42 8a 54 05 df mov      DL, byte ptr [RBP + R8*0x1 + -0x21]
0000D6B5 42 88 44 05 df mov      byte ptr [RBP + R8*0x1 + -0x21], AL
0000D6BA 41 0f b7 c1 movzx    EAX, R9W
0000D6BE ff c0      inc      EAX
0000D6C0 88 54 0d df mov      byte ptr [RBP + RCX*0x1 + -0x21], DL
0000D6C4 83 f8 28   cmp      EAX, 0x28
0000D6C7 72 d9      jc       0x0000d6a2
0000D6C9 48 8b 75 d7 mov      RSI, qword ptr [RBP + -0x29]
0000D6CD 44 88 55 ed mov      byte ptr [RBP + -0x13], R10B
0000D6D1 66 44 39 13 cmp      word ptr [RBX], R10W
0000D6D5 0f 8c cf 00 00 00 jl       0x0000d7aa
0000D6DB b8 00 04 00 00 mov      EAX, 0x400
0000D6E0 66 85 83 a6 00 00 00 test     word ptr [RBX + 0xa6], AX
0000D6E7 74 09      jz       0x0000d6f2
0000D6E9 48 8b 93 c8 00 00 00 mov      RDX, qword ptr [RBX + 0xc8]
0000D6F0 eb 03      jmp      0x0000d6f5
0000D6F2 8b 53 78   mov      EDX, dword ptr [RBX + 0x78]
0000D6F5 b8 00 10 00 00 mov      EAX, 0x1000
0000D6FA 66 85 83 d4 00 00 00 test     word ptr [RBX + 0xd4], AX
0000D701 74 1a      jz       0x0000d71d
0000D703 0f b7 8b ec 00 00 00 movzx    ECX, word ptr [RBX + 0xec]
0000D70A 0f b7 83 ea 00 00 00 movzx    EAX, word ptr [RBX + 0xea]
0000D711 48 c1 e1 10 shl      RCX, 0x10
0000D715 48 0b c8   or       RCX, RAX
0000D718 48 03 c9   add      RCX, RCX
0000D71B eb 05      jmp      0x0000d722
0000D71D b9 00 02 00 00 mov      ECX, 0x200
0000D722 44 8b c1   mov      R8D, ECX
0000D725 4c 8d 4d df lea      R9, [RBP + -0x21]
0000D729 4c 0f af c2 imul     R8, RDX
0000D72D 48 b8 2f 4b 69 6d 82 be e0 12 mov      RAX, 0x12e0be826d694b2f
0000D737 49 f7 e0   mul      R8
0000D73A 49 8b c8   mov      RCX, R8
0000D73D 48 2b ca   sub      RCX, RDX
0000D740 48 d1 e9   shr      RCX, 0x1
0000D743 48 03 ca   add      RCX, RDX
0000D746 48 c1 e9 1d shr      RCX, 0x1d
0000D74A 48 69 c1 00 ca 9a 3b imul     RAX, RCX, 0x3b9aca00
0000D751 4c 2b c0   sub      R8, RAX
0000D754 48 b8 fd ce 61 84 11 77 cc ab mov      RAX, -0x543388ee7b9e3103
0000D75E 49 f7 e0   mul      R8
0000D761 4c 8d 05 90 90 01 00 lea      R8, [0x267f8]
0000D768 48 c1 ea 1a shr      RDX, 0x1a
0000D76C 89 54 24 28 mov      dword ptr [RSP + 0x28], EDX
0000D770 ba 00 01 00 00 mov      EDX, 0x100
0000D775 89 4c 24 20 mov      dword ptr [RSP + 0x20], ECX
0000D779 48 8b cf   mov      RCX, RDI
0000D77C e8 a7 e9 00 00 call     0x0001c128
0000D781 b8 ff ff 00 00 mov      EAX, 0xffff
0000D786 66 39 83 98 00 00 00 cmp      word ptr [RBX + 0x98], AX
0000D78D 74 12      jz       0x0000d7a1
0000D78F f6 83 9c 00 00 00 40 test     byte ptr [RBX + 0x9c], 0x40
0000D796 74 09      jz       0x0000d7a1
0000D798 4c 8d 05 69 90 01 00 lea      R8, [0x26808]
0000D79F eb 28      jmp      0x0000d7c9
0000D7A1 4c 8d 05 70 90 01 00 lea      R8, [0x26818]
0000D7A8 eb 1f      jmp      0x0000d7c9
0000D7AA 4c 8d 4d df lea      R9, [RBP + -0x21]
0000D7AE ba 00 01 00 00 mov      EDX, 0x100
0000D7B3 4c 8d 05 6e 90 01 00 lea      R8, [0x26828]
0000D7BA 48 8b cf   mov      RCX, RDI
0000D7BD e8 66 e9 00 00 call     0x0001c128
0000D7C2 4c 8d 05 6f 90 01 00 lea      R8, [0x26838]
0000D7C9 ba 40 00 00 00 mov      EDX, 0x40
0000D7CE 48 8b ce   mov      RCX, RSI
0000D7D1 e8 52 e9 00 00 call     0x0001c128
0000D7D6 48 8b 4d 67 mov      RCX, qword ptr [RBP + 0x67]
0000D7DA 4c 8d 05 4b 8f 01 00 lea      R8, [0x2672c]
0000D7E1 4c 8b cf   mov      R9, RDI
0000D7E4 41 0f b7 d4 movzx    EDX, R12W
0000D7E8 e8 93 2e ff ff call     0x00000680
0000D7ED 48 8b 4d 67 mov      RCX, qword ptr [RBP + 0x67]
0000D7F1 4c 8d 05 34 8f 01 00 lea      R8, [0x2672c]
0000D7F8 4c 8b ce   mov      R9, RSI
0000D7FB 41 0f b7 d5 movzx    EDX, R13W
0000D7FF e8 7c 2e ff ff call     0x00000680
0000D804 48 8b 05 6d bc 01 00 mov      RAX, qword ptr [0x00029478]
0000D80B 48 8b cb   mov      RCX, RBX
0000D80E ff 50 48   call     qword ptr [RAX + 0x48]
0000D811 45 33 e4   xor      R12D, R12D
0000D814 4c 8d 2d e5 27 ff ff lea      R13, [0x0]
0000D81B 41 fe c7   inc      R15B
0000D81E 41 0f b6 df movzx    EBX, R15B
0000D822 48 3b 5d 97 cmp      RBX, qword ptr [RBP + -0x69]
0000D826 0f 82 5e fd ff ff jc       0x0000d58a
0000D82C 48 8b 4d 9f mov      RCX, qword ptr [RBP + -0x61]
0000D830 48 85 c9   test     RCX, RCX
0000D833 74 0a      jz       0x0000d83f
0000D835 48 8b 05 3c bc 01 00 mov      RAX, qword ptr [0x00029478]
0000D83C ff 50 48   call     qword ptr [RAX + 0x48]
0000D83F 48 8b 05 32 bc 01 00 mov      RAX, qword ptr [0x00029478]
0000D846 48 8b cf   mov      RCX, RDI
0000D849 ff 50 48   call     qword ptr [RAX + 0x48]
0000D84C 48 8b ce   mov      RCX, RSI
0000D84F 48 8b 05 22 bc 01 00 mov      RAX, qword ptr [0x00029478]
0000D856 ff 50 48   call     qword ptr [RAX + 0x48]
0000D859 48 81 c4 b8 00 00 00 add      RSP, 0xb8
0000D860 41 5f      pop      R15
0000D862 41 5e      pop      R14
0000D864 41 5d      pop      R13
0000D866 41 5c      pop      R12
0000D868 5f         pop      RDI
0000D869 5e         pop      RSI
0000D86A 5b         pop      RBX
0000D86B 5d         pop      RBP
0000D86C c3         ret      
