; Setup @ 00003458   poll_icc_setup_state   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00003458.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00003458 48 89 5c 24 08 - - - - - - -        mov      qword ptr [RSP + 0x8], RBX
0000345D 55 - - - - - - - - - - -            push     RBP
0000345E 57 - - - - - - - - - - -            push     RDI
0000345F 41 56 - - - - - - - - - -           push     R14
00003461 48 8b ec - - - - - - - - -          mov      RBP, RSP
00003464 48 81 ec 80 00 00 00 - - - - -      sub      RSP, 0x80
0000346B 48 8b 05 06 60 02 00 - - - - -      mov      RAX, qword ptr [0x00029478]
00003472 4c 8d 45 c0 - - - - - - - -         lea      R8, [RBP + -0x40]
00003476 48 8b f9 - - - - - - - - -          mov      RDI, RCX
00003479 48 c7 45 b0 1d 02 00 00 - - - -     mov      qword ptr [RBP + -0x50], 0x21d
00003481 41 be 08 00 00 00 - - - - - -       mov      R14D, 0x8
00003487 48 8d 0d 92 02 02 00 - - - - -      lea      RCX, [0x23720]
0000348E 33 d2 - - - - - - - - - -           xor      EDX, EDX
00003490 4c 89 75 b8 - - - - - - - -         mov      qword ptr [RBP + -0x48], R14
00003494 ff 90 40 01 00 00 - - - - - -       call     qword ptr [RAX + 0x140]
0000349A 48 85 c0 - - - - - - - - -          test     RAX, RAX
0000349D 0f 88 8e 01 00 00 - - - - - -       js       0x00003631
000034A3 41 8b d6 - - - - - - - - -          mov      EDX, R14D
000034A6 48 8d 4d 38 - - - - - - - -         lea      RCX, [RBP + 0x38]
000034AA e8 91 ce ff ff - - - - - - -        call     0x00000340
000034AF 48 83 3d d1 5d 02 00 00 - - - -     cmp      qword ptr [0x00029288], 0x0
000034B7 0f 84 74 01 00 00 - - - - - -       jz       0x00003631
000034BD 48 8d 05 6c 60 02 00 - - - - -      lea      RAX, [0x29530]
000034C4 48 89 44 24 20 - - - - - - -        mov      qword ptr [RSP + 0x20], RAX
000034C9 4c 8d 4d b0 - - - - - - - -         lea      R9, [RBP + -0x50]
000034CD 48 8b 05 b4 5f 02 00 - - - - -      mov      RAX, qword ptr [0x00029488]
000034D4 4c 8d 45 30 - - - - - - - -         lea      R8, [RBP + 0x30]
000034D8 48 8d 15 11 04 02 00 - - - - -      lea      RDX, [0x238f0]
000034DF 48 8d 0d 8a 2b 02 00 - - - - -      lea      RCX, [0x26070]
000034E6 ff 50 48 - - - - - - - - -          call     qword ptr [RAX + 0x48]
000034E9 48 8d 45 38 - - - - - - - -         lea      RAX, [RBP + 0x38]
000034ED 45 33 c0 - - - - - - - - -          xor      R8D, R8D
000034F0 48 89 44 24 20 - - - - - - -        mov      qword ptr [RSP + 0x20], RAX
000034F5 4c 8d 4d b8 - - - - - - - -         lea      R9, [RBP + -0x48]
000034F9 48 8b 05 88 5f 02 00 - - - - -      mov      RAX, qword ptr [0x00029488]
00003500 48 8d 15 79 00 02 00 - - - - -      lea      RDX, [0x23580]
00003507 48 8d 0d 0a 2b 02 00 - - - - -      lea      RCX, [0x26018]
0000350E ff 50 48 - - - - - - - - -          call     qword ptr [RAX + 0x48]
00003511 48 85 c0 - - - - - - - - -          test     RAX, RAX
00003514 0f 88 17 01 00 00 - - - - - -       js       0x00003631
0000351A 80 3d 5f 5d 02 00 00 - - - - -      cmp      byte ptr [0x00029280], 0x0
00003521 0f b6 0d 25 62 02 00 - - - - -      movzx    ECX, byte ptr [0x0002974d]
00003528 0f b6 05 4e 5d 02 00 - - - - -      movzx    EAX, byte ptr [0x0002927d]
0000352F 8a 5d 3e - - - - - - - - -          mov      BL, byte ptr [RBP + 0x3e]
00003532 0f 44 c8 - - - - - - - - -          cmovz    ECX, EAX
00003535 88 0d 12 62 02 00 - - - - - -       mov      byte ptr [0x0002974d], CL
0000353B 3a d9 - - - - - - - - - -           cmp      BL, CL
0000353D 74 1b - - - - - - - - - -           jz       0x0000355a
0000353F 8a cb - - - - - - - - - -           mov      CL, BL
00003541 e8 d2 d3 01 00 - - - - - - -        call     0x00020918
00003546 88 1d 01 62 02 00 - - - - - -       mov      byte ptr [0x0002974d], BL
0000354C c6 05 2d 5d 02 00 01 - - - - -      mov      byte ptr [0x00029280], 0x1
00003553 c6 05 36 5d 02 00 01 - - - - -      mov      byte ptr [0x00029290], 0x1
0000355A 45 33 c0 - - - - - - - - -          xor      R8D, R8D
0000355D 48 8d 4d c8 - - - - - - - -         lea      RCX, [RBP + -0x38]
00003561 41 8d 50 30 - - - - - - - -         lea      EDX, [R8 + 0x30]
00003565 e8 b6 cd ff ff - - - - - - -        call     0x00000320
0000356A 80 3d 0f 5d 02 00 00 - - - - -      cmp      byte ptr [0x00029280], 0x0
00003571 0f 85 a8 00 00 00 - - - - - -       jnz      0x0000361f
00003577 80 7d 3f 00 - - - - - - - -         cmp      byte ptr [RBP + 0x3f], 0x0
0000357B 0f 84 9e 00 00 00 - - - - - -       jz       0x0000361f
00003581 80 3d f1 5c 02 00 00 - - - - -      cmp      byte ptr [0x00029279], 0x0
00003588 0f 84 91 00 00 00 - - - - - -       jz       0x0000361f
0000358E 0f b7 45 38 - - - - - - - -         movzx    EAX, word ptr [RBP + 0x38]
00003592 69 c8 10 27 00 00 - - - - - -       imul     ECX, EAX, 0x2710
00003598 80 3d 96 61 02 00 00 - - - - -      cmp      byte ptr [0x00029735], 0x0
0000359F 8a 45 3a - - - - - - - - -          mov      AL, byte ptr [RBP + 0x3a]
000035A2 c6 05 e7 5c 02 00 01 - - - - -      mov      byte ptr [0x00029290], 0x1
000035A9 c6 05 c9 5c 02 00 00 - - - - -      mov      byte ptr [0x00029279], 0x0
000035B0 89 4d e4 - - - - - - - - -          mov      dword ptr [RBP + -0x1c], ECX
000035B3 88 45 f1 - - - - - - - - -          mov      byte ptr [RBP + -0xf], AL
000035B6 c6 45 f0 04 - - - - - - - -         mov      byte ptr [RBP + -0x10], 0x4
000035BA c6 45 dc 01 - - - - - - - -         mov      byte ptr [RBP + -0x24], 0x1
000035BE 74 19 - - - - - - - - - -           jz       0x000035d9
000035C0 0f b7 45 f4 - - - - - - - -         movzx    EAX, word ptr [RBP + -0xc]
000035C4 b9 cf ff 00 00 - - - - - - -        mov      ECX, 0xffcf
000035C9 66 23 c1 - - - - - - - - -          and      AX, CX
000035CC c6 05 bd 5c 02 00 01 - - - - -      mov      byte ptr [0x00029290], 0x1
000035D3 66 41 0b c6 - - - - - - - -         or       AX, R14W
000035D7 eb 39 - - - - - - - - - -           jmp      0x00003612
000035D9 0f b6 0d 56 61 02 00 - - - - -      movzx    ECX, byte ptr [0x00029736]
000035E0 85 c9 - - - - - - - - - -           test     ECX, ECX
000035E2 74 17 - - - - - - - - - -           jz       0x000035fb
000035E4 83 f9 01 - - - - - - - - -          cmp      ECX, 0x1
000035E7 75 2d - - - - - - - - - -           jnz      0x00003616
000035E9 b8 c7 ff 00 00 - - - - - - -        mov      EAX, 0xffc7
000035EE c6 05 9b 5c 02 00 00 - - - - -      mov      byte ptr [0x00029290], 0x0
000035F5 66 21 45 f4 - - - - - - - -         and      word ptr [RBP + -0xc], AX
000035F9 eb 1b - - - - - - - - - -           jmp      0x00003616
000035FB 0f b7 45 f4 - - - - - - - -         movzx    EAX, word ptr [RBP + -0xc]
000035FF b9 d7 ff 00 00 - - - - - - -        mov      ECX, 0xffd7
00003604 66 23 c1 - - - - - - - - -          and      AX, CX
00003607 c6 05 82 5c 02 00 00 - - - - -      mov      byte ptr [0x00029290], 0x0
0000360E 66 83 c8 10 - - - - - - - -         or       AX, 0x10
00003612 66 89 45 f4 - - - - - - - -         mov      word ptr [RBP + -0xc], AX
00003616 48 8d 4d c8 - - - - - - - -         lea      RCX, [RBP + -0x38]
0000361A e8 01 fa ff ff - - - - - - -        call     0x00003020
0000361F 48 85 ff - - - - - - - - -          test     RDI, RDI
00003622 74 0d - - - - - - - - - -           jz       0x00003631
00003624 48 8b 05 4d 5e 02 00 - - - - -      mov      RAX, qword ptr [0x00029478]
0000362B 48 8b cf - - - - - - - - -          mov      RCX, RDI
0000362E ff 50 70 - - - - - - - - -          call     qword ptr [RAX + 0x70]
00003631 48 8b 9c 24 a0 00 00 00 - - - -     mov      RBX, qword ptr [RSP + 0xa0]
00003639 48 81 c4 80 00 00 00 - - - - -      add      RSP, 0x80
00003640 41 5e - - - - - - - - - -           pop      R14
00003642 5f - - - - - - - - - - -            pop      RDI
00003643 5d - - - - - - - - - - -            pop      RBP
00003644 c3 - - - - - - - - - - -            ret      
