; Setup @ 00001074   FUN_00001074
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00001074.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00001074 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00001079 48 89 74 24 10 mov      qword ptr [RSP + 0x10], RSI
0000107E 4c 89 7c 24 18 mov      qword ptr [RSP + 0x18], R15
00001083 33 f6      xor      ESI, ESI
00001085 4c 8d 51 04 lea      R10, [RCX + 0x4]
00001089 4d 8b d8   mov      R11, R8
0000108C 48 8b da   mov      RBX, RDX
0000108F 44 8b ce   mov      R9D, ESI
00001092 44 8d 7e 01 lea      R15D, [RSI + 0x1]
00001096 45 0f b7 42 fc movzx    R8D, word ptr [R10 + -0x4]
0000109B 41 0f b6 cf movzx    ECX, R15B
0000109F 41 8d 40 d0 lea      EAX, [R8 + -0x30]
000010A3 66 83 f8 36 cmp      AX, 0x36
000010A7 41 8d 40 c6 lea      EAX, [R8 + -0x3a]
000010AB 0f 47 ce   cmova    ECX, ESI
000010AE 66 83 f8 06 cmp      AX, 0x6
000010B2 0f b6 d1   movzx    EDX, CL
000010B5 0f 46 d6   cmovbe   EDX, ESI
000010B8 66 41 83 e8 47 sub      R8W, 0x47
000010BD 66 41 83 f8 19 cmp      R8W, 0x19
000010C2 0f b6 c2   movzx    EAX, DL
000010C5 0f 46 c6   cmovbe   EAX, ESI
000010C8 84 c0      test     AL, AL
000010CA 0f 84 7f 01 00 00 jz       0x0000124f
000010D0 45 0f b7 42 fe movzx    R8D, word ptr [R10 + -0x2]
000010D5 41 0f b6 cf movzx    ECX, R15B
000010D9 41 8d 40 d0 lea      EAX, [R8 + -0x30]
000010DD 66 83 f8 36 cmp      AX, 0x36
000010E1 41 8d 40 c6 lea      EAX, [R8 + -0x3a]
000010E5 0f 47 ce   cmova    ECX, ESI
000010E8 66 83 f8 06 cmp      AX, 0x6
000010EC 0f b6 d1   movzx    EDX, CL
000010EF 0f 46 d6   cmovbe   EDX, ESI
000010F2 66 41 83 e8 47 sub      R8W, 0x47
000010F7 66 41 83 f8 19 cmp      R8W, 0x19
000010FC 0f b6 c2   movzx    EAX, DL
000010FF 0f 46 c6   cmovbe   EAX, ESI
00001102 84 c0      test     AL, AL
00001104 0f 84 45 01 00 00 jz       0x0000124f
0000110A 45 0f b7 02 movzx    R8D, word ptr [R10]
0000110E 41 0f b6 cf movzx    ECX, R15B
00001112 41 8d 40 d0 lea      EAX, [R8 + -0x30]
00001116 66 83 f8 36 cmp      AX, 0x36
0000111A 41 8d 40 c6 lea      EAX, [R8 + -0x3a]
0000111E 0f 47 ce   cmova    ECX, ESI
00001121 66 83 f8 06 cmp      AX, 0x6
00001125 0f b6 d1   movzx    EDX, CL
00001128 0f 46 d6   cmovbe   EDX, ESI
0000112B 66 41 83 e8 47 sub      R8W, 0x47
00001130 66 41 83 f8 19 cmp      R8W, 0x19
00001135 0f b6 c2   movzx    EAX, DL
00001138 0f 46 c6   cmovbe   EAX, ESI
0000113B 84 c0      test     AL, AL
0000113D 0f 84 0c 01 00 00 jz       0x0000124f
00001143 45 0f b7 42 02 movzx    R8D, word ptr [R10 + 0x2]
00001148 41 0f b6 cf movzx    ECX, R15B
0000114C 41 8d 40 d0 lea      EAX, [R8 + -0x30]
00001150 66 83 f8 36 cmp      AX, 0x36
00001154 41 8d 40 c6 lea      EAX, [R8 + -0x3a]
00001158 0f 47 ce   cmova    ECX, ESI
0000115B 66 83 f8 06 cmp      AX, 0x6
0000115F 0f b6 d1   movzx    EDX, CL
00001162 0f 46 d6   cmovbe   EDX, ESI
00001165 66 41 83 e8 47 sub      R8W, 0x47
0000116A 66 41 83 f8 19 cmp      R8W, 0x19
0000116F 0f b6 c2   movzx    EAX, DL
00001172 0f 46 c6   cmovbe   EAX, ESI
00001175 84 c0      test     AL, AL
00001177 0f 84 d2 00 00 00 jz       0x0000124f
0000117D 48 8b 03   mov      RAX, qword ptr [RBX]
00001180 49 2b c7   sub      RAX, R15
00001183 4c 3b c8   cmp      R9, RAX
00001186 0f 83 c3 00 00 00 jnc      0x0000124f
0000118C 41 8a 4a fc mov      CL, byte ptr [R10 + -0x4]
00001190 8d 41 d0   lea      EAX, [RCX + -0x30]
00001193 3c 09      cmp      AL, 0x9
00001195 77 05      ja       0x0000119c
00001197 80 e9 30   sub      CL, 0x30
0000119A eb 0f      jmp      0x000011ab
0000119C 8d 41 bf   lea      EAX, [RCX + -0x41]
0000119F 3c 05      cmp      AL, 0x5
000011A1 77 05      ja       0x000011a8
000011A3 80 e9 37   sub      CL, 0x37
000011A6 eb 03      jmp      0x000011ab
000011A8 80 e9 57   sub      CL, 0x57
000011AB 80 e1 0f   and      CL, 0xf
000011AE 0f b6 d1   movzx    EDX, CL
000011B1 66 c1 e2 04 shl      DX, 0x4
000011B5 66 43 89 14 4b mov      word ptr [R11 + R9*0x2], DX
000011BA 41 8a 4a fe mov      CL, byte ptr [R10 + -0x2]
000011BE 8d 41 d0   lea      EAX, [RCX + -0x30]
000011C1 3c 09      cmp      AL, 0x9
000011C3 77 05      ja       0x000011ca
000011C5 80 e9 30   sub      CL, 0x30
000011C8 eb 0f      jmp      0x000011d9
000011CA 8d 41 bf   lea      EAX, [RCX + -0x41]
000011CD 3c 05      cmp      AL, 0x5
000011CF 77 05      ja       0x000011d6
000011D1 80 e9 37   sub      CL, 0x37
000011D4 eb 03      jmp      0x000011d9
000011D6 80 e9 57   sub      CL, 0x57
000011D9 44 0f b6 c1 movzx    R8D, CL
000011DD 66 44 0b c2 or       R8W, DX
000011E1 66 41 c1 e0 04 shl      R8W, 0x4
000011E6 66 47 89 04 4b mov      word ptr [R11 + R9*0x2], R8W
000011EB 41 8a 0a   mov      CL, byte ptr [R10]
000011EE 8d 41 d0   lea      EAX, [RCX + -0x30]
000011F1 3c 09      cmp      AL, 0x9
000011F3 77 05      ja       0x000011fa
000011F5 80 e9 30   sub      CL, 0x30
000011F8 eb 0f      jmp      0x00001209
000011FA 8d 41 bf   lea      EAX, [RCX + -0x41]
000011FD 3c 05      cmp      AL, 0x5
000011FF 77 05      ja       0x00001206
00001201 80 e9 37   sub      CL, 0x37
00001204 eb 03      jmp      0x00001209
00001206 80 e9 57   sub      CL, 0x57
00001209 0f b6 d1   movzx    EDX, CL
0000120C 66 41 0b d0 or       DX, R8W
00001210 66 c1 e2 04 shl      DX, 0x4
00001214 66 43 89 14 4b mov      word ptr [R11 + R9*0x2], DX
00001219 41 8a 4a 02 mov      CL, byte ptr [R10 + 0x2]
0000121D 8d 41 d0   lea      EAX, [RCX + -0x30]
00001220 3c 09      cmp      AL, 0x9
00001222 77 05      ja       0x00001229
00001224 80 e9 30   sub      CL, 0x30
00001227 eb 0f      jmp      0x00001238
00001229 8d 41 bf   lea      EAX, [RCX + -0x41]
0000122C 3c 05      cmp      AL, 0x5
0000122E 77 05      ja       0x00001235
00001230 80 e9 37   sub      CL, 0x37
00001233 eb 03      jmp      0x00001238
00001235 80 e9 57   sub      CL, 0x57
00001238 0f b6 c1   movzx    EAX, CL
0000123B 49 83 c2 08 add      R10, 0x8
0000123F 66 0b c2   or       AX, DX
00001242 66 43 89 04 4b mov      word ptr [R11 + R9*0x2], AX
00001247 4d 03 cf   add      R9, R15
0000124A e9 47 fe ff ff jmp      0x00001096
0000124F 4c 8b 7c 24 18 mov      R15, qword ptr [RSP + 0x18]
00001254 4c 89 0b   mov      qword ptr [RBX], R9
00001257 48 8b 5c 24 08 mov      RBX, qword ptr [RSP + 0x8]
0000125C 66 43 89 34 4b mov      word ptr [R11 + R9*0x2], SI
00001261 48 8b 74 24 10 mov      RSI, qword ptr [RSP + 0x10]
00001266 c3         ret      
