; Setup @ 0001376C   FUN_0001376c
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 0001376C.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

0001376C 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00013771 57         push     RDI
00013772 48 83 ec 20 sub      RSP, 0x20
00013776 48 8b fa   mov      RDI, RDX
00013779 48 8b d9   mov      RBX, RCX
0001377C 48 85 c9   test     RCX, RCX
0001377F 74 4c      jz       0x000137cd
00013781 48 85 d2   test     RDX, RDX
00013784 74 47      jz       0x000137cd
00013786 e8 29 a0 00 00 call     0x0001d7b4
0001378B 48 8b cf   mov      RCX, RDI
0001378E 4c 8b d8   mov      R11, RAX
00013791 e8 1e a0 00 00 call     0x0001d7b4
00013796 4c 3b d8   cmp      R11, RAX
00013799 75 32      jnz      0x000137cd
0001379B 48 8b cb   mov      RCX, RBX
0001379E e8 11 a0 00 00 call     0x0001d7b4
000137A3 4c 8b c0   mov      R8, RAX
000137A6 48 8b d7   mov      RDX, RDI
000137A9 48 8b cb   mov      RCX, RBX
000137AC e8 23 b6 00 00 call     0x0001edd4
000137B1 48 85 c0   test     RAX, RAX
000137B4 75 04      jnz      0x000137ba
000137B6 b0 01      mov      AL, 0x1
000137B8 eb 15      jmp      0x000137cf
000137BA 48 8b d7   mov      RDX, RDI
000137BD 48 8b cb   mov      RCX, RBX
000137C0 e8 eb fe ff ff call     0x000136b0
000137C5 48 85 c0   test     RAX, RAX
000137C8 0f 94 c0   setz     AL
000137CB eb 02      jmp      0x000137cf
000137CD 32 c0      xor      AL, AL
000137CF 48 8b 5c 24 30 mov      RBX, qword ptr [RSP + 0x30]
000137D4 48 83 c4 20 add      RSP, 0x20
000137D8 5f         pop      RDI
000137D9 c3         ret      
