; Setup @ 0001F958   poll_timer_port_until_target   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 0001F958.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

0001F958 48 89 5c 24 08 - - - - - - -        mov      qword ptr [RSP + 0x8], RBX
0001F95D 48 89 74 24 10 - - - - - - -        mov      qword ptr [RSP + 0x10], RSI
0001F962 57 - - - - - - - - - - -            push     RDI
0001F963 48 83 ec 20 - - - - - - - -         sub      RSP, 0x20
0001F967 8b d9 - - - - - - - - - -           mov      EBX, ECX
0001F969 8b f9 - - - - - - - - - -           mov      EDI, ECX
0001F96B c1 eb 16 - - - - - - - - -          shr      EBX, 0x16
0001F96E 81 e7 ff ff 3f 00 - - - - - -       and      EDI, 0x3fffff
0001F974 ba 08 18 00 00 - - - - - - -        mov      EDX, 0x1808
0001F979 ed - - - - - - - - - - -            in       EAX, DX
0001F97A 8b f0 - - - - - - - - - -           mov      ESI, EAX
0001F97C 81 e6 ff ff ff 00 - - - - - -       and      ESI, 0xffffff
0001F982 03 f7 - - - - - - - - - -           add      ESI, EDI
0001F984 bf 00 00 40 00 - - - - - - -        mov      EDI, 0x400000
0001F989 eb 0a - - - - - - - - - -           jmp      0x0001f995
0001F98B e8 90 0a fe ff - - - - - - -        call     0x00000420
0001F990 ba 08 18 00 00 - - - - - - -        mov      EDX, 0x1808
0001F995 ed - - - - - - - - - - -            in       EAX, DX
0001F996 8b ce - - - - - - - - - -           mov      ECX, ESI
0001F998 2b c8 - - - - - - - - - -           sub      ECX, EAX
0001F99A 0f ba e1 17 - - - - - - - -         bt       ECX, 0x17
0001F99E 73 eb - - - - - - - - - -           jnc      0x0001f98b
0001F9A0 8b c3 - - - - - - - - - -           mov      EAX, EBX
0001F9A2 ff cb - - - - - - - - - -           dec      EBX
0001F9A4 85 c0 - - - - - - - - - -           test     EAX, EAX
0001F9A6 75 cc - - - - - - - - - -           jnz      0x0001f974
0001F9A8 48 8b 5c 24 30 - - - - - - -        mov      RBX, qword ptr [RSP + 0x30]
0001F9AD 48 8b 74 24 38 - - - - - - -        mov      RSI, qword ptr [RSP + 0x38]
0001F9B2 48 83 c4 20 - - - - - - - -         add      RSP, 0x20
0001F9B6 5f - - - - - - - - - - -            pop      RDI
0001F9B7 c3 - - - - - - - - - - -            ret      
