; Setup @ 0001F454   FUN_0001f454
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 0001F454.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

0001F454 48 8b c4   mov      RAX, RSP
0001F457 48 89 58 08 mov      qword ptr [RAX + 0x8], RBX
0001F45B 48 89 68 10 mov      qword ptr [RAX + 0x10], RBP
0001F45F 48 89 70 18 mov      qword ptr [RAX + 0x18], RSI
0001F463 48 89 78 20 mov      qword ptr [RAX + 0x20], RDI
0001F467 33 f6      xor      ESI, ESI
0001F469 4d 8b d8   mov      R11, R8
0001F46C 8a da      mov      BL, DL
0001F46E 4c 8b d1   mov      R10, RCX
0001F471 48 85 c9   test     RCX, RCX
0001F474 75 04      jnz      0x0001f47a
0001F476 33 c0      xor      EAX, EAX
0001F478 eb 6d      jmp      0x0001f4e7
0001F47A 48 8b c6   mov      RAX, RSI
0001F47D 48 8b ce   mov      RCX, RSI
0001F480 bd f0 ff 00 00 mov      EBP, 0xfff0
0001F485 41 b8 01 00 00 00 mov      R8D, 0x1
0001F48B eb 1e      jmp      0x0001f4ab
0001F48D bf f1 ff 00 00 mov      EDI, 0xfff1
0001F492 66 3b d7   cmp      DX, DI
0001F495 74 1e      jz       0x0001f4b5
0001F497 66 85 d2   test     DX, DX
0001F49A 74 19      jz       0x0001f4b5
0001F49C 49 03 c8   add      RCX, R8
0001F49F 84 db      test     BL, BL
0001F4A1 74 05      jz       0x0001f4a8
0001F4A3 49 3b cb   cmp      RCX, R11
0001F4A6 77 0d      ja       0x0001f4b5
0001F4A8 48 ff c0   inc      RAX
0001F4AB 41 0f b7 14 42 movzx    EDX, word ptr [R10 + RAX*0x2]
0001F4B0 66 3b d5   cmp      DX, BP
0001F4B3 75 d8      jnz      0x0001f48d
0001F4B5 66 41 39 34 42 cmp      word ptr [R10 + RAX*0x2], SI
0001F4BA 74 27      jz       0x0001f4e3
0001F4BC 84 db      test     BL, BL
0001F4BE 74 05      jz       0x0001f4c5
0001F4C0 49 3b cb   cmp      RCX, R11
0001F4C3 77 1b      ja       0x0001f4e0
0001F4C5 66 41 39 2c 42 cmp      word ptr [R10 + RAX*0x2], BP
0001F4CA 4c 8b c6   mov      R8, RSI
0001F4CD 41 0f 95 c0 setnz    R8B
0001F4D1 49 ff c0   inc      R8
0001F4D4 48 ff c0   inc      RAX
0001F4D7 66 41 39 34 42 cmp      word ptr [R10 + RAX*0x2], SI
0001F4DC 74 05      jz       0x0001f4e3
0001F4DE eb cb      jmp      0x0001f4ab
0001F4E0 49 89 01   mov      qword ptr [R9], RAX
0001F4E3 48 8d 04 09 lea      RAX, [RCX + RCX*0x1]
0001F4E7 48 8b 5c 24 08 mov      RBX, qword ptr [RSP + 0x8]
0001F4EC 48 8b 6c 24 10 mov      RBP, qword ptr [RSP + 0x10]
0001F4F1 48 8b 74 24 18 mov      RSI, qword ptr [RSP + 0x18]
0001F4F6 48 8b 7c 24 20 mov      RDI, qword ptr [RSP + 0x20]
0001F4FB c3         ret      
