; Setup @ 0001EA50   append_wide_component_and_parse   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 0001EA50.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

0001EA50 48 8b c4 - - - - - - - - -          mov      RAX, RSP
0001EA53 48 89 58 08 - - - - - - - -         mov      qword ptr [RAX + 0x8], RBX
0001EA57 48 89 68 10 - - - - - - - -         mov      qword ptr [RAX + 0x10], RBP
0001EA5B 48 89 70 18 - - - - - - - -         mov      qword ptr [RAX + 0x18], RSI
0001EA5F 57 - - - - - - - - - - -            push     RDI
0001EA60 41 56 - - - - - - - - - -           push     R14
0001EA62 41 57 - - - - - - - - - -           push     R15
0001EA64 48 83 ec 40 - - - - - - - -         sub      RSP, 0x40
0001EA68 48 83 60 d8 00 - - - - - - -        and      qword ptr [RAX + -0x28], 0x0
0001EA6D 49 8b e9 - - - - - - - - -          mov      RBP, R9
0001EA70 48 8b 05 39 aa 00 00 - - - - -      mov      RAX, qword ptr [0x000294b0]
0001EA77 4d 8b f0 - - - - - - - - -          mov      R14, R8
0001EA7A 4c 8b fa - - - - - - - - -          mov      R15, RDX
0001EA7D 48 8b f9 - - - - - - - - -          mov      RDI, RCX
0001EA80 48 85 c0 - - - - - - - - -          test     RAX, RAX
0001EA83 75 38 - - - - - - - - - -           jnz      0x0001eabd
0001EA85 48 8b 05 0c aa 00 00 - - - - -      mov      RAX, qword ptr [0x00029498]
0001EA8C 4c 8d 05 1d aa 00 00 - - - - -      lea      R8, [0x294b0]
0001EA93 33 d2 - - - - - - - - - -           xor      EDX, EDX
0001EA95 48 8d 0d 54 68 00 00 - - - - -      lea      RCX, [0x252f0]
0001EA9C ff 90 40 01 00 00 - - - - - -       call     qword ptr [RAX + 0x140]
0001EAA2 48 85 c0 - - - - - - - - -          test     RAX, RAX
0001EAA5 79 0f - - - - - - - - - -           jns      0x0001eab6
0001EAA7 48 b8 0e 00 00 00 00 00 00 80 - -   mov      RAX, -0x7ffffffffffffff2
0001EAB1 e9 02 01 00 00 - - - - - - -        jmp      0x0001ebb8
0001EAB6 48 8b 05 f3 a9 00 00 - - - - -      mov      RAX, qword ptr [0x000294b0]
0001EABD 48 83 3d f3 a9 00 00 00 - - - -     cmp      qword ptr [0x000294b8], 0x0
0001EAC5 75 29 - - - - - - - - - -           jnz      0x0001eaf0
0001EAC7 48 8b 05 ca a9 00 00 - - - - -      mov      RAX, qword ptr [0x00029498]
0001EACE 4c 8d 05 e3 a9 00 00 - - - - -      lea      R8, [0x294b8]
0001EAD5 33 d2 - - - - - - - - - -           xor      EDX, EDX
0001EAD7 48 8d 0d 02 68 00 00 - - - - -      lea      RCX, [0x252e0]
0001EADE ff 90 40 01 00 00 - - - - - -       call     qword ptr [RAX + 0x140]
0001EAE4 48 85 c0 - - - - - - - - -          test     RAX, RAX
0001EAE7 78 be - - - - - - - - - -           js       0x0001eaa7
0001EAE9 48 8b 05 c0 a9 00 00 - - - - -      mov      RAX, qword ptr [0x000294b0]
0001EAF0 48 89 6c 24 28 - - - - - - -        mov      qword ptr [RSP + 0x28], RBP
0001EAF5 48 8d 54 24 30 - - - - - - -        lea      RDX, [RSP + 0x30]
0001EAFA 41 b1 01 - - - - - - - - -          mov      R9B, 0x1
0001EAFD 4c 89 74 24 20 - - - - - - -        mov      qword ptr [RSP + 0x20], R14
0001EB02 45 33 c0 - - - - - - - - -          xor      R8D, R8D
0001EB05 48 8b c8 - - - - - - - - -          mov      RCX, RAX
0001EB08 ff 50 08 - - - - - - - - -          call     qword ptr [RAX + 0x8]
0001EB0B 48 b9 05 00 00 00 00 00 00 80 - -   mov      RCX, -0x7ffffffffffffffb
0001EB15 48 3b c1 - - - - - - - - -          cmp      RAX, RCX
0001EB18 0f 85 9a 00 00 00 - - - - - -       jnz      0x0001ebb8
0001EB1E 48 8b 5c 24 30 - - - - - - -        mov      RBX, qword ptr [RSP + 0x30]
0001EB23 48 8d 4b 70 - - - - - - - -         lea      RCX, [RBX + 0x70]
0001EB27 e8 1c ec ff ff - - - - - - -        call     0x0001d748
0001EB2C 4c 8d 0d cd 67 00 00 - - - - -      lea      R9, [0x25300]
0001EB33 48 8b c8 - - - - - - - - -          mov      RCX, RAX
0001EB36 4c 8d 05 2b 70 00 00 - - - - -      lea      R8, [0x25b68]
0001EB3D 48 8b f0 - - - - - - - - -          mov      RSI, RAX
0001EB40 48 8d 53 70 - - - - - - - -         lea      RDX, [RBX + 0x70]
0001EB44 e8 6b f8 ff ff - - - - - - -        call     0x0001e3b4
0001EB49 4c 8b 15 60 a9 00 00 - - - - -      mov      R10, qword ptr [0x000294b0]
0001EB50 48 8d 54 24 30 - - - - - - -        lea      RDX, [RSP + 0x30]
0001EB55 48 89 6c 24 28 - - - - - - -        mov      qword ptr [RSP + 0x28], RBP
0001EB5A 41 b1 01 - - - - - - - - -          mov      R9B, 0x1
0001EB5D 49 8b ca - - - - - - - - -          mov      RCX, R10
0001EB60 4c 89 74 24 20 - - - - - - -        mov      qword ptr [RSP + 0x20], R14
0001EB65 4c 8d 04 46 - - - - - - - -         lea      R8, [RSI + RAX*0x2]
0001EB69 41 ff 52 08 - - - - - - - -         call     qword ptr [R10 + 0x8]
0001EB6D 48 8b d8 - - - - - - - - -          mov      RBX, RAX
0001EB70 48 85 c0 - - - - - - - - -          test     RAX, RAX
0001EB73 78 33 - - - - - - - - - -           js       0x0001eba8
0001EB75 48 8b 07 - - - - - - - - -          mov      RAX, qword ptr [RDI]
0001EB78 4c 8b cf - - - - - - - - -          mov      R9, RDI
0001EB7B 48 89 44 24 30 - - - - - - -        mov      qword ptr [RSP + 0x30], RAX
0001EB80 4d 8b c7 - - - - - - - - -          mov      R8, R15
0001EB83 48 8d 44 24 38 - - - - - - -        lea      RAX, [RSP + 0x38]
0001EB88 48 8b d6 - - - - - - - - -          mov      RDX, RSI
0001EB8B 48 89 44 24 20 - - - - - - -        mov      qword ptr [RSP + 0x20], RAX
0001EB90 48 8b 05 21 a9 00 00 - - - - -      mov      RAX, qword ptr [0x000294b8]
0001EB97 48 8b c8 - - - - - - - - -          mov      RCX, RAX
0001EB9A ff 50 20 - - - - - - - - -          call     qword ptr [RAX + 0x20]
0001EB9D 48 8b d8 - - - - - - - - -          mov      RBX, RAX
0001EBA0 48 8b 44 24 30 - - - - - - -        mov      RAX, qword ptr [RSP + 0x30]
0001EBA5 48 89 07 - - - - - - - - -          mov      qword ptr [RDI], RAX
0001EBA8 48 8b 05 e9 a8 00 00 - - - - -      mov      RAX, qword ptr [0x00029498]
0001EBAF 48 8b ce - - - - - - - - -          mov      RCX, RSI
0001EBB2 ff 50 48 - - - - - - - - -          call     qword ptr [RAX + 0x48]
0001EBB5 48 8b c3 - - - - - - - - -          mov      RAX, RBX
0001EBB8 48 8b 5c 24 60 - - - - - - -        mov      RBX, qword ptr [RSP + 0x60]
0001EBBD 48 8b 6c 24 68 - - - - - - -        mov      RBP, qword ptr [RSP + 0x68]
0001EBC2 48 8b 74 24 70 - - - - - - -        mov      RSI, qword ptr [RSP + 0x70]
0001EBC7 48 83 c4 40 - - - - - - - -         add      RSP, 0x40
0001EBCB 41 5f - - - - - - - - - -           pop      R15
0001EBCD 41 5e - - - - - - - - - -           pop      R14
0001EBCF 5f - - - - - - - - - - -            pop      RDI
0001EBD0 c3 - - - - - - - - - - -            ret      
