; Setup @ 0001B514   FUN_0001b514
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 0001B514.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

0001B514 48 83 ec 28 sub      RSP, 0x28
0001B518 48 8b 05 59 df 00 00 mov      RAX, qword ptr [0x00029478]
0001B51F 4c 8d 44 24 40 lea      R8, [RSP + 0x40]
0001B524 b9 04 00 00 00 mov      ECX, 0x4
0001B529 ff 50 40   call     qword ptr [RAX + 0x40]
0001B52C 48 8b 4c 24 40 mov      RCX, qword ptr [RSP + 0x40]
0001B531 33 d2      xor      EDX, EDX
0001B533 48 85 c0   test     RAX, RAX
0001B536 48 0f 48 ca cmovs    RCX, RDX
0001B53A 48 8b c1   mov      RAX, RCX
0001B53D 48 83 c4 28 add      RSP, 0x28
0001B541 c3         ret      
