; Setup @ 00018E34   FUN_00018e34
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 00018E34.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

00018E34 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00018E39 48 89 74 24 10 mov      qword ptr [RSP + 0x10], RSI
00018E3E 57         push     RDI
00018E3F 48 83 ec 50 sub      RSP, 0x50
00018E43 48 8b 05 4e 06 01 00 mov      RAX, qword ptr [0x00029498]
00018E4A 45 33 c0   xor      R8D, R8D
00018E4D 0f b7 da   movzx    EBX, DX
00018E50 48 8b f1   mov      RSI, RCX
00018E53 48 8d 4c 24 30 lea      RCX, [RSP + 0x30]
00018E58 41 0f b7 f9 movzx    EDI, R9W
00018E5C 41 8d 50 11 lea      EDX, [R8 + 0x11]
00018E60 ff 90 68 01 00 00 call     qword ptr [RAX + 0x168]
00018E66 0f b7 84 24 80 00 00 00 movzx    EAX, word ptr [RSP + 0x80]
00018E6E 48 8d 54 24 30 lea      RDX, [RSP + 0x30]
00018E73 33 c9      xor      ECX, ECX
00018E75 66 89 44 24 32 mov      word ptr [RSP + 0x32], AX
00018E7A 0f b7 84 24 88 00 00 00 movzx    EAX, word ptr [RSP + 0x88]
00018E82 41 b0 08   mov      R8B, 0x8
00018E85 88 4c 24 28 mov      byte ptr [RSP + 0x28], CL
00018E89 66 89 44 24 34 mov      word ptr [RSP + 0x34], AX
00018E8E b8 df dd 00 00 mov      EAX, 0xdddf
00018E93 48 89 4c 24 20 mov      qword ptr [RSP + 0x20], RCX
00018E98 44 8d 49 11 lea      R9D, [RCX + 0x11]
00018E9C 48 8b ce   mov      RCX, RSI
00018E9F 66 89 44 24 38 mov      word ptr [RSP + 0x38], AX
00018EA4 66 89 5c 24 36 mov      word ptr [RSP + 0x36], BX
00018EA9 66 89 7c 24 3a mov      word ptr [RSP + 0x3a], DI
00018EAE c6 44 24 3c 14 mov      byte ptr [RSP + 0x3c], 0x14
00018EB3 c7 44 24 3d 00 00 20 00 mov      dword ptr [RSP + 0x3d], 0x200000
00018EBB e8 88 88 00 00 call     0x00021748
00018EC0 48 8b 5c 24 60 mov      RBX, qword ptr [RSP + 0x60]
00018EC5 48 8b 74 24 68 mov      RSI, qword ptr [RSP + 0x68]
00018ECA 48 83 c4 50 add      RSP, 0x50
00018ECE 5f         pop      RDI
00018ECF c3         ret      
