; Setup @ 0001E448   FUN_0001e448
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 0001E448.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

0001E448 48 89 5c 24 10 mov      qword ptr [RSP + 0x10], RBX
0001E44D 48 89 6c 24 18 mov      qword ptr [RSP + 0x18], RBP
0001E452 56         push     RSI
0001E453 57         push     RDI
0001E454 41 56      push     R14
0001E456 48 83 ec 20 sub      RSP, 0x20
0001E45A 48 8b 05 37 b0 00 00 mov      RAX, qword ptr [0x00029498]
0001E461 4c 8d 44 24 40 lea      R8, [RSP + 0x40]
0001E466 45 33 f6   xor      R14D, R14D
0001E469 48 8b f1   mov      RSI, RCX
0001E46C 41 8b de   mov      EBX, R14D
0001E46F 41 8b ee   mov      EBP, R14D
0001E472 41 8d 4e 04 lea      ECX, [R14 + 0x4]
0001E476 ff 50 40   call     qword ptr [RAX + 0x40]
0001E479 0f b7 3e   movzx    EDI, word ptr [RSI]
0001E47C 66 85 ff   test     DI, DI
0001E47F 74 5c      jz       0x0001e4dd
0001E481 48 8b c6   mov      RAX, RSI
0001E484 66 83 ff 26 cmp      DI, 0x26
0001E488 75 38      jnz      0x0001e4c2
0001E48A 48 8b 15 af a5 00 00 mov      RDX, qword ptr [0x00028a40]
0001E491 48 8d 48 02 lea      RCX, [RAX + 0x2]
0001E495 41 b8 0c 00 00 00 mov      R8D, 0xc
0001E49B e8 34 09 00 00 call     0x0001edd4
0001E4A0 48 85 c0   test     RAX, RAX
0001E4A3 75 1d      jnz      0x0001e4c2
0001E4A5 eb 05      jmp      0x0001e4ac
0001E4A7 66 85 c0   test     AX, AX
0001E4AA 74 0d      jz       0x0001e4b9
0001E4AC 48 ff c3   inc      RBX
0001E4AF 0f b7 04 5e movzx    EAX, word ptr [RSI + RBX*0x2]
0001E4B3 66 83 f8 26 cmp      AX, 0x26
0001E4B7 75 ee      jnz      0x0001e4a7
0001E4B9 0f b7 3c 5e movzx    EDI, word ptr [RSI + RBX*0x2]
0001E4BD 66 85 ff   test     DI, DI
0001E4C0 74 1b      jz       0x0001e4dd
0001E4C2 48 8b 44 24 40 mov      RAX, qword ptr [RSP + 0x40]
0001E4C7 48 ff c3   inc      RBX
0001E4CA 66 89 3c 68 mov      word ptr [RAX + RBP*0x2], DI
0001E4CE 48 8d 04 5e lea      RAX, [RSI + RBX*0x2]
0001E4D2 0f b7 38   movzx    EDI, word ptr [RAX]
0001E4D5 48 ff c5   inc      RBP
0001E4D8 66 85 ff   test     DI, DI
0001E4DB 75 a7      jnz      0x0001e484
0001E4DD 48 8b 44 24 40 mov      RAX, qword ptr [RSP + 0x40]
0001E4E2 4c 8d 04 6d 02 00 00 00 lea      R8, [0x2 + RBP*0x2]
0001E4EA 48 8b ce   mov      RCX, RSI
0001E4ED 66 44 89 34 68 mov      word ptr [RAX + RBP*0x2], R14W
0001E4F2 48 8b 54 24 40 mov      RDX, qword ptr [RSP + 0x40]
0001E4F7 e8 d4 4e 00 00 call     0x000233d0
0001E4FC 48 8b 05 95 af 00 00 mov      RAX, qword ptr [0x00029498]
0001E503 48 8b 4c 24 40 mov      RCX, qword ptr [RSP + 0x40]
0001E508 ff 50 48   call     qword ptr [RAX + 0x48]
0001E50B 48 8b 5c 24 48 mov      RBX, qword ptr [RSP + 0x48]
0001E510 48 8b 6c 24 50 mov      RBP, qword ptr [RSP + 0x50]
0001E515 48 83 c4 20 add      RSP, 0x20
0001E519 41 5e      pop      R14
0001E51B 5f         pop      RDI
0001E51C 5e         pop      RSI
0001E51D c3         ret      
