; Setup @ 000216BC   free_byte_buffer_context   [named]
; Ghidra 12.1.3 disassembly, generated by bios/tools/bios_extract.py -- do not edit.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, Setup.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e
; This is the machine code. The decompiled C for this address is 000216BC.c in the same tree;
; where the two disagree, this file is right and the C is a reading of it.

000216BC 40 53 - - - - - - - - - -           push     RBX
000216BE 48 83 ec 20 - - - - - - - -         sub      RSP, 0x20
000216C2 48 8b d9 - - - - - - - - -          mov      RBX, RCX
000216C5 48 8b 09 - - - - - - - - -          mov      RCX, qword ptr [RCX]
000216C8 48 85 c9 - - - - - - - - -          test     RCX, RCX
000216CB 74 0a - - - - - - - - - -           jz       0x000216d7
000216CD 48 8b 05 a4 7d 00 00 - - - - -      mov      RAX, qword ptr [0x00029478]
000216D4 ff 50 48 - - - - - - - - -          call     qword ptr [RAX + 0x48]
000216D7 48 8b 05 9a 7d 00 00 - - - - -      mov      RAX, qword ptr [0x00029478]
000216DE 48 8b cb - - - - - - - - -          mov      RCX, RBX
000216E1 48 83 c4 20 - - - - - - - -         add      RSP, 0x20
000216E5 5b - - - - - - - - - - -            pop      RBX
000216E6 48 ff 60 48 - - - - - - - -         jmp      qword ptr [RAX + 0x48]
