; OemGlobalNvsSmm: Ghidra 12.1.3 disassembly
; Generated by bios/tools/bios_extract.py -- do not edit. This is the machine code the decompiled C reads from.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemGlobalNvsSmm.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e

; ==== save_cpu_context_to_frame @ 00001000
00001000 51 - - - - - - - - -          push     RCX
00001001 48 83 c4 e0 - - - - - -       add      RSP, -0x20
00001005 e8 d2 04 00 00 - - - - -      call     0x000014dc
0000100A 48 83 c4 20 - - - - - -       add      RSP, 0x20
0000100E 59 - - - - - - - - -          pop      RCX
0000100F 5a - - - - - - - - -          pop      RDX
00001010 48 31 c0 - - - - - - -        xor      RAX, RAX
00001013 48 89 81 f8 00 00 00 - - -    mov      qword ptr [RCX + 0xf8], RAX
0000101A 8b 05 50 10 00 00 - - - -     mov      EAX, dword ptr [0x00002070]
00001020 85 c0 - - - - - - - -         test     EAX, EAX
00001022 74 1f - - - - - - - -         jz       0x00001043
00001024 0f 20 e0 - - - - - - -        mov      RAX, CR4
00001027 0f ba e0 17 - - - - - -       bt       EAX, 0x17
0000102B 73 16 - - - - - - - -         jnc      0x00001043
0000102D b8 01 00 00 00 - - - - -      mov      EAX, 0x1
00001032 f3 48 0f ae e8 - - - - -      incsspq  RAX
00001037 f3 48 0f 1e c8 - - - - -      rdsspq   RAX
0000103C 48 89 81 f8 00 00 00 - - -    mov      qword ptr [RCX + 0xf8], RAX
00001043 48 89 19 - - - - - - -        mov      qword ptr [RCX], RBX
00001046 48 89 61 08 - - - - - -       mov      qword ptr [RCX + 0x8], RSP
0000104A 48 89 69 10 - - - - - -       mov      qword ptr [RCX + 0x10], RBP
0000104E 48 89 79 18 - - - - - -       mov      qword ptr [RCX + 0x18], RDI
00001052 48 89 71 20 - - - - - -       mov      qword ptr [RCX + 0x20], RSI
00001056 4c 89 61 28 - - - - - -       mov      qword ptr [RCX + 0x28], R12
0000105A 4c 89 69 30 - - - - - -       mov      qword ptr [RCX + 0x30], R13
0000105E 4c 89 71 38 - - - - - -       mov      qword ptr [RCX + 0x38], R14
00001062 4c 89 79 40 - - - - - -       mov      qword ptr [RCX + 0x40], R15
00001066 48 89 51 48 - - - - - -       mov      qword ptr [RCX + 0x48], RDX
0000106A 0f ae 59 50 - - - - - -       stmxcsr  dword ptr [RCX + 0x50]
0000106E f3 0f 7f 71 58 - - - - -      movdqu   xmmword ptr [RCX + 0x58], XMM6
00001073 f3 0f 7f 79 68 - - - - -      movdqu   xmmword ptr [RCX + 0x68], XMM7
00001078 f3 44 0f 7f 41 78 - - - -     movdqu   xmmword ptr [RCX + 0x78], XMM8
0000107E f3 44 0f 7f 89 88 00 00 00 -  movdqu   xmmword ptr [RCX + 0x88], XMM9
00001087 f3 44 0f 7f 91 98 00 00 00 -  movdqu   xmmword ptr [RCX + 0x98], XMM10
00001090 f3 44 0f 7f 99 a8 00 00 00 -  movdqu   xmmword ptr [RCX + 0xa8], XMM11
00001099 f3 44 0f 7f a1 b8 00 00 00 -  movdqu   xmmword ptr [RCX + 0xb8], XMM12
000010A2 f3 44 0f 7f a9 c8 00 00 00 -  movdqu   xmmword ptr [RCX + 0xc8], XMM13
000010AB f3 44 0f 7f b1 d8 00 00 00 -  movdqu   xmmword ptr [RCX + 0xd8], XMM14
000010B4 f3 44 0f 7f b9 e8 00 00 00 -  movdqu   xmmword ptr [RCX + 0xe8], XMM15
000010BD 48 31 c0 - - - - - - -        xor      RAX, RAX
000010C0 ff e2 - - - - - - - -         jmp      RDX

; ==== restore_cpu_context_from_frame @ 000010D0
000010D0 8b 05 9a 0f 00 00 - - - -     mov      EAX, dword ptr [0x00002070]
000010D6 85 c0 - - - - - - - -         test     EAX, EAX
000010D8 74 26 - - - - - - - -         jz       0x00001100
000010DA 0f 20 e0 - - - - - - -        mov      RAX, CR4
000010DD 0f ba e0 17 - - - - - -       bt       EAX, 0x17
000010E1 73 1d - - - - - - - -         jnc      0x00001100
000010E3 52 - - - - - - - - -          push     RDX
000010E4 48 8b 91 f8 00 00 00 - - -    mov      RDX, qword ptr [RCX + 0xf8]
000010EB f3 48 0f 1e c8 - - - - -      rdsspq   RAX
000010F0 48 29 c2 - - - - - - -        sub      RDX, RAX
000010F3 48 89 d0 - - - - - - -        mov      RAX, RDX
000010F6 48 c1 e8 03 - - - - - -       shr      RAX, 0x3
000010FA f3 48 0f ae e8 - - - - -      incsspq  RAX
000010FF 5a - - - - - - - - -          pop      RDX
00001100 48 8b 19 - - - - - - -        mov      RBX, qword ptr [RCX]
00001103 48 8b 61 08 - - - - - -       mov      RSP, qword ptr [RCX + 0x8]
00001107 48 8b 69 10 - - - - - -       mov      RBP, qword ptr [RCX + 0x10]
0000110B 48 8b 79 18 - - - - - -       mov      RDI, qword ptr [RCX + 0x18]
0000110F 48 8b 71 20 - - - - - -       mov      RSI, qword ptr [RCX + 0x20]
00001113 4c 8b 61 28 - - - - - -       mov      R12, qword ptr [RCX + 0x28]
00001117 4c 8b 69 30 - - - - - -       mov      R13, qword ptr [RCX + 0x30]
0000111B 4c 8b 71 38 - - - - - -       mov      R14, qword ptr [RCX + 0x38]
0000111F 4c 8b 79 40 - - - - - -       mov      R15, qword ptr [RCX + 0x40]
00001123 0f ae 51 50 - - - - - -       ldmxcsr  dword ptr [RCX + 0x50]
00001127 f3 0f 6f 71 58 - - - - -      movdqu   XMM6, xmmword ptr [RCX + 0x58]
0000112C f3 0f 6f 79 68 - - - - -      movdqu   XMM7, xmmword ptr [RCX + 0x68]
00001131 f3 44 0f 6f 41 78 - - - -     movdqu   XMM8, xmmword ptr [RCX + 0x78]
00001137 f3 44 0f 6f 89 88 00 00 00 -  movdqu   XMM9, xmmword ptr [RCX + 0x88]
00001140 f3 44 0f 6f 91 98 00 00 00 -  movdqu   XMM10, xmmword ptr [RCX + 0x98]
00001149 f3 44 0f 6f 99 a8 00 00 00 -  movdqu   XMM11, xmmword ptr [RCX + 0xa8]
00001152 f3 44 0f 6f a1 b8 00 00 00 -  movdqu   XMM12, xmmword ptr [RCX + 0xb8]
0000115B f3 44 0f 6f a9 c8 00 00 00 -  movdqu   XMM13, xmmword ptr [RCX + 0xc8]
00001164 f3 44 0f 6f b1 d8 00 00 00 -  movdqu   XMM14, xmmword ptr [RCX + 0xd8]
0000116D f3 44 0f 6f b9 e8 00 00 00 -  movdqu   XMM15, xmmword ptr [RCX + 0xe8]
00001176 48 89 d0 - - - - - - -        mov      RAX, RDX
00001179 ff 61 48 - - - - - - -        jmp      qword ptr [RCX + 0x48]

; ==== memmove @ 00001180
00001180 56 - - - - - - - - -          push     RSI
00001181 57 - - - - - - - - -          push     RDI
00001182 48 89 d6 - - - - - - -        mov      RSI, RDX
00001185 48 89 cf - - - - - - -        mov      RDI, RCX
00001188 4e 8d 4c 06 ff - - - - -      lea      R9, [RSI + R8*0x1 + -0x1]
0000118D 48 39 fe - - - - - - -        cmp      RSI, RDI
00001190 48 89 f8 - - - - - - -        mov      RAX, RDI
00001193 73 05 - - - - - - - -         jnc      0x0000119a
00001195 49 39 f9 - - - - - - -        cmp      R9, RDI
00001198 73 10 - - - - - - - -         jnc      0x000011aa
0000119A 4c 89 c1 - - - - - - -        mov      RCX, R8
0000119D 49 83 e0 07 - - - - - -       and      R8, 0x7
000011A1 48 c1 e9 03 - - - - - -       shr      RCX, 0x3
000011A5 f3 48 a5 - - - - - - -        movsq.rep RDI, RSI
000011A8 eb 09 - - - - - - - -         jmp      0x000011b3
000011AA 4c 89 ce - - - - - - -        mov      RSI, R9
000011AD 4a 8d 7c 07 ff - - - - -      lea      RDI, [RDI + R8*0x1 + -0x1]
000011B2 fd - - - - - - - - -          std      
000011B3 4c 89 c1 - - - - - - -        mov      RCX, R8
000011B6 f3 a4 - - - - - - - -         movsb.rep RDI, RSI
000011B8 fc - - - - - - - - -          cld      
000011B9 5f - - - - - - - - -          pop      RDI
000011BA 5e - - - - - - - - -          pop      RSI
000011BB c3 - - - - - - - - -          ret      

; ==== cpu_pause @ 000011C0
000011C0 f3 90 - - - - - - - -         pause    
000011C2 c3 - - - - - - - - -          ret      

; ==== read_tsc_64bit @ 000011D0
000011D0 0f 31 - - - - - - - -         rdtsc    
000011D2 48 c1 e2 20 - - - - - -       shl      RDX, 0x20
000011D6 48 09 d0 - - - - - - -        or       RAX, RDX
000011D9 c3 - - - - - - - - -          ret      

; ==== enable_interrupts @ 000011E0
000011E0 fb - - - - - - - - -          sti      
000011E1 c3 - - - - - - - - -          ret      

; ==== disable_interrupts @ 000011F0
000011F0 fa - - - - - - - - -          cli      
000011F1 c3 - - - - - - - - -          ret      

; ==== read_rflags @ 00001200
00001200 9c - - - - - - - - -          pushfq   
00001201 58 - - - - - - - - -          pop      RAX
00001202 c3 - - - - - - - - -          ret      

; ==== smm_entry_save_context_and_register_handler @ 00001230
00001230 40 53 - - - - - - - -         push     RBX
00001232 48 83 ec 20 - - - - - -       sub      RSP, 0x20
00001236 e8 a9 00 00 00 - - - - -      call     0x000012e4
0000123B 48 b8 01 00 00 00 00 00 00 80 mov      RAX, -0x7fffffffffffffff
00001245 48 8d 0d 94 0e 00 00 - - -    lea      RCX, [0x20e0]
0000124C 48 89 05 8d 0f 00 00 - - -    mov      qword ptr [0x000021e0], RAX
00001253 e8 a8 fd ff ff - - - - -      call     0x00001000
00001258 48 85 c0 - - - - - - -        test     RAX, RAX
0000125B 75 6a - - - - - - - -         jnz      0x000012c7
0000125D 48 21 44 24 48 - - - - -      and      qword ptr [RSP + 0x48], RAX
00001262 4c 8d 44 24 40 - - - - -      lea      R8, [RSP + 0x40]
00001267 48 8b 05 3a 0e 00 00 - - -    mov      RAX, qword ptr [0x000020a8]
0000126E 48 8d 0d 8b 0d 00 00 - - -    lea      RCX, [0x2000]
00001275 33 d2 - - - - - - - -         xor      EDX, EDX
00001277 ff 90 40 01 00 00 - - - -     call     qword ptr [RAX + 0x140]
0000127D 48 8b 4c 24 40 - - - - -      mov      RCX, qword ptr [RSP + 0x40]
00001282 ba 08 00 00 00 - - - - -      mov      EDX, 0x8
00001287 e8 54 02 00 00 - - - - -      call     0x000014e0
0000128C 48 8b 05 1d 0e 00 00 - - -    mov      RAX, qword ptr [0x000020b0]
00001293 4c 8d 0d 5e 0f 00 00 - - -    lea      R9, [0x21f8]
0000129A 45 33 c0 - - - - - - -        xor      R8D, R8D
0000129D 48 8d 15 9c 0d 00 00 - - -    lea      RDX, [0x2040]
000012A4 48 8d 4c 24 48 - - - - -      lea      RCX, [RSP + 0x48]
000012A9 ff 90 a8 00 00 00 - - - -     call     qword ptr [RAX + 0xa8]
000012AF 48 83 25 29 0f 00 00 00 - -   and      qword ptr [0x000021e0], 0x0
000012B7 48 8d 0d 22 0e 00 00 - - -    lea      RCX, [0x20e0]
000012BE 48 83 ca ff - - - - - -       or       RDX, -0x1
000012C2 e8 09 fe ff ff - - - - -      call     0x000010d0
000012C7 48 8b 1d 12 0f 00 00 - - -    mov      RBX, qword ptr [0x000021e0]
000012CE 48 85 db - - - - - - -        test     RBX, RBX
000012D1 79 05 - - - - - - - -         jns      0x000012d8
000012D3 e8 a0 02 00 00 - - - - -      call     0x00001578
000012D8 48 8b c3 - - - - - - -        mov      RAX, RBX
000012DB 48 83 c4 20 - - - - - -       add      RSP, 0x20
000012DF 5b - - - - - - - - -          pop      RBX
000012E0 c3 - - - - - - - - -          ret      

; ==== FUN_000012e4 @ 000012E4
000012E4 4c 8b dc - - - - - - -        mov      R11, RSP
000012E7 49 89 5b 20 - - - - - -       mov      qword ptr [R11 + 0x20], RBX
000012EB 49 89 4b 08 - - - - - -       mov      qword ptr [R11 + 0x8], RCX
000012EF 57 - - - - - - - - -          push     RDI
000012F0 48 83 ec 20 - - - - - -       sub      RSP, 0x20
000012F4 48 8b 42 60 - - - - - -       mov      RAX, qword ptr [RDX + 0x60]
000012F8 4d 8d 43 10 - - - - - -       lea      R8, [R11 + 0x10]
000012FC 49 83 63 10 00 - - - - -      and      qword ptr [R11 + 0x10], 0x0
00001301 48 8d 0d 28 0d 00 00 - - -    lea      RCX, [0x2030]
00001308 48 89 15 91 0d 00 00 - - -    mov      qword ptr [0x000020a0], RDX
0000130F 33 d2 - - - - - - - -         xor      EDX, EDX
00001311 48 89 05 90 0d 00 00 - - -    mov      qword ptr [0x000020a8], RAX
00001318 ff 90 40 01 00 00 - - - -     call     qword ptr [RAX + 0x140]
0000131E 48 8b 44 24 38 - - - - -      mov      RAX, qword ptr [RSP + 0x38]
00001323 48 8d 15 86 0d 00 00 - - -    lea      RDX, [0x20b0]
0000132A 48 8b c8 - - - - - - -        mov      RCX, RAX
0000132D ff 50 08 - - - - - - -        call     qword ptr [RAX + 0x8]
00001330 b8 00 00 00 e0 - - - - -      mov      EAX, 0xe0000000
00001335 c6 05 7c 0d 00 00 01 - - -    mov      byte ptr [0x000020b8], 0x1
0000133C 48 89 05 7d 0d 00 00 - - -    mov      qword ptr [0x000020c0], RAX
00001343 4c 8d 44 24 40 - - - - -      lea      R8, [RSP + 0x40]
00001348 48 8b 05 59 0d 00 00 - - -    mov      RAX, qword ptr [0x000020a8]
0000134F 48 8d 0d fa 0c 00 00 - - -    lea      RCX, [0x2050]
00001356 33 d2 - - - - - - - -         xor      EDX, EDX
00001358 ff 90 40 01 00 00 - - - -     call     qword ptr [RAX + 0x140]
0000135E 48 8b 44 24 40 - - - - -      mov      RAX, qword ptr [RSP + 0x40]
00001363 48 8d 54 24 30 - - - - -      lea      RDX, [RSP + 0x30]
00001368 48 83 64 24 30 00 - - - -     and      qword ptr [RSP + 0x30], 0x0
0000136E 45 33 c0 - - - - - - -        xor      R8D, R8D
00001371 48 8b c8 - - - - - - -        mov      RCX, RAX
00001374 ff 50 18 - - - - - - -        call     qword ptr [RAX + 0x18]
00001377 48 8b 54 24 30 - - - - -      mov      RDX, qword ptr [RSP + 0x30]
0000137C e8 c7 01 00 00 - - - - -      call     0x00001548
00001381 48 89 05 68 0e 00 00 - - -    mov      qword ptr [0x000021f0], RAX
00001388 48 8d 54 24 30 - - - - -      lea      RDX, [RSP + 0x30]
0000138D 4c 8b c0 - - - - - - -        mov      R8, RAX
00001390 48 8b 44 24 40 - - - - -      mov      RAX, qword ptr [RSP + 0x40]
00001395 48 8b c8 - - - - - - -        mov      RCX, RAX
00001398 ff 50 18 - - - - - - -        call     qword ptr [RAX + 0x18]
0000139B 48 8b 44 24 30 - - - - -      mov      RAX, qword ptr [RSP + 0x30]
000013A0 48 c1 e8 05 - - - - - -       shr      RAX, 0x5
000013A4 48 89 05 3d 0e 00 00 - - -    mov      qword ptr [0x000021e8], RAX
000013AB e8 04 02 00 00 - - - - -      call     0x000015b4
000013B0 e8 ff 01 00 00 - - - - -      call     0x000015b4
000013B5 48 8b 15 ac 0c 00 00 - - -    mov      RDX, qword ptr [0x00002068]
000013BC 41 b9 ff ff 00 00 - - - -     mov      R9D, 0xffff
000013C2 4c 8b 05 97 0c 00 00 - - -    mov      R8, qword ptr [0x00002060]
000013C9 eb 0d - - - - - - - -         jmp      0x000013d8
000013CB 66 83 f9 04 - - - - - -       cmp      CX, 0x4
000013CF 74 12 - - - - - - - -         jz       0x000013e3
000013D1 0f b7 48 02 - - - - - -       movzx    ECX, word ptr [RAX + 0x2]
000013D5 48 03 c1 - - - - - - -        add      RAX, RCX
000013D8 0f b7 08 - - - - - - -        movzx    ECX, word ptr [RAX]
000013DB 66 41 3b c9 - - - - - -       cmp      CX, R9W
000013DF 75 ea - - - - - - - -         jnz      0x000013cb
000013E1 33 c0 - - - - - - - -         xor      EAX, EAX
000013E3 48 85 c0 - - - - - - -        test     RAX, RAX
000013E6 74 0e - - - - - - - -         jz       0x000013f6
000013E8 4c 3b 40 08 - - - - - -       cmp      R8, qword ptr [RAX + 0x8]
000013EC 75 e3 - - - - - - - -         jnz      0x000013d1
000013EE 48 3b 50 10 - - - - - -       cmp      RDX, qword ptr [RAX + 0x10]
000013F2 74 58 - - - - - - - -         jz       0x0000144c
000013F4 eb db - - - - - - - -         jmp      0x000013d1
000013F6 e8 05 fe ff ff - - - - -      call     0x00001200
000013FB 48 8b d8 - - - - - - -        mov      RBX, RAX
000013FE e8 ed fd ff ff - - - - -      call     0x000011f0
00001403 c1 eb 09 - - - - - - -        shr      EBX, 0x9
00001406 80 e3 01 - - - - - - -        and      BL, 0x1
00001409 ba 08 18 00 00 - - - - -      mov      EDX, 0x1808
0000140E ed - - - - - - - - -          in       EAX, DX
0000140F 8b f8 - - - - - - - -         mov      EDI, EAX
00001411 81 e7 ff ff ff 00 - - - -     and      EDI, 0xffffff
00001417 e8 b4 fd ff ff - - - - -      call     0x000011d0
0000141C eb 05 - - - - - - - -         jmp      0x00001423
0000141E e8 9d fd ff ff - - - - -      call     0x000011c0
00001423 ba 08 18 00 00 - - - - -      mov      EDX, 0x1808
00001428 8d 8f 6b 01 00 00 - - - -     lea      ECX, [RDI + 0x16b]
0000142E ed - - - - - - - - -          in       EAX, DX
0000142F 2b c8 - - - - - - - -         sub      ECX, EAX
00001431 0f ba e1 17 - - - - - -       bt       ECX, 0x17
00001435 73 e7 - - - - - - - -         jnc      0x0000141e
00001437 e8 94 fd ff ff - - - - -      call     0x000011d0
0000143C 84 db - - - - - - - -         test     BL, BL
0000143E 74 07 - - - - - - - -         jz       0x00001447
00001440 e8 9b fd ff ff - - - - -      call     0x000011e0
00001445 eb 05 - - - - - - - -         jmp      0x0000144c
00001447 e8 a4 fd ff ff - - - - -      call     0x000011f0
0000144C 48 8b 05 5d 0c 00 00 - - -    mov      RAX, qword ptr [0x000020b0]
00001453 45 33 c0 - - - - - - -        xor      R8D, R8D
00001456 4c 8b 88 98 00 00 00 - - -    mov      R9, qword ptr [RAX + 0x98]
0000145D 48 8b 90 a0 00 00 00 - - -    mov      RDX, qword ptr [RAX + 0xa0]
00001464 4d 85 c9 - - - - - - -        test     R9, R9
00001467 74 25 - - - - - - - -         jz       0x0000148e
00001469 48 8b 05 a8 0b 00 00 - - -    mov      RAX, qword ptr [0x00002018]
00001470 4c 8b 15 99 0b 00 00 - - -    mov      R10, qword ptr [0x00002010]
00001477 4c 3b 12 - - - - - - -        cmp      R10, qword ptr [RDX]
0000147A 75 06 - - - - - - - -         jnz      0x00001482
0000147C 48 3b 42 08 - - - - - -       cmp      RAX, qword ptr [RDX + 0x8]
00001480 74 0c - - - - - - - -         jz       0x0000148e
00001482 49 ff c0 - - - - - - -        inc      R8
00001485 48 83 c2 18 - - - - - -       add      RDX, 0x18
00001489 4d 3b c1 - - - - - - -        cmp      R8, R9
0000148C 72 e9 - - - - - - - -         jc       0x00001477
0000148E 48 8b 05 3b 0c 00 00 - - -    mov      RAX, qword ptr [0x000020d0]
00001495 48 85 c0 - - - - - - -        test     RAX, RAX
00001498 75 29 - - - - - - - -         jnz      0x000014c3
0000149A 48 8b 05 07 0c 00 00 - - -    mov      RAX, qword ptr [0x000020a8]
000014A1 4c 8d 05 28 0c 00 00 - - -    lea      R8, [0x20d0]
000014A8 33 d2 - - - - - - - -         xor      EDX, EDX
000014AA 48 8d 0d 7f 0b 00 00 - - -    lea      RCX, [0x2030]
000014B1 ff 90 40 01 00 00 - - - -     call     qword ptr [RAX + 0x140]
000014B7 48 85 c0 - - - - - - -        test     RAX, RAX
000014BA 78 13 - - - - - - - -         js       0x000014cf
000014BC 48 8b 05 0d 0c 00 00 - - -    mov      RAX, qword ptr [0x000020d0]
000014C3 48 8d 15 0e 0c 00 00 - - -    lea      RDX, [0x20d8]
000014CA 48 8b c8 - - - - - - -        mov      RCX, RAX
000014CD ff 10 - - - - - - - -         call     qword ptr [RAX]
000014CF 48 8b 5c 24 48 - - - - -      mov      RBX, qword ptr [RSP + 0x48]
000014D4 48 83 c4 20 - - - - - -       add      RSP, 0x20
000014D8 5f - - - - - - - - -          pop      RDI
000014D9 c3 - - - - - - - - -          ret      

; ==== ret_stub @ 000014DC
000014DC c2 00 00 - - - - - - -        ret      0x0

; ==== copy_to_global_0x21f8 @ 000014E0
000014E0 48 83 ec 28 - - - - - -       sub      RSP, 0x28
000014E4 48 8d 05 0d 0d 00 00 - - -    lea      RAX, [0x21f8]
000014EB 48 3b c1 - - - - - - -        cmp      RAX, RCX
000014EE 74 0e - - - - - - - -         jz       0x000014fe
000014F0 4c 8b c2 - - - - - - -        mov      R8, RDX
000014F3 48 8b d1 - - - - - - -        mov      RDX, RCX
000014F6 48 8b c8 - - - - - - -        mov      RCX, RAX
000014F9 e8 82 fc ff ff - - - - -      call     0x00001180
000014FE 48 83 c4 28 - - - - - -       add      RSP, 0x28
00001502 c3 - - - - - - - - -          ret      

; ==== FUN_00001504 @ 00001504
00001504 4c 8b 0d dd 0c 00 00 - - -    mov      R9, qword ptr [0x000021e8]
0000150B 33 d2 - - - - - - - -         xor      EDX, EDX
0000150D 4c 8b d9 - - - - - - -        mov      R11, RCX
00001510 4d 85 c9 - - - - - - -        test     R9, R9
00001513 74 2c - - - - - - - -         jz       0x00001541
00001515 48 8b 05 d4 0c 00 00 - - -    mov      RAX, qword ptr [0x000021f0]
0000151C 4c 8d 40 08 - - - - - -       lea      R8, [RAX + 0x8]
00001520 4d 8b 10 - - - - - - -        mov      R10, qword ptr [R8]
00001523 4d 3b da - - - - - - -        cmp      R11, R10
00001526 72 0d - - - - - - - -         jc       0x00001535
00001528 49 8b 40 08 - - - - - -       mov      RAX, qword ptr [R8 + 0x8]
0000152C 49 8d 0c 02 - - - - - -       lea      RCX, [R10 + RAX*0x1]
00001530 4c 3b d9 - - - - - - -        cmp      R11, RCX
00001533 72 0f - - - - - - - -         jc       0x00001544
00001535 48 ff c2 - - - - - - -        inc      RDX
00001538 49 83 c0 20 - - - - - -       add      R8, 0x20
0000153C 49 3b d1 - - - - - - -        cmp      RDX, R9
0000153F 72 df - - - - - - - -         jc       0x00001520
00001541 32 c0 - - - - - - - -         xor      AL, AL
00001543 c3 - - - - - - - - -          ret      
00001544 b0 01 - - - - - - - -         mov      AL, 0x1
00001546 c3 - - - - - - - - -          ret      

; ==== query_interface_via_offset_0x50 @ 00001548
00001548 48 83 ec 28 - - - - - -       sub      RSP, 0x28
0000154C 48 8b 05 5d 0b 00 00 - - -    mov      RAX, qword ptr [0x000020b0]
00001553 4c 8d 44 24 40 - - - - -      lea      R8, [RSP + 0x40]
00001558 b9 06 00 00 00 - - - - -      mov      ECX, 0x6
0000155D ff 50 50 - - - - - - -        call     qword ptr [RAX + 0x50]
00001560 48 8b 4c 24 40 - - - - -      mov      RCX, qword ptr [RSP + 0x40]
00001565 33 d2 - - - - - - - -         xor      EDX, EDX
00001567 48 85 c0 - - - - - - -        test     RAX, RAX
0000156A 48 0f 48 ca - - - - - -       cmovs    RCX, RDX
0000156E 48 8b c1 - - - - - - -        mov      RAX, RCX
00001571 48 83 c4 28 - - - - - -       add      RSP, 0x28
00001575 c3 - - - - - - - - -          ret      

; ==== forward_by_range_test @ 00001578
00001578 48 83 ec 28 - - - - - -       sub      RSP, 0x28
0000157C 48 8b 0d 6d 0c 00 00 - - -    mov      RCX, qword ptr [0x000021f0]
00001583 e8 7c ff ff ff - - - - -      call     0x00001504
00001588 48 8b 0d 61 0c 00 00 - - -    mov      RCX, qword ptr [0x000021f0]
0000158F 84 c0 - - - - - - - -         test     AL, AL
00001591 74 0f - - - - - - - -         jz       0x000015a2
00001593 48 8b 05 16 0b 00 00 - - -    mov      RAX, qword ptr [0x000020b0]
0000159A 48 83 c4 28 - - - - - -       add      RSP, 0x28
0000159E 48 ff 60 58 - - - - - -       jmp      qword ptr [RAX + 0x58]
000015A2 48 8b 05 ff 0a 00 00 - - -    mov      RAX, qword ptr [0x000020a8]
000015A9 48 83 c4 28 - - - - - -       add      RSP, 0x28
000015AD 48 ff 60 48 - - - - - -       jmp      qword ptr [RAX + 0x48]

; ==== find_cached_entry_by_16_byte_key @ 000015B4
000015B4 48 8b 0d 0d 0b 00 00 - - -    mov      RCX, qword ptr [0x000020c8]
000015BB 33 c0 - - - - - - - -         xor      EAX, EAX
000015BD 48 85 c9 - - - - - - -        test     RCX, RCX
000015C0 75 57 - - - - - - - -         jnz      0x00001619
000015C2 48 8b 15 d7 0a 00 00 - - -    mov      RDX, qword ptr [0x000020a0]
000015C9 8b c8 - - - - - - - -         mov      ECX, EAX
000015CB 48 89 05 f6 0a 00 00 - - -    mov      qword ptr [0x000020c8], RAX
000015D2 4c 8b 42 68 - - - - - -       mov      R8, qword ptr [RDX + 0x68]
000015D6 4d 85 c0 - - - - - - -        test     R8, R8
000015D9 74 3e - - - - - - - -         jz       0x00001619
000015DB 4c 8b 4a 70 - - - - - -       mov      R9, qword ptr [RDX + 0x70]
000015DF 4c 8b 15 42 0a 00 00 - - -    mov      R10, qword ptr [0x00002028]
000015E6 49 8b d1 - - - - - - -        mov      RDX, R9
000015E9 4c 8b 1d 30 0a 00 00 - - -    mov      R11, qword ptr [0x00002020]
000015F0 4c 3b 1a - - - - - - -        cmp      R11, qword ptr [RDX]
000015F3 75 06 - - - - - - - -         jnz      0x000015fb
000015F5 4c 3b 52 08 - - - - - -       cmp      R10, qword ptr [RDX + 0x8]
000015F9 74 0e - - - - - - - -         jz       0x00001609
000015FB 48 ff c0 - - - - - - -        inc      RAX
000015FE 48 83 c2 18 - - - - - -       add      RDX, 0x18
00001602 49 3b c0 - - - - - - -        cmp      RAX, R8
00001605 73 12 - - - - - - - -         jnc      0x00001619
00001607 eb e7 - - - - - - - -         jmp      0x000015f0
00001609 48 8d 04 40 - - - - - -       lea      RAX, [RAX + RAX*0x2]
0000160D 49 8b 4c c1 10 - - - - -      mov      RCX, qword ptr [R9 + RAX*0x8 + 0x10]
00001612 48 89 0d af 0a 00 00 - - -    mov      qword ptr [0x000020c8], RCX
00001619 48 8b c1 - - - - - - -        mov      RAX, RCX
0000161C c3 - - - - - - - - -          ret      

