; OemHooks: Ghidra 12.1.3 disassembly
; Generated by bios/tools/bios_extract.py -- do not edit. This is the machine code the decompiled C reads from.
; Source: GM7MG7P/GMxMGxxN109A08.ROM, OemHooks.efi (PE32 body, RVA space), SHA-256 dfe8047f35bb1125bbb45d69c96ad83d64e59dd5e50b8d88052c0db04a2d920e

; ==== FUN_00000260 @ 00000260
00000260 f3 90      pause    
00000262 c3         ret      

; ==== FUN_00000270 @ 00000270
00000270 0f 31      rdtsc    
00000272 48 c1 e2 20 shl      RDX, 0x20
00000276 48 09 d0   or       RAX, RDX
00000279 c3         ret      

; ==== FUN_00000280 @ 00000280
00000280 fb         sti      
00000281 c3         ret      

; ==== FUN_00000290 @ 00000290
00000290 fa         cli      
00000291 c3         ret      

; ==== FUN_000002a0 @ 000002A0
000002A0 9c         pushfq   
000002A1 58         pop      RAX
000002A2 c3         ret      

; ==== entry @ 00000310
00000310 40 53      push     RBX
00000312 48 83 ec 20 sub      RSP, 0x20
00000316 48 8b da   mov      RBX, RDX
00000319 e8 0e 00 00 00 call     0x0000032c
0000031E 48 8b d3   mov      RDX, RBX
00000321 e8 12 01 00 00 call     0x00000438
00000326 48 83 c4 20 add      RSP, 0x20
0000032A 5b         pop      RBX
0000032B c3         ret      

; ==== FUN_0000032c @ 0000032C
0000032C 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00000331 57         push     RDI
00000332 48 83 ec 20 sub      RSP, 0x20
00000336 48 8b 42 60 mov      RAX, qword ptr [RDX + 0x60]
0000033A 48 89 05 47 0a 00 00 mov      qword ptr [0x00000d88], RAX
00000341 48 89 15 38 0a 00 00 mov      qword ptr [0x00000d80], RDX
00000348 e8 4f 07 00 00 call     0x00000a9c
0000034D e8 4a 07 00 00 call     0x00000a9c
00000352 48 8b 15 cf 09 00 00 mov      RDX, qword ptr [0x00000d28]
00000359 41 b9 ff ff 00 00 mov      R9D, 0xffff
0000035F 4c 8b 05 ba 09 00 00 mov      R8, qword ptr [0x00000d20]
00000366 eb 0d      jmp      0x00000375
00000368 66 83 f9 04 cmp      CX, 0x4
0000036C 74 12      jz       0x00000380
0000036E 0f b7 48 02 movzx    ECX, word ptr [RAX + 0x2]
00000372 48 03 c1   add      RAX, RCX
00000375 0f b7 08   movzx    ECX, word ptr [RAX]
00000378 66 41 3b c9 cmp      CX, R9W
0000037C 75 ea      jnz      0x00000368
0000037E 33 c0      xor      EAX, EAX
00000380 48 85 c0   test     RAX, RAX
00000383 74 0e      jz       0x00000393
00000385 4c 3b 40 08 cmp      R8, qword ptr [RAX + 0x8]
00000389 75 e3      jnz      0x0000036e
0000038B 48 3b 50 10 cmp      RDX, qword ptr [RAX + 0x10]
0000038F 74 58      jz       0x000003e9
00000391 eb db      jmp      0x0000036e
00000393 e8 08 ff ff ff call     0x000002a0
00000398 48 8b d8   mov      RBX, RAX
0000039B e8 f0 fe ff ff call     0x00000290
000003A0 c1 eb 09   shr      EBX, 0x9
000003A3 80 e3 01   and      BL, 0x1
000003A6 ba 08 18 00 00 mov      EDX, 0x1808
000003AB ed         in       EAX, DX
000003AC 8b f8      mov      EDI, EAX
000003AE 81 e7 ff ff ff 00 and      EDI, 0xffffff
000003B4 e8 b7 fe ff ff call     0x00000270
000003B9 eb 05      jmp      0x000003c0
000003BB e8 a0 fe ff ff call     0x00000260
000003C0 ba 08 18 00 00 mov      EDX, 0x1808
000003C5 8d 8f 6b 01 00 00 lea      ECX, [RDI + 0x16b]
000003CB ed         in       EAX, DX
000003CC 2b c8      sub      ECX, EAX
000003CE 0f ba e1 17 bt       ECX, 0x17
000003D2 73 e7      jnc      0x000003bb
000003D4 e8 97 fe ff ff call     0x00000270
000003D9 84 db      test     BL, BL
000003DB 74 07      jz       0x000003e4
000003DD e8 9e fe ff ff call     0x00000280
000003E2 eb 05      jmp      0x000003e9
000003E4 e8 a7 fe ff ff call     0x00000290
000003E9 48 8b 05 b8 09 00 00 mov      RAX, qword ptr [0x00000da8]
000003F0 48 85 c0   test     RAX, RAX
000003F3 75 29      jnz      0x0000041e
000003F5 48 8b 05 8c 09 00 00 mov      RAX, qword ptr [0x00000d88]
000003FC 4c 8d 05 a5 09 00 00 lea      R8, [0xda8]
00000403 33 d2      xor      EDX, EDX
00000405 48 8d 0d 04 09 00 00 lea      RCX, [0xd10]
0000040C ff 90 40 01 00 00 call     qword ptr [RAX + 0x140]
00000412 48 85 c0   test     RAX, RAX
00000415 78 13      js       0x0000042a
00000417 48 8b 05 8a 09 00 00 mov      RAX, qword ptr [0x00000da8]
0000041E 48 8d 15 8b 09 00 00 lea      RDX, [0xdb0]
00000425 48 8b c8   mov      RCX, RAX
00000428 ff 10      call     qword ptr [RAX]
0000042A 48 8b 5c 24 30 mov      RBX, qword ptr [RSP + 0x30]
0000042F 48 83 c4 20 add      RSP, 0x20
00000433 5f         pop      RDI
00000434 c3         ret      

; ==== FUN_00000438 @ 00000438
00000438 48 89 4c 24 08 mov      qword ptr [RSP + 0x8], RCX
0000043D 55         push     RBP
0000043E 53         push     RBX
0000043F 57         push     RDI
00000440 48 8d ac 24 00 f6 ff ff lea      RBP, [RSP + -0xa00]
00000448 48 81 ec 00 0b 00 00 sub      RSP, 0xb00
0000044F 83 a5 30 0a 00 00 00 and      dword ptr [RBP + 0xa30], 0x0
00000456 40 b7 ff   mov      DIL, 0xff
00000459 48 83 3d 37 09 00 00 00 cmp      qword ptr [0x00000d98], 0x0
00000461 48 c7 44 24 50 d8 07 00 00 mov      qword ptr [RSP + 0x50], 0x7d8
0000046A c7 44 24 30 43 d6 87 ec mov      dword ptr [RSP + 0x30], 0xec87d643
00000472 c7 44 24 34 a4 eb b5 4b mov      dword ptr [RSP + 0x34], 0x4bb5eba4
0000047A c7 44 24 38 a1 e5 3f 3e mov      dword ptr [RSP + 0x38], 0x3e3fe5a1
00000482 c7 44 24 3c 36 b2 0d a9 mov      dword ptr [RSP + 0x3c], 0xa90db236
0000048A 48 c7 85 38 0a 00 00 bb 02 00 00 mov      qword ptr [RBP + 0xa38], 0x2bb
00000495 c7 44 24 40 ff 97 8f b0 mov      dword ptr [RSP + 0x40], 0xb08f97ff
0000049D c7 44 24 44 e8 e6 93 41 mov      dword ptr [RSP + 0x44], 0x4193e6e8
000004A5 c7 44 24 48 a9 97 5e 9e mov      dword ptr [RSP + 0x48], 0x9e5e97a9
000004AD c7 44 24 4c 9b 0a db 32 mov      dword ptr [RSP + 0x4c], 0x32db0a9b
000004B5 75 12      jnz      0x000004c9
000004B7 48 89 15 da 08 00 00 mov      qword ptr [0x00000d98], RDX
000004BE 48 8b 42 58 mov      RAX, qword ptr [RDX + 0x58]
000004C2 48 89 05 c7 08 00 00 mov      qword ptr [0x00000d90], RAX
000004C9 41 b0 07   mov      R8B, 0x7
000004CC b2 a3      mov      DL, 0xa3
000004CE b1 62      mov      CL, 0x62
000004D0 e8 1b 04 00 00 call     0x000008f0
000004D5 48 85 c0   test     RAX, RAX
000004D8 78 1d      js       0x000004f7
000004DA 41 b0 50   mov      R8B, 0x50
000004DD b2 a2      mov      DL, 0xa2
000004DF b1 62      mov      CL, 0x62
000004E1 e8 0a 04 00 00 call     0x000008f0
000004E6 48 85 c0   test     RAX, RAX
000004E9 78 0c      js       0x000004f7
000004EB 45 33 c0   xor      R8D, R8D
000004EE b2 a5      mov      DL, 0xa5
000004F0 b1 62      mov      CL, 0x62
000004F2 e8 f9 03 00 00 call     0x000008f0
000004F7 48 8d 85 40 07 00 00 lea      RAX, [RBP + 0x740]
000004FE 48 89 44 24 20 mov      qword ptr [RSP + 0x20], RAX
00000503 4c 8d 8d 38 0a 00 00 lea      R9, [RBP + 0xa38]
0000050A 48 8b 05 7f 08 00 00 mov      RAX, qword ptr [0x00000d90]
00000511 4c 8d 85 30 0a 00 00 lea      R8, [RBP + 0xa30]
00000518 48 8d 54 24 40 lea      RDX, [RSP + 0x40]
0000051D 48 8d 0d 0c 08 00 00 lea      RCX, [0xd30]
00000524 ff 50 48   call     qword ptr [RAX + 0x48]
00000527 48 85 c0   test     RAX, RAX
0000052A 0f 88 4f 02 00 00 js       0x0000077f
00000530 48 8d 44 24 60 lea      RAX, [RSP + 0x60]
00000535 48 89 44 24 20 mov      qword ptr [RSP + 0x20], RAX
0000053A 4c 8d 4c 24 50 lea      R9, [RSP + 0x50]
0000053F 48 8b 05 4a 08 00 00 mov      RAX, qword ptr [0x00000d90]
00000546 4c 8d 85 30 0a 00 00 lea      R8, [RBP + 0xa30]
0000054D 48 8d 54 24 30 lea      RDX, [RSP + 0x30]
00000552 48 8d 0d ef 07 00 00 lea      RCX, [0xd48]
00000559 ff 50 48   call     qword ptr [RAX + 0x48]
0000055C 48 85 c0   test     RAX, RAX
0000055F 78 5e      js       0x000005bf
00000561 4c 8d 85 20 0a 00 00 lea      R8, [RBP + 0xa20]
00000568 b2 42      mov      DL, 0x42
0000056A e8 91 04 00 00 call     0x00000a00
0000056F 80 bd a4 06 00 00 01 cmp      byte ptr [RBP + 0x6a4], 0x1
00000576 b2 42      mov      DL, 0x42
00000578 44 8a 85 20 0a 00 00 mov      R8B, byte ptr [RBP + 0xa20]
0000057F 75 06      jnz      0x00000587
00000581 41 80 c8 03 or       R8B, 0x3
00000585 eb 04      jmp      0x0000058b
00000587 41 80 e0 fc and      R8B, 0xfc
0000058B e8 28 04 00 00 call     0x000009b8
00000590 4c 8d 85 20 0a 00 00 lea      R8, [RBP + 0xa20]
00000597 b2 58      mov      DL, 0x58
00000599 e8 62 04 00 00 call     0x00000a00
0000059E 80 bd 49 07 00 00 01 cmp      byte ptr [RBP + 0x749], 0x1
000005A5 44 8a 85 20 0a 00 00 mov      R8B, byte ptr [RBP + 0xa20]
000005AC 75 06      jnz      0x000005b4
000005AE 41 80 c8 80 or       R8B, 0x80
000005B2 eb 04      jmp      0x000005b8
000005B4 41 80 e0 7f and      R8B, 0x7f
000005B8 b2 58      mov      DL, 0x58
000005BA e8 f9 03 00 00 call     0x000009b8
000005BF ba 70 00 00 00 mov      EDX, 0x70
000005C4 b0 f0      mov      AL, 0xf0
000005C6 ee         out      DX, AL
000005C7 ba 71 00 00 00 mov      EDX, 0x71
000005CC b0 02      mov      AL, 0x2
000005CE ee         out      DX, AL
000005CF 41 b0 07   mov      R8B, 0x7
000005D2 b2 a3      mov      DL, 0xa3
000005D4 b1 62      mov      CL, 0x62
000005D6 33 db      xor      EBX, EBX
000005D8 e8 13 03 00 00 call     0x000008f0
000005DD 48 85 c0   test     RAX, RAX
000005E0 78 59      js       0x0000063b
000005E2 41 b0 4c   mov      R8B, 0x4c
000005E5 b2 a2      mov      DL, 0xa2
000005E7 b1 62      mov      CL, 0x62
000005E9 e8 02 03 00 00 call     0x000008f0
000005EE 48 85 c0   test     RAX, RAX
000005F1 78 48      js       0x0000063b
000005F3 b2 a4      mov      DL, 0xa4
000005F5 b1 62      mov      CL, 0x62
000005F7 e8 90 01 00 00 call     0x0000078c
000005FC 48 85 c0   test     RAX, RAX
000005FF 78 3a      js       0x0000063b
00000601 8d 53 66   lea      EDX, [RBX + 0x66]
00000604 ec         in       AL, DX
00000605 a8 01      test     AL, 0x1
00000607 75 29      jnz      0x00000632
00000609 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
00000610 73 29      jnc      0x0000063b
00000612 b9 0f 00 00 00 mov      ECX, 0xf
00000617 e8 4c 05 00 00 call     0x00000b68
0000061C ba 66 00 00 00 mov      EDX, 0x66
00000621 ec         in       AL, DX
00000622 48 ff c3   inc      RBX
00000625 a8 01      test     AL, 0x1
00000627 74 e0      jz       0x00000609
00000629 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
00000630 73 09      jnc      0x0000063b
00000632 ba 62 00 00 00 mov      EDX, 0x62
00000637 ec         in       AL, DX
00000638 40 8a f8   mov      DIL, AL
0000063B 40 0f b6 cf movzx    ECX, DIL
0000063F 83 e1 0f   and      ECX, 0xf
00000642 0f 84 0a 01 00 00 jz       0x00000752
00000648 83 e9 01   sub      ECX, 0x1
0000064B 0f 84 01 01 00 00 jz       0x00000752
00000651 83 e9 01   sub      ECX, 0x1
00000654 0f 84 f8 00 00 00 jz       0x00000752
0000065A 83 e9 01   sub      ECX, 0x1
0000065D 0f 84 aa 00 00 00 jz       0x0000070d
00000663 83 e9 01   sub      ECX, 0x1
00000666 0f 84 e6 00 00 00 jz       0x00000752
0000066C 83 e9 01   sub      ECX, 0x1
0000066F 0f 84 dd 00 00 00 jz       0x00000752
00000675 83 e9 01   sub      ECX, 0x1
00000678 0f 84 d4 00 00 00 jz       0x00000752
0000067E 83 e9 01   sub      ECX, 0x1
00000681 74 4a      jz       0x000006cd
00000683 83 f9 01   cmp      ECX, 0x1
00000686 74 0c      jz       0x00000694
00000688 c6 85 a3 03 00 00 00 mov      byte ptr [RBP + 0x3a3], 0x0
0000068F e9 be 00 00 00 jmp      0x00000752
00000694 c7 85 b5 03 00 00 01 41 6f a0 mov      dword ptr [RBP + 0x3b5], 0xa06f4101
0000069E c7 85 b9 03 00 00 69 30 40 6f mov      dword ptr [RBP + 0x3b9], 0x6f403069
000006A8 66 c7 85 bd 03 00 00 a0 69 mov      word ptr [RBP + 0x3bd], 0x69a0
000006B1 c7 85 f4 03 00 00 01 15 1e 1e mov      dword ptr [RBP + 0x3f4], 0x1e1e1501
000006BB c6 85 f8 03 00 00 20 mov      byte ptr [RBP + 0x3f8], 0x20
000006C2 66 c7 85 7c 04 00 00 20 20 mov      word ptr [RBP + 0x47c], 0x2020
000006CB eb 77      jmp      0x00000744
000006CD c7 85 b5 03 00 00 01 61 6e a0 mov      dword ptr [RBP + 0x3b5], 0xa06e6101
000006D7 c7 85 b9 03 00 00 7b 49 5f 79 mov      dword ptr [RBP + 0x3b9], 0x795f497b
000006E1 66 c7 85 bd 03 00 00 a0 70 mov      word ptr [RBP + 0x3bd], 0x70a0
000006EA c6 85 bf 03 00 00 31 mov      byte ptr [RBP + 0x3bf], 0x31
000006F1 c7 85 f4 03 00 00 01 16 11 11 mov      dword ptr [RBP + 0x3f4], 0x11111601
000006FB c6 85 f8 03 00 00 1c mov      byte ptr [RBP + 0x3f8], 0x1c
00000702 66 c7 85 7c 04 00 00 1c 1c mov      word ptr [RBP + 0x47c], 0x1c1c
0000070B eb 3e      jmp      0x0000074b
0000070D c7 85 b5 03 00 00 01 65 6a a0 mov      dword ptr [RBP + 0x3b5], 0xa06a6501
00000717 c7 85 b9 03 00 00 72 43 63 71 mov      dword ptr [RBP + 0x3b9], 0x71634372
00000721 66 c7 85 bd 03 00 00 a0 6a mov      word ptr [RBP + 0x3bd], 0x6aa0
0000072A c7 85 f4 03 00 00 01 1a 13 13 mov      dword ptr [RBP + 0x3f4], 0x13131a01
00000734 c6 85 f8 03 00 00 1b mov      byte ptr [RBP + 0x3f8], 0x1b
0000073B 66 c7 85 7c 04 00 00 1b 1b mov      word ptr [RBP + 0x47c], 0x1b1b
00000744 c6 85 bf 03 00 00 2f mov      byte ptr [RBP + 0x3bf], 0x2f
0000074B c6 85 a3 03 00 00 01 mov      byte ptr [RBP + 0x3a3], 0x1
00000752 44 8b 85 30 0a 00 00 mov      R8D, dword ptr [RBP + 0xa30]
00000759 48 8d 44 24 60 lea      RAX, [RSP + 0x60]
0000075E 48 89 44 24 20 mov      qword ptr [RSP + 0x20], RAX
00000763 48 8d 54 24 30 lea      RDX, [RSP + 0x30]
00000768 48 8b 05 21 06 00 00 mov      RAX, qword ptr [0x00000d90]
0000076F 48 8d 0d d2 05 00 00 lea      RCX, [0xd48]
00000776 41 b9 d8 07 00 00 mov      R9D, 0x7d8
0000077C ff 50 58   call     qword ptr [RAX + 0x58]
0000077F 48 81 c4 00 0b 00 00 add      RSP, 0xb00
00000786 5f         pop      RDI
00000787 5b         pop      RBX
00000788 5d         pop      RBP
00000789 c3         ret      

; ==== FUN_0000078c @ 0000078C
0000078C 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00000791 48 89 74 24 10 mov      qword ptr [RSP + 0x10], RSI
00000796 57         push     RDI
00000797 48 83 ec 20 sub      RSP, 0x20
0000079B 40 8a f2   mov      SIL, DL
0000079E 33 db      xor      EBX, EBX
000007A0 8d 53 66   lea      EDX, [RBX + 0x66]
000007A3 80 f9 60   cmp      CL, 0x60
000007A6 8d 43 64   lea      EAX, [RBX + 0x64]
000007A9 0f 45 c2   cmovnz   EAX, EDX
000007AC 0f b6 f8   movzx    EDI, AL
000007AF 0f b7 d7   movzx    EDX, DI
000007B2 ec         in       AL, DX
000007B3 a8 02      test     AL, 0x2
000007B5 74 33      jz       0x000007ea
000007B7 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
000007BE 73 1e      jnc      0x000007de
000007C0 b9 0f 00 00 00 mov      ECX, 0xf
000007C5 e8 9e 03 00 00 call     0x00000b68
000007CA 0f b7 d7   movzx    EDX, DI
000007CD ec         in       AL, DX
000007CE 48 ff c3   inc      RBX
000007D1 a8 02      test     AL, 0x2
000007D3 75 e2      jnz      0x000007b7
000007D5 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
000007DC 72 0c      jc       0x000007ea
000007DE 48 b8 07 00 00 00 00 00 00 80 mov      RAX, -0x7ffffffffffffff9
000007E8 eb 09      jmp      0x000007f3
000007EA 0f b7 d7   movzx    EDX, DI
000007ED 40 8a c6   mov      AL, SIL
000007F0 ee         out      DX, AL
000007F1 33 c0      xor      EAX, EAX
000007F3 48 8b 5c 24 30 mov      RBX, qword ptr [RSP + 0x30]
000007F8 48 8b 74 24 38 mov      RSI, qword ptr [RSP + 0x38]
000007FD 48 83 c4 20 add      RSP, 0x20
00000801 5f         pop      RDI
00000802 c3         ret      

; ==== FUN_00000804 @ 00000804
00000804 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00000809 48 89 74 24 10 mov      qword ptr [RSP + 0x10], RSI
0000080E 57         push     RDI
0000080F 48 83 ec 20 sub      RSP, 0x20
00000813 40 8a f9   mov      DIL, CL
00000816 33 db      xor      EBX, EBX
00000818 40 80 ff 60 cmp      DIL, 0x60
0000081C 8d 43 64   lea      EAX, [RBX + 0x64]
0000081F 8d 4b 66   lea      ECX, [RBX + 0x66]
00000822 0f 45 c1   cmovnz   EAX, ECX
00000825 0f b6 f0   movzx    ESI, AL
00000828 0f b7 d6   movzx    EDX, SI
0000082B ec         in       AL, DX
0000082C a8 01      test     AL, 0x1
0000082E 74 47      jz       0x00000877
00000830 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
00000837 73 32      jnc      0x0000086b
00000839 ba 60 00 00 00 mov      EDX, 0x60
0000083E 40 3a fa   cmp      DIL, DL
00000841 8d 4a 02   lea      ECX, [RDX + 0x2]
00000844 66 0f 45 d1 cmovnz   DX, CX
00000848 ec         in       AL, DX
00000849 8d 51 1e   lea      EDX, [RCX + 0x1e]
0000084C ee         out      DX, AL
0000084D b9 88 13 00 00 mov      ECX, 0x1388
00000852 e8 11 03 00 00 call     0x00000b68
00000857 0f b7 d6   movzx    EDX, SI
0000085A ec         in       AL, DX
0000085B 48 ff c3   inc      RBX
0000085E a8 01      test     AL, 0x1
00000860 75 ce      jnz      0x00000830
00000862 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
00000869 72 0c      jc       0x00000877
0000086B 48 b8 07 00 00 00 00 00 00 80 mov      RAX, -0x7ffffffffffffff9
00000875 eb 02      jmp      0x00000879
00000877 33 c0      xor      EAX, EAX
00000879 48 8b 5c 24 30 mov      RBX, qword ptr [RSP + 0x30]
0000087E 48 8b 74 24 38 mov      RSI, qword ptr [RSP + 0x38]
00000883 48 83 c4 20 add      RSP, 0x20
00000887 5f         pop      RDI
00000888 c3         ret      

; ==== FUN_0000088c @ 0000088C
0000088C 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00000891 57         push     RDI
00000892 48 83 ec 20 sub      RSP, 0x20
00000896 33 db      xor      EBX, EBX
00000898 8d 53 66   lea      EDX, [RBX + 0x66]
0000089B 80 f9 60   cmp      CL, 0x60
0000089E 8d 43 64   lea      EAX, [RBX + 0x64]
000008A1 0f 45 c2   cmovnz   EAX, EDX
000008A4 0f b6 f8   movzx    EDI, AL
000008A7 0f b7 d7   movzx    EDX, DI
000008AA ec         in       AL, DX
000008AB a8 02      test     AL, 0x2
000008AD 74 33      jz       0x000008e2
000008AF 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
000008B6 73 1e      jnc      0x000008d6
000008B8 b9 0f 00 00 00 mov      ECX, 0xf
000008BD e8 a6 02 00 00 call     0x00000b68
000008C2 0f b7 d7   movzx    EDX, DI
000008C5 ec         in       AL, DX
000008C6 48 ff c3   inc      RBX
000008C9 a8 02      test     AL, 0x2
000008CB 75 e2      jnz      0x000008af
000008CD 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
000008D4 72 0c      jc       0x000008e2
000008D6 48 b8 07 00 00 00 00 00 00 80 mov      RAX, -0x7ffffffffffffff9
000008E0 eb 02      jmp      0x000008e4
000008E2 33 c0      xor      EAX, EAX
000008E4 48 8b 5c 24 30 mov      RBX, qword ptr [RSP + 0x30]
000008E9 48 83 c4 20 add      RSP, 0x20
000008ED 5f         pop      RDI
000008EE c3         ret      

; ==== FUN_000008f0 @ 000008F0
000008F0 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
000008F5 48 89 6c 24 10 mov      qword ptr [RSP + 0x10], RBP
000008FA 48 89 74 24 18 mov      qword ptr [RSP + 0x18], RSI
000008FF 57         push     RDI
00000900 41 56      push     R14
00000902 41 57      push     R15
00000904 48 83 ec 20 sub      RSP, 0x20
00000908 45 8a f0   mov      R14B, R8B
0000090B 40 8a f2   mov      SIL, DL
0000090E 40 8a f9   mov      DIL, CL
00000911 e8 76 ff ff ff call     0x0000088c
00000916 33 db      xor      EBX, EBX
00000918 48 8b e8   mov      RBP, RAX
0000091B 48 85 c0   test     RAX, RAX
0000091E 78 7d      js       0x0000099d
00000920 40 8a cf   mov      CL, DIL
00000923 e8 dc fe ff ff call     0x00000804
00000928 40 8a d6   mov      DL, SIL
0000092B 40 8a cf   mov      CL, DIL
0000092E e8 59 fe ff ff call     0x0000078c
00000933 40 8a cf   mov      CL, DIL
00000936 e8 51 ff ff ff call     0x0000088c
0000093B 8d 73 60   lea      ESI, [RBX + 0x60]
0000093E 40 3a fe   cmp      DIL, SIL
00000941 8d 43 64   lea      EAX, [RBX + 0x64]
00000944 8d 4b 66   lea      ECX, [RBX + 0x66]
00000947 0f 45 c1   cmovnz   EAX, ECX
0000094A 44 0f b6 f8 movzx    R15D, AL
0000094E 41 0f b7 d7 movzx    EDX, R15W
00000952 ec         in       AL, DX
00000953 a8 02      test     AL, 0x2
00000955 74 28      jz       0x0000097f
00000957 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
0000095E 73 32      jnc      0x00000992
00000960 b9 0f 00 00 00 mov      ECX, 0xf
00000965 e8 fe 01 00 00 call     0x00000b68
0000096A 41 0f b7 d7 movzx    EDX, R15W
0000096E ec         in       AL, DX
0000096F 48 ff c3   inc      RBX
00000972 a8 02      test     AL, 0x2
00000974 75 e1      jnz      0x00000957
00000976 48 81 fb 00 00 02 00 cmp      RBX, 0x20000
0000097D 73 13      jnc      0x00000992
0000097F b8 62 00 00 00 mov      EAX, 0x62
00000984 40 3a fe   cmp      DIL, SIL
00000987 66 0f 45 f0 cmovnz   SI, AX
0000098B 41 8a c6   mov      AL, R14B
0000098E 0f b7 d6   movzx    EDX, SI
00000991 ee         out      DX, AL
00000992 40 8a cf   mov      CL, DIL
00000995 e8 6a fe ff ff call     0x00000804
0000099A 48 8b c5   mov      RAX, RBP
0000099D 48 8b 5c 24 40 mov      RBX, qword ptr [RSP + 0x40]
000009A2 48 8b 6c 24 48 mov      RBP, qword ptr [RSP + 0x48]
000009A7 48 8b 74 24 50 mov      RSI, qword ptr [RSP + 0x50]
000009AC 48 83 c4 20 add      RSP, 0x20
000009B0 41 5f      pop      R15
000009B2 41 5e      pop      R14
000009B4 5f         pop      RDI
000009B5 c3         ret      

; ==== FUN_000009b8 @ 000009B8
000009B8 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
000009BD 57         push     RDI
000009BE 48 83 ec 20 sub      RSP, 0x20
000009C2 41 8a f8   mov      DIL, R8B
000009C5 8a da      mov      BL, DL
000009C7 41 b0 04   mov      R8B, 0x4
000009CA b2 a3      mov      DL, 0xa3
000009CC b1 62      mov      CL, 0x62
000009CE e8 1d ff ff ff call     0x000008f0
000009D3 48 85 c0   test     RAX, RAX
000009D6 78 1d      js       0x000009f5
000009D8 44 8a c3   mov      R8B, BL
000009DB b2 a2      mov      DL, 0xa2
000009DD b1 62      mov      CL, 0x62
000009DF e8 0c ff ff ff call     0x000008f0
000009E4 48 85 c0   test     RAX, RAX
000009E7 78 0c      js       0x000009f5
000009E9 44 8a c7   mov      R8B, DIL
000009EC b2 a5      mov      DL, 0xa5
000009EE b1 62      mov      CL, 0x62
000009F0 e8 fb fe ff ff call     0x000008f0
000009F5 48 8b 5c 24 30 mov      RBX, qword ptr [RSP + 0x30]
000009FA 48 83 c4 20 add      RSP, 0x20
000009FE 5f         pop      RDI
000009FF c3         ret      

; ==== FUN_00000a00 @ 00000A00
00000A00 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00000A05 48 89 74 24 10 mov      qword ptr [RSP + 0x10], RSI
00000A0A 57         push     RDI
00000A0B 48 83 ec 20 sub      RSP, 0x20
00000A0F 49 8b f0   mov      RSI, R8
00000A12 40 8a fa   mov      DIL, DL
00000A15 41 b0 04   mov      R8B, 0x4
00000A18 b2 a3      mov      DL, 0xa3
00000A1A b1 62      mov      CL, 0x62
00000A1C 33 db      xor      EBX, EBX
00000A1E e8 cd fe ff ff call     0x000008f0
00000A23 48 85 c0   test     RAX, RAX
00000A26 78 63      js       0x00000a8b
00000A28 44 8a c7   mov      R8B, DIL
00000A2B b2 a2      mov      DL, 0xa2
00000A2D b1 62      mov      CL, 0x62
00000A2F e8 bc fe ff ff call     0x000008f0
00000A34 48 85 c0   test     RAX, RAX
00000A37 78 52      js       0x00000a8b
00000A39 b2 a4      mov      DL, 0xa4
00000A3B b1 62      mov      CL, 0x62
00000A3D e8 4a fd ff ff call     0x0000078c
00000A42 48 85 c0   test     RAX, RAX
00000A45 78 44      js       0x00000a8b
00000A47 8d 53 66   lea      EDX, [RBX + 0x66]
00000A4A ec         in       AL, DX
00000A4B a8 01      test     AL, 0x1
00000A4D 75 32      jnz      0x00000a81
00000A4F bf 00 00 02 00 mov      EDI, 0x20000
00000A54 48 3b df   cmp      RBX, RDI
00000A57 73 1c      jnc      0x00000a75
00000A59 b9 0f 00 00 00 mov      ECX, 0xf
00000A5E e8 05 01 00 00 call     0x00000b68
00000A63 ba 66 00 00 00 mov      EDX, 0x66
00000A68 ec         in       AL, DX
00000A69 48 ff c3   inc      RBX
00000A6C a8 01      test     AL, 0x1
00000A6E 74 e4      jz       0x00000a54
00000A70 48 3b df   cmp      RBX, RDI
00000A73 72 0c      jc       0x00000a81
00000A75 48 b8 07 00 00 00 00 00 00 80 mov      RAX, -0x7ffffffffffffff9
00000A7F eb 0a      jmp      0x00000a8b
00000A81 ba 62 00 00 00 mov      EDX, 0x62
00000A86 ec         in       AL, DX
00000A87 88 06      mov      byte ptr [RSI], AL
00000A89 33 c0      xor      EAX, EAX
00000A8B 48 8b 5c 24 30 mov      RBX, qword ptr [RSP + 0x30]
00000A90 48 8b 74 24 38 mov      RSI, qword ptr [RSP + 0x38]
00000A95 48 83 c4 20 add      RSP, 0x20
00000A99 5f         pop      RDI
00000A9A c3         ret      

; ==== FUN_00000a9c @ 00000A9C
00000A9C 48 8b 0d fd 02 00 00 mov      RCX, qword ptr [0x00000da0]
00000AA3 33 c0      xor      EAX, EAX
00000AA5 48 85 c9   test     RCX, RCX
00000AA8 75 57      jnz      0x00000b01
00000AAA 48 8b 15 cf 02 00 00 mov      RDX, qword ptr [0x00000d80]
00000AB1 8b c8      mov      ECX, EAX
00000AB3 48 89 05 e6 02 00 00 mov      qword ptr [0x00000da0], RAX
00000ABA 4c 8b 42 68 mov      R8, qword ptr [RDX + 0x68]
00000ABE 4d 85 c0   test     R8, R8
00000AC1 74 3e      jz       0x00000b01
00000AC3 4c 8b 4a 70 mov      R9, qword ptr [RDX + 0x70]
00000AC7 4c 8b 15 3a 02 00 00 mov      R10, qword ptr [0x00000d08]
00000ACE 49 8b d1   mov      RDX, R9
00000AD1 4c 8b 1d 28 02 00 00 mov      R11, qword ptr [0x00000d00]
00000AD8 4c 3b 1a   cmp      R11, qword ptr [RDX]
00000ADB 75 06      jnz      0x00000ae3
00000ADD 4c 3b 52 08 cmp      R10, qword ptr [RDX + 0x8]
00000AE1 74 0e      jz       0x00000af1
00000AE3 48 ff c0   inc      RAX
00000AE6 48 83 c2 18 add      RDX, 0x18
00000AEA 49 3b c0   cmp      RAX, R8
00000AED 73 12      jnc      0x00000b01
00000AEF eb e7      jmp      0x00000ad8
00000AF1 48 8d 04 40 lea      RAX, [RAX + RAX*0x2]
00000AF5 49 8b 4c c1 10 mov      RCX, qword ptr [R9 + RAX*0x8 + 0x10]
00000AFA 48 89 0d 9f 02 00 00 mov      qword ptr [0x00000da0], RCX
00000B01 48 8b c1   mov      RAX, RCX
00000B04 c3         ret      

; ==== FUN_00000b08 @ 00000B08
00000B08 48 89 5c 24 08 mov      qword ptr [RSP + 0x8], RBX
00000B0D 48 89 74 24 10 mov      qword ptr [RSP + 0x10], RSI
00000B12 57         push     RDI
00000B13 48 83 ec 20 sub      RSP, 0x20
00000B17 8b d9      mov      EBX, ECX
00000B19 8b f9      mov      EDI, ECX
00000B1B c1 eb 16   shr      EBX, 0x16
00000B1E 81 e7 ff ff 3f 00 and      EDI, 0x3fffff
00000B24 ba 08 18 00 00 mov      EDX, 0x1808
00000B29 ed         in       EAX, DX
00000B2A 8b f0      mov      ESI, EAX
00000B2C 81 e6 ff ff ff 00 and      ESI, 0xffffff
00000B32 03 f7      add      ESI, EDI
00000B34 bf 00 00 40 00 mov      EDI, 0x400000
00000B39 eb 0a      jmp      0x00000b45
00000B3B e8 20 f7 ff ff call     0x00000260
00000B40 ba 08 18 00 00 mov      EDX, 0x1808
00000B45 ed         in       EAX, DX
00000B46 8b ce      mov      ECX, ESI
00000B48 2b c8      sub      ECX, EAX
00000B4A 0f ba e1 17 bt       ECX, 0x17
00000B4E 73 eb      jnc      0x00000b3b
00000B50 8b c3      mov      EAX, EBX
00000B52 ff cb      dec      EBX
00000B54 85 c0      test     EAX, EAX
00000B56 75 cc      jnz      0x00000b24
00000B58 48 8b 5c 24 30 mov      RBX, qword ptr [RSP + 0x30]
00000B5D 48 8b 74 24 38 mov      RSI, qword ptr [RSP + 0x38]
00000B62 48 83 c4 20 add      RSP, 0x20
00000B66 5f         pop      RDI
00000B67 c3         ret      

; ==== FUN_00000b68 @ 00000B68
00000B68 40 53      push     RBX
00000B6A 48 83 ec 20 sub      RSP, 0x20
00000B6E 48 69 d1 99 9e 36 00 imul     RDX, RCX, 0x369e99
00000B75 48 8b d9   mov      RBX, RCX
00000B78 48 b8 db 34 b6 d7 82 de 1b 43 mov      RAX, 0x431bde82d7b634db
00000B82 48 f7 e2   mul      RDX
00000B85 48 c1 ea 12 shr      RDX, 0x12
00000B89 8b ca      mov      ECX, EDX
00000B8B e8 78 ff ff ff call     0x00000b08
00000B90 48 8b c3   mov      RAX, RBX
00000B93 48 83 c4 20 add      RSP, 0x20
00000B97 5b         pop      RBX
00000B98 c3         ret      

